### ISSUE TITLE
PDF selection returns more than cursor selected.

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#1067]
On this PDF.
http://www.colorado.gov/cs/Satellite?blobcol=urldata&blobheadername1=Content-Disposition&blobheadername2=Content-Type&blobheadervalue1=inline%3B+filename%3D%22CEPaaS+White+Paper.pdf%22&blobheadervalue2=application%2Fpdf&blobkey=id&blobtable=MungoBlobs&blobwhere=1251785273349&ssbinary=true

Select pretty much any word.

**Comment by judell** [comment]
Wanted to test with 4.1.139 but example URL now 400. Close as unreproducible?
