### ISSUE TITLE
User does not get notified when saving an annotation fails on server-side

### ISSUE THREAD

**Issue by gergely-ujvari** [hypothesis/h#1142]
If any exception occur during the saving of an annotation, then in the client side:
- The error message not always pop-up (so the "Your annotation was not saved" is not always showed, and even when yes, only with a great delay)
- The javascript console has the 500 Internal error exception 
- The annotation card is not showed, but the annotation itself is counted in the tabs. This is inconsistent.

**Comment by BigBlueHat** [comment]
Just hit this on http://quod.lib.umich.edu/j/jep/3336451.0017.201?view=text;rgn=main

As did our partner...

Please prioritize this one, k? :smiley:

**Comment by dwhly** [comment]
When an annotation fails to save, can we notify [insert monitoring app]?

**Comment by tilgovi** [comment]
@dwhly probably nothing to do there.

We already track all exceptions in Sentry on the server. If an annotation fails to save and it's not already logged there then the most likely cause is connectivity and the monitoring would likely fail, too, for the same reason.

**Comment by dwhly** [comment]
Tx

**Comment by tilgovi** [comment]
Closed by #2197
