### ISSUE TITLE
Favoriting

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#119]

**Comment by seanh** [comment]
It's got UI already? What are the requirements for this feature exactly?

**Comment by dwhly** [comment]
Hmm... I'd say this probably "needs design".  @RawKStar77 ?

**Comment by tilgovi** [comment]
No idea what I was referring to when I wrote that.

**Comment by JakeHartnell** [comment]
> Hmm... I'd say this probably "needs design". @RawKStar77 ?

C.C. @conordelahunty

**Comment by JakeHartnell** [comment]
https://github.com/hypothesis/vision/issues/53

**Comment by nickstenning** [comment]
Closing this one as a feature that should come down the product prio/design pipeline.
