### ISSUE TITLE
Properties stored in edited annotations

### ISSUE THREAD

**Issue by tilgovi** [hypothesis/h#1207]
When I mentioned to @csillag the other day that I thought I saw `diffHTML` in the stored annotations, I was mis-remembering.

What I have seen, and what I see right now in production, is `reply_list` as a property stored in the annotation.

The root problem is that we store this property _on the annotation model object_ when it should be an ephemeral property of the view.

It's often not a problem because it's empty for new annotations.

The problem manifests when an annotation has replies and then is edited. The update will save the `reply_list` in the annotation.

Marked as a blocker for v0.1 since it potentially explodes the storage.

**Comment by gergely-ujvari** [comment]
Do we still have this issue?

**Comment by tilgovi** [comment]
Yeah. I think so. Diff info still in the targets at least.

**Comment by tilgovi** [comment]
Here's the status on this one.

Removable (check means I ran a migration and these are now expunged):
- [x] _updatedAnnotation
- [x] showDiff
- [x] reply_count
- [x] reply_list
- [x] $$hashKey
  - [x] top level
  - [x] nested in target
  - [x] nested in selector
- [x] target.quote
- [x] annotation.quote

Not removable yet:
- diffCaseOnly
- target.pos
- annotation.uri
  - comments need to create a target
  - fragment selector should take from nearest ancestor

**Comment by tilgovi** [comment]
By "not removable yet" I mean that our current client still creates these, so it doesn't make sense to remove it.

**Comment by judell** [comment]
Still relevant in 4.1.nnnn?

**Comment by tilgovi** [comment]
I think not, because `diffCaseOnly` is about show differences, which is currently not functional in the new code and `target.pos` has moved to an `$anchors` property (to address this issue). Let's wait for that to merge, ship, and run a migration and then I'll close this.

**Comment by tilgovi** [comment]
Oh this can finally be closed! \o/
