### ISSUE TITLE
IE css style warning

### ISSUE THREAD

**Issue by gergely-ujvari** [hypothesis/h#1225]
Upon loading the h application under IE11, it says the following warning: 

```SEC7115: :visited and :link styles can only differ by color. Some styles were not applied to :visited.```

[Here](http://msdn.microsoft.com/en-us/library/ie/hh180764%28v=vs.85%29.aspx) they say that the problem is:  
```
More than one attribute, such as font or size, were changed by using the visited and link styles.
```
Solution would be to:
```
Change only the color attribute.
```

This is by no means a really serious error, but maybe we could style our css that IE could be happy with it too.

**Comment by judell** [comment]
Not reproduced at https://via.hypothes.is/blog.jonudell.net in IE11.
