### ISSUE TITLE
Highlighting pen icon

### ISSUE THREAD

**Issue by BigBlueHat** [hypothesis/h#1261]
As a frenetic mouse clicker/highlighter/(ab)user while reading, I'm finding the sidebar highlight mode status icon to be too minimal.

I'd like my cursor to change shape--ideally, text select icon + highlight pen nearby (bottom left, probably). That would help prevent my random clicking habit turning into unintentional highlighting.

**Comment by RawKStar77** [comment]
Closed via https://github.com/hypothesis/h/pull/2031
