### ISSUE TITLE
Embedded view of annotations (for other websites)

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#141]

**Comment by csillag** [comment]
Is http://oembed.com/ the dominant standard in this field?

**Comment by aron** [comment]
@csillag yes I believe so, that and open graph http://ogp.me

**Comment by csillag** [comment]
Does open graph specify something about how to produce embeddable snippets? (From a cursory overview, I only see stuff about metadata...)

**Comment by aron** [comment]
What do you mean by produce embeddable snippets? It provides urls to representations for the document such as thumbnails, images, audio, videos which can then be embedded in a separate document much in the same way as oembed. It doesn't have the capability to provide raw html like oembed if that's what you mean?

**Comment by edsu** [comment]
HTML is returned, e.g.

## YouTube:

http://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=myfByN5p928

```javascript
{
  thumbnail_width: 480,
  author_url: "https://www.youtube.com/user/whitehouse",
  title: "President Obama Delivers Remarks on Reducing Gun Violence",
  author_name: "The White House",
  html: "<iframe width="480" height="270" src="https://www.youtube.com/embed/myfByN5p928?feature=oembed" frameborder="0" allowfullscreen></iframe>",
  provider_name: "YouTube",
  version: "1.0",
  height: 270,
  thumbnail_height: 360,
  type: "video",
  width: 480,
  thumbnail_url: "https://i.ytimg.com/vi/myfByN5p928/hqdefault.jpg",
  provider_url: "https://www.youtube.com/"
}
```

## Instagram

https://api.instagram.com/oembed/?url=http://instagram.com/p/V8UMy0LjpX/

```javascript
{
  provider_url: "https://www.instagram.com",
  media_id: "395279707428239959_14057957",
  author_name: "zooeydeschanel",
  height: null,
  thumbnail_url: "https://instagram.fash1-1.fna.fbcdn.net/hphotos-xaf1/t51.2885-15/e15/11262720_891453137565191_1495973619_n.jpg",
  thumbnail_width: 612,
  thumbnail_height: 612,
  provider_name: "Instagram",
  title: "My favorite cat from tonight's episode- a true winner. #newgirl",
  html: "<blockquote class="instagram-media" data-instgrm-captioned data-instgrm-version="6" style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:658px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);"><div style="padding:8px;"> <div style=" background:#F8F8F8; line-height:0; margin-top:40px; padding:50.0% 0; text-align:center; width:100%;"> <div style=" background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACwAAAAsCAMAAAApWqozAAAAGFBMVEUiIiI9PT0eHh4gIB4hIBkcHBwcHBwcHBydr+JQAAAACHRSTlMABA4YHyQsM5jtaMwAAADfSURBVDjL7ZVBEgMhCAQBAf//42xcNbpAqakcM0ftUmFAAIBE81IqBJdS3lS6zs3bIpB9WED3YYXFPmHRfT8sgyrCP1x8uEUxLMzNWElFOYCV6mHWWwMzdPEKHlhLw7NWJqkHc4uIZphavDzA2JPzUDsBZziNae2S6owH8xPmX8G7zzgKEOPUoYHvGz1TBCxMkd3kwNVbU0gKHkx+iZILf77IofhrY1nYFnB/lQPb79drWOyJVa/DAvg9B/rLB4cC+Nqgdz/TvBbBnr6GBReqn/nRmDgaQEej7WhonozjF+Y2I/fZou/qAAAAAElFTkSuQmCC); display:block; height:44px; margin:0 auto -44px; position:relative; top:-22px; width:44px;"></div></div> <p style=" margin:8px 0 0 0; padding:0 4px;"> <a href="https://www.instagram.com/p/V8UMy0LjpX/" style=" color:#000; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:normal; line-height:17px; text-decoration:none; word-wrap:break-word;" target="_blank">My favorite cat from tonight&#39;s episode- a true winner. #newgirl</a></p> <p style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; line-height:17px; margin-bottom:0; margin-top:8px; overflow:hidden; padding:8px 0 7px; text-align:center; text-overflow:ellipsis; white-space:nowrap;">A photo posted by Zooey Deschanel (@zooeydeschanel) on <time style=" font-family:Arial,sans-serif; font-size:14px; line-height:17px;" datetime="2013-02-20T06:17:14+00:00">Feb 19, 2013 at 10:17pm PST</time></p></div></blockquote> <script async defer src="//platform.instagram.com/en_US/embeds.js"></script>",
  width: 658,
  version: "1.0",
  author_url: "https://www.instagram.com/zooeydeschanel",
  author_id: 14057957,
  type: "rich"
}
```

This makes me wonder if some generic oEmbed functionality with a whitelist of hostnames could be used in [media-embedder.js](https://github.com/hypothesis/h/blob/master/h/static/scripts/media-embedder.js)?

**Comment by nickstenning** [comment]
Hi there! I'm going to close this as part of a clean-up of all issues currently open on this repo that represent ideas or features rather than reports of bugs or technical chores. 

I want to be clear that **this isn't intended to say anything at all about the content of this issue**—it certainly doesn't mean we're no longer planning to do the work discussed here—just that we don't want to use GitHub issues to track feature requests or ideas, because the threads can get long and somewhat unwieldy.

If you're interested in what we are working on at the moment, you can check out [our Trello board](https://trello.com/b/o2ungX1n/current-sprint) and, for a longer-term view, [our roadmap](https://hypothes.is/roadmap/).

And, if you're interested in following up on this issue, please do continue the discussion on our [developer community mailing list](https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev). You might also want to check out [our contributing guide](https://github.com/hypothesis/h/blob/master/CONTRIBUTING.rst).
