### ISSUE TITLE
Annotation loaded, but not shown on Scalar "Cantaloupe" UI

### ISSUE THREAD

**Issue by BigBlueHat** [hypothesis/h#1443]
This page:
http://scalar.usc.edu/dev/dev-test-book-cantaloupe/index
Has this annotation:
https://hypothes.is/a/SHT2NV0YS0eaWG4zD_9TJg
However, it doesn't display.

The "Cantaloupe" UI for Scalar does *heavy* DOM manipulation--first loading an RDFa rich HTML document, then reformating that document with UI affordances for browsing, etc.

Here's the last 4 lines:
```
"Loading annotations for: http://scalar.usc.edu/dev/dev-test-book-cantaloupe/index" hypothesis-app.js:3
"Loaded" 1 "annotations." hypothesis-app.js:2
"Could not create anchor for annotation '" "SHT2NV0YS0eaWG4zD_9TJg" "'." hypothesis-assets.js:19
"Loaded" 0 "annotations." hypothesis-app.js:2
```

The XPath stored is `/article[1]/header[1]/h1[1]` but perhaps should probably be `//article[1]/header[1]/h1[1]` (which works).

**Comment by BigBlueHat** [comment]
Relates to hypothesis/vision#119

**Comment by judell** [comment]
Does not repro in 4.1.139.
