### ISSUE TITLE
Mockup URL space for per-User and per-Group storage model

### ISSUE THREAD

**Issue by BigBlueHat** [hypothesis/h#1471]
The public feed URL's could stay the same.

The "bucket" URL's could live somewhere like `/~bigbluehat` or `/~my-group-space` or `/~{group_UUID}` (using ye olde user URL's).

We could also try something like `/u/bigbluehat`, but I think that reads more like a filter on the public stream than as a separate space.

Discuss! :bulb:

**Comment by jeremydean** [comment]
ok, but will the user have to deal with all this or are we going to give them buttons or radio buttons?

(also, i'm in over my head here in these convos so pardon me if this is off topic.)

![screen shot 2015-04-02 at 2 48 50 pm](https://cloud.githubusercontent.com/assets/3261902/6970995/6bac2a02-d947-11e4-8b78-736cec7d57df.png)

![screen shot 2015-04-02 at 2 49 17 pm](https://cloud.githubusercontent.com/assets/3261902/6971000/75e8a7a2-d947-11e4-919b-894fa62b80a2.png)

**Comment by BigBlueHat** [comment]
The user would only see a list of visibility options. Right now, there are
two: "Public" and "Only me."

Groups would appear as additionally choices in the list (imagine: "Public"
| "Hypothesis" | "Only me."), and would subsequently map to its own storage
space / index (one for each group / audience).

The advantages are clear permission boundaries, simpler architecture
(because of that), and the ability for those storage spaces to be
anywhere--not just on hypothes.is.

The disadvantage is that searching across a combination of these storage
spaces would mean querying multiple indexes and aggregating the results.
The aggregate index would then become the plane we determine permission
around--not the storage location. Or there could be an index per
user--which would be super fabulous if it were in their browser.
:smiley_cat:

It streamlines quite a few things and preps nicely for federation.

Conceptually, the reading side of the coin is not unlike any RSS or Atom
feed reader--pull from the locations I'm subscribed to and let me search
those.

**Comment by edsu** [comment]
I just recently enjoyed reading [this](https://medium.com/@johnbattelle/blogging-meet-medium-please-procreate-aa2776b3ebfb) which got me looking for my own page on Hypothesis, similar to Battelle's list of [Medium highlights](https://medium.com/@johnbattelle/highlights). I did manage to find my way to https://hypothes.is/stream?q=user:acct:edsu@hypothes.is but it wasn't exactly obvious. Maybe it probably should be linked under the Account info in the menu bar?

Also, it would be great to be able to get my annotations as RSS/Atom for integration with things like IFTTT. I was hoping https://hypothes.is/stream.rss?q=user:acct:edsu@hypothes.is would work, but no dice. 

Sorry if this comment is off topic for this issue. I can move it elsewhere if it should be tracked differently.

**Comment by BigBlueHat** [comment]
@edsu thanks for the links!

There should be a `My Annotations` link under your Account menu (top right corner of the sidebar under your name) which takes you to a simpler version of the user query:
https://hypothes.is/stream?q=user:edsu

Sadly, the query parameters differ on the RSS & Atom feeds. The equivalent for those endpoints would be:
https://hypothes.is/stream.rss?user=edsu
https://hypothes.is/stream.atom?user=edsu

Also, fully qualifying the user name isn't a bad idea if you ever plan to work with multiple Hypothes.is instances. All those queries work equally well with the full `acct:edsu@hypothes.is`--which is your "real" URI in the Hypothes.is accounts space.

Hope that helps!

**Comment by edsu** [comment]
Oh wow, I'm not sure how I missed My Annotations -- clear as day now. Thanks for the links to the RSS too.

**Comment by edsu** [comment]
Oh wow, I'm not sure how I missed My Annotations -- clear as day now. Thanks for the links to the RSS too.

**Comment by edsu** [comment]
Oh wow, I'm not sure how I missed My Annotations -- clear as day now. Thanks for the links to the RSS too.

**Comment by edsu** [comment]
Oh wow, I'm not sure how I missed My Annotations -- clear as day now. Thanks for the links to the RSS too.

**Comment by nickstenning** [comment]
Hi there! I'm going to close this as part of a clean-up of all issues currently open on this repo that represent ideas or features rather than reports of bugs or technical chores. 

I want to be clear that **this isn't intended to say anything at all about the content of this issue**—it certainly doesn't mean we're no longer planning to do the work discussed here—just that we don't want to use GitHub issues to track feature requests or ideas, because the threads can get long and somewhat unwieldy.

If you're interested in what we are working on at the moment, you can check out [our Trello board](https://trello.com/b/o2ungX1n/current-sprint) and, for a longer-term view, [our roadmap](https://hypothes.is/roadmap/).

And, if you're interested in following up on this issue, please do continue the discussion on our [developer community mailing list](https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev). You might also want to check out [our contributing guide](https://github.com/hypothesis/h/blob/master/CONTRIBUTING.rst).
