### ISSUE TITLE
Tab problems when creating tags for an annotation

### ISSUE THREAD

**Issue by gergely-ujvari** [hypothesis/h#1484]
Steps to reproduce:
1. Create a new/reply to an annotation
2. Type in some text for the body
3. Click on the tag editor
4. Type in exactly 1-2 characters
5. Press tab

Result: 
![tab_problem2](https://cloud.githubusercontent.com/assets/2094134/4214517/21f91b0a-38c4-11e4-9e29-646679f74319.png)

So the control went to the save button which is inactive, and it can a bit confusing, because it seems at first that now the whole editor is "passive"

**Comment by gergely-ujvari** [comment]
Update on this issue.
Now the save button is active and you can save the annotation but tags shorter than 3 characters are automatically discarded. Not the best.

**Comment by gergely-ujvari** [comment]
So yes, reintroducing form-control would help here.

**Comment by dwhly** [comment]
> Ah, I think we have a limit on tags being at least 3 characters, we should either remove this limit or show an error message on the field.

I assume there's a technical reason for this.  Can someone explain?

> Now the save button is active and you can save the annotation but tags shorter than 3 characters are automatically discarded. Not the best.

Indeed.

**Comment by aron** [comment]
@dwhly no technical reason that I can see. I think it's common to do this to try and keep tags meaningful, e.g. "a" or "4" aren't ideal if you want people to converge around a common vocabulary.

**Comment by dwhly** [comment]
Lets go ahead and let people make the tags they want.  I don't see a reason to force people to adopt our constraints for tags.  A class instructor may want to use the letters of the alphabet for tags.  No reason she shouldn't be able to.

**Comment by csillag** [comment]
>  I don't see a reason to force people to adopt our constraints or sense of meaning.

This should be a configuration option at *at most*, which certain integrators might want to turn on. Our default installation shouldn't have restrictions like this.

**Comment by csillag** [comment]
>  I don't see a reason to force people to adopt our constraints or sense of meaning.

+1.

**Comment by aron** [comment]
Done in #1835
