### ISSUE TITLE
Gracefully handle expiration of API auth token

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#1492]
When the session expires the UI still appears logged in and things are broken.

**Comment by judell** [comment]
Presumably still the case. What is the time-to-expiration in the token, btw?

**Comment by tilgovi** [comment]
Looks like it's a week right now.

**Comment by tilgovi** [comment]
The issue describes session expiration, but there's also the API auth token that has a separate expiry that is much shorter, I think 1 hour.

**Comment by tilgovi** [comment]
I think this issue probably should be modified to describe the auth token. It is more likely that @dwhly experienced his token lapsing after a day (not refreshing a tab for a day) than that he had his session expire (which would mean a week of zero activity at all, on any hypothes.is URL).

**Comment by tilgovi** [comment]
I dunno if we should split those, whatever. Doesn't matter much to me. Happy for this to be a placeholder for both until someone has time to spec out what should happen in each case.

**Comment by judell** [comment]
OK, thx.

**Comment by judell** [comment]
"It is more likely that @dwhly experienced his token lapsing after a day (not refreshing a tab for a day)" Maryann just showed me the same thing in a tab inactive since yesterday. Attempt to annotate results in a 403 forbidden flash message in the sidebar. 

Retitling to reflect that we believe this is expiry of the API auth token.

**Comment by dwhly** [comment]
Got this during my demo on Saturday.  Tab inactive for about an hour.

**Comment by judell** [comment]
Verified today that the TTL is 1 hour, after which a page refresh is currently required. @tilgovi's original guess of a day seems more reasonable than an hour, any downside to expanding the window?

**Comment by tilgovi** [comment]
Always better to keep these tokens as short-lived as is reasonable. Limits the damage from a compromised token.

The right thing to do is refresh it, because the session lasts much, much longer (currently a month, I think).

**Comment by tilgovi** [comment]
Right now it seems silly, but ideally we wouldn't be sending the session cookie along with these requests. One should be able to make lots of API requests with the token alone and keep your session well secure. I mean, HTTPS and all, but https://en.wikipedia.org/wiki/Layered_security

**Comment by tilgovi** [comment]
Closed by db221d3eb12fc3ad7af087c5f722ca9b1ecf8ecd
