### ISSUE TITLE
Storage API Documentation

### ISSUE THREAD

**Issue by BigBlueHat** [hypothesis/h#1516]
[AnnotatorJS's Storage API documentation](https://github.com/openannotation/annotator/blob/3359eabb13fa7e422174df76cba421c5c87d4421/doc/storage.rst)--which, since we use a fork of it also serves for our docs atm--are fine for humans, but I wanted something that could be used to stub out other backend implementations...so docs for humans **and** robots was needed. :smile:

I've begun crafting some [RAML](http://raml.org/) docs for the Storage API:
https://anypoint.mulesoft.com/apiplatform/repository/public/organizations/2169/apis/2849/versions/2846/files/root (I'll add it as a separate comment also).

This was driven by a few conversations with partners who have an interest in building their own implementation of the API on their choice of database (vs. using `annotator-store` or `h` directly).

More to come.

**Comment by BigBlueHat** [comment]
Replaced by #2099

**Comment by judell** [comment]
I want to update the docs with what I learned last week about the /search API. Trying to sort out where everything is. Have encountered (so far):

https://github.com/hypothesis/h/blob/master/docs/api.rst

https://github.com/openannotation/annotator/blob/3359eabb13fa7e422174df76cba421c5c87d4421/doc/storage.rst

http://docs.hypothesis.apiary.io/

https://h.readthedocs.org/en/latest/api.html

Seems like https://github.com/hypothesis/h/blob/master/docs/api.rst should be the canonical source, and https://h.readthedocs.org/en/latest/api.html the canonical human-readable view?

Intending to tweak the former in my fork of it, this happened:

judell  Did https://github.com/hypothesis/h/blob/master/docs/api.rst used to be fully viewable in GitHub?
judell  exploring at http://rst.ninjs.org/, looks like this pattern -- .. http:get:: /api/search -- borks the viewer (Unknown directive type "http:get".)

**Comment by tilgovi** [comment]
You need sphinxcontrib-httpdomain for these HTTP documentation directives, so an online editor is probably not going to work.

Our repo is the source for h.readthedocs.org. So https://github.com/hypothesis/h/blob/master/docs/api.rst => https://h.readthedocs.org/en/latest/api.html

Similarly, for annotator.

**Comment by judell** [comment]
So if I want to propose changes to the .rst, I should view my changes before sending a PR using ____?

**Comment by tilgovi** [comment]
If you want to see what it will look on readthedocs.org, then you want to run `make html` from the docs directory.
