### ISSUE TITLE
Review annotation cards for new viewer

### ISSUE THREAD

**Issue by JakeHartnell** [hypothesis/h#1520]
During the last [design meeting](https://docs.google.com/a/hypothes.is/document/d/1tRHJToGElsuKwtm7rxzF_arC3hPZGSdAV4yqiSfIRXU/edit) we talked about some issues related to the cards that have arisen since view-sort-overhaul was merged. Some things to consider:

- The cards take up much more space than the used to, need to evaluate if this is a problem and then explore ways of reducing the height.
- Clearly distinguish between comments, annotations and highlights using iconography.
- Hover states on text elements feel inconsistent, the reply toggle has a red hover state when the thread is hovered, the timestamp and share links is only when the inner annotation is hovered. Reply and timestamp have two shades of red, reply links only have one.
- Pull quote always showing (Text collapses but quotes do not.) https://github.com/hypothesis/h/issues/487

Note: @aron has plans to look into the cards as a whole entity, so rather than open them as separate tickets we have lumped these points together into a larger issue.

**Comment by judell** [comment]
Suggest closing. Annotation density both in the sidebar and the document are major issues, but nothing concrete here to do. (I'm tracking this externally under the tag annotation_density.)

**Comment by tilgovi** [comment]
Yeah, that's fine. Closing. I think this was about finalizing the card design for Aron's alternative viewer implementation. Let's treat card positioning and card layout separately.
