### ISSUE TITLE
Review Open Annotation Data Model related AnnotatorJS plugins

### ISSUE THREAD

**Issue by BigBlueHat** [hypothesis/h#1529]
From the [AnnotatorJS plugins list](https://github.com/openannotation/annotator/wiki#plugins-3rd-party):
> - [lorestore Plugin](https://github.com/uq-eresearch/annotator/blob/master/src/plugin/lorestore.coffee) - an alternate store plugin that provides compatibility with OpenAnnotation as implemented by [lorestore](https://github.com/uq-eresearch/lorestore)
> - [Motivations Plugin](https://github.com/uq-eresearch/annotator/blob/master/src/plugin/motivations.coffee) - allows OA motivations to be attached to annotations
> - [Prov Plugin](https://github.com/uq-eresearch/annotator/blob/master/src/plugin/prov.coffee) - displays OA provenance properties in annotation viewer

@Treora you're into this sort of thing! :wink: Mind helping me review some of these for use with `h`?

**Comment by judell** [comment]
Still need doing?

**Comment by tilgovi** [comment]
Nah. None of these are going to end up being used because we'll be looking toward Annotator 2.0 as the development base for OA support, I think.
