### ISSUE TITLE
Implement the new filter bar design

### ISSUE THREAD

**Issue by aron** [hypothesis/h#1562]
Code is partially implemented here: https://github.com/hypothesis/h/tree/filter-bar-styles

This moves the viewer sorting out of the stream and into the filter bar in preparation for the pending viewer work. The intention is for this menu to grow in future with more filtering options such as facets etc. But the first step is just sorting.

With regard to the above branch, I’ve put the example markup in the app.pt for the moment. The idea is that the bar is hidden by default. When you click the icon the filter bar appears, clicking the icon again hides it. When a filter is active the icon is red. For the moment we only have sort filters, so those can stay the same.

![filter-bar](https://cloud.githubusercontent.com/assets/47144/4580257/0135bf96-4fd4-11e4-9a23-08007c83e704.png)

**Comment by robertknight** [comment]
A new design for the filter bar has been implemented in master. The dropdown is not the same as the design above, although the filter indicator in the toolbar is quite similar. I see there were a bunch of other issues being discussed here, they can be handled separately.
