### ISSUE TITLE
WSJ issues

### ISSUE THREAD

**Issue by csillag** [hypothesis/h#1587]
@dwhly ran into this a few days ago.

URL: http://online.wsj.com/articles/climate-science-is-not-settled-1411143565
Chrome. Latest live extension.

Steps to reproduce:

1. Go to the given URL.
2. Wait until the page finishes initializing (which might take longer than a minute)
3. Deploy H

Expected result: it works;
Actual result: it doesn't :)

In fact, deploying H on the page unleashes an unending torrent of error messages on the console, most of which does not even come from our code, but theirs.

I have not yet spent time to understand what the issue is; it might also be a problem with the site's code. (Maybe we can work around it, maybe not.) Or it might be our bug.

**Comment by BigBlueHat** [comment]
@tilgovi any guess where that code lives now?

@csillag is this still an issue for you? Getting support requests that match this issue in both FF and Chrome on Ubuntu 14.04.

Thanks! :coffee:

**Comment by tilgovi** [comment]
Doesn't appear to be valid anymore. Not seeing any strange messages in the console.
