### ISSUE TITLE
Orphaned annotations shown by default

### ISSUE THREAD

**Issue by csillag** [hypothesis/h#1612]
1. Open the welcome page
2. Create an annotation
3. Change the text you annotated
4. Reload the app
5. Observe that the annotation can not be reanchored properly, but the card is still there on the sidebar.

(You can see that it's not anchored by turning on always-on annotations, or by hovering the pointer over the card - no highlight will be activated, because there is none. It's an orphaned annotation.)

Earlier, we were not showing those, and according to @dwhly, we should not show them by default.

**Comment by tilgovi** [comment]
Closed by #2080
