### ISSUE TITLE
Update Chrome Extension to only use content scripts

### ISSUE THREAD

**Issue by aron** [hypothesis/h#1629]
Chrome Extensions can run code in "content scripts" that have access to the page DOM but are completely isolated from the page's javascript execution context. When a script is run with `chrome.tabs.executeScript` it is evaluated within a content script context. When a script tag is injected manually it is within the page context.

The problem we have with running in the page context is that we run the chance of conflicting with existing variables or even modified native objects.

In order to move away from this we need to use `chrome.tabs.executeScript` for everything. This includes replacing `yepnope` as well as the `configure` and `destroy` scripts.

Further reading:

https://developer.chrome.com/extensions/content_scripts#execution-environment
https://stackoverflow.com/questions/9915311/chrome-extension-code-vs-content-scripts-vs-injected-scripts

**Comment by tilgovi** [comment]
This is getting closed for now since it's too much for us to currently reason about multiple injection environments.
