### ISSUE TITLE
Upgrade angularjs to 1.3.x

### ISSUE THREAD

**Issue by gergely-ujvari** [hypothesis/h#1631]
Our current angularjs version (1.2.25) is legacy, so we should do the upgrade.
Also Angularjs 1.3.x has some new nice features we may use in the future.

**Comment by gergely-ujvari** [comment]
For the record we upgraded angularjs to the latest 1.2.x version, namely 1.2.28

**Comment by robertknight** [comment]
Angular has been upgraded to 1.4.7 on master.
