### ISSUE TITLE
Scrollable panes may have scrollbar covered by collapsed sidebar

### ISSUE THREAD

**Issue by Treora** [hypothesis/h#1657]
In PDFs, Hypothes.is prohibits interacting with the document's scrollbar. It's still visible because the collapsed sidebar is translucent, but trying to click it will open the sidebar instead.
![snapshot1](https://cloud.githubusercontent.com/assets/4191409/4976208/063a4f28-68ea-11e4-8fcd-faeeee0e21be.png)

**Comment by judell** [comment]
Not only a PDF issue, see http://www.a2gov.org/services/Pages/OpenCityHall.aspx?pd_url=http%3A%2F%2Fwww.peakdemocracy.com%2Fportals%2F116%2Fforum_home%3Fadmin_mode%253Doff

**Comment by tilgovi** [comment]
Change the title.

**Comment by seanh** [comment]
@judell Have to say I don't immediately see an obvious solution to this. Our sidebar slides in over the page. If the page has an embedded scrollbar (or anything else crucial) near the right hand side our sidebar is gonna cover it up. I'll take a look though

**Comment by seanh** [comment]
If you go to [any tumblr blog](http://rentzsch.tumblr.com/) there's a tumblr button in the top right, when you hover over it a tumblr sidebar slides in, it _pushes_ the page content instead of sliding over it:

http://youtu.be/7BqP1acaNZw

But this is a big change to h, and it just has the disadvantage of potentially pushing some of the content that you want to annotate off the left hand edge of the window.

I'll look and see if there's a simpler solution to this scrollbar issue

**Comment by judell** [comment]
Did this land as part of https://github.com/hypothesis/h/pull/2149? If not are there related items I'm not finding?

**Comment by tilgovi** [comment]
4c49e0349ba71b34ffb6ba19b168d234bb37b6d9 and 2a60244a9e1a2b66b91972e4e8d1d685b8182954

**Comment by tilgovi** [comment]
It still covers the scrollbar, but it doesn't intercept clicks on the scrollbar.

**Comment by judell** [comment]
OK, thanks.

**Comment by RawKStar77** [comment]
> It still covers the scrollbar, but it doesn't intercept clicks on the scrollbar.

So, where does that leave the state of this issue. Close?

**Comment by tilgovi** [comment]
@judell? See My and @RawKStar77 comments.

**Comment by dwhly** [comment]
Vote to close here.

**Comment by judell** [comment]
Ideally we'd close after a review of an integrated staging release including this and other things in flight. But for now, ok and thanks.

**Comment by tilgovi** [comment]
@judell this isn't the place to get into it, but I think that's got to happen in some other way. From a repo perspective, something is closed when the fix hits master.
