### ISSUE TITLE
Annotations on local documents breaks annotation card titles

### ISSUE THREAD

**Issue by aron** [hypothesis/h#1664]
Currently we wrongly assume that annotation urls are web links. So when displaying an annotation on a local document the title href, points to the document on the author's system. Secondly we fail to determine the parent domain and display empty parentheses.

![screen shot 2014-11-10 at 18 20 00](https://cloud.githubusercontent.com/assets/47144/4980184/d377b6f2-68fd-11e4-8919-fe8f90bcefab.png)

Documents without `http/s` protocols should not be links nor show parenthesis. We also indicated that this is an unaccessible document.

**Comment by lenazun** [comment]
This was solved by removing the link but showing the file name here: https://github.com/hypothesis/h/commit/1ac2d8c27ce2e77b6e899277d4c9689eed6e3fe8
