### ISSUE TITLE
Chrome extension: support local HTML documents

### ISSUE THREAD

**Issue by csillag** [hypothesis/h#1684]
Currently, this does not work, because of browser security restrictions.

But we could probably work around this, if we wanted, doing the same thing we are doing for local PDF:
- Create a "viewer" application, and ship it with the extension
- When the need arises to deploy H on a local HTML document, redirect the user to our viewer
- ... which would then load the local HTML document, and add H (just like we do with PDF)
- Hopefully, the "viewer application" could be as simple as an empty wrapper page, which loads the local HTML content in an iframe (or using some other method, if required by CSP restrictions).

The biggest challenge I see is that PDF documents have fingerprints, but HTML document have no such thing, so unless they have canonical URLs (or something similar), we would have no proper way to identify the documents, except the local path, which we might not want to save at all. So cooperation between different parties over offline documents might be difficult. (Of course, this could be solved by requiring some metadata in the document which can be used to reliably identify them.)

**Comment by ryanwwest** [comment]
The vision discussion is now closed, but I think this could be quite valuable nowadays for those who like to archive articles, blogs, and other sites to avoid link rot. Some people use the [Zotero Connector](https://chrome.google.com/webstore/detail/zotero-connector/ekhagklcjbdpajgpjgmbionohlpdbjgc?hl=en) browser extension to save local copies of both PDFs and HTML documents not only for academic use but for archival and personal use later on. Zotero allows annotating PDFs, but not HTML or ePUB (which H does at least through extensions), and it would be really nice to open up these locally saved files, annotate them (possibly saving the annotations locally as well), and potentially share them with others with the annotations (perhaps as a separate file) to get around the lack-of-a-fingerprint issue. 

It would of course be nice to open the URL version from where the local file originated and get the locally stored annotations loaded there as well, but that's a lot more complicated.

**Comment by ryanwwest** [comment]
See https://github.com/elias-sundqvist/obsidian-annotator, for example, who actually already uses the H client to do this very thing (including storing the annotations as a local file for HTML and ePUB, but not necessarily via Zotero). Its main problems are bugginess, not very actively developed, and restricted to Obsidian.
