### ISSUE TITLE
Prevent double embedding

### ISSUE THREAD

**Issue by BigBlueHat** [hypothesis/h#1688]
Pages like this [JEP post about Hypothes.is](http://quod.lib.umich.edu/j/jep/3336451.0017.201?view=text;rgn=main) include our `embed.js` by default. If you then turn on the Chrome extension or use the bookmarklet, you'll end up with two Hypothes.is (the Firefox extension currently has a different bug...which I'll post shortly).

Previous conversation around this issue can be found here:
https://github.com/hypothesis/h/commit/f80109b430e18ef9bf65a53d21be72e194fd6720#commitcomment-8561557

**Comment by csillag** [comment]
Solved in https://github.com/hypothesis/h/pull/2166. Moved this do "Done".

**Comment by csillag** [comment]
> Solved in https://github.com/hypothesis/h/pull/2166. Moved this do "Done".

Should we also close this?

**Comment by tilgovi** [comment]
I'm pushing to stage and going to give a quick test against extension and via.

**Comment by tilgovi** [comment]
The double embedding is indeed fixed.

**Comment by judell** [comment]
Hallelujah, and thanks.
