### ISSUE TITLE
Visibility setting is not always clear to users

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#1691]
@aron and I discussed a possible banner that would alert early users to the implications of the visibility status they've selected.   Either that what they're about to post is public, or that what they're about to post is private.  Either can be potentially confusing, depending on what the default setting is.  The banner might be able to be dismissed, or might only show for the first annotation.

**Comment by gergely-ujvari** [comment]
@tilgovi: Yes, IMO we want a separate issue for introducing a library for walkthroughs. Meanwhile let's decide on how to solve this issue too.

So let's make a poll.
- Do we want to implement @Treora's idea about changing the save to publish for public visibility?
- Do we want to move the visibility settings closer to the save/publish button?
- etc?

**Comment by BigBlueHat** [comment]
This just came up on the support@ list. I dug a bit into where the user was looking, and here was the response:
> I was looking at the bottom of the window – because I was ready to
"Save" and then paused, thinking "I remember there was some mention in
the website description of being able to set an annotation as public
or private," so I was hunting around for something in the vicinity of
the "Save" button – probably on the idea that it would either "save as
public" or "save as private".

So. I did this mockup. :smile_cat: 

---
![permissions rework](https://cloud.githubusercontent.com/assets/43209/6856350/ed3297e0-d3d5-11e4-9e3d-cb091e6897e2.png)

---
The one on the far right is the proposed solution. It puts the visibility options near the `Save` button (where folks are looking). Puts the current `CC0` note next to the visibility choice (which should hide if you switch to "Only Me"--note: it currently doesn't). It's also about 0.7em shorter thanks to dropping the user name out of the header. :smile: It was lonely, unnecessary, taking up space, and already in the top-right of the sidebar.

@RawKStar77 would love your thoughts on this draft. It should be fairly easy to implement...for someone who knows our angularz. :wink:

**Comment by tilgovi** [comment]
Sounds like a totally reasonable proposal.

**Comment by RawKStar77** [comment]
I would put the Save and Cancel button below the visibility setting. In the flow of creating an annotation, Save is the last thing you click, so it feels weird to me to put the visibility setting below the save button.

**Comment by BigBlueHat** [comment]
I'd actually wanted it up next to the `Save` button, but I couldn't quite make that work without more drastic UI movement.

Above it is OK by me, but I (personally) don't want to have to skip over it visually every time. It's a secondary thought to the `Save` action--again, for me personally. :smile: I think "I want to save this...oh...who else will see this."

There'd be more drafting to do if we move them into that button space. Your turn @RawKStar77? :wink:

**Comment by judell** [comment]
https://github.com/hypothesis/h/issues/1691

**Comment by judell** [comment]
https://github.com/hypothesis/h/issues/2285
