### ISSUE TITLE
Elasticsearch can fail for some document metadata mappings

### ISSUE THREAD

**Issue by hlapp** [hypothesis/h#1730]
On the following page I can make annotations, and they show while I keep the browser on the page, but none of them show the delete, edit, reply etc controls, and when I reload the page the annotations I just made are all gone: http://bioinformatics.oxfordjournals.org/content/28/19/2502.full

This is with being logged in, using Chrome on Mac OSX 10.10.1, and I have now verified that the extension seems to work fine on other sites (such as http://lappland.io), so it seems unlikely that it has something to do with my account, browser, or OS. I suspect the faulty behavior is because the annotations fail to save to the backend, hence the issue title, though of course I may be jumping to conclusions. And as there doesn't seem to be anything obviously special about said example page, I suspect this isn't the only page or site where the Hypothes.is extension isn't fully working. Also note that there is no error indication to the user.

I do have the Diigo extension, but the problem persists when I turn it off.

Here are some snippets from the JavaScript console that may shed light on what's going wrong:

    WebSocket connection to 'wss://hypothes.is/__streamer__/297/41hx9tk_/websocket' failed: WebSocket is closed before the connection is established.

    jquery.min.js?cf25e276:4 POST https://hypothes.is/api/annotations 500 (INTERNAL SERVER ERROR)

**Comment by gergely-ujvari** [comment]
I've tried this out with my local env, and the error does not happen. Maybe upgrading ES on prod will just simply solve this. (I'm using ES 1.3.2 )

**Comment by gergely-ujvari** [comment]
What version of ES are we using on prod?

**Comment by tilgovi** [comment]
Prod uses 1.3.1. It could be there was a change upstream to this. What I suspect instead is that during local testing ES is just detecting the field as a string. In production, some site must have had a proper date and ES auto-detected that. Then, a later index operation failed because the field failed to parse as a date.

**Comment by tilgovi** [comment]
@judell this is a nasty one we should consider for our next sprint, if we want more things to do around making sure we always retrieve the right annotations and store proper metadata. The result is discarded metadata.

**Comment by judell** [comment]
I'm able to annotate that page.

What I see at http://bioinformatics.oxfordjournals.org/content/28/19/2502.full is:

```
   <meta content="10/01/2012" name="citation_date" />
   <meta content="2012-10-01" name="DC.Date" />
```

In the Chrome console, window.annotator.getMetadata() reports both were successfully parsed.

@hlapp are you still seeing the same problem?

**Comment by tilgovi** [comment]
Oh, right. We don't try to parse dates anymore. I should have remembered this from my revisiting of this code last week.
