### ISSUE TITLE
Stream search icon shifts when extension is loaded

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/h#1764]
### Steps to reproduce

1. Go to https://hypothes.is/stream
2. Load the extension

### Expected behaviour

No change to display of stream UI.

### Observed behaviour

Stream search icon shifts upwards:

![screen shot 2014-12-04 at 17 17 42](https://cloud.githubusercontent.com/assets/3602/5301551/fea99e8c-7bd9-11e4-9a55-1a667ab48730.png)

**Comment by gergely-ujvari** [comment]
When we load the extension the `[class*=" h-icon-"], [class^=h-icon-]` rule is applied to the search icon setting the `line-height` property from 2 to 1.

**Comment by gergely-ujvari** [comment]
This rule is coming from the `hypothesis.min.css` and as I see this css contains the our `icomoon.css` and gets that rule from there.

Do we really need the icomoon on our inject part?

**Comment by aron** [comment]
@gergely-ujvari it's used for all the icons in the embedded document. Shouldn't be a too tricky to fix though, I'll look into it today.
