### ISSUE TITLE
As a user I would prefer not to see orphaned annotations...

### ISSUE THREAD

**Issue by RawKStar77** [hypothesis/h#1769]
...next to anchored ones in the sidebar so I can easily read content that applies to the current state of the document

### Acceptance criteria

- [ ] When I visit a page that has changed so much that some annotations don't anchor successfully, those annotations are hidden from view.

---

EDIT: Jake's original ticket: https://gist.github.com/aron/4d6119d4c8109e9dcbbf

**Comment by nickstenning** [comment]
Closing in favour of hypothesis/vision#153.
