### ISSUE TITLE
Bring back the padded scrolling

### ISSUE THREAD

**Issue by Treora** [hypothesis/h#1776]
When we scroll to a highlight (either by clicking an up/down arrow tab, or clicking an annotation (as fixed since #1634)), we scroll _just_ far enough to get the highlighted text into view. However, at least at the top of the screen, there are often bars covering a lines of the text, like for example on [Medium](https://medium.com/@jedsundwall/how-do-we-stay-sane-57b4078974fb). This makes me search every time where the highlight is until I discover it was just out of sight.

I suggest we scroll a little further so that it the highlight is not on the edge of the page. Maybe we want to get it exactly in the middle of the window?

**Comment by tilgovi** [comment]
Closed in 676f91812e10e286d14b77fe395a9ffaf5d24434
