### ISSUE TITLE
Firefox Add-on fixes post 0.2.2 submission

### ISSUE THREAD

**Issue by BigBlueHat** [hypothesis/h#1782]
Here's the feedback I got from the Mozilla Add-on (AMO) editors:

```
Your version was rejected because of the following problems:

Note: Addon contain 87 JS/JSM files.

1) Add-on contains duplicate/hidden/unused/unnecessary files or folders. These
complicate the review process and may contain sensitive information about the
system you created the XPI on. Please correct your packaging process so that
these files aren't included.

2) Please do not include both minified and non-minified versions of the same
libraries.

3) When including libraries, please only include the files that are needed and
used by the addon, instead of including the entire library package.

Examples:

resources/hypothesis/data/.sass-cache/ ... and its content

resources/hypothesis/data/scripts/vendor/Markdown.Converter.js
resources/hypothesis/data/scripts/vendor/Markdown.Converter.min.js
resources/hypothesis/data/scripts/vendor/angular-animate.js
resources/hypothesis/data/scripts/vendor/angular-animate.min.js
resources/hypothesis/data/scripts/vendor/angular-bootstrap.js
resources/hypothesis/data/scripts/vendor/angular-bootstrap.min.js
resources/hypothesis/data/scripts/vendor/angular-resource.js
resources/hypothesis/data/scripts/vendor/angular-resource.min.js
resources/hypothesis/data/scripts/vendor/angular-route.js
resources/hypothesis/data/scripts/vendor/angular-route.min.js
resources/hypothesis/data/scripts/vendor/angular-sanitize.js
resources/hypothesis/data/scripts/vendor/angular-sanitize.min.js
resources/hypothesis/data/scripts/vendor/angular.js
resources/hypothesis/data/scripts/vendor/angular.min.js
resources/hypothesis/data/scripts/vendor/annotator.auth.js
resources/hypothesis/data/scripts/vendor/annotator.auth.min.js
resources/hypothesis/data/scripts/vendor/annotator.document.js
resources/hypothesis/data/scripts/vendor/annotator.document.min.js
resources/hypothesis/data/scripts/vendor/annotator.domtextmapper.js
resources/hypothesis/data/scripts/vendor/annotator.fuzzytextanchors.js
resources/hypothesis/data/scripts/vendor/annotator.js
resources/hypothesis/data/scripts/vendor/annotator.min.js
resources/hypothesis/data/scripts/vendor/annotator.permissions.js
resources/hypothesis/data/scripts/vendor/annotator.permissions.min.js
resources/hypothesis/data/scripts/vendor/annotator.store.js
resources/hypothesis/data/scripts/vendor/annotator.store.min.js
resources/hypothesis/data/scripts/vendor/gettext.js
resources/hypothesis/data/scripts/vendor/gettext.min.js
resources/hypothesis/data/scripts/vendor/jquery-1.10.2.js
resources/hypothesis/data/scripts/vendor/jquery.min.js
resources/hypothesis/data/scripts/vendor/jschannel.js
resources/hypothesis/data/scripts/vendor/jschannel.min.js
resources/hypothesis/data/scripts/vendor/jstz.js
resources/hypothesis/data/scripts/vendor/jstz.min.js
resources/hypothesis/data/scripts/vendor/jwz.js
resources/hypothesis/data/scripts/vendor/jwz.min.js
resources/hypothesis/data/scripts/vendor/moment-timezone-data.js
resources/hypothesis/data/scripts/vendor/moment-timezone-data.min.js
resources/hypothesis/data/scripts/vendor/moment-timezone.js
resources/hypothesis/data/scripts/vendor/moment-timezone.min.js
resources/hypothesis/data/scripts/vendor/moment-with-langs.js
resources/hypothesis/data/scripts/vendor/moment.min.js
resources/hypothesis/data/scripts/vendor/ng-tags-input.js
resources/hypothesis/data/scripts/vendor/ng-tags-input.min.js
resources/hypothesis/data/scripts/vendor/polyfills/autofill-event.js
resources/hypothesis/data/scripts/vendor/polyfills/autofill-event.min.js
resources/hypothesis/data/scripts/vendor/polyfills/wgxpath.install.js
resources/hypothesis/data/scripts/vendor/polyfills/wgxpath.install.min.js
resources/hypothesis/data/scripts/vendor/sockjs-0.3.4.js
resources/hypothesis/data/scripts/vendor/sockjs.min.js
resources/hypothesis/data/scripts/vendor/uuid.js
resources/hypothesis/data/scripts/vendor/uuid.min.js

Please fix them and submit again. Thank you.
```

Mostly looks like some pruning of the assets.yml for this scenario.

Lots of `.min.` files we can ignore and instead ship the full copy (which they require), example: `uuid.js` vs. `uuid.min.js`

/cc @dwhly

**Comment by BigBlueHat** [comment]
@aron @tilgovi  mail me the email addresses you use for your http://addons.mozilla.org accounts (rashly assuming you have one :smiley: ). If you don't have one, get one. :wink: 

I'll get this resubmission going now regardless.

**Comment by BigBlueHat** [comment]
Resubmitted. "Queue Position: 30 of 30" Promising... :smile:

**Comment by pguth** [comment]
Uah, this is taking ages...

**Comment by dwhly** [comment]
Position 26 out of 45 as of this morning.

**Comment by pguth** [comment]
Thanks for the update!

**Comment by BigBlueHat** [comment]
@pguth if you're just wanting to try it out, you can get it here:
https://addons.mozilla.org/en-US/firefox/addon/hypothesis/

It's just not approved by the Mozilla editors yet. Doesn't mean it doesn't work, though. :wink:

**Comment by pguth** [comment]
@BigBlueHat ah, I didn't know that. Thank you very much! Maybe make that public under https://hypothes.is/alpha/ as `alpha` fits that stage quite perfectly?

**Comment by pguth** [comment]
@BigBlueHat Ah, it is actually not working with the latest [Firefox Developer Edition](https://www.mozilla.org/en-US/firefox/developer/) :-(
Buttons appear but do not work at all. After a restart of Firefox I can not login anymore ('Session is invalid. Please try again. '). I also tried deleting my hypothesis cookies.

**Comment by aron** [comment]
Hmm, I'm seeing some issues too, I can log in but the web socket connection doesn't seem to be working. @BigBlueHat can you also give it a shot?

**Comment by BigBlueHat** [comment]
Yeah...just checked. Toolbar button does work for me: injects the embed.js which in turn successfully loads the sidebar. However, beyond that, nothing works...

I'm logged in, can open and close the sidebar, all the HTTP requests checkout fine, but nothing happens beyond the `101 Switching Protocols` sent in response to `GET https://hypothes.is/ws`.

Bookmarklet on the same page works swimmingly. Testing with https://themanual.org/read/issues/4/paul-ford/article

I'm not finding anything in either console (Web or Browser) that shows any sign of error or even warning. :frowning:

**Comment by csillag** [comment]
> I'm not finding anything in either console (Web or Browser) that shows any sign of error or even warning. :frowning:

That's the best kind of problem to debug. Utter dysfunction in total silence. Good luck!

**Comment by tilgovi** [comment]
I see no issues with the WebSocket but I get no adder on selections.

**Comment by BigBlueHat** [comment]
@tilgovi are you seeing any annotations in the sidebar?

**Comment by tilgovi** [comment]
Nope.

**Comment by tilgovi** [comment]
Another issue I see, not sure this was always present, is this:

    downloadable font: OS/2: bad linegap: -64 (font-family: "h" ...

**Comment by tilgovi** [comment]
I see the token request but then no search request. Also, what version of the code did we submit? I thought we started using the same version numbers as h?

**Comment by tilgovi** [comment]
Closing. Moved to #1956
