### ISSUE TITLE
Cannot close share-popup

### ISSUE THREAD

**Issue by gergely-ujvari** [hypothesis/h#1802]
1. Select an annotation card
2. Click on the Share link/icon.
3. Observe that a popup appears with the standalone-page link

However there is no way to close this popup except pushing the edit button and cancelling the edit.
I expect that if I click on the share icon again then the popup will disappear.

**Comment by gergely-ujvari** [comment]
@aron was right. The `stopPropagation()` prevents closing the share-popup in our `thread` directive.

**Comment by gergely-ujvari** [comment]
The source of the problem is that we attach an event to the `$document` to close that share 'popup' when we click anywhere inside our sidebar (https://github.com/hypothesis/h/blob/master/h/static/scripts/directives/annotation.coffee#L344). But there are many places where we stop event propagation (i.e. all annotation cards because of the thread directive) causing the document not receiving the event.

If we want to stick on attaching the event to the `document` (as this represents the fact that we want to close the share dialog if I click to anywhere in the sidebar), then either we invent same kind of 'unstoppable'  events, or we manually feed the events to the `document` which were stopped from propagating. Neither of those sounds nice.

An alternative could be to review our directives and weed out the `stopPropagation()` calls if possible, but I'm not sure we can do this.

A second alternative could be to handle this share 'popup' more like an old-school popup, setting a time limit for it if it looses focus and it'd close itself.

**Comment by BigBlueHat** [comment]
+1 for fixing this as folks are reporting the bug to support@hypothes.is now.

**Comment by tilgovi** [comment]
Recommend this solution:

- Use the 'blur' event on the input
- Remove the "open" class after a delay, so that cicking on the icon inside the dialog still works.
