### ISSUE TITLE
Unclear whether buttons in toolbar are off or on

### ISSUE THREAD

**Issue by RawKStar77** [hypothesis/h#1806]
This has come up in user testing multiple times now, and I think the fix is pretty simple. Basically, it's hard to know if a toolbar button is off or on. Users click the button for example for highlight mode or show highlights, and then often click it again because they are unsure if the setting has changed. I think the problem stems from 

We can be much clearer by having the color explicitly change when clicking on it (red = on, clear = off). Currently, it just moves a bit which is not sufficient and seems to be causing a bit of completely unnecessary confusion in user tests. Additionally, the button is red even when it is off and you are not hovering over it... I think this adds to the confusion.

![toolbarconfusion](https://cloud.githubusercontent.com/assets/521978/5442038/7f295c0a-844a-11e4-9e25-9688c74e6528.jpg)

**Comment by nickstenning** [comment]
This appears to be fixed on master.
