### ISSUE TITLE
Investigate loading the bundled app.html file into the iframe in the FF extension

### ISSUE THREAD

**Issue by aron** [hypothesis/h#1819]
Currently due to [a bug](https://bugzilla.mozilla.org/show_bug.cgi?id=792479), you cannot load a local html file into an iframe. I've seen a number of workarounds online.

* Using data uris for the html source. I've quickly tried this and it works, but the data uri plays havoc with the angular router causing infinite digest errors. Might be fixable though.
* Hosting a remote shell page and using post message to send through the html content to a parent page. I don't know if this actually has any benefit over just pointing to our primary domain.

Resources:

* https://blog.mozilla.org/addons/2012/01/11/sdk-1-4-known-issue-with-hard-coding-resource-uris/
* http://stackoverflow.com/questions/21082162/firefox-addon-sdk-loading-addon-file-into-iframe

**Comment by tilgovi** [comment]
This can be done with a data URI, but we're pushing the limit of the length of that right now. It would help greatly if we separated the widget and the site bundles so that the sidebar only contained the code and templates for the sidebar widget rather than the whole application.

**Comment by nickstenning** [comment]
The old Firefox extension is no more, so I'm going to close this issue. Hopefully a new WebExtensions-based Firefox extension will not have the same problems.
