### ISSUE TITLE
Realtime annotations leaking between targets

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#1840]
What I did:
- Pulled up two *different* pages in chrome.
- Launched the extension on both.  Open the sidebars.
- Annotate one, and the annotation shows in the sidebar on the other page.

I did proved this using these two URLs:
- http://uk.businessinsider.com/?r=US
- http://www.lolcats.com/
But it doesn't seem to matter.

If I reload the page that was not annotated, the misrendered annotation is no longer there.

**Comment by dwhly** [comment]
To be clear.  From what I can tell, all annotations made on any page are now being made visible to any other person on any other page if they have the extension enabled.

**Comment by nickstenning** [comment]
Fixed by #1841.
