### ISSUE TITLE
Realtime updates are not available until you force a digest cycle if the page has no annotations

### ISSUE THREAD

**Issue by gergely-ujvari** [hypothesis/h#1842]
1. Choose a web-page which has no annotations.
2. Enable the extension/bookmarklet on it
3. Switch away that tab/browser without clicking anywhere inside that page, and without moving the mouse cursor to the sidebar
4. Open the same page in another tab/browser
5. Create an annotation
6. Switch back to the other tab/browser

Expected: Via realtime updates the annotation appears there too.
Observed: The annotations doesn't appear.

Cause: https://github.com/hypothesis/h/blob/master/h/static/scripts/controllers.coffee#L132
No digest cycle is triggered to send the filter via the streamer service.

If the page has any annotation its processing will trigger the digest cycle and this problem goes away.
The same happens when clicking anywhere to start highlighting or playing with the sidebar.

**Comment by tilgovi** [comment]
I think you diagnosed this correctly. Here is where the digest is missing.
https://github.com/hypothesis/h/blob/master/h/static/scripts/services.coffee#L108
