### ISSUE TITLE
Stream search sometimes displays invisible annotations

### ISSUE THREAD

**Issue by gergely-ujvari** [hypothesis/h#1844]
Detected on master branch

1. Create an annotation. 
2. Choose a word from its body and from its quote to search for. (I.e. 'test' and 'scale')
3. Open stream
4. Search for "test" (observe that the search finds the newly created annotation)
5. Search for "test quote:scale" (observe that the search finds the newly created annotation)
6. Search for "test scale"

Result: No annotation is displayed.
Expected: Newly created annotation is displayed.

And here comes the trick. Use inspect element in your browser and you'll see that the annotation card is there, but hidden!
Path: `html -> body.ng-scope -> div#wrapper -> main.content.ng-scope -> ul.stream-list.ng.scope -> li.paper.thread.ng-scope.ng-hide`

Or if you insert a console.log or watcher to the `applyUpdates` function (https://github.com/hypothesis/h/blob/master/h/static/scripts/controllers.coffee#L19) you'll see that the backend gives back the search results yet they're displayed invisibly.

This has to be fixed.

**Comment by tilgovi** [comment]
Probably differences between search on the front-end and back-end. Currently, the search filters on the front-end are still active even on the stream page, even though the annotations are cleared and loaded according to the query from the backend.
