### ISSUE TITLE
via.hypothes.is giving a "redirect loop" at the NYT

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#1845]
Click here:

https://via.hypothes.is/h/http://www.nytimes.com/2015/01/12/business/media/pop-music-critic-leaves-the-new-yorker-to-annotate-lyrics-for-a-start-up.html?gwh=D7261152B8A43951CDB507B033AE73A8&gwt=pay&assetType=nyt_now&_r=0

**Comment by tilgovi** [comment]
Please file this against hypothesis/via.
