### ISSUE TITLE
Scrolling to annotations (by clicking on the annotation card) is [partially] broken

### ISSUE THREAD

**Issue by csillag** [hypothesis/h#1873]
When the user clicks on an annotation card in the sidebar, the document scrolls to reveal to corresponding highlight. (Just like when the user clicks on the up/down arrows on the ~~heatmap~~ bucket bar.)

This is supposed to work even on PDF, and other lazy-rendering environments. 

However, it looks like this feature has been partially broken by one of the refactoring of the "focus" behavior, so now the the scrolling sometimes fails in lazy-rendered environments.

To reproduce:
 - Go to a PDF file (10 pages minimum)
 - Create an annotation at the bottom
 - Go back to to top
 - Refresh, redeploy
 - Click on the card

**Comment by tilgovi** [comment]
Thanks for your patience with me on this @csillag
