### ISSUE TITLE
Don't center Math

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#1877]
I *think* we agreed not to center math.

![screen shot 2015-01-22 at 8 23 02 am](https://cloud.githubusercontent.com/assets/1413074/5859549/ebe62cd2-a20f-11e4-9015-09a35076a3ef.png)

**Comment by dwhly** [comment]
Discussion w @RawKStar77 seem to indicate that Katex is not centering and Mathjax is.  Adding jake on as owner.

**Comment by RawKStar77** [comment]
Fixed with https://github.com/hypothesis/h/pull/1884
