### ISSUE TITLE
Notification panel visible in stream view, but not sidebar.

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#1880]
Open sidebar / account.
Notification panel not visible.

![screen shot 2015-01-23 at 11 12 37 am](https://cloud.githubusercontent.com/assets/1413074/5880972/915b6f9c-a2f1-11e4-822a-56d0159bce33.png)

Works on /stream.

**Comment by aron** [comment]
Very strange, it's appearing for me in both sidebar and stream for all browsers. I wonder if it's something to do with your subscription settings?

**Comment by dwhly** [comment]
My subscription settings shouldn't affect whether the panel is there or not, right?

**Comment by BigBlueHat** [comment]
@aron were you testing the Chrome extension? or the bookmarklet or FF extension?

**Comment by gergely-ujvari** [comment]
I'm seeing this using Chrome extension.

**Comment by aron** [comment]
@BigBlueHat I was using the /docs/help page, I'll build a new extension, test and submit it.

**Comment by aron** [comment]
Okay, I've built and submitted 0.3.2.1254 to the store, it should be available in 30 mins or so.

**Comment by gergely-ujvari** [comment]
Yes, now I see the notification tab with the chrome extension.
