### ISSUE TITLE
Math syntax breaks when rendered inside backticks

### ISSUE THREAD

**Issue by aron** [hypothesis/h#1885]
Example:

```
[..] within enclosing `\( ... \)` for short snippets, or `$$ … $$` for longer blocks.
```

Rendered:

![screen shot 2015-01-27 at 10 03 45](https://cloud.githubusercontent.com/assets/47144/5915945/cc22b514-a60b-11e4-8c8b-b537b10b41b2.png)

This might be fixed by swapping the order of the processors, really though we should probably look at extending the Markdown processor to support the new syntax.

**Comment by RawKStar77** [comment]
> really though we should probably look at extending the Markdown processor to support the new syntax.

+1

**Comment by RawKStar77** [comment]
Closing in favor of https://github.com/hypothesis/h/issues/763
