### ISSUE TITLE
Cron / Worker script for periodic tasks

### ISSUE THREAD

**Issue by BigBlueHat** [hypothesis/h#1891]
Related to hypothesis/vision#151, we need a simple script that runs in the same permissions / setup space as the rest of h, but who's primary purpose is one-off execution of various tasks.

Current / primary use case is...
* [ ] calculating various metrics
* [ ] storing the output (in a CSV or sqlite table)
* [ ] emailing the results

**Comment by gergely-ujvari** [comment]
I've a question here. Do we want to give full access to this script to our ES/user db or should it use our search/etc api for accessing it with an admin user? If yes, how can we set up a user like this?

**Comment by tilgovi** [comment]
Won't do this. When #1871 is merged we can run other scripts that generate their own authorization tokens for an admin user.

**Comment by tilgovi** [comment]
Re-opened, but now I see why I closed it. Should be in vision.

**Comment by BigBlueHat** [comment]
@tilgovi I'd thought you'd closed it due to a different approach being preferred (re: your earlier comment).

**Comment by nickstenning** [comment]
Closing in favour of a problem-oriented story vision#151.
