### ISSUE TITLE
Text box does not get focus upon new annotation creation

### ISSUE THREAD

**Issue by Treora** [hypothesis/h#1894]
Issue occurs consistently in Firefox, but all works fine in Chromium. Occurs using current master, and I think it's been like this for quite a while.
To reproduce: select a piece of text, click the annotation button that pops up. Sidebar opens and editor shows with text area, but it stays grey and unfocussed.

**Comment by RawKStar77** [comment]
Can't reproduce in Firefox, Chrome, or Chromium on current master. Closing...
