### ISSUE TITLE
'Show Annotations' mode not or not wholly enabled upon load

### ISSUE THREAD

**Issue by Treora** [hypothesis/h#1895]
When enabling the extension/bookmarklet, 'show annotations' should be on by default.
![screenshot1](https://cloud.githubusercontent.com/assets/4191409/5939022/cb212436-a708-11e4-94c8-9952239f2e37.png)

In Firefox, it is not turned on at all.

In Chromium it is turned on, but in the toolbar the eye button is not shown as pressed (nor coloured red). And when it is clicked, it works fine (disables the mode), but becomes red and stays red upon subsequent clicks.

**Comment by aron** [comment]
Part two, is fixed in #1883

**Comment by seanh** [comment]
Tested production hytpothes.is today: bookmarklet in Firefox shows the eye icon filled in by default, and does show the annotation highlights inline too. Addon in Chrome is the same. Fixed?

**Comment by tilgovi** [comment]
Yep.
