### ISSUE TITLE
Default limit is not enough for search requests

### ISSUE THREAD

**Issue by gergely-ujvari** [hypothesis/h#1897]
How to reproduce:
1. Check this annotation, it'll be our exemplary one: https://api.hypothes.is/annotations/mkXj3RyVSYyBK7OnH94Wwg
2. Notice its uri: http://online.wsj.com/articles/climate-science-is-not-settled-1411143565
3. Launch a search request for this uri: https://api.hypothes.is/search?uri=http://www.wsj.com/articles/climate-science-is-not-settled-1411143565
4. And a next one with bigger limit: https://api.hypothes.is/search?uri=http://www.wsj.com/articles/climate-science-is-not-settled-1411143565&limit=5000

Notice that the first search request doesn't retrieve our annotation, the second one does.
When we launch search requests for our app, we do not set the limit, that means older annotations are not loaded into the sidebar.

This has to be fixed.
As a workaround I'll increase the limit but we should work on a more robust solution.

**Comment by gergely-ujvari** [comment]
What is really interesting that the `total` field's value is 43 in both cases yet the results are different.

**Comment by gergely-ujvari** [comment]
As I see the default limit is 20. So from the 43 annotations we retrieve 20. But the count number is misleading.

**Comment by Treora** [comment]
The value of `total` has always been the total number of items that match
the query, not the number of items that are returned. This makes sense as
one can use this information, for example a hypothetical paginated client
could calculate how many pages of annotations it should show.

**Comment by gergely-ujvari** [comment]
@Treora: yes, right. Good point.

**Comment by gergely-ujvari** [comment]
As a workaround I increased the limit to 200 (instead of 20) in this commit: https://github.com/hypothesis/h/commit/6bd953441cd07df5a424d2a89d1b96aa49e4b29c, but we need to invent a permanent solution for this. (loading more via websocket can help via scrolling down)

**Comment by Treora** [comment]
I kept this default limit at 20 when rewriting our API endpoints. We used
to always provide `limit=1000` in the search query, I don't know when that
disappeared.

For the longer run, we should indeed think about dynamic loading again, but
I suppose we can do without it for now. (and ideally we would first load
the x most relevant annotations)

**Comment by gergely-ujvari** [comment]
It disappeared when we dropped the annotator store plugin.

**Comment by tilgovi** [comment]
For the time being we should probably load more, via pagination, up to a certain limit, and leave a TODO in the code about possibly showing an indication of this and a way to load more in the UI. I don't know what the right chunk size is, so I would leave it at 20. It probably depends on the connection latency, throughput, CPU, etc.

**Comment by nickstenning** [comment]
Closing in favour of hypothesis/vision#154.
