### ISSUE TITLE
[Chome] [Extension] If a sites serves us PDF, but it doesn't declare it so in the filename, we fail to inject

### ISSUE THREAD

**Issue by csillag** [hypothesis/h#1900]
That's because our extension code only recognizes a PDF file from the filename.

We need to add some better detection.

@RichardLitt suggested [this code](https://github.com/BeagleLab/beagle/blob/master/js/main.js#L71-L81).

**Comment by RichardLitt** [comment]
[Example](http://www.plosone.org/article/fetchObject.action?uri=info:doi/10.1371/journal.pone.0115253&representation=PDF)

**Comment by csillag** [comment]
Btw, [here](https://github.com/hypothesis/h/blob/63d22c83485ecbc931426a6276112c2067488877/h/browser/chrome/lib/sidebar-injector.js#L65) is the code, that we are currently using to recognize a PDF file.

**Comment by csillag** [comment]
Example URL: http://www.plosone.org/article/fetchObject.action?uri=info:doi/10.1371/journal.pone.0115253&representation=PDF

**Comment by tilgovi** [comment]
Looks fine. I would suggest requiring that the embed tag also have `name="plugin"`. The Chrome PDF viewer seems to do this. It might avoid a false positive when a page is actually HTML that contains as merely one thing in it an embedded PDF, but where the PDF document is not _the_ document.

**Comment by dwhly** [comment]
Bumping this.  Reported 2x in 2 days.

**Comment by judell** [comment]
An amusing workaround: I changed http://poseidon01.ssrn.com/delivery.php?ID=137098066007090115070127002103026089032018023086008028101069091065073095098024101121048045116005042126027029099118119074000120049004063019046069083002114070126094030082056120015097075112002090077100016105005106000080097008070075016114025005090106&EXT=pdf&TYPE=2

 to

 http://poseidon01.ssrn.com/delivery.php?ID=137098066007090115070127002103026089032018023086008028101069091065073095098024101121048045116005042126027029099118119074000120049004063019046069083002114070126094030082056120015097075112002090077100016105005106000080097008070075016114025005090106&EXT=pdf&TYPE=2&name=foo.pdf

That enabled H to inject, and associate the PDF hash with the set of aliases.
