### ISSUE TITLE
annotator-toolbar obscured by Tumblr control's max z-index

### ISSUE THREAD

**Issue by judell** [hypothesis/h#1909]
Related to #683, Tumblr obscures the toolbar. It is using the max z-index (http://stackoverflow.com/questions/8565821/css-max-z-index-value).

Example: http://evgenymorozov.tumblr.com/. 

It's a scary game of one-upmanship, but possible of course to search for elements (hopefully a small set, maybe just iframes and divs?) with max z-indexes, lower them, and raise annotator-toolbar above them.

**Comment by tilgovi** [comment]
I would rather not start lower z-index values for elements we don't control. If this continues to be a problem in many places we should consider a different UI solution.

**Comment by judell** [comment]
OK then!
