### ISSUE TITLE
Invalid tab numbers

### ISSUE THREAD

**Issue by gergely-ujvari** [hypothesis/h#1912]
Detected on https://stage.hypothes.is/

When I load the page the numbers on the tabs said there are 3 annotations on the page, but in the sidebar obviously more annotations are loaded. They have to be consistent.

![invalid_tab_number](https://cloud.githubusercontent.com/assets/2094134/6062492/878226dc-ad50-11e4-91b7-18b439f8d8ba.png)

**Comment by gergely-ujvari** [comment]
+ Info: It seems the numbers can change at every load.
I opened two tabs for the same page and used the same bookmarklet and got different results.

Result 1:
![invalid_tab_01](https://cloud.githubusercontent.com/assets/2094134/6062601/5666b9a4-ad51-11e4-93aa-2d492abccd64.png)

Result 2:
![invalid_tab_02](https://cloud.githubusercontent.com/assets/2094134/6062605/59e5336c-ad51-11e4-99d9-0023045620a3.png)

**Comment by tilgovi** [comment]
I cannot see from this issue that there is a problem. For example, if annotations fail to anchor they won't show in the tabs but they will be in the sidebar. As to them being different on different loads, I can't see from the screenshot if you're scrolled to the same place, same size viewport, same login state, etc. There's not enough information here to diagnose a problem. Please reopen with more info.

**Comment by gergely-ujvari** [comment]
More info, round 1:
Yes, you're right, that anchors are not counted into any tab. That is confusing but we have an issue for that so not relevant here)

But, threads where the root annotation is deleted are not anchored, because the root element is deleted.
Of course this way it is impossible to anchor them, but now these discussion have much less meaning then before.

What I mean, that when we had redaction, at least the anchoring stayed and we knew to which part of document that discussion was going on. Now they're floating in the air, that's terrible.

**Comment by gergely-ujvari** [comment]
I've made a slight correction in my previous comment in this thread.

**Comment by gergely-ujvari** [comment]
More info, round 2:
This is different, from the previous problems.

1. Open http://hypothes.is/ in two different tabs within the same browser. Use the same zoom level, and do not scroll to anywhere (so let's be top on both pages)
2. Open https://stage.hypothes.is/ in a third tab, log off if you're logged on (that way we can see the same) and apply its bookmarklet to both of the previously opened tab.
3. Observe the tab numbers.

For me, in the first page I see:
- A bucket with the number 4 on it,
- A  lower bucket with the number 10 on it.
In the second page, I see:
- A bucket with the number 6 on it,
- A  lower bucket with the number 15 on it.

And obviously the numbers should be equal, not different. I'm using Chrome40.

And this is an issue.



For me:

**Comment by tilgovi** [comment]
I see the same numbers in both.
