### ISSUE TITLE
WebSocket is already in CLOSING or CLOSED state

### ISSUE THREAD

**Issue by gergely-ujvari** [hypothesis/h#1913]
I'm seeing this error sporadically on stage.

If I deploy the bookmarklet to any page I see this on console log

```
WebSocket is already in CLOSING or CLOSED state.app.min.js:5201 
Streamer.send app.min.js:5201
```

**Comment by tilgovi** [comment]
Looks like stage hasn't been deployed in a while. I think this has been fixed. I'll deploy stage now.
