### ISSUE TITLE
Realtime notifications are broken

### ISSUE THREAD

**Issue by gergely-ujvari** [hypothesis/h#1914]
Detected on stage.

I've opened the same pages in two different tabs and created an annotation on the first one.

Expected: The annotation appears on the second page.
Actual: It doesn't.

And this is a different bug from #1913 because there is no error or warning message this time.

**Comment by dwhly** [comment]
From what I can tell notifications are broken live too.

**Comment by tilgovi** [comment]
Yes. We need an environment config override in h/config.py for the settings key 'origin' and than we can set this in our production environment to trust our chrome-extension origin. Right now we are denying the WebSocket request based on the HTTP Origin header.

**Comment by aron** [comment]
PR for this here #1922

**Comment by dwhly** [comment]
This is still an issue live.

**Comment by gergely-ujvari** [comment]
@dwhly: I've just tried this out with the current extension and it is seem to be working for me. Can you add the url where it wasn't working? Maybe it has something to do with the page.

**Comment by dwhly** [comment]
Try this one with me now:
https://www.techdirt.com/articles/20150202/08473429881/guardian-salon-show-how-keeping-fixing-news-comments-isnt-hard-if-you-give-half-damn.shtml

**Comment by dwhly** [comment]
Wait-- what's the current extension build?

**Comment by gergely-ujvari** [comment]
I'm using:  0.3.2.1490

**Comment by dwhly** [comment]
Arg.  That was it.  Sorry. :)
Q: How quickly does chrome typically check for new versions of extensions?

**Comment by gergely-ujvari** [comment]
@dwhly: https://stackoverflow.com/questions/24100507/how-often-do-chrome-extensions-automatically-update (In short: 5 hours)
