### ISSUE TITLE
Gollam easter-egg when applying stage bookmarklet on hypothes.is

### ISSUE THREAD

**Issue by gergely-ujvari** [hypothesis/h#1915]
Now I'm seriously not believing my own eyes.

Let's deploy the stage's bookmarklet into http://hypothes.is/
and check the network tab.
Jquery initiates to load a picture from s3.rapgenius: 

```
Remote Address:54.231.2.48:80
Request URL:http://s3.amazonaws.com/rapgenius/DQSzH9WFTNiXyCpYEKvo_golum.jpg
Request Method:GET
```

 This picture:
![dqszh9wftnixycpyekvo_golum](https://cloud.githubusercontent.com/assets/2094134/6062941/eae12068-ad53-11e4-928e-1ac247d69f70.jpg)

WHY?

**Comment by aron** [comment]
@gergely-ujvari sometimes it pays to do a little investigation before opening an issue.

https://stage.hypothes.is/a/uPCO1rcGRz2EWVoPfcFYwQ

**Comment by gergely-ujvari** [comment]
Lool, okay, :)  I haven't noticed that.
