### ISSUE TITLE
Too many message not available on stream

### ISSUE THREAD

**Issue by gergely-ujvari** [hypothesis/h#1916]
When I open a stream page I often see too many "message not available" cards with some replies.
This is very confusing for a normal user and he/she may believe that the stream is not working.
![bad_stream](https://cloud.githubusercontent.com/assets/2094134/6063123/2965fea2-ad55-11e4-90df-a488cd0c5b49.png)
 
The cause of this error that our search requests are sorted (and sadly this is "hardcoded" in the backend) by the updated field descending.

This means that the replies (as they were created later then the parent) are retrieved before their parents thus resulting in "Message not available" cards with replies that you can open. 
Of course scrolling down solves this as by the inf. scrolling feature the parents will be loaded eventually.

We have to seriously improve this.

**Comment by tilgovi** [comment]
Proposal: simply hide them.

Modify the `shouldShowThread` scope method in the `StreamSearchController` to return false when `container.message` is `null`.

**Comment by aron** [comment]
I'm not sure hiding them is a solution here. If the query is paged to say 20, then I would expect to see a stream with 20 annotations in it regardless of each annotations children.

The stream query should either only be returning the top level annotations that match the query expecting the client to then make further requests for replies. Or the server should be cleverer about what it returns and ensure that it returns entire threads.

**Comment by dwhly** [comment]
So, yesterday I went to the stream searching for an annotation I made.  I had replied to someone else's annotation, and then about an hour later, couldn't remember which page it was on.  So I went to the stream assuming that it would be there, and it wasn't. It was most likely at the bottom somewhere in one of the cards.

Imagine, you reply to an annotation that's months old.  Should you see your reply at the top of your personal stream-- perhaps with the parent collapsed?  I think so.  So, if we get replies we should fetch their parents I think.

**Comment by tilgovi** [comment]
@dwhly depends on what the stream is for, as we've talked about so many times but never resolved.

**Comment by nickstenning** [comment]
Consensus is that we should hide these for now.

**Comment by dwhly** [comment]
@RawKStar77 I've taken an issue for us to work on user stories for the stream so that we can address the question of how exactly it works.

**Comment by gergely-ujvari** [comment]
We have agreed at retrospective that we want to solve this server-side for now.
