### ISSUE TITLE
Reconsider the activation system

### ISSUE THREAD

**Issue by tilgovi** [hypothesis/h#1933]
ref hypothesis/vision#133
ref hypothesis/vision#156

Goals:
- [ ] Remove the activation / email confirm status bits from the user table
- [ ] Consider multiple activations in the event of slow email
- [ ] Do something smarter than deactivation by random email

**Comment by dwhly** [comment]
Would we no longer be able to tell whether a given user account had ever activated?

**Comment by tilgovi** [comment]
@dwhly what do you mean by activated and / or what are you trying to use the information you want for?

**Comment by dwhly** [comment]
> what do you mean by activated

They've clicked the activation link.

> what are you trying to use the information you want for?

Tracking stats on how many people activate their accounts-- how can we improve the experience to increase conversions between stages: visit / register / activate / annotate / reply / etc.

**Comment by tilgovi** [comment]
I suspect it's not related to this ticket and would be handled in another place where events are logged. This ticket is about the mechanism of activation, not activity reporting. I'll let hypothesis/vision#155 trickle requirements down into this repo where appropriate, but I wouldn't consider those requirement in this issue.

**Comment by tilgovi** [comment]
In other words, I think what you're concerned with is better handled by instrumentation that's orthogonal to this issue.

**Comment by nickstenning** [comment]
:+1: to improving activation. The most sensible way of doing this IME is the same way we currently issue notification unsubscribe links: signed, salted tokens in the URL. We keep no state in the database, and validate only the URL itself.

**Comment by nickstenning** [comment]
We've made some major improvements to activation in #2803, #2903, #2904. Closing.
