### ISSUE TITLE
Mixed content warnings with image embeds

### ISSUE THREAD

**Issue by tilgovi** [hypothesis/h#1940]
Annotations with embedded images generate mixed content warnings.

We could consider proxying images. Maybe look at https://github.com/thumbor/thumbor for a potential solution.

**Comment by tilgovi** [comment]
Actually, going to move this to vision.

**Comment by robertknight** [comment]
Noticed this again today. I'm going to reopen as it is a bug IMO. _If_ many of the images that users try to embed come from services that support HTTPS then we could simply change the protocol for embedded image URLs to HTTPS and only fall back to loading via HTTP if loading the media fails.

**Comment by tilgovi** [comment]
Long term solution could be to deploy thumbor, serve the images yourself,
and that way also have control over optimizing, scaling, and caching them.

**Comment by tilgovi** [comment]
https://github.com/thumbor/thumbor

**Comment by nickstenning** [comment]
Clearly we do want to address this issue in future -- in particular we will need to address this before (or as part of) applying a more restrictive Content-Security-Policy to our service. That said, the service is currently operating as designed, so this isn't a bug.

I've opened https://github.com/hypothesis/product-backlog/issues/176 to track the work implied by this ticket.
