### ISSUE TITLE
CC logo is missing in front of editor license text

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#1944]
Extension v 0.3.2.1490

![screen shot 2015-02-12 at 10 43 08 am](https://cloud.githubusercontent.com/assets/1413074/6174491/f68da792-b2a3-11e4-9b4f-026ace79ac92.png)

**Comment by aron** [comment]
Fixed in https://github.com/hypothesis/h/pull/1945

**Comment by csillag** [comment]
The fix (#1945) has been merged, so I am closing this.
