### ISSUE TITLE
Chrome extension injects embed.js even when already present

### ISSUE THREAD

**Issue by BigBlueHat** [hypothesis/h#1946]
Site's like JEP include an `embed.js` line:
http://quod.lib.umich.edu/j/jep/3336451.0017.201?view=text;rgn=main

If you have the Chrome extension on for that tab, you'll get a second h--which causes other issues.

**Comment by BigBlueHat** [comment]
This is an increasing issue now that Via's in place and getting usage. If you have the Chrome extension on and visit a Via link...it'll likely kill your tab...at least it did for me just now.

**Comment by tilgovi** [comment]
Closing as duplicate of #1688
