### ISSUE TITLE
The FF extension is defunct

### ISSUE THREAD

**Issue by csillag** [hypothesis/h#1956]
quoting @BigBlueHat from IRC:

>  looks like bootstrap.js fell out of the FF build...

Translation: currently, it doesn't work.

**Comment by dwhly** [comment]
Does updating our submission reset our place in the queue?  cc @aron.

**Comment by BigBlueHat** [comment]
@dwhly I'd assume so, yeah.

**Comment by BigBlueHat** [comment]
FWIW, this error is only seen on the current `master` (dd5c4163a14f538418dec0d0f0bece726fe245b8).

No idea why 0.3.2.1 (what's in the Addons Editorial queue atm) is failing (see #1954).

Might be related...might not.

**Comment by csillag** [comment]
Actually, I think the published FF extension doesn't have this bug.

**Comment by csillag** [comment]
So, this bug kills all deployment. The version that's currently published at mozilla works for HTML, only fails for PDF (#1954). So I think problem has crept in since we have published that.

**Comment by dwhly** [comment]
I can't even get the adder to surface on the FF extension.

**Comment by csillag** [comment]
> I can't even get the adder to surface on the FF extension.

Now that I checked, me neither.

**Comment by dwhly** [comment]
If they'll accept a non-functional app we should probably let it sit and fix it after just from a queue perspective.

**Comment by aron** [comment]
@dwhly I'd assume so too.
@BigBlueHat as mentioned in #1954 I believe it's failing due to the add-on embedding an older version of h into the document (prior to the bridge refactor), and the iframe loading the current production scripts from hypothes,is (post refactor). I would say the two are not compatible and that the extension needs to be updated with the code from master.

**Comment by tilgovi** [comment]
We should go through this comment (https://github.com/hypothesis/h/issues/1954#issuecomment-74970756) and make issues out of each problem.
