### ISSUE TITLE
Deactivating chrome extension throws exception.

### ISSUE THREAD

**Issue by gergely-ujvari** [hypothesis/h#1962]
Tested with v0.3.2.1541

To reproduce:
1. Activate the extension on a web-page
2. Deactivate the extension.
3. Check the console logs.

Result:
```
Uncaught TypeError: Cannot read property 'Plugin' of undefined hypothesis.min.js?c324417e:10 
Annotator.Plugin.CrossFrame.destroy hypothesis.min.js?c324417e:16 
Annotator.Guest.Guest.destroy destroy.js:1 (anonymous function)
```

Expected: no exception.

**Comment by tilgovi** [comment]
Oh, I just commented on #1963 with the same.

**Comment by tilgovi** [comment]
Not seeing this on master. Marking as closed and pushing out a new extension build.
