### ISSUE TITLE
Activating-deactivating-reactivating extension makes impossible to create annotations

### ISSUE THREAD

**Issue by gergely-ujvari** [hypothesis/h#1963]
Tested with v0.3.2.1541

1. Activate the extension on a web-page
2. Deactivate the extension.
3. Reactivate the extension on the same page
4. Notice that the sidebar does not open and try to select a text to create a new annotation

Result:
No adder icon and an exception in the console log:
```
Uncaught TypeError: Cannot read property 'getStartPosForNode' of undefined hypothesis.min.js?c324417e:12 
Annotator.Plugin.TextPosition.TextPosition._getTextPositionSelectorhypothesis.min.js?c324417e:11 __bind hypothesis.min.js?c324417e:12 
Annotator.Plugin.EnhancedAnchoring.EnhancedAnchoring.getSelectorsFromSelection hypothesis.min.js?c324417e:11 
__bind hypothesis.min.js?c324417e:16 
Annotator.Guest.Guest._getTargetFromSelection hypothesis.min.js?c324417e:16 
(anonymous function) hypothesis.min.js?c324417e:16 
Annotator.Guest.Guest.onSuccessfulSelection hypothesis.min.js?c324417e:11 
Annotator.Plugin.TextSelection.TextSelection.checkForEndSelection hypothesis.min.js?c324417e:11 
__bind hypothesis.min.js?c324417e:2 
jQuery.event.dispatch hypothesis.min.js?c324417e:2 
jQuery.event.add.elemData.handle
```

Expected: Adder icon and new exception.

**Comment by tilgovi** [comment]
This is the first error I see in my console:

![console](https://cloud.githubusercontent.com/assets/20818/6305779/68058568-b8e2-11e4-8af2-9ef22aca023b.png)

There's a comment in the code:

    # super doesnt work here :(

Well, apparently neither does what's being done here. @aron, got any ideas? Why doesn't `super` work?

**Comment by aron** [comment]
The method is defined inside the constructor and CoffeeScript does not support super calls in these cases. The error is being thrown because `Annotator.Plugin.prototype.destroy` doesn't exist so the entire line can go anyway.

**Comment by tilgovi** [comment]
Is it because it doesn't exist or because `Annotator` isn't in scope at that point?

**Comment by tilgovi** [comment]
Not seeing this on master. Marking as closed and pushing out a new extension build.
