### ISSUE TITLE
Icons on toolbar not properly rendering.

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#1975]
Go here:
https://via.hypothes.is/h/http://caseyboyle.net/3860/readings/gorgias.html

Look at toolbar icons.

**Comment by tilgovi** [comment]
There's an `a:before` rule on that page that takes precedence over `.h-icon-comment:before`.

**Comment by judell** [comment]
Not seeing it at the cited URL in via, nor without via in 4.1.139.

I often see this however:

![image](https://cloud.githubusercontent.com/assets/46509/8120678/d409af34-1056-11e5-8317-910a3fdacf1c.png) 

including here in GitHub where I am annotating to tag issues.

Tagging with display and icons.

**Comment by judell** [comment]
Ah, finally I understand. Those broken icons are https://github.com/hypothesis/h/issues/2266 (Content Security Policy). I doubt that was the problem at caseboyle.net but I'm glad to finally understand that https://github.com/hypothesis/h/issues/2266 *is* the problem on GitHub and elsewhere.

**Comment by nickstenning** [comment]
Seems to be fixed now.
