### ISSUE TITLE
Configurable service URL

### ISSUE THREAD

**Issue by tilgovi** [hypothesis/h#1976]
Since the API is actually a separate application from the site, we should have a way to configure its root URL and use that in path generation throughout the back-end.

This will enable us to use a subdomain for the API.

- [ ] #2074
- [ ] #2075

**Comment by nickstenning** [comment]
Closing as we're moving away from using the API over HTTP from within the app.

**Comment by tilgovi** [comment]
This was poorly described above, but it's about configuring the URL we tell the client to use for the API calls. It's easier now than ever, and I've already written it, I just held off because it was orthogonal to the work I was doing in the moment.

**Comment by tilgovi** [comment]
In other words, it's not just about the API client within the server, it's about the browser client: reducing the payload and keeping the session secure by eliminating cookies from API requests, having a separate subdomain for CloudFlare or cache config... etc, keeping this open.

**Comment by nickstenning** [comment]
This is now done: #2619, #2633, #2878, #2881.
