### ISSUE TITLE
Crash when user starts to annotate before scanning is finished

### ISSUE THREAD

**Issue by csillag** [hypothesis/h#1977]
If the user starts to annotate before we have finished scanning the document, the operation fails.

This can happen if the user is very fast, or if the document is very large or complex.

This is a regression: earlier, we used to disable annotating on boot, and only enable it when everything is ready, but that feature has been removed, so the problem is back.

Ideally, we should indicate somehow that we are not yet ready for annotating; at least if the user tries to annotate.

**Comment by tilgovi** [comment]
Ideally, we should be ready to annotate.

**Comment by csillag** [comment]
True.

2015. febr. 27., p 0.20-kor-kor, Randall Leeds 
<notifications@github.com> írta:

**Comment by dwhly** [comment]
> Ideally, we should be ready to annotate.
+1

**Comment by csillag** [comment]
> Ideally, we should be ready to annotate.

OK, so, until that ideal case can be reached, how should we handle this?

1. Just hope that the computer will always be faster than the user? (Just what we have now, basically.)

2. So something heavy-handed, like show a pop-up saying "initializing" until we are ready to go?

3. Let the user continue reading the document, but disable annotating until we are ready? (You can select text, but the adder button won't appear until everything is fully operational.)

I vote for option 3. (That's what we had earlier, anyway.)

**Comment by csillag** [comment]
>  So something heavy-handed, like show a pop-up saying "initializing" until we are ready to go?

I mean: **Do** something heavy-handed...

**Comment by tilgovi** [comment]
I vote to ignore it and solve the underlying problem.

**Comment by tilgovi** [comment]
Scanning is going away.
