### ISSUE TITLE
Race condition [?] during deployment

### ISSUE THREAD

**Issue by csillag** [hypothesis/h#1978]
When deploying H using a static embed in a HTML document, upon loading the document,
sometimes I get this:

> TypeError: wrapper[0] is undefined

This is intermittent; only happens every few times.

**Comment by csillag** [comment]
... or here is a new error I sometimes get (when embedding embed.js into a static HTML page):

> TypeError: Annotator is undefined

**Comment by tilgovi** [comment]
I longer traceback would be helpful, if you have it.

**Comment by tilgovi** [comment]
Hmm. I'm actually just going to close this unless we can get more info. I've not seen anything like this and I've not heard any other reports.

Well, actually, I have seen something that could be like this when you try to make multiple requests before the assets are built. Then, multiple requests try to build the assets at once and sometimes cause 500s on one of them.

**Comment by csillag** [comment]
> Well, actually, I have seen something that could be like this when you try to make multiple requests before the assets are built. Then, multiple requests try to build the assets at once and sometimes cause 500s on one of them.

Now, this is not that.
In my case, the app is working normally at first, I can make annotations, etc.
Then I leave it alone for a while (30 min?), and come back, try to resume my session, but I can no longer create annotations; i'm getting 500s. If I refresh the page, it starts to work again.

I'll try to get more info ... but there was no stacktrace. (I couldn't yet reproduce locally, only on prod.)

**Comment by csillag** [comment]
> Now, this is not that.
> In my case, the app is working normally at first, I can make annotations, etc.
> Then I leave it alone for a while (30 min?), and come back, try to resume my session, but I can no longer create annotations; i'm getting 500s. If I refresh the page, it starts to work again.

> I'll try to get more info ... but there was no stacktrace. (I couldn't yet reproduce locally, only on prod.)

Sorry, I mixed this up with a different bug report. 
What I described here is #1982, not this one.
I'll ping back when I manage to reproduce this again.
