### ISSUE TITLE
annotating is defunct while in page search

### ISSUE THREAD

**Issue by csillag** [hypothesis/h#1979]
This is a regression, coming from the umpteenth refactoring of the page search and the viewer.
And it's really, really ugly.

1. Go to a page and deploy h
2. Run a page search. (You don't need any results; just go to search mode. An empty result list is fine.)
3. Now try to create a new annotation

Expected result: the editor shows up
Actual result: only a small stub (and empty rectangle) shows up. 

Annotation creation does not work. 

If we leave search mode, even the stub disappears, and there is no trace indicating that we were trying to annotate beforehand. (However, we can annotate again.)

I am marking this as a blocker.

**Comment by csillag** [comment]
In fact this bug is also triggered when we select some annotations (either clicking on the bars on the bucket bar, or on the highlights in always-on mode), and then try to create an annotation.

**Comment by csillag** [comment]
This is a blocker bug, and possibly an easy fix. Any takers?

**Comment by tilgovi** [comment]
I looked at it. It's not an easy fix. The tricky part is getting the counts right for the "show more". I think we need to change how we're doing that a bit. It's easy with simple match on the counters when the new edit is a child, but when it's a grandchild and it's caused a whole tree to stay open even when there's only a match further up the ancestry, the numbers aren't as simple.

**Comment by tilgovi** [comment]
It's probably still pretty easy... but that's the part that requires some thought.

**Comment by csillag** [comment]
> The tricky part is getting the counts right for the "show more".

That's only a problem if want to stay in "search mode" / "selection mode" when adding a new editor.

The simple way would be simply kill the search/selection, go back to default mode, and add the editor there.

No counter to update :)

**Comment by tilgovi** [comment]
That is nice. Possibly sensible.

**Comment by dwhly** [comment]
> The simple way would be simply kill the search/selection, go back to default mode, and add the editor there.

I'd strongly support this.  Am I correct in that this could potentially apply to anytime there is a selected set of annotations?  Because currently when, for instance, a tab is selected, and a new annotation is created, the editor isn't visible.  Entering the edit mode should kill the selection.

**Comment by dwhly** [comment]
Sorry.  Department of redundancy department-- closer reading says that is exactly what's being discussed.
