### ISSUE TITLE
Intermittent permissions problems on prod server (on annotation creation)

### ISSUE THREAD

**Issue by csillag** [hypothesis/h#1982]
I am logged in.
Sometimes, I can create annotations; other times I can't.

When I can't, there is no user visible error message.
Also, the console is empty.
Checking the network traffic, I see this response to my request:

```
Access was denied to this resource.
Unauthorized: create failed permission check
```

The Annotation card is created nevertheless, but it's non reactive. (Buttons don't appear on hover, etc.)

Any idea what's going on?

**Comment by tilgovi** [comment]
Is this by any chance a page you've had open for a very long time?

**Comment by csillag** [comment]
Not more than 30 minutes, I guess.

2015. febr. 26., cs 21.47-kor-kor, Randall Leeds 
<notifications@github.com> írta:

**Comment by tilgovi** [comment]
No idea. We have an open issue IIRC for the lack of error message. The rest of this I can't reproduce. What do you want to do with it?

**Comment by csillag** [comment]
Next time I'll see it, I'l note the timestamp, so that we can check the 
server logs for any exceptions.
OTOH, Sentry would reveal it to us anyway, wouldn't it?


2015. febr. 26., cs 22.57-kor-kor, Randall Leeds 
<notifications@github.com> írta:

**Comment by tilgovi** [comment]
Yep.

**Comment by csillag** [comment]
I have seen this several times in the last few days. Still working on determining the exact circumstances that trigger it.

**Comment by tilgovi** [comment]
Please re-open if you experience this again or if you can provide more info.
