### ISSUE TITLE
Open Graph metadata needs a summary

### ISSUE THREAD

**Issue by tilgovi** [hypothesis/h#1988]

**Comment by tilgovi** [comment]
This is pretty horrendous:

![bad-summary.png](https://cloud.githubusercontent.com/assets/20818/6447075/6535e064-c0c4-11e4-8c65-c4415234f9e2.png)

**Comment by tilgovi** [comment]
@BigBlueHat you might want to knock this one out quickly.

**Comment by BigBlueHat** [comment]
:stuck_out_tongue_closed_eyes: fixing...

Also, consider this a solid :heavy_plus_sign: :one: for having actual annotation content *in* the markup.

**Comment by tilgovi** [comment]
It might be worth looking at this commit: https://github.com/tilgovi/h/commit/d74654127f8c6ab0c28e6777079a581a1cf77e15

For that I was experimenting with using pyramid_layout's panels feature to make a 'static' panel that renders in place of the angular view. It gets replaced as soon as angular loads but it serves as the static content of the page at fetch time.

**Comment by BigBlueHat** [comment]
@tilgovi awesome. I'll tackle that soon. Adding `og:description` for now.
