### ISSUE TITLE
H appears and then disappears

### ISSUE THREAD

**Issue by csillag** [hypothesis/h#2004]
Latest master branch

1. Run server
2. Point FF to local welcome page

Expected result: H sidebar is available.

Actual result: the H top bar main button appears briefly, but hen disappears from view.

No errors on server log.
No serious errors on browser console log.

If it "works" that same in production environments, too, then this would be a blocker .. right?

**Comment by tilgovi** [comment]
You have the extension installed?

**Comment by tilgovi** [comment]
If so, this is #1689

**Comment by csillag** [comment]
> You have the extension installed?

Yeah, that's it. I forgot. Thanks.

Closing as duplicate.
