### ISSUE TITLE
No check for limitation on embedding to local HTML

### ISSUE THREAD

**Issue by csillag** [hypothesis/h#2005]
When I open a local HTML file in FF, and try to deploy H using the bookmarklet, I get a pop-up with an error message explaining that 

> Sorry, Hypothesis doesn't work on this type of file. Only PDF's can be annotated locally.

That's all well and good, but when I try to do the same thing with an embed (that is, open a local HTML file that has H embedded), I get no explanation, only a crash on the console:

> SyntaxError: An invalid or illegal string was specified

Since we are bumping into the same limitation, ideally, we should use the same check, and the same warning message.

**Comment by csillag** [comment]
> When I open a local HTML file in FF,

It's all the same with Chrome.

**Comment by tilgovi** [comment]
I don't think this is fixable. If the HTML is loaded from file: then XHR won't work so our embed code never runs.

**Comment by csillag** [comment]
> I don't think this is fixable. If the HTML is loaded from file: then XHR won't work so our embed code never runs.

According to my tests, our embed code *does* run. That fails is the `postMessage` call, because of invalid parameters. There is nothing stopping us from detecting the invalidity of those params without calling `postMessage` on them.

**Comment by tilgovi** [comment]
Oh, duh. Of course. The initial load isn't XHR, it's a script tag.

**Comment by tilgovi** [comment]
Maybe this would just fix it?

```diff
diff --git a/h/static/scripts/bridge.coffee b/h/static/scripts/bridge.coffee
index 3b2d65f..bb6f3bb 100644
--- a/h/static/scripts/bridge.coffee
+++ b/h/static/scripts/bridge.coffee
@@ -99,6 +99,7 @@ module.exports = class Bridge
   _buildChannel: (options) ->
     # jschannel chokes on FF and Chrome extension origins.
     if (options.origin.match /^chrome-extension:\/\//) or
-        (options.origin.match /^resource:\/\//)
+        (options.origin.match /^resource:\/\//) or
+        (options.origin.match /^file:\/\//)
       options = $.extend {}, options, {origin: '*'}
     channel = Channel.build(options)
```

**Comment by tilgovi** [comment]
According to https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage#Using_window.postMessage_in_extensions it seems it should.

**Comment by csillag** [comment]
> Maybe this would just fix it?

Maybe it would. But (as with anything tricky) it needs testing. (Especially be careful about avoid accidentally killing the local PDF support by a too lax regexp.)

**Comment by tilgovi** [comment]
The risk is that we're too lax with security here, but it doesn't risk "killing" anything.

**Comment by tilgovi** [comment]
Here's a full patch that seems to work:

```diff
diff --git a/h/static/scripts/bridge.coffee b/h/static/scripts/bridge.coffee
index 3b2d65f..8adb2d9 100644
--- a/h/static/scripts/bridge.coffee
+++ b/h/static/scripts/bridge.coffee
@@ -97,8 +97,9 @@ module.exports = class Bridge
 
   # Construct a channel to another frame
   _buildChannel: (options) ->
-    # jschannel chokes on FF and Chrome extension origins.
+    # Don't choke on non-standard schemes, just allow it.
     if (options.origin.match /^chrome-extension:\/\//) or
-        (options.origin.match /^resource:\/\//)
+        (options.origin.match /^resource:\/\//) or
+        (options.origin.match /^file:\/\//)
       options = $.extend {}, options, {origin: '*'}
     channel = Channel.build(options)
diff --git a/h/static/scripts/discovery.coffee b/h/static/scripts/discovery.coffee
index 140e234..f090da0 100644
--- a/h/static/scripts/discovery.coffee
+++ b/h/static/scripts/discovery.coffee
@@ -86,6 +86,12 @@ module.exports = class Discovery
   _onMessage: (event) =>
     {source, origin, data} = event
 
+    # If `origin` is null the source frame is a file URL or loaded over some
+    # other scheme for which the `origin` is undefined. In this case, just
+    # accept any origin.
+    if origin is 'null' or not origin?
+      origin = '*'
+
     # Check if the message is at all related to our discovery mechanism
     match = data.match? /^__cross_frame_dhcp_(discovery|offer|request|ack)(?::(\d+))?$/
     return unless match
```

**Comment by judell** [comment]
Tagged with firefox, embed, local_html
