### ISSUE TITLE
Highlighter and Adder icons don't match

### ISSUE THREAD

**Issue by BigBlueHat** [hypothesis/h#2007]
The icons don't match, but they represent the same thing.

Either:
 - let's make them match
 - OR let's switch to @RawKStar77's two icon adder (which matches how Microsoft's Windows 8 PDF viewer displays annotation actions, fwiw):
![Annotation in Windows 8 PDF Viewer](https://s3.amazonaws.com/f.cl.ly/items/0v1p2E3i451j2n152F1t/2015-01-26%2010_36_24-Greenshot.png)

**Comment by RawKStar77** [comment]
Closed via https://github.com/hypothesis/h/pull/2031
