### ISSUE TITLE
Made some highlights, logged in, got my entire list of annotations in the sidebar

### ISSUE THREAD

**Issue by BigBlueHat** [hypothesis/h#2009]
:astonished: 

Not sure if that's the only way to trigger that happening, but it's the first time I've seen it.

**Comment by RawKStar77** [comment]
I'm not exactly sure what this bug is about. Could you clarify a bit more?

**Comment by BigBlueHat** [comment]
By "entire list of annotations" I mean every annotation I've left on *any* resource...not just the one I'm viewing.

To reproduce:
 - open a web page to annotate
 - turn on Hypothes.is (I used the bookmarklet, but they should all be..nearly..the same)
 - make sure you're logged out (private browsing sessions are useful here)
 - turn on highlight mode
 - make some highlights
 - login
 - scroll up and down a bit to get the sidebar to load any non-visible content

Also...try toggling highlight mode on and off (after logging in) and you'll watch the cards collapse and refill...which is possibly a different :bug:.

**Comment by tilgovi** [comment]
/me wonders if it's some race between login and search.

**Comment by tilgovi** [comment]
or, rather, maybe we lose the page metadata at some point and don't properly filter the new search.

**Comment by tilgovi** [comment]
Without more info, it's impossible to make progress here.

**Comment by BigBlueHat** [comment]
k. This just happened again. This time on https://hypothes.is/blog/poynter-annotation-summit-at-the-new-york-times/

Made some a selection, started to annotate, realized I wasn't logged in, clicked login, logged in, sidebar (previously empty) reloaded with what seem to be loads of annotations from `http(s)://hypothes.is/` +/- query strings.

**Comment by BigBlueHat** [comment]
Actually....it's doing it for that page anytime I open the sidebar post-login (not just immediately after).

Happened using both the extension in Chrome and the bookmarklet in Firefox.

Oh...and it seems the list of results is in at least a different order... :confused:

**Comment by tilgovi** [comment]
Could this be: https://github.com/hypothesis/h/issues/2240

Known to affect our blog.

**Comment by tilgovi** [comment]
If it's truly a separate bug you'll know it by seeing annotations that aren't anywhere on hypothes.is.

**Comment by judell** [comment]
Tagged false_positives

**Comment by tilgovi** [comment]
Closing as duplicate of #2240 until @BigBlueHat says otherwise.

**Comment by BigBlueHat** [comment]
Yeah. I do think this was #2240 the first time I saw it. :stuck_out_tongue: 

Cheers!
