### ISSUE TITLE
Can't deploy on this Wikipedia page

### ISSUE THREAD

**Issue by csillag** [hypothesis/h#2016]
If I hit http://en.wikipedia.org/wiki/Linux with either the production extension (with Chromium), or with the bookmarklet (with Chromium, H running on my local box, latest master), the initial scan never seems to finish. Eventually, I get a "page crashed" message.

However, Firefox works correctly. 

Unfortunately, I can't get a profile by Chromium's usual profiling tool, but disabling d-t-m makes the problem go away, so I guess it's a d-t-m thing.

**Comment by csillag** [comment]
@gergely-ujvari can't reproduce this on his computer; that might simply be because his box packs more power.

**Comment by dwhly** [comment]
This appears to work now w/ latest Chrome extension.

**Comment by dwhly** [comment]
@pfowler and I just confirmed.

**Comment by dwhly** [comment]
@pegfowler and I just confirmed.

**Comment by csillag** [comment]
Good for you, but it still crashes for me.

I guess it depends on how big a punch your CPU packs. My box is a feeble old servant... which is good for testing, because we should support those, too.

I think this is **not** a performance issue, but a bug.

**Comment by judell** [comment]
When I visit http://en.wikipedia.org/wiki/Linux I see (in the Chrome debugger) my browser making 3 related API calls:

1 https://hypothes.is/api/search?limit=20&offset=0&order=asc&sort=created&uri=http:%2F%2Fen.wikipedia.org%2Fwiki%2FLinux

2 https://hypothes.is/api/search?limit=20&offset=0&order=asc&sort=created&uri=android-app:%2F%2Forg.wikipedia%2Fhttp%2Fen.m.wikipedia.org%2Fwiki%2FLinux

3 https://hypothes.is/api/search?limit=20&offset=0&order=asc&sort=created&uri=http:%2F%2Fen.wikipedia.org%2Fw%2Findex.php%3Ftitle%3DLinux%26action%3Dedit

What are #2 and #3 doing?

**Comment by gergely-ujvari** [comment]
The source of that wiki page contains alternative links for that page 
```
<link rel="alternate" href="android-app://org.wikipedia/http/en.m.wikipedia.org/wiki/Linux" />
<link rel="alternate" type="application/x-wiki" title="Edit this page" href="/w/index.php?title=Linux&amp;action=edit" />
```

The annotator document plugin discovers these links and the h client tries to load annotations saved with those uris. This way the annotations will be showed no matter in which uri we created them. 

(But IMO this is no longer needed as we collect document equivalencies at server side)

**Comment by tilgovi** [comment]
I hesitate to change this. We don't necessarily know about every alias unless a user has created an annotation. For instance, you could open a PDF and it's URL might be different from the one someone else used to access that document. If we only search for the URI we would not get their annotations. If we search for every name we can locally determine for it that will include things like the URN fingerprint, which will match stored annotations.

**Comment by tilgovi** [comment]
We could probably do some filtering on rel=alternate, though. Only some small number of types there might be useful for us.

**Comment by tilgovi** [comment]
This needs to move to the dtm or be simply left alone since it's looking likely we won't be using dtm anymore.
