### ISSUE TITLE
Show differences no longer works

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#2041]
Go to this page:
https://thedeadcanary.wordpress.com/2014/05/11/song-of-myself/

Enable the chrome extension.

This annotation requires fuzzy matching to re-anchor.  The show differences feature that should be visible on the pull quote of the selection is not there.

**Comment by gergely-ujvari** [comment]
It seems that the `JSON.stringify` call [inside the jschannel](https://github.com/hypothesis/h/blob/master/h/static/scripts/vendor/jschannel.js#L507) removes the `diffCaseOnly` and `diffHTML` properties from the annotation.target so it doesn't go through the jschannel.

Anyone has any idea why?

**Comment by tilgovi** [comment]
@gergely-ujvari are you sure about that?

**Comment by gergely-ujvari** [comment]
My current debugging leads to there. This is not something I expected. I'll make another check but my first step-by-step debugging lead me to there.

**Comment by csillag** [comment]
Is this during serialisation or during deserialization?
2015.03.20. 17:51 ezt írta ("gergely-ujvari" <notifications@github.com>):

**Comment by gergely-ujvari** [comment]
serialisation

**Comment by csillag** [comment]
Maybe one of involved objects has a custom toString  method or something
like that, which derails default serialization?
2015.03.20. 20:31 ezt írta ("gergely-ujvari" <notifications@github.com>):

**Comment by gergely-ujvari** [comment]
Now I see that the browser's debugger was playing with me. The problem is not with the json serialization (it seemed strange anyway)
