### ISSUE TITLE
URL polyfill not loading in IE

### ISSUE THREAD

**Issue by csillag** [hypothesis/h#2048]
The [IE autodetect branch](https://github.com/hypothesis/h/tree/add-ie-autodetect) of H (see PR https://github.com/hypothesis/h/pull/2047) now doesn't even try to to load dom-text-mapper under IE, but this uncovers another crash, probably in jsChannel code.

Go to http://ie.dokku.hypothes.is for reproducing this.

**Comment by gergely-ujvari** [comment]
It is actually guest related, IE11 doesn't know what the `URL` object is 

It fails here:
```
Guest.prototype._removeHash = function (url) {
                        url = new URL(url);
```

**Comment by tilgovi** [comment]
Easily fixed by changing the embed code to detect lack of support for `URL` and include the polyfill.

**Comment by csillag** [comment]
I already added the required polyfill here: https://github.com/hypothesis/h/commit/4f46e9ff88455b651e8e039cbaee6ba589633b79

I wonder why it isn't loaded...

**Comment by tilgovi** [comment]
Because the embed code doesn't load it.

    Easily fixed by changing the embed code to detect lack of support for URL and include the polyfill.

**Comment by csillag** [comment]
> Because the embed code doesn't load it.

It's part of the app bundle defined in [assets.yaml](https://github.com/hypothesis/h/blob/ee5ad5e727c13f6d3897f3e8da34f8e290a06d40/h/assets.yaml#L106). What else do we need to do to have it loaded in the embed code?

**Comment by csillag** [comment]
Oh, it's the wrong iframe, that's why...
