### ISSUE TITLE
IE Styling improvements

### ISSUE THREAD

**Issue by gergely-ujvari** [hypothesis/h#2049]
I'm using https://ie.dokku.hypothes.is/ as a reference.
Tested with IE11 (under W7)

The search text and icon is only displayed half in the sidebar:
![ie_01](https://cloud.githubusercontent.com/assets/2094134/6694791/c575033c-ccdc-11e4-948b-92429e505eb5.png)

And the icons are too big and clumsy in the sidebar (but not in the welcome page):
![ie_02](https://cloud.githubusercontent.com/assets/2094134/6694841/22c487a6-ccdd-11e4-959d-7a4fc822e036.png)

**Comment by gergely-ujvari** [comment]
+1: Adder icons:
![ie_03](https://cloud.githubusercontent.com/assets/2094134/6695082/cbe0cf24-ccde-11e4-9a20-0365aaefa767.png)

And big annotation card icons (Hopefully they all have the same root):
![ie_04](https://cloud.githubusercontent.com/assets/2094134/6695100/f5e89694-ccde-11e4-94b2-a00b93a86c3b.png)

**Comment by judell** [comment]
Still a problem. Tagged display, style, ie11.

**Comment by robertknight** [comment]
Did some testing of IE earlier today with current H. The above issues are fixed except for alignment of menu items in the dropdown - https://github.com/hypothesis/h/issues/2659
