### ISSUE TITLE
Realtime not working

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#2060]
Open two tabs to the same source page, create an annotation, it won't show on the other tab until you reload.

Also, simultaneously noticing that scroll-for-more on the stream is not working.  Related?

**Comment by tilgovi** [comment]
Stream server wasn't running. Not a code issue. Please direct support requests and outage reports to site reliability (sr@hypothes.is) or the user support forum (support@hypothes.is).

**Comment by tilgovi** [comment]
Or, you know, texting would be okay in such a case.

**Comment by dwhly** [comment]
On March 19, 2015 at 7:45:49 PM, Randall Leeds (notifications@github.com) wrote:

Stream server wasn't running. Not a code issue. Please direct support requests and outage reports to site reliability (sr@hypothes.is) or the user support forum (support@hypothes.is).

Ok— sometimes tough to tell which is which.  But if I suspect, I’ll do so.

Can we establish a monitor for the stream server?
