### ISSUE TITLE
Display domain and/or "via" (or icon) for Via-annotated resources

### ISSUE THREAD

**Issue by BigBlueHat** [hypothesis/h#2062]
Right now, we've got `via.hypothes.is` showing up frequently in the stream--which is exciting! :smile: 

However, that's not what's being annotated...it's the resource that's passed to Via that is being annotated.

We're handling this correctly in the code--storing the annotations in associate with the non-proxied version. Our UI just needs to show it now.

**Comment by tilgovi** [comment]
Suggesting using the canonical URL, if known (`annotation.document` should have it).
Also, maybe an issue to via is appropriate to add a default canonical rel to the original page URI if the proxied page doesn't provide its own.

**Comment by tilgovi** [comment]
Or some other such issue for via where pages not supplying any data like this still result in annotations that have the correct URL.

**Comment by tilgovi** [comment]
It's possible that we want to have such a thing, but looking unlikely as we're currently working to get the via link _out_ of the card and replacing it with the original site URL.
