### ISSUE TITLE
Fire a hypothesis-* event when adding a highlight node

### ISSUE THREAD

**Issue by hubgit** [hypothesis/h#2068]
It looks like [a `domChange` event is fired](https://github.com/hypothesis/h/blob/master/h/static/scripts/annotator/plugin/texthighlights.coffee#L27) on each node that's wrapped in a highlight span, but would it be possible to fire a hypothesis-specific event on the highlight node after it's inserted (and perhaps after the associated annotation is edited/removed, too)?

This would allow the page to display a _Medium_-style annotation count alongside each parent element (paragraph, for example). 

If the event contained the details of the annotation, then user interaction with the annotation count could display the associated annotations - I'm not sure how that should integrate with the sidebar for editing and replies, though…

**Comment by tilgovi** [comment]
Yes. That `domChange` event is an internal detail of some hacks around maintaining our anchoring layer. In the future, we plan to do exactly what you say.

That work is coming from nickstenning/domannotations, where the events will be `annotationcreate`, etc, and aim to be in line with what a platform-provided annotation system might be expected to provide.

We have a bunch of work to do to get there, roughly:

- Narrow down the final scope of Annotator 2
- Move Annotator 2 to domannotations
- Release Annotator 2
- ~~Remove as many dependencies on Annotator 1 as possible~~
- Port Hypothesis to Annotator 2

This might be cut short if we decide to forgo annotator altogether for Hypothesis, and focus on re-using a base component like domannotations.

If this is very much blocking a need of yours in the short term, please take it to our mailing list if you don't mind. I'd be happy to think about whether we can start mimicking the behavior of domannotations before we get everything refactored.
