### ISSUE TITLE
Site report: Fails to inject sidebar

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#2090]
https://www.airpair.com/angularjs/posts/component-based-angularjs-directives

Uncaught Error: [$injector:nomod] Module 'h' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.3.2/$injector/nomod?p0=h

**Comment by gergely-ujvari** [comment]
It seems this page is already deploying anguljarjs and a newer version than we use.
This way our angularjs version is not used and h currently does not work with angularjs 1.3.x

**Comment by tilgovi** [comment]
This is already fixed by #2092, when that merges.

**Comment by tilgovi** [comment]
Between fixing conflicts with require.js and conflicts with angular.js, #2092 is going to fix the application for a _lot_ of sites.

**Comment by dwhly** [comment]
:tada:
