### ISSUE TITLE
Add babelify (to allow ES6 code)

### ISSUE THREAD

**Issue by csillag** [hypothesis/h#2093]
To sooth the pain of the Coffee -> JS transition, it would be great if we could (experimentally) use ES6.
For that, we need [Babel](http://babeljs.io). To use Babel with Browserify, we need [Babelify](https://github.com/babel/babelify).

Please add Babelify to our build system!

**Comment by tilgovi** [comment]
This is as simple as adding the babelify transform to package.json in the browserify transforms and as a dev dependency. It should be done when it's needed. Write some ES6 code for your next contribution!
