### ISSUE TITLE
Normalize URL syntax and query behavior across /api and /stream

### ISSUE THREAD

**Issue by judell** [hypothesis/h#2095]
NOW:

https://hypothes.is/stream?q=tag:%27h-examples%27 -> 1 result
https://hypothes.is/api/search?tags=%27h-examples%27 -> many results

IDEAL:

https://hypothes.is/stream?q=tag:%27h-examples%27 -> 1 result
https://hypothes.is/api/search?q=tag:%27h-examples%27 -> 1 result

or (i..e. pick either style, just be consistent)

https://hypothes.is/stream?tags=%27h-examples%27 -> 1 result
https://hypothes.is/api/search?tags=%27h-examples%27 -> 1 result

Also it's unclear whether or in which context compound queries work, e.g.:

?user=dwhly&tags=w3c

?user=dwhly&tags=w3c,spec

Again, ideally same pattern as between /stream and /api

**Comment by judell** [comment]
IRC conversation from 3/27/2015: https://gist.github.com/judell/bd5c2a6374dba27338e4

**Comment by tilgovi** [comment]
Confirmed fixed on stage.

**Comment by judell** [comment]
I'm not seeing a difference between stage and production for the above comparison:

https://hypothes.is/stream?q=tag:%27h-examples%27 -> 1 result
https://hypothes.is/api/search?tags=%27h-examples%27 -> many results

Formerly the production stream matched only the whole tag, the production api matched tag fragments.

Now the production stream and api match tag fragments. As do stage stream and api. So I'm missing what it is that we are confirming here.

**Comment by judell** [comment]
#2153 as a reminder that we need user feedback about partial-match search.

**Comment by tilgovi** [comment]
@judell I think you just caught this in the minute I was cutting stage back over to the standard index alias and doing the final reindexing and cut-over for prod. Prod is up now and prod and stage both show 14 annotations for those URLs for me.

Sorry about that.

**Comment by judell** [comment]
No worries. As advertised, things that were inconsistent are now consistent. Thanks!
