### ISSUE TITLE
Firefox: clicking on the delete button causes an $apply already in progress error

### ISSUE THREAD

**Issue by gergely-ujvari** [hypothesis/h#2097]
Seen this on local master branch and stage.hypothes.is

To reproduce:
1: Use firefox
2. Open a page with it, apply h
3. Login
4. Create an annotation
5. Click on the delete button/link on the annotation card.

Result:  Popup (as expected) but if you check the developer console, you'll find an exception.
Maybe this is an angular error (as we don't have this on chrome) and an upgrade can solve it.
At least upgrading to [v1.2.28](https://code.angularjs.org/1.2.28/) from 1.2.25 shouldn't cause any problem.

Stacktrace:
```
"Error: [$rootScope:inprog] $apply already in progress
http://errors.angularjs.org/1.2.25/$rootScope/inprog?p0=%24apply
minErr/<@http://localhost:5000/assets/scripts/vendor/angular.js:78:5
beginPhase@http://localhost:5000/assets/scripts/vendor/angular.js:13009:9
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost:5000/assets/scripts/vendor/angular.js:12798:11
ngEventHandler/<@http://localhost:5000/assets/scripts/vendor/angular.js:19138:17
jQuery.event.special[orig].handle@http://localhost:5000/assets/scripts/vendor/jquery.js:5020:5
jQuery.event.dispatch@http://localhost:5000/assets/scripts/vendor/jquery.js:4641:1
jQuery.event.add/elemData.handle@http://localhost:5000/assets/scripts/vendor/jquery.js:4309:1
[12]</AnnotationController</this.delete@http://localhost:5000/assets/scripts/app.min.js?d415dfb7:1425:1
Parser.prototype.functionCall/<@http://localhost:5000/assets/scripts/vendor/angular.js:10846:1
ngEventHandler/</callback@http://localhost:5000/assets/scripts/vendor/angular.js:19133:28
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://localhost:5000/assets/scripts/vendor/angular.js:12701:9
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost:5000/assets/scripts/vendor/angular.js:12799:11
ngEventHandler/<@http://localhost:5000/assets/scripts/vendor/angular.js:19138:17
jQuery.event.dispatch@http://localhost:5000/assets/scripts/vendor/jquery.js:4641:1
jQuery.event.add/elemData.handle@http://localhost:5000/assets/scripts/vendor/jquery.js:4309:1

´´´

**Comment by tilgovi** [comment]
Using blocking calls like "confirm" is a problem inside a digest cycle. Simple solution is to use $timeout with the skip digest parameter, do the confirm outside the digest cycle, and then invoke whatever subsequent action needs to occur inside an $apply.

Our draft service and our annotation directive use confirm.

Another solution is to not use the stock "confirm" function but have our own modal.

**Comment by tilgovi** [comment]
This doesn't break anything, afaik, so this is pretty low priority.
