### ISSUE TITLE
API (hence client) coalesces via and not-via, stream does not

### ISSUE THREAD

**Issue by judell** [hypothesis/h#2113]
URL: http://blog.jonudell.net/2015/01/22/a-federated-wikipedia/

I made annotations using both via and the extension. Testing coalescence...

The api (and hence the product) finds everything:

https://hypothes.is/api/search?uri=https://via.hypothes.is/h/http://blog.jonudell.net/2015/01/22/a-federated-wikipedia/

The stream, however:

https://hypothes.is/a/u10seIqZQbeJ0tWm2YcItw -> single annotation using via

https://hypothes.is/a/eAubKKXaRlKAhMrUY7bNBw -> others made via extension

Expected: only 1 annotation id in the stream for target URL, which finds 4 annotations
Actual: 2 annotation ids in stream for target URL, annotations divided between them

**Comment by BigBlueHat** [comment]
Stream search results:
https://hypothes.is/stream?q=uri:http:%2F%2Fblog.jonudell.net%2F2015%2F01%2F22%2Fa-federated-wikipedia%2F
 - found 3 (one from via)

https://hypothes.is/stream?q=uri:https:%2F%2Fvia.hypothes.is%2Fh%2Fhttp:%2F%2Fblog.jonudell.net%2F2015%2F01%2F22%2Fa-federated-wikipedia%2F
 - found 1 (the one made via via)

**Comment by judell** [comment]
For me, both of those stream queries return only the same "Annotating via via" annotation.

**Comment by judell** [comment]
Same result for https://hypothes.is/stream?q=uri:http:%2F%2Fblog.jonudell.net%2F
![annotating-via-via-03](https://cloud.githubusercontent.com/assets/46509/6906007/bc799500-d6e0-11e4-8b37-e65923fad4c7.jpg)

**Comment by judell** [comment]
But we have multiple annotation ids for http://blog.jonudell.net/2015/01/22/a-federated-wikipedia/:

https://hypothes.is/a/u10seIqZQbeJ0tWm2YcItw -> single annotation using via

https://hypothes.is/a/eAubKKXaRlKAhMrUY7bNBw -> others made via extension
![annotating-via-via-05](https://cloud.githubusercontent.com/assets/46509/6906088/60be566e-d6e1-11e4-8d0e-a6c53235ba8d.jpg)
![annotating-via-via-04](https://cloud.githubusercontent.com/assets/46509/6906089/60c137e4-d6e1-11e4-8260-9e803291019a.jpg)

**Comment by judell** [comment]
From the API point of view (and hence the interactive frame):

4: https://hypothes.is/api/search?uri=http://blog.jonudell.net/2015/01/22/a-federated-wikipedia/

4: https://hypothes.is/api/search?uri=https://via.hypothes.is/h/http://blog.jonudell.net/2015/01/22/a-federated-wikipedia/

**Comment by tilgovi** [comment]
Can anyone describe the issue a bit more succinctly? I see a bunch of screen shots and search results but I can't tell:

1. Expected result
1. Actual result

**Comment by judell** [comment]
Sorry, started to document one thing and several others appeared. Will try to isolate.

**Comment by judell** [comment]
I'm closing this for now but will leave some placeholder observations and questions.

Given an URL, http://mashable.com/2015/03/16/vanuatu-cyclone-pam-global-warming/, that I annotated once from the extension and once from the via relay...

Searching for the non-via URL on the stream yields two results, both mine:

https://hypothes.is/stream?q=uri:http:%2F%2Fmashable.com%2F2015%2F03%2F16%2Fvanuatu-cyclone-pam-global-warming%2F

Searching for the via URL on the stream yields one result (mine):

https://hypothes.is/stream?q=uri:https:%2F%2Fvia.hypothes.is%2Fh%2Fhttp:%2F%2Fmashable.com%2F2015%2F03%2F16%2Fvanuatu-cyclone-pam-global-warming%2F

Searching for the non-via URL on the API yields 13 results (two mine):

https://hypothes.is/api/search?uri=http:%2F%2Fmashable.com%2F2015%2F03%2F16%2Fvanuatu-cyclone-pam-global-warming%2F

And for the two that are mine, one target URI is:

https://via.hypothes.is/h/http://mashable.com/2015/03/16/vanuatu-cyclone-pam-global-warming/

the other is:

https://http://mashable.com/2015/03/16/vanuatu-cyclone-pam-global-warming/

Searching for the via URL on the API yields same as non-via.

More observation, the extension makes this GET request:

https://hypothes.is/api/search?limit=20&offset=0&order=asc&sort=created&uri=http:%2F%2Fmashable.com%2F2015%2F03%2F16%2Fvanuatu-cyclone-pam-global-warming%2F

And via makes these GET requests:

https://hypothes.is/api/search?limit=20&offset=0&order=asc&sort=created&uri=https:%2F%2Fvia.hypothes.is%2Fh%2Fhttp:%2F%2Fmashable.com%2F2015%2F03%2F16%2Fvanuatu-cyclone-pam-global-warming%2F

https://hypothes.is/api/search?limit=20&offset=0&order=asc&sort=created&uri=http:%2F%2Fmashable.com%2F2015%2F03%2F16%2Fvanuatu-cyclone-pam-global-warming%2F

Thinks I'd like to understand:

1. Why does the stream request filter down to just my annotations, even after I clear cache and cookies?

2. Should a user of /stream expect coalescence such that the most general (e.g. non-via) query returns both via and non-via results, but the via subset can be isolated with a separate query?

3. Should a user of /api also expect coalescence, but realize that the query won't isolate and if that's needed the isolation happens by picking apart the json?

Please don't spend time on this unless you want to and it's quick/easy to respond. Otherwise like I said these are just observations to help me figure out what's happening between /api and /search on the one hand, and via vs extension on the other.
