### ISSUE TITLE
Replying on the stream is broken when query is not blank

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#2117]
Go to the stream.  For instance, here: 
https://hypothes.is/stream?q=tag:%27reading%27

Click "reply" on a card.  Editor not visible.
Instead, this happens:

![screen shot 2015-03-31 at 7 38 58 am](https://cloud.githubusercontent.com/assets/1413074/6924232/e3b74ddc-d78b-11e4-9208-e7a9a44a70f2.png)

**Comment by tilgovi** [comment]
I just went digging because I was sure we'd fixed this. Turns out in hypothesis/h#2070 we fixed the same symptom on the page search by clearing the query as soon as the user tries to make an annotation. That's not really a complete fix, though, since it clearly wouldn't work well on the stream.

**Comment by tilgovi** [comment]
Ref #2088

**Comment by tilgovi** [comment]
Need better handling of:

- Count of results
- Count of replies
- Count of matches at each level
- Count of edits in progress at each level

Right now it can be difficult to disambiguate certain scenarios and the counts can be off. The original intention was to have it be that any threads with edits in progress would stay open.

**Comment by dwhly** [comment]
This specific behavior is no longer present.  Now, when I click reply in the stream, I get the proper annotation editor, and I can effectively reply.  However, I cannot cancel the open dialog.  Reported here: https://github.com/hypothesis/h/issues/2182
