### ISSUE TITLE
Logging in on the streamer page redirects you to the viewer

### ISSUE THREAD

**Issue by gergely-ujvari** [hypothesis/h#2122]
Current master branch, local env
To reproduce:
1. Log off
2. Go to the streamer page
3. Observe the url (i.e. localhost:5000/stream)
4. Click on `sign in`
5. Fill properly the fields and click on the sign in button
6. Observe the url.

Excepted: Still the same
Actual: switched to the /viewer route.

**Comment by tilgovi** [comment]
This might be fixed by an angular update. Newer docs specifically mention that hash-only href's will not be rewritten. In our case, I think it's being rewritten to /#login-form which then redirects to /viewer#login-form due to our routing.

**Comment by csillag** [comment]
OK, just linking our angular updating issue here: https://github.com/hypothesis/h/issues/1631

**Comment by gergely-ujvari** [comment]
This has been fixed by https://github.com/hypothesis/h/commit/77a015100445672daa2d054ac22426e83a8039d6

Closing.
