### ISSUE TITLE
Can't create annotation if the text is at the top of the page

### ISSUE THREAD

**Issue by rgaiacs** [hypothesis/h#2124]
I loaded

~~~
<html>
  <head>
    <script async defer src="//hypothes.is/embed.js"></script>
  </head>
  <body>
    <p>Small paragraph for use as sample.</p>
  </body>
</html>
~~~

but I can't use hypothes.is widget because it isn't visible on Firefox and Chromium.

![h](https://cloud.githubusercontent.com/assets/1506457/6952371/c95fb796-d897-11e4-884d-49d4cc0eb1fe.jpg)

**Sorry if this wasn't the right place to report this.**

**Comment by csillag** [comment]
> Sorry if this wasn't the right place to report this.

Perfectly correct place to report this. Also, working example attached. Perfect. Thanks.

**Comment by csillag** [comment]
>but I can't use hypothes.is widget because it isn't visible on Firefox and Chromium.

OK, this should obviously be improved, but technically, you can still create annotations: even if the adder button is not accessible, you can just open the menu (by clicking the visible H button on the top right), and clicking on "comment".

Usually, that button is for adding page comments (ie. comments that don't address a specific part of the document, but the whole thing as a whole), but if you have a selection while clicking the button, you get a normal annotation.

That being said, we still want to fix this, at some point. Labeling this as s bug.

**Comment by dwhly** [comment]
Should we just flip the adder upside down at the top of the page? @RawKStar77?

**Comment by csillag** [comment]
In theory, that sounds good, but it might be tricky to determine correctly that we are "at the top of the page", because
  - This can also happen in the middle of the document, if the scroll position is unfortunate (ie. selected part right at the upper edge of the currently viewed segment)
  - There can be several different scrollable components on the page, making it hard to determine what to measure
  - Even if we know what to measure, it's not necessarily trivial to determine that we are at the edge, since the size of the adder button might in a different unit of measurement that the scrolling ...

... etc.

That is not to say we shouldn't explore this idea, I am just pointing out that this might not be a trivial thing to do.

**Comment by tilgovi** [comment]
We could also ditch the adder. We know it collides with other annotation tools. @RawKStar77, I think, has put a highlight button into the toolbar at the right for mobile in his open PR.

**Comment by tilgovi** [comment]
In other words, do everything from the toolbar. Shortcuts for power users.

**Comment by csillag** [comment]
> We could also ditch the adder. We know it collides with other annotation tools. 

On the other hand, there is a reason other annotation tools use the same position: it's very convenient.
Removing that ability would make it less convenient in the majority of cases.

**Comment by csillag** [comment]
> In other words, do everything from the toolbar. Shortcuts for power users.

My concern with this is that in order to get any power users, we need to be able to *retain new users*. And making the tool less convenient for them *especially at the beginning of their learning curve* might not help with that.

**Comment by tilgovi** [comment]
Obviously true, but we have to consider that we may have different needs as an extension than "other annotation tools".

An adder like that is also something we could offer to publishers and not enable for the extension, just to keep driving the point that we don't (and probably shouldn't) make our application identical across all environments.

**Comment by tilgovi** [comment]
None of which is to say that the fix is hard. I think it's easier than @csillag makes it out to be. Assuming the adder is a child of the body then we don't care about scroll position, just the viewport rectangle and actual bounding rect of the selection, which we can get from the `Range` object.

**Comment by csillag** [comment]
> and actual bounding rect of the selection, which we can get from the `Range` object.

We already have `getTop()` and `getHeight()` calls on our highlights (see [here](https://github.com/hypothesis/h/blob/cd87c2cab4017cc109ff0d4f8652db48538240eb/h/static/scripts/annotator/plugin/texthighlights.coffee#L113)); no need to go to the raw DOM APIs here.

**Comment by csillag** [comment]
> I think it's easier than @csillag makes it out to be. 

Hopefully it is; I was just mentioning *potential* difficulties. The last bit I'm still not sure about comparing the size of the adder with size available between the top of the selection and the top of the viewport rectangle. (There might be different units of measurements in play, if one is in pixels and the other is in something else... but then again, it might all be in pixels, and then it's trivial.) 

   * * *

In any case, we could work around this by simply flipping the adder over if we are closer to the top of the viewport than the bottom. (Like we do with the stems of the note in musical notation.)

**Comment by nickstenning** [comment]
Well, it took us a while, but the current adder implementation correctly positions the adder when the selection is near the viewport boundary. (See #3347).
