### ISSUE TITLE
Reorder new icons for commenting and highlighting?

### ISSUE THREAD

**Issue by JackDougherty** [hypothesis/h#2130]
I'm just a Hypothesis fan, not a user interface expert. But if you've decided to add two icons -- for commenting and highlighting -- would you consider flipping the order, so that they appear more like this?
![hypothesisicons2](https://cloud.githubusercontent.com/assets/649719/6987382/7b0501fe-da14-11e4-82b1-140c192f0e53.jpg)

Two reasons for re-ordering: highlighter -- comment
1) from left-to-right, increasing order of activity depth (commenting is more complex than highlighting)
2) moving the comment button to the right would place it closer to the actual comments in right-hand margin; more intuitive

my two cents
Jack

**Comment by RawKStar77** [comment]
Thanks for the two cents! I like this idea.

Follow up question @JackDougherty: Which do you use more?

**Comment by RawKStar77** [comment]
Also, I've added this as a commit to https://github.com/hypothesis/h/pull/2087

**Comment by JackDougherty** [comment]
Thanks @RawKStar77. I use the tool for collaborative commenting with undergraduate students. Highlighting is a nice feature, but it's the commenting that matters most.

**Comment by judell** [comment]
Thanks Jack. FYI, there are supposed to be tooltips showing on those icons, they are waiting in the wings and will soon appear. Let's see how it feels once that's done.

**Comment by tilgovi** [comment]
@RawKStar77 

> Also, I've added this as a commit to #2087

Please don't do that. Keep separate things separate.

**Comment by RawKStar77** [comment]
> Please don't do that. Keep separate things separate.

Ok, I removed that commit and will introduce it separately.

**Comment by judell** [comment]
Thanks for that separation.

**Comment by RawKStar77** [comment]
After talking about this in the design meeting and realizing that a bunch of people had different opinions on this issue, we decided it's best to close this issue for now, though if we get further feedback that this is wanted we may at some point switch them.

**Comment by BigBlueHat** [comment]
FWIW, I'd be *for* this proposed layout--just with proper fanfare about the change.

Here's how Windows 8.1 Reader app does it:
![Windows 8.1 Reader app](https://s3.amazonaws.com/f.cl.ly/items/0v1p2E3i451j2n152F1t/2015-01-26%2010_36_24-Greenshot.png)

I've seen it somewhere else recently also...but where escapes me at present.

**Comment by BigBlueHat** [comment]
Here's another vote for reordering to match "prevailing trends"...this one from [Medium.com](http://medium.com/)
![Medium's highlighter](https://s3.amazonaws.com/f.cl.ly/items/0I0k2S0i0J3l3X363p0L/Screen%20shot%202015-04-17%20at%202.59.08%20PM.png)

**Comment by BigBlueHat** [comment]
Ran into this again today.
![screen shot 2015-08-04 at 10 17 26 am](https://cloud.githubusercontent.com/assets/43209/9062837/b911eef6-3a92-11e5-8f14-b0f254e5d777.png)

(highlight from https://medium.com/matter/the-web-we-have-to-save-2eb1fe15a426)

I still feel we have this backwards given the wider context of annotation tools.

@conordelahunty this one's likely yours to sort out now. :smile:

**Comment by conordelahunty** [comment]
Thanks @BigBlueHat. Sounds like a fun one to sort out ;)

**Comment by JackDougherty** [comment]
For what it's worth, I agree with @BigBlueHat that reordering the icons (highlight and comment, from left to right) is more prevalent and intuitive. Looking forward to seeing how y'all sort this out.
