### ISSUE TITLE
Reset password flow confusion

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/h#2140]
The reset password flow currently displays a form to the user that they have no hope of filling out.

Steps to reproduce:

1. sign out and trigger the "forgot password?" flow
2. enter your email address and submit.
3. stare at this form:

    ![screen shot 2015-04-08 at 11 31 50](https://cloud.githubusercontent.com/assets/3602/7042601/472141fe-dde3-11e4-986c-c7e28bd2a767.png)

4. go check email and click on reset password link
5. new tab opens -- set new password and log in
6. some time later close new tab, and see the form that you had open in step 3.

Issues:

- Our reset password email currently looks like the following. No normal user is going to know that their "reset code" is the last component of the link URL.

> Hello, nickstenning!
>
> Someone requested resetting your password. If it was you, click here: https://hypothes.is/reset_password/2dda1be02c17
>
> If you don't want to change your password, please ignore this email message.
> 
> Regards, https://hypothes.is

- If the user follows the instructions in the email, they have no need of the form presented in step 3.

**Comment by judell** [comment]
Thanks for the heads-up. i'm finding other issues too. I am considering hijacking this morning's design meeting to air them.
