### ISSUE TITLE
Stream: uri escaping problems

### ISSUE THREAD

**Issue by gergely-ujvari** [hypothesis/h#2141]
Coming from #2129 

Problem: Stream does not give back search results for an uri which has annotations.

Hunch: The specified uri already has html escaped parts and double escape happens.

To reproduce:
uri: http://www.a2gov.org/services/Pages/OpenCityHall.aspx?pd_url=http%3a//www.peakdemocracy.com/portals/116/forum_home?admin_mode%3Doff#peak_democracy
(notice that it already has some html escaping)

1. Open the uri, enable the extension
2. Observe that the sidebar has three public annotations
3. Confirm the same with our search api: https://hypothes.is/api/search?uri=http://www.a2gov.org/services/Pages/OpenCityHall.aspx?pd_url=http%3a//www.peakdemocracy.com/portals/116/forum_home?admin_mode%3Doff#peak_democracy
4. Open the stream page: https://hypothes.is/stream
5. Search for `uri:http://www.a2gov.org/services/Pages/OpenCityHall.aspx?pd_url=http%3a//www.peakdemocracy.com/portals/116/forum_home?admin_mode%3Doff#peak_democracy`

Expected result: see the three annotations in the stream

Actual result: No result for the search.

**Comment by tilgovi** [comment]
Confirm fix on stage.

**Comment by tilgovi** [comment]
*fixed

**Comment by judell** [comment]
Double-checked and confirmed.
