### ISSUE TITLE
Undo

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#2146]
Support undoing and redoing annotation deletes and edits.

**Comment by tilgovi** [comment]
What do you mean by undoing an edit? We don't save-on-the-fly so one can hit cancel before saving.

**Comment by seanh** [comment]
I mean keep a history of saved edits and support reverting to previous versions. It might kind of pointless having a github issue for something like this, happy for this to be closed

**Comment by tilgovi** [comment]
Whatever you like. I'm just speculating that a basic ability to undo deletions could probably be implemented with much less effort than an edit history, and that they might not have equivalent value for users, so we may not wish to couple them.

**Comment by seanh** [comment]
That's a good point. Ok I've split this into two issues https://github.com/hypothesis/h/issues/2150 and https://github.com/hypothesis/h/issues/2151
