### ISSUE TITLE
Firefox: add-on not available in Private Browsing mode

### ISSUE THREAD

**Issue by RaoOfPhysics** [hypothesis/h#2160]
I tried to install the [Firefox add-on](https://addons.mozilla.org/en-US/firefox/addon/hypothesis/), but it appears that the add-on only works in non-Private-Browsing mode. Perhaps, if the add-on was built using the SDK, the solution is here: https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/private-browsing

I do most of my no-cookies-required browsing in private mode and even have my Firefox Developer Edition set to permanent-private mode, so this fix would be very much appreciated! I can (and do) use the bookmarklet currently.

Many thanks!

**Comment by tilgovi** [comment]
Tough call. Let's see what @judell thinks.

I had originally decided not to do this for the Chrome extension since having the extension on means sending annotation queries back to the server that reveal your browsing activity.

Even though we try to be transparent about our data usage, I think thought it was a potential confusion / worry if we didn't stay out of the private browsing mode.

**Comment by judell** [comment]
I think @tilgovi did the right thing. We might be able to provide override for an informed user like  @RaoOfPhysics. But many other things will be ahead of that in the queue! 

I'm quite interested in your experiences with the bookmarklet, especially the extent to which CSP (Content Security Policy) has been an issue.

**Comment by RaoOfPhysics** [comment]
@tilgovi, @judell: Thanks for the quick responses and my apologies for taking so long to get back to you.

I'm aware that "private browsing" merely disables cookies and history at my end and that anyone from my ISP to Google/Facebook can track my activities if I'm signed in. My use of it is merely an exercise in self-control, forcing me to save content I find useful without relying on endless histories etc. Also, I prefer not to store cookies unless absolutely needed (e.g. for Google 2FA).

So, I'm not under illusions that using private browsing will give me privacy from those whose content I choose to visit, e.g. hypothes.is.

If there were a way to enable this (a la Chrome extensions), it would be great! And even though I'm not much of a coder, I'd be happy to explore this feature if it's not high on your list.

Somewhat related, and sorry for asking here instead of digging further: do you have plans for offline synchronisation of annotations (at least private ones)? I do a lot of my reading while travelling, and the ability to annotate/note-take without relying on an internet connection would be marvellous.

**Comment by tilgovi** [comment]
Ohh, actually, in Chrome, the user can just enable this from their extension settings.

Firefox doesn't seem to have that flexibility.

I'm tempted to say that this usage is unusual and for now you should use the bookmarklet if you must annotate from a private window.

**Comment by judell** [comment]
We like PouchDB :-)

**Comment by tilgovi** [comment]
@RaoOfPhysics here's the stub issue you can watch for offline support: https://github.com/hypothesis/vision/issues/45

Maybe we close this issue here. Thoughts?

**Comment by judell** [comment]
Agree. Thanks @RaoOfPhysics and please do keep me posted on your adventures with the bookmarklet, we're in data-gathering mode w/respect to its use, and are trying some variations on it.

**Comment by RaoOfPhysics** [comment]
@tilgovi:

> Ohh, actually, in Chrome, the user can just enable this from their extension settings.

> Firefox doesn't seem to have that flexibility.

Yeah, this is what I alluded to above. Shame that Firefox doesn't offer this feature.

I'll continue to use the bookmarklet.

> Maybe we close this issue here. Thoughts?

Agreed, thank you for addressing my comments. 

And thank you for pointing me to https://github.com/hypothesis/vision/issues/45! I'll keep an eye on it.

@judell: Will do!
