### ISSUE TITLE
Stream won't infinite scroll when there's no scroll bar.

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#2163]
This morning, the stream looked like this:

![screen shot 2015-04-16 at 7 52 37 am](https://cloud.githubusercontent.com/assets/1413074/7184559/bdb1f6ee-e412-11e4-84df-7d2004b258e7.png)

per IRC:

nickstenn> dwhly: isn't that just the same problem we've always had?
08:17 <•dwhly> i don't think so, for 2 reasons
08:18 <•dwhly> - there are only 2 annotations and a few replies showing
08:18 <•dwhly> - infinite scroll is broken
08:18 <•dwhly> my understanding of our problem is that we get the blank message cards because we haven't yet requested enough annotations to fill them in
08:19 <•dwhly> because we request 50 or 100 or whatever at a time
08:19 <•dwhly> but why would we terminate with after only fetching / rendering 6 or 7 objects total?
08:20 <•nickstenn> we request 10 at a time it seems!
08:20 <•nickstenn> that seems like a low number
08:21 <•nickstenn> infinite scroll isn't broken here, but I've run into this before
08:21 <•nickstenn> I think our infinite scroll feature isn't very smart
08:21 <•nickstenn> and if your window is big enough that there's no scroll
08:21 <•nickstenn> *scrollbar
08:21 <•nickstenn> then you can't trigger it
08:21 <•nickstenn> so yes, it's broken
08:21 <•nickstenn> but in a slightly subtle way
08:22 <•nickstenn> I think this is one for the issue tracker
08:22 <•nickstenn> take some screenshots and write it up
08:22 <•nickstenn> and file a bug
08:23 <•nickstenn> the fact that we're still showing those "Message not available" cards is, to my mind, the highest priority
08:23 <•nickstenn> it's just not something that will ever make sense to a user and so we should hide them
08:24 <•nickstenn> I think the problem is that if of the initial load enough of them are "Message not available" cards, then there's a non-trivial chance that we'll end up not rendering a scroll bar
08:24 <•nickstenn> at which point there's no `scroll` event and infinite scroll doesn't work

**Comment by tilgovi** [comment]
Since annotations may be replies we might consider fetching annotations until we have fetched all the annotations or the page is taller than the viewport.

**Comment by dwhly** [comment]
Maybe fetch annotations until the message not avail cards are filled in?

**Comment by dwhly** [comment]
This was fixed recently.

**Comment by tilgovi** [comment]
I don't think that's accurate.

**Comment by dwhly** [comment]
Sorry...

**Comment by nickstenning** [comment]
This is basically fixed. The result of #2737 is that either we load 20 annotations or all annotations (for a given query). The only scenario in which this might be a problem is if your browser window is somehow taller than 20 annotations, which is vanishingly unlikely.
