### ISSUE TITLE
Fetch more annotations on the stream

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#2164]
Related to #2163 

08:19 <•dwhly> but why would we terminate after only fetching / rendering 6 or 7 objects total?
08:20 <•nickstenn> we request 10 at a time it seems!
08:20 <•nickstenn> that seems like a low number

**Comment by tilgovi** [comment]
Our sidebar searches for 200 at a time. However, the stream uses a websocket for the infinite scroll so the overhead is considerably less than a regular search request. 200 is probably too many. 10 may be too small. Twitter, for comparison, seems to load 20 for me.

**Comment by dwhly** [comment]
+1 for doubling what we have -- we can revisit later if we don't like.
