### ISSUE TITLE
via not seeing annotations in some situations

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#2176]
Go here in chrome:
https://via.hypothes.is/http://www.nolmecolindor.com/thinking/

No annotations are visible.
Visit the same URL with the chrome extension, many annotations are visible.

Not sure how widespread this is, but this is likely a high priority issue.

**Comment by tilgovi** [comment]
@ikreymer it appears that perhaps via/pywb is injecting a rel canonical that is blank.

**Comment by tilgovi** [comment]
How's that?

**Comment by ikreymer** [comment]
yep, good catch! that field was renamed at 0.9.0, luckily a quick fix.. not sure how missed that before (maybe was using older version)
