### ISSUE TITLE
Chrome extension: local PDF support is broken

### ISSUE THREAD

**Issue by csillag** [hypothesis/h#2177]
I have just noticed that our support for annotating local PDF files in Chrome (using the extension) is broken.

I think we had this one working before, but something must have broken along the way.
Support for remote PDF files (with Chrome extension) is not broken; this only impacts offline PDF support.

**Comment by csillag** [comment]
I have just tested the state of affairs with the [PDF.js chrome extension](https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm), and it turns out that can't open local PDF files, either.

Which means that this might be caused by a policy change in Chrome[ium], because it used to work earlier.

**Comment by csillag** [comment]
At least it still works with FF. (Tested with 37.0.1, on GNU/Linux)

**Comment by tilgovi** [comment]
Cannot reproduce.

**Comment by dwhly** [comment]
Failing for me too.  

![screen shot 2015-04-18 at 12 23 32 pm](https://cloud.githubusercontent.com/assets/1413074/7216921/c96b1664-e5c5-11e4-9ecb-210c65fe65eb.png)

Using the chrome extension (0.3.2.1984) and loading the PDF I always use for local PDF testing, I get the following warning:

PDF.js v1.0.907 (build: e9072ac)
Message: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'file:///Users/dan/Downloads/patent.pdf'.
Stack: Error: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'file:///Users/dan/Downloads/patent.pdf'.
    at Error (native)
    at webViewerInitialized (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/content/web/viewer.js:6387:11)

I doublechecked that I have local file URLs enabled.

**Comment by csillag** [comment]
> Failing for me too. 

I guess that proves beyond any reasonable doubt that this is real, so I am reopening the ticket.

**Comment by tilgovi** [comment]
You're going to have to provide a bit more info, fellas. I can't reproduce on Chrome 42 or 44 (dev) on my box.

**Comment by dwhly** [comment]
> You're going to have to provide a bit more info, fellas.

Any suggestions?  I'd love to provide whatever I can. 

@csillag Are you seeing a console warning? Which chrome extension are you using?
@RawKStar77 @judell Can you deny/confirm this behavior?

**Comment by csillag** [comment]
> @csillag Are you seeing a console warning? 

The explanation given by the "more info" button:
```
PDF.js v1.0.907 (build: e9072ac)
Message: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'file:///home/csillag/Dokumentumok/test.pdf'.
Stack: Error: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'file:///home/csillag/Dokumentumok/test.pdf'.
    at Error (native)
    at webViewerInitialized (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/content/web/viewer.js:6387:11)
```

On the console:

```
XMLHttpRequest cannot load file:///home/csillag/Dokumentumok/test.pdf. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.
```

> Which chrome extension are you using?

0.3.2.1984

**Comment by tilgovi** [comment]
Any of you feel like giving your Chrome versions?

**Comment by dwhly** [comment]
42 "Up to date".

**Comment by csillag** [comment]
Chromium, 

> 42.0.2311.90 Built on 8.0, running on Debian 7.8 (64-bit)

**Comment by tilgovi** [comment]
Well, that's a bit odd. I have the same version and it works fine.

**Comment by tilgovi** [comment]
Un-installed extension. Re-installed. No problems.

**Comment by dwhly** [comment]
Uninstalled, reinstalled, and it's working now.  @csillag?

**Comment by csillag** [comment]
Sorry, already traveling. Will check when I can.
2015.04.19. 3:19 ezt írta ("Dan Whaley" <notifications@github.com>):

**Comment by csillag** [comment]
> Uninstalled, reinstalled, and it's working now.  @csillag?

Same here. After uninstalling and reinstalling the extension, the problem goes away.
Weird, but I don't think it's our fault. (Probably an oddity around managing permissions in Chrome.)
Closing.

**Comment by tilgovi** [comment]
Thanks. Let's keep an eye on these things with future updates.
