### ISSUE TITLE
Useless URL displayed for PDF annotations

### ISSUE THREAD

**Issue by csillag** [hypothesis/h#2178]
When a PDF annotation appears on the stream page, for the source, we are displaying links like this one:

[source](unsafe:urn:x-pdf:4d729513b8c25fc4f87ae4ec47952fda)

Technically, the x-pdf URN-s are generated from the PDF fingerprints, and they are indeed useful *for the system* to identify different copies of the same document, but it makes no sense whatsoever to display these links in a web page. In fact, we used to have code to specifically *avoid* displaying these, and show the file-based URLs instead.

Maybe we have stopped storing the file paths for PDFs since that; but in that case, maybe we simply shouldn't display any clickable source links for PDFs? (I guess no link is better than a broken link.)

**Comment by csillag** [comment]
> we are displaying links like this one:
>
> [source](unsafe:urn:x-pdf:4d729513b8c25fc4f87ae4ec47952fda)

Looks like github won't identify a URL using an unknown protocol as a real link, so here is the URL, copied verbatim:

unsafe:urn:x-pdf:4d729513b8c25fc4f87ae4ec47952fda

(instead of something like http:// or file:// )

**Comment by tilgovi** [comment]
Similar to #2062

**Comment by seanh** [comment]
Can't reproduce
