### ISSUE TITLE
Stream uri: search gives different results for urls prefixed with http://

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#2180]
Results differ for:

https://hypothes.is/stream?q=uri:http:%2F%2Fwww.theatlantic.com%2Ftechnology%2Farchive%2F2014%2F08%2Fadvertising-is-the-internets-original-sin%2F376041%2F

and 

https://hypothes.is/stream?q=uri:www.theatlantic.com%2Ftechnology%2Farchive%2F2014%2F08%2Fadvertising-is-the-internets-original-sin%2F376041%2F

**Comment by tilgovi** [comment]
Open PR for this at #2184

**Comment by tilgovi** [comment]
Cannot confirm fix on stage.

**Comment by tilgovi** [comment]
Possibly diagnosis: the "document" type doesn't use the new analysis so the URI alias expansion doesn't work correctly.

**Comment by tilgovi** [comment]
Issue as described is fixed, so I'm opening another issue for the new problem.

**Comment by tilgovi** [comment]
#2213
