### ISSUE TITLE
Display unanchorable annotations (orphans)?

### ISSUE THREAD

**Issue by judell** [hypothesis/h#2187]
In some cases it is possible to create an annotation that will fail to anchor. They exist on the server but do not appear in the sidebar. From the user's point of view they are expected but missing. A Google Sheet is one such case. 

- Should such annotations be displayed? 

- Is this case distinct from the case where annotation fails because of document churn?

https://github.com/hypothesis/vision/issues/76

**Comment by csillag** [comment]
> In some cases it is possible to create an annotation that will fail to
anchor

You mean, it won't even appear right after creation?

If yes, then I think it means that we basically don't support annotating
that page, so for now, those pages might need to be blacklisted.

> Should such annotations be displayed?

We used to have a widget for switching the view, and one of the views
was for "orphan annotations", but later it was removed.
Right now, there is no user-accessible way to display them in the sidebar.

> Is this case distinct from the case where annotation fails because of
document churn?

I am not sure about what this case is; if it's about the annotation
being created with wrong information, then yes, it's distinct.

**Comment by dwhly** [comment]
I think @RawKStar77 has a few design ideas for how to surface orphans. They need a home, and the current work he's doing is potentially well positioned to address this.

**Comment by tilgovi** [comment]
Alright, hypothesis/vision#76 needs to be split in two if you want that, but this issue should be closed here as it doesn't constitute work in progress or a bug in h. Please keep feature requests to vision so that we can properly filter actionable work before it hits a code repository.
