### ISSUE TITLE
Add JSONP to the API

### ISSUE THREAD

**Issue by wagoodman** [hypothesis/h#2189]
Currently the hypothesis API returns JSON, however without a CORS header in the HTTP response then you cannot use the API in a different domain (I see https://github.com/hypothesis/h/issues/2186 will take care of that). It may be useful to add a `&callback=callbackfunction` to a search request to allow JSONP responses (wrap the JSON return with a callback function):
`callbackfunction({
    "total": 16, 
    "rows": ...
});`
instead of:
`{
    "total": 16, 
    "rows": ...
}`

**Comment by tilgovi** [comment]
Should be simple. We should upgrade our Pyramid dependency if we need to, though: http://docs.pylonsproject.org/docs/pyramid/en/latest/changes.html#changes-1-5-5

**Comment by akuckartz** [comment]
Better CORS than JSONP.

**Comment by akuckartz** [comment]
According to https://github.com/hypothesis/h/pull/2303 CORS is implemented.

**Comment by robertknight** [comment]
Yes, CORS has been implemented for the API endpoints at `https://hypothes.is/api` for all HTTP methods.

For fetching public annotations this is fine. Our authentication process if you want to implement a client that can fetch private annotations or create/update annotations still sucks though. We're going to fix that in the new year.
