### ISSUE TITLE
annotations not displaying in https://via.hypothes.is/http://blogs.plos.org/scicomm/2015/04/13/hello-world/

### ISSUE THREAD

**Issue by rdhyee** [hypothesis/h#2190]
Annotations are not showing up in https://via.hypothes.is/http://blogs.plos.org/scicomm/2015/04/13/hello-world/ (on Chrome Version 42.0.2311.90 (64-bit) on Mac OS X 10.9.5 and in Firefox 37.0.2 on the same system):

![via_plos org](https://cloud.githubusercontent.com/assets/153266/7322682/80de931a-ea5e-11e4-91f3-7dee11f92025.jpg)

However, they do show up when I use the browser plugin:

![h_plugin_plos org](https://cloud.githubusercontent.com/assets/153266/7322703/9984a5f8-ea5e-11e4-9820-2f9d3ecf797a.jpg)

**Comment by judell** [comment]
Yep, we broke via again. As a consolation for the vanishing annotations, the counts remain available in the buckets, and the title flashes entertainingly. https://via.hypothes.is/http://www.nytimes.com/2015/01/17/science/earth/2014-was-hottest-year-on-record-surpassing-2010.html?_r=2

**Comment by gergely-ujvari** [comment]
For the first analysis, it seems via is doing a double (or triple) embedding.
```
Uncaught Error: A second Discovery server has been detected at https://hypothes.is.
This is unsupported and will cause unexpected behaviour.
```

This is the start of the carnage

**Comment by csillag** [comment]
> For the first analysis, it seems via is doing a double (or triple) embedding.

That's strage for several reasons.
1. We are supposed to have protection in place against that.
2. Where do the two instances come from? (nytimes doesn't have H embedded; there is no active extension - so there is only via.)

**Comment by gergely-ujvari** [comment]
There are no more instances, our libraries load and after a while they load again (and sometimes again) I'm checking if there is any redirection issue or something similar

**Comment by gergely-ujvari** [comment]
@tilgovi: In commit https://github.com/hypothesis/via/commit/b60c70cef1e27f1bfd3e1b9eb89855c49755f309 you're no longer removing the embed script (or calling the destroy.js) can this be the source of this double-triple calling?

**Comment by tilgovi** [comment]
If that's the source of the issue it's not because I'm no longer removing the embed script. The embed script has never been removed, AFAIK. That code had a delete_h function that would remove the embed script, but it was never called.

**Comment by tilgovi** [comment]
But, the idea that something is causing the script to be re-added / re-evaluated is a reasonable thought.

**Comment by ikreymer** [comment]
With the latest change, the inject is happening on every iframe, so pages that have multiple iframes get multiple injects. A simple:

```
if (window != window.top) {
   return;
}
```
seems to be enough to prevent this behavior.

**Comment by tilgovi** [comment]
Fixed and deployed. Thanks, @ikreymer. @judell please re-open if you see anything like this again.

**Comment by tilgovi** [comment]
Or you, @rdhyee. Or anyone :).

**Comment by judell** [comment]
Thanks, @ikreymer <https://github.com/ikreymer>

**Comment by rdhyee** [comment]
Thanks everyone!  I had no idea about all the cool stuff behind `via` until I heard yesterday's talk by @ikreymer.   So thanks for `via` too. :-)
