### ISSUE TITLE
[hack day] Page search: add support for searching for multiple users

### ISSUE THREAD

**Issue by csillag** [hypothesis/h#2191]
Currently, in page search, we can't run a search like "user:userA,userB".
This would be required to select the annotations made by a specific group of people.

**Comment by tilgovi** [comment]
Doesn't the `user:userA user:userB` syntax work?

**Comment by csillag** [comment]
@gergely-ujvari has just pointed out that it does.

(Earlier someone suggested `user:userA,userB`, so I tried that one first, and mistakenly concluded that it doesn't work.)
