### ISSUE TITLE
ny times story works in via, fails in extension

### ISSUE THREAD

**Issue by judell** [hypothesis/h#2194]
http://www.nytimes.com/2015/01/17/science/earth/2014-was-hottest-year-on-record-surpassing-2010.html

browser: chrome
extension: 0.3.2.1984

 Uncaught TypeError: undefined is not a function
?url=http%3A%2F%2Fwww.nytimes.com%2F2015%2F01%2F17%2Fscience%2Fearth%2F2014-was-hottest-year-on-rec…:374 Uncaught TypeError: undefined is not a function
framework.js:2 Uncaught Error: Mismatched anonymous define() module: function (){return lib$es6$promise$umd$$ES6Promise}
http://requirejs.org/docs/errors.html#mismatch
?url=http%3A%2F%2Fwww.nytimes.com%2F2015%2F01%2F17%2Fscience%2Fearth%2F2014-was-hottest-year-on-rec…:384 Uncaught TypeError: undefined is not a function
framework.js:2 Uncaught Error: Mismatched anonymous define() module: function (){return Hammer}
http://requirejs.org/docs/errors.html#mismatch

**Comment by tilgovi** [comment]
This is 18055d642f0cee140fc1b00d9cfc33b681772625 we just haven't shipped a new extension yet, because the way I changed the double embed prevention conflicts with the way the extension does things. I'll be working on this tomorrow.

**Comment by tilgovi** [comment]
So, uh, I'll leave this issue open as that, even though the traceback shows an error that's already fixed, in a sense.

**Comment by judell** [comment]
Ok. Since for the time being we are two different clients on two different release schedules, shall we name and version them accordingly? 

Longer term, should we release in a synchronized way? It's confusing even to me to think about how and why one path to H functionality can behave so differently from  another, I don't want to inflict that on users.

-----Original Message-----

**Comment by tilgovi** [comment]
We're in this state because I rushed things out the door in response to the rapid churn we've experienced trying to clean up the via/extension interactions. Let's see if that settles and be mindful before we fragment our deploy process. I'd much rather just have a simple check-list and deploy all the things every time.

**Comment by judell** [comment]
+1 to the all-the-things-always approach and the checklist to validate it.
Let's discuss offline about the checklist.

**Comment by judell** [comment]
Another item for the checklist: http://www.wsj.com/articles/climate-science-is-not-settled-1411143565. Is this in the same state as http://www.nytimes.com/2015/01/17/science/earth/2014-was-hottest-year-on-record-surpassing-2010.html? I ask because the error in this case is coming from jschannel.
