### ISSUE TITLE
Enable touch annotation on iOS

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#2200]
I've phrased this as a feature request since I can't recall whether we'd intended that the current touch capability was supposed to work on iOS yet.  I think not.

At the moment, selecting text and clicking the annotation icon does not work.

**Comment by csillag** [comment]
>  I can't recall whether we'd intended that the current touch capability
was supposed to work on iOS yet. I think not.

IIRC, it was supposed to work.

**Comment by tilgovi** [comment]
That's my recollection, too.

**Comment by RawKStar77** [comment]
> At the moment, selecting text and clicking the annotation icon does not work.

Clarification: That *Does* work, I made [this annotation](https://hypothes.is/a/AlQKzHBwSpSgaA0aeZgi_w) on my phone running iOS 8.2.

I think touch annotation is a good idea regardless and so +1 for the existence of this issue. Apologies, I must have forgotten about that requirement. : /

**Comment by RawKStar77** [comment]
Let's clarify what we mean by "touch annotation." My interpretation:
1. User selects text on a mobile device.
2. We watch for a touch event on the highlight.
3. On touch we highlight the text.

**Comment by dwhly** [comment]
Ok, more data:

I upgraded from iOS 7.1 to iOS 8.whatever and the problem has disappeared on Safari (latest).  So, clearly this issue as labeled does not apply.  We could relabel it as a 7.x issue, though I'm not sure it's worth the time to chase right now.  Here are some 8x vs 7x stats, which show penetration at about 76% which in just 8 months, suggesting that things should be approaching 90% probably by the end of the year?

It's possible that selection still doesn't work on Chrome, but this is impossible to test at the moment because of this new issue (https://github.com/hypothesis/via/issues/10) that is blocking jake and i from even being able to test Chrome on iOS.

**Comment by dwhly** [comment]
I'm going to close this pending the resolution of https://github.com/hypothesis/via/issues/10

**Comment by dwhly** [comment]
Wait:

> Let's clarify what we mean by "touch annotation." My interpretation:
> 1. User selects text on a mobile device.
> 2. We watch for a touch event on the highlight.
> 3. On touch we highlight the text.

I don't understand.

Currently, with Safari, I select text and press the annotation icon.  It works quite well.  To me that's probably sufficient for now.  What else is possible?

**Comment by RawKStar77** [comment]
> Currently, with Safari, I select text and press the annotation icon. It works quite well. To me that's probably sufficient for now. What else is possible?

We might want to explore different UX for highlight creation on mobile, but I think there are more pressing concerns now.

**Comment by dwhly** [comment]
+1
