### ISSUE TITLE
libsass and bourbon

### ISSUE THREAD

**Issue by tilgovi** [hypothesis/h#2201]
Consider switching to libsass and bourbon instead of compass.
http://bourbon.io/
https://pypi.python.org/pypi/libsass/0.7.0

**Comment by keitheis** [comment]
Autoprefixer might be another candidate to compass or bourbon.
https://github.com/postcss/autoprefixer
http://webassets.readthedocs.org/en/latest/builtin_filters.html#autoprefixer

**Comment by nickstenning** [comment]
Closing as a dupe of #1292.
