### ISSUE TITLE
Links in markdown prepend hypothes.is when http:// is not specified.

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#2202]
Create a link in markdown, like this:

![screen shot 2015-04-30 at 9 06 33 am](https://cloud.githubusercontent.com/assets/1413074/7417059/5d6ffa18-ef18-11e4-9941-0d2232f6edb1.png)

The link that's created is "https://hypothes.is/yahoo.com"

This can be circumvented by specifying http:// before the domain.

**Comment by judell** [comment]
Although Markdown is not a standard, I don't think you'll find an implementation that doesn't behave this way. For example: https://github.com/judell/elmcity/issues/3

**Comment by nickstenning** [comment]
That's not a bug. That's how links work. It doesn't prepend "https://hypothes.is", it creates a relative link.

**Comment by dwhly** [comment]
tx, i suppose it makes sense of course.
