### ISSUE TITLE
"message not available" on stream

### ISSUE THREAD

**Issue by judell** [hypothesis/h#2203]
https://hypothes.is/stream?q=user:jallred

related:

https://github.com/hypothesis/h/issues/1916
https://github.com/hypothesis/h/issues/1613

others?

https://hypothes.is/api/search?user=jallred sees 5 annotations, all on www.theatlantic.com/technology/archive/2014/08/advertising-is-the-internets-original-sin/376041/

https://hypothes.is/stream?q=user:jallred sees 2, reports 3 missing

user:jallred the sidebar sees 5 results: 2 annotations and 3 replies

**Comment by tilgovi** [comment]
Duplicate of #1916, per your own description. Is there a reason why you opened this issue?

**Comment by judell** [comment]
Sorry, I thought incorrectly this was solved. I'll close this and focus on #1916.
