### ISSUE TITLE
clarify result count for search in sidebar

### ISSUE THREAD

**Issue by judell** [hypothesis/h#2204]
At http://www.theatlantic.com/technology/archive/2014/08/advertising-is-the-internets-original-sin/376041/ jallred has made 5 contributions: 2 annotations, 3 replies.

These searches report 5 results:

jallred

or 

user:jallred

So far, so good. Now expand the first collapsed reply to jallred's first annotation, from tilgovi.

*Found 6 results*

Now expand the next annotation from jeremydean which is collapsed because jallred only replied to it.

*Found 8 results*

And again for my annotation to which jallred replied.

*Found 9 results*

There are 9 annotations in threads that jallred started or joined. But still only 5 annotations or replies that match *jallred*.

For the same Atlantic article, search for *economic context*

*Found 1 result*

Click *View 2 more in conversation*

*Found 3 results*

Alternatively just expand jallred's reply to tilgovi:

*Found 2 results*

Now search for *ads*

*Found 3 results*

The first is in a standalone jeremydean annotation.

The second is in an expanded jallred reply to collapsed jeremydean annotation (collapsed because it does not contain *ads*), and the third is in an expanded reply to that reply.

Now expand that collapsed jeremydean annotation:

*Found 4 results*

The behavior here -- revealing just the annotations and replies that contain the search term -- is sophisticated and effective. This is only a question about how to describe what is happening.

Straw man proposals:

*term* found in n annotations

*term* found in n annotations and m replies

Either way, the numbers would not change as collapsed parts of threads are expanded. The count of search results does not vary, it's only the visibility of context surrounding them that does.

**Comment by tilgovi** [comment]
Duplicate of #2088?

**Comment by judell** [comment]
Closing in favor of #2088.
