### ISSUE TITLE
Non-standard CSS property disables selection

### ISSUE THREAD

**Issue by BigBlueHat** [hypothesis/h#2205]
Surfacing from [Disable `user-select: none` when found](https://github.com/openannotation/annotator/issues/522) posted for Annotator.

Objective is to either:
 - let the user know hypothes.is can't (or isn't being "allowed" to) annotate the page
 - remove the CSS property so that the selection works as the user would want

Test it out on:
http://pitbullmixed.com/ :dog: 

This quote from http://caniuse.com/#feat=user-select-none says it all:
> Currently the user-select property does not appear in any W3C specification. Support information here is only for "none" value, not others.

**Comment by csillag** [comment]
> Non-standard CSS selector disables selection

True, but I don't see 
 * why is that a problem?
 * what could/should we do about that?

AFAIK, the `user-select` property is there to make some elements (for example, buttons and such) non-selectable. Why is it a problem that we can't select those items?

... or is the point of this report that *in the presence* of this CSS selector (anywhere on the page), we can't select *anything*? If so, is this a browser problem, or a Annotator/H problem?

**Comment by BigBlueHat** [comment]
Did you try the site? :smile:

You can't select any text on the page. Which means there are no selection
events for annotator to catch. Which means it is not annotate-able unless
it's removed. Hence the issue.

We don't work on this site (and others like it) unless we disable the
disabler. :)

**Comment by csillag** [comment]
On p, máj 1, 2015 at 9:00 , BigBlueHat <notifications@github.com> 
wrote:
> Did you try the site? :smile:

Yes. I couldn't select anything.

What was unclear to me is whether this was the intended effect of the 
site's creator,
or was this a browser bug?

If this was an intended effect, then do we still want to force it?

**Comment by tilgovi** [comment]
I wouldn't force this.

**Comment by BigBlueHat** [comment]
@csillag it's definitely the intention of the site's creator. My original post was unclear (so, I'll update it shortly). Point was that we need to let users know--as we're working to do on other site's we fail on (currently). Or, we take action (disable that "feature") in order to properly function on the site.

@tilgovi "I wouldn't force this"--meaning? You wouldn't force it off?

If not, we at least need to let the user know (somehow) why Hypothes.is isn't / won't function on the site. Otherwise, it looks like our system/UI has failed...

**Comment by tilgovi** [comment]
I think there are reasons why someone might use this selector, e.g.
interface elements that are not meant to be part of the text.

So I'm reacting to the idea that we would be choosing between sometimes
doing the wrong thing or doing some heuristic thing, which is always less
straightforward than doing something all-or-nothing.

Finally, I want to aim for such a quality of product that a person's first
thought is to blame the site, and not our application.

Let's fix the problems that impact a user's ability to trust that our
product works. Then we don't have to worry about all the ways site owners
break their sites.

**Comment by BigBlueHat** [comment]
> Finally, I want to aim for such a quality of product that a person's first
thought is to blame the site, and not our application.

That'd be super if most people knew the difference in the first place...

I've no clear way to solve this one, other than to say if a user tries to use Hypothes.is on a site with this setting, the user will be unhappy. Maybe with the site. Maybe with us. If they're currently trying to annotation and can't, it'll be unhappy with us. Regardless, they'll move on.

Here's hoping someone can craft a clear solution, so I can annotate all those wonderful pit bull articles. :dog: :wink:

**Comment by tilgovi** [comment]
Speaking about people who _install our application_ I think it's safe to say they know the difference between us and the site their on. After all, they _installed_ our application.

About people who haven't, the site owner is embedding the application and it's safe to say they will not do so when they've also simultaneously made it impossible to use.

I'm closing this as won't fix. I'm not about to check the computed styles on everything just to neutralize this bad publisher practice that most serious publishers would never go near anyway.
