### ISSUE TITLE
Controls are incredibly small on Nexus 6

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#2211]
It looks like the interface doesn't size appropriately in consideration of my Nexus 6 / android.
https://via.hypothes.is/http://www.folgerdigitaltexts.org/html/MND.html

![screenshot_2015-05-03-06-53-59](https://cloud.githubusercontent.com/assets/1413074/7445332/a31d0dac-f162-11e4-81b7-8884e67a1406.png)

**Comment by RawKStar77** [comment]
I this in general? Or on that specific page?

**Comment by tilgovi** [comment]
bump what @RawKStar77 said

**Comment by dwhly** [comment]
Sorry, its general, I had to go look for examples, but no, its the same on any page for this device, which has a particularly large screen btw

**Comment by chdorner** [comment]
It looks a bit better nowadays, but still too small IMO. Screenshot from a Nexus 5:
![screenshot_20160722-164015](https://cloud.githubusercontent.com/assets/112063/17060658/56484c2a-502b-11e6-834d-d0d426e39376.png)

**Comment by nickstenning** [comment]
Moved to https://github.com/hypothesis/client/issues/255.
