### ISSUE TITLE
chrome extension may fail to update

### ISSUE THREAD

**Issue by judell** [hypothesis/h#2212]
I saw this last month, when my extension was weeks out of date and I had to force-update from 1816 to 1927.

Jeremy Dean reported the same thing today. His extension was 1927 (April 6), we are currently at 2019 (April 30).

Google say extensions auto-update within hours but manifestly that can be weeks 

No normal user will ever think a) forcing an update is needed, b) figure out that to do so you need to check the Developer Mode box on the Extensions page to reveal the Update Extensions Now button, or c) want to remove/re-add in order to force update.

**Comment by tilgovi** [comment]
We need to see if this is actually still a problem.

In the most recent updates I added code that reloads the extension when a new version becomes available. In the past, I think you had to close and reopen chrome, which we know many people do rarely.

**Comment by tilgovi** [comment]
Of course, Jeremy having the old code would not have that feature.

We need to see what happens on the next update, but as far as I can reason this is already closed.

Or if it isn't, we need real requirements in the form of, for instance, "It should take no longer than..."

And, of course, we should have a story other than, "As a member of the team I'd like to help more with Q&A...". In other words, most users might not care most of the time about whether they have the absolute newest version.

**Comment by dwhly** [comment]
> In the most recent updates I added code that reloads the extension when a new version becomes available. 

:heart:

**Comment by judell** [comment]
"We need to see what happens on the next update, but as far as I can reason this is already closed."

Excellent! If you alert us when the next extension lands we can verify that we're all updated promptly.
