### ISSUE TITLE
URI search for via.hypothes.is gives back unexpected results

### ISSUE THREAD

**Issue by gergely-ujvari** [hypothesis/h#2217]
I tried to search for annotations created with the via uri like this:
https://api.hypothes.is/search?uri=https://via.hypothes.is/
also checked out the new es-mappings for uri in stage:
https://stage.hypothes.is/api/search?uri=https://via.hypothes.is/

The result in both cases is 4 annotations with google.com domain uris.  (Check the links)
This is not be right.

**Comment by gergely-ujvari** [comment]
Adding the stream link, because annotation cards are easier to read than raw json: https://hypothes.is/stream?q=uri:https:%2F%2Fvia.hypothes.is%2F

**Comment by judell** [comment]
See also:

https://hypothes.is/stream?q=uri:http%3A//blog.jonudell.net

https://hypothes.is/stream?q=uri:http%3A//blog.jonudell.net/

**Comment by judell** [comment]
Still an issue.

https://hypothes.is/api/search?uri=http%3A%2F%2Fblog.jonudell.net%2F -> 3

https://hypothes.is/api/search?uri=http%3A%2F%2Fblog.jonudell.net

Tagged: document_equivalence

**Comment by judell** [comment]
Does not repro. Thought #2413 was the fix, apparently not, but closing anyway.

**Comment by judell** [comment]
Actually I think https://github.com/hypothesis/h/commit/38bc599488b9100adc752fa952ead73df21bfca0   is the fix.

**Comment by judell** [comment]
Actually I think https://github.com/hypothesis/h/commit/38bc599488b9100adc752fa952ead73df21bfca0   is the fix.

**Comment by judell** [comment]
Actually I think https://github.com/hypothesis/h/commit/38bc599488b9100adc752fa952ead73df21bfca0   is the fix.

**Comment by judell** [comment]
https://github.com/hypothesis/h/commit/38bc599488b9100adc752fa952ead73df21bfca0
