### ISSUE TITLE
"Session is invalid": Firefox bookmarklet

### ISSUE THREAD

**Issue by RaoOfPhysics** [hypothesis/h#2223]
For the last couple of days, I have noticed that I am unable to call hypothes.is via the bookmarklet to annotate webpages or PDFs. While I can sign in by heading to https://hypothes.is/login and I appear signed in when I'm surfing any pages on the hypothes.is domain, I appear offline when elsewhere. Attempts to sign in present me with this error message:

![screen shot 2015-05-09 at 20 43 19](https://cloud.githubusercontent.com/assets/7623019/7551545/732e0414-f68c-11e4-9b18-09d6ffa8edc7.png)

I have uninstalled all (all!) extensions and cleared all local caches/proxies, but the error persists. Any advice would be very much appreciated!

**Comment by tilgovi** [comment]
Do you have third party cookies disabled?

**Comment by RaoOfPhysics** [comment]
@tilgovi: m-(

Indeed. My apologies. I added `https://hypothes.is` as an "always allow" exception.

**Comment by tilgovi** [comment]
Thanks. We're aware of this issue and #914 tracks the work.

**Comment by RaoOfPhysics** [comment]
@tilgovi: I'm getting the same error once again. I hadn't changed the configuration from before -- `https://hypothes.is` is still an "always allow" exception for browser cookies. I also tested it with all add-ons disabled. It won't work in Firefox or Firefox Developer Edition.

Any suggestions?

**Comment by pguth** [comment]
> Do you have third party cookies disabled?

This just bit me too. Firefox hides (\*argh\*) the relevant setting under `Preferences` -> `Privacy` -> `Firefox ... will: [Dropdown] Remember History`. Switch it to `Use custom settings for history` then you can change/set third party cookie options.

**Comment by tlc** [comment]
I just want to verify that 3rd party cookies are absolutely necessary.
I tried adding "https://hypothes.is as an "always allow" exception" as someone said above, but that didn't work (w/o 3rd party cookies).

I miss h, but I recently became more tracking sensitive and really don't want to turn on 3rd party cookies.  I haven't spotted an extension that manages 3rd party access...

**Comment by robertknight** [comment]
Hello @tlc - Third party cookies (or at least always allowing https://hypothes.is to get/set cookies when loaded in a third-party context) are currently required by the client, but hopefully not for too much longer. We're currently in the process of changing the way the client authenticates which should remove that requirement.

We're also working on a Firefox extension to provide a better experience for Firefox users.
