### ISSUE TITLE
annotations don't sync from sidebar to rows in html tables

### ISSUE THREAD

**Issue by judell** [hypothesis/h#2227]
I would guess this has been reported before but I searched and did not find so, in case not:

http://jonudell.net/h/table-test.html

The bucket bar knows where the annotated rows are and tracks them. But clicking the annotations in the sidebar does not sync the document.

Not expecting action soon on this, just wanted it noted. I'm tempted to create a SynchronizedScrolling label for this and similar cases. We don't seem to label with that granularity, though. Maybe I should use pinboard.in for more granular tagging?

**Comment by tilgovi** [comment]
Feel free to make labels if you need them. I cleaned some out yesterday. Just ask yourself whether the label really helps visualize the data in a way that's useful. If it's more about finding a particular issue again in the future, I find the search to usually be pretty good, provided we don't have a million bugs.

**Comment by judell** [comment]
It's often useful to me when I am tentatively classifying things in ways that morph as I proceed. But that process creates a lot of tag churn so maybe I'll do it externally.

**Comment by judell** [comment]
Tagged: sidebar_document_sync

**Comment by tilgovi** [comment]
Can't reproduce.

**Comment by judell** [comment]
The test was pre-0.5, I wonder if this improvement is no-dtm-related or something else. In any case, excellent!
