### ISSUE TITLE
plosone pdf view not working in chrome

### ISSUE THREAD

**Issue by judell** [hypothesis/h#2229]
http://www.plosone.org/article/fetchObject.action?uri=info:doi/10.1371/journal.pone.0114911&representation=PDF

Uncaught TypeError: Cannot read property 'appendChild' of null

https://groups.google.com/a/list.hypothes.is/forum/#!search/plos/dev/KSHFNlH0YU8/cAIu1gZLUDsJ

Local annotation is fine.

**Comment by tilgovi** [comment]
Environment? Works fine for me in FF.

**Comment by judell** [comment]
Doh. Sorry. Chrome.

**Comment by tilgovi** [comment]
Duplicate of #1900?

**Comment by judell** [comment]
Ah, yes, thanks. Closing in favor of #1900.

**Comment by judell** [comment]
I really must try to remember that almost everything has happened before.
