### ISSUE TITLE
Add feed icon to sidebar

### ISSUE THREAD

**Issue by BigBlueHat** [hypothesis/h#2252]
We have Atom feed support, and it is possible to construct a feed of the annotations on a specific resource, but good luck to the user who figures that out! :wink: 

If we do the proposal I made in https://github.com/hypothesis/h/pull/2215#issuecomment-104915938 for moving the share icon closer to the other click-able things, we'd also provide space for this button as well:
![feed-icon](https://cloud.githubusercontent.com/assets/43209/7784923/5cd1a364-0146-11e5-9754-482646b1d2f4.png)

Clicking that feed icon could bring up a palate similar to the one currently proposed for `share` (#2215) and would include (initially) a URL to click (and/or copy/paste) for the Atom feed itself as well as (eventually) a feel to subscribe via email (by entering an email address if you haven't yet, etc).

Steps:
 - [ ] add the link in that sare
 - [ ] make it open a card/palette thing similar to `share` (in #2215)
 - [ ] have that include a click-able URL (As some browsers have feed readers built in...or Do The Right Thing when clicked)
 - [ ] also include a copy/paste-out-of box for those who don't have cool browsers :smile:

**Comment by tilgovi** [comment]
:+1:

**Comment by judell** [comment]
We'll need to work through the possibilities because there is not one Atom feed, there's the possibility to follow activity for:

* a user 

* an URL

* a tag

* (and eventually) a group

I'm fine with using the RSS icon to signify following in general -- which most people will not prefer to do using RSS or Atom, but rather email, phone notification, etc -- but we will surely need to explore how to invite these different modes of following.

I hope we can continue https://groups.dokku.hypothes.is/ as a way of doing that exploration.

**Comment by BigBlueHat** [comment]
The Atom feed linked to behind that icon would be based on whatever the current view filter(s) are--including search, group your looking at, etc.

I think there's going to be a need to "fix" the view filters as you scroll the sidebar down--especially as we add more filters. Or perhaps they all need to go up into that search bar...which will get quite crowded quite soon....hmm....sounds like a job for @RawKStar77 :exclamation: :wink:

**Comment by BigBlueHat** [comment]
@conordelahunty would love to see this added to the Share dialog (at least). /cc @robertknight 

Went looking for the annotation Atom feed for a page I'm encouraging annotation on...but looks like I'll have to construct it by hand. Users won't want to do that...and certainly shouldn't have to--as I'm sure you know. :wink:

**Comment by judell** [comment]
We'll revisit this in the context of a design that exposes query facets explicitly.
