### ISSUE TITLE
KeyError: 'ws4py.websocket' on every page load

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#2256]
I'm getting the traceback below on every page load on master. It seems to have been introduced by this commit:<https://github.com/hypothesis/h/commit/2b19126cba3b2588dfe7c084b9253298b11ca2bb>. Re-enabling h.feature.queue and h.feature.streamer gets rid of the error (although it introduces another traceback that I'm still investigating).

@tilgovi Why disable the WebSocket streaming, email notifications, and the NSQ dependency in development? Generally I'd think that differences between development and production are a bad thing. And are you seeing the same error as me on master?

```
/home/seanh/.virtualenvs/h/local/lib/python2.7/site-packages/sqlalchemy/ext/declarative/api.py:173: SAWarning: Unmanaged access of declarative attribute __tablename__ from non-mapped class UserGroupMixin
  (desc.fget.__name__, cls.__name__))
/home/seanh/.virtualenvs/h/local/lib/python2.7/site-packages/sqlalchemy/ext/declarative/api.py:173: SAWarning: Unmanaged access of declarative attribute __tablename__ from non-mapped class GroupMixin
  (desc.fget.__name__, cls.__name__))
/home/seanh/.virtualenvs/h/local/lib/python2.7/site-packages/sqlalchemy/ext/declarative/api.py:173: SAWarning: Unmanaged access of declarative attribute __tablename__ from non-mapped class ActivationMixin
  (desc.fget.__name__, cls.__name__))
/home/seanh/.virtualenvs/h/local/lib/python2.7/site-packages/sqlalchemy/ext/declarative/api.py:173: SAWarning: Unmanaged access of declarative attribute __tablename__ from non-mapped class UserMixin
  (desc.fget.__name__, cls.__name__))
Traceback (most recent call last):
  File "/home/seanh/.virtualenvs/h/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 508, in handle_one_response
    self.run_application()
  File "/home/seanh/.virtualenvs/h/local/lib/python2.7/site-packages/ws4py/server/geventserver.py", line 58, in run_application
    ws = self.environ.pop('ws4py.websocket')
KeyError: 'ws4py.websocket'
{'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, sdch',
 'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.8',
 'HTTP_CACHE_CONTROL': 'no-cache',
 'HTTP_CONNECTION': 'Upgrade',
 'HTTP_COOKIE': 'XSRF-TOKEN=742d00d8d4ac868b13b4199bbc96804b438edb07; session=vTgGcIDSM3WLIJGcWT8lvOu-G-C754gSKiZMXz4ZqYaBRAsx-RYl3MChL8bf7Ra8miJ1nBmlXWhQdBqFNgtg9YACSuRzZFVHQdVX0tJBL3d9cQFVB19jc3JmdF9xAlgoAAAANzQyZDAwZDhkNGFjODY4YjEzYjQxOTliYmM5NjgwNGI0MzhlZGIwN3EDc4dxBC4',
 'HTTP_DNT': '1',
 'HTTP_HOST': '127.0.0.1:5000',
 'HTTP_ORIGIN': 'http://127.0.0.1:5000',
 'HTTP_PRAGMA': 'no-cache',
 'HTTP_SEC_WEBSOCKET_EXTENSIONS': 'permessage-deflate; client_max_window_bits',
 'HTTP_SEC_WEBSOCKET_KEY': 'qxsXc2LEdlB3ZUEogbg6iQ==',
 'HTTP_SEC_WEBSOCKET_VERSION': '13',
 'HTTP_UPGRADE': 'websocket',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.65 Safari/537.36',
 'PATH_INFO': '/ws',
 'QUERY_STRING': '',
 'RAW_URI': '/ws',
 'REMOTE_ADDR': '127.0.0.1',
 'REMOTE_PORT': '54983',
 'REQUEST_METHOD': 'GET',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'localhost',
 'SERVER_PORT': '5000',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'gevent/1.0.2 gunicorn/19.3.0',
 'gunicorn.sock': <socket at 0x2b3166214650 fileno=13 sock=127.0.0.1:5000 peer=127.0.0.1:54983>,
 'webob._parsed_cookies': ({u'XSRF-TOKEN': u'742d00d8d4ac868b13b4199bbc96804b438edb07',
                            u'session': u'vTgGcIDSM3WLIJGcWT8lvOu-G-C754gSKiZMXz4ZqYaBRAsx-RYl3MChL8bf7Ra8miJ1nBmlXWhQdBqFNgtg9YACSuRzZFVHQdVX0tJBL3d9cQFVB19jc3JmdF9xAlgoAAAANzQyZDAwZDhkNGFjODY4YjEzYjQxOTliYmM5NjgwNGI0MzhlZGIwN3EDc4dxBC4'},
                           'XSRF-TOKEN=742d00d8d4ac868b13b4199bbc96804b438edb07; session=vTgGcIDSM3WLIJGcWT8lvOu-G-C754gSKiZMXz4ZqYaBRAsx-RYl3MChL8bf7Ra8miJ1nBmlXWhQdBqFNgtg9YACSuRzZFVHQdVX0tJBL3d9cQFVB19jc3JmdF9xAlgoAAAANzQyZDAwZDhkNGFjODY4YjEzYjQxOTliYmM5NjgwNGI0MzhlZGIwN3EDc4dxBC4'),
 'webob._parsed_query_vars': (GET([]), ''),
 'wsgi.errors': <gunicorn.http.wsgi.WSGIErrorsWrapper object at 0x2b3164db7b90>,
 'wsgi.file_wrapper': <class 'gunicorn.http.wsgi.FileWrapper'>,
 'wsgi.input': <gevent.pywsgi.Input object at 0x2b316628cd10>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)} failed with KeyError
```

**Comment by tilgovi** [comment]
When Nick reverted the feature flags in the client commit I made, this was
the side effect.

It happens because the front end is still trying to open a WebSocket.

It doesn't happen on every request. It happens on the WebSocket request.

It's harmless.

The features are disabled in dev because I feel one should opt in to
features that require extra dependencies, especially when one may just want
to edit some templates and CSS.

If it bothers you that they aren't the same, you can turn off all the
features in prod.

**Comment by tilgovi** [comment]
This isn't a bug in h. At most, it's a bug in ws4py. We see the symptom here, but it's harmless.

**Comment by seanh** [comment]
So the frontend is still trying to open a websocket, even though the queue and streamer features are turned off on the backend? Should we stop it from trying to do that? (Is https://github.com/hypothesis/h/pull/2247 going to do that?)

About dev vs prod: what I meant was I think it's bad if our dev environments and configurations are different from the production one that's deployed at hypothes.is, so I want to develop with streamer and queue on for example.

**Comment by seanh** [comment]
> So the frontend is still trying to open a websocket, even though the queue and streamer features are 
> turned off on the backend? Should we stop it from trying to do that?

Or we could just turn the queue and streamer on in development and not even have feature flags for them. I know what you mean about wanting to make it easy for people to get hacking on the app but I wonder if they way to do that is rather to use things like vagrant or docker to make getting a dev environment up and running really easy.

**Comment by tilgovi** [comment]
Yes, re #2247.

As for dev vs prod you can turn it on if you want, for yourself.

I maintain that reducing the number of required dependencies to lower the
barrier to new contribution is more important.

They're not well tested features if it breaks in one of the two states and
we have (are working on) a stage release process to ensure we test the
production configuration before it's live.

I don't think we should get drawn in to the paranoia and the corresponding
shortcut of trying to make everything the same everywhere.

I do think it makes sense for production features to be opt in, though.

**Comment by judell** [comment]
I was seeing this in my dev env too, now not seeing it. Close this?

**Comment by seanh** [comment]
Yeah I think @tilgovi fixed this (and closed it)
