### ISSUE TITLE
Problem when building Chrome extension for staging

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#2259]
When I try to build the Chrome extension for staging with `hypothesis-buildext conf/production.ini chrome --base 'https://stage.hypothes.is/' --assets 'chrome-extension://oldbkmekfdjiffgkconlamcngmkioffd/public'` it builds a broken extension.

Angular isn't running so I see the unrendered `{{ ... }}` Angular templates in the sidebar, and in the console I have this from `angular.min.js:4`:

```
TypeError: Cannot read property 'hasOwnProperty' of undefined
    at new AppController (app.min.js:1)
    at invoke (angular.min.js:2)
    at Object.instantiate (angular.min.js:2)
    at angular.min.js:3
    at angular.min.js:3
    at forEach (angular.min.js:1)
    at nodeLinkFn (angular.min.js:3)
    at compositeLinkFn (angular.min.js:2)
    at publicLinkFn (angular.min.js:2)
    at angular.min.js:1
```

Here's a screencast of me building the extension:

http://youtu.be/t6pedTSH7z0

Notes:

* On current latest master
* No modifications except to add a dependency (needed to build the extension with production.ini) to setup.py
* Fresh virtualenv, make dev is working, tests are all passing
* Lots of output from npm, I do have some things globally installed, but nothing that looks bad
* Chrome extension ID is correct
* I get one warning when building the extension about a secret key but that doesn't seem like it would cause this
* No previous copy of the extension installed, I'm installing it first time as an unpacked extension
* The extension opens hypothes.is/welcome even though it was built for stage.hypothes.is

If I turn on _pause on uncaught exceptions_ in Chrome I'm getting baffling exceptions in the middle of `jquery.min.js`.

No idea what's wrong here.

I'll investigate further later this afternoon

**Comment by seanh** [comment]
uglify-js 2.4.23, browserify 9.0.8, coffee script 1.7.1 -- it all seems to have been installed in node_modules correctly according to package.json, I'm not seeing anything obviously wrong here.

**Comment by seanh** [comment]
After many hours of investigation this issue has just disappeared on its own, no idea why :(

**Comment by tilgovi** [comment]
OH SO FRUSTRATING but also a relief

**Comment by seanh** [comment]
I'm mostly happy and relieved but with a lingering underlying sense of angst!
