### ISSUE TITLE
note icons need tooltips

### ISSUE THREAD

**Issue by judell** [hypothesis/h#2263]
Suggestions:

![image](https://cloud.githubusercontent.com/assets/46509/7891670/60a6e44c-0603-11e5-8dc5-7eef5de6d962.png)

Discussion: One thing revealed clearly in a couple of recent reports is that when things go wrong for one reason or another and selection-based annotation becomes unavailable, people find their way to page-based annotation, without realizing that it is page-based annotation. These changes aim to sharpen the distinction between selection-based notes and page-based notes, and also clarify the other iconography.

**Comment by tilgovi** [comment]
There's only one problem with this suggestion: that button isn't just for page notes. If you have a selection, it creates a targeted annotation.

**Comment by BigBlueHat** [comment]
I'd vote for changing that and "reducing" it to just page notes. If you've made a selection (barring some nasty browser/UI bug) you should be able--and most likely to--click the "note" icon near the selection.

I (for one) didn't realize that sidebar icon did anything more than make a "page note." Who knew! :smile_cat:

**Comment by tilgovi** [comment]
This was a change Jake made in order to support annotating on touch devices
where we otherwise wouldn't see an event to indicate that the selection
changed.

There are possibly other ways to accommodate touch devices, but none that
we found that was as straightforward or portable.

Happy to see code that does something smarter. Barring that, this stays as
it is unless it's determined that annotating on touch devices is to be
considered unsupported.

**Comment by BigBlueHat** [comment]
Ah. Makes sense. I don't immediately have a counter proposal...and I don't
really want to see more buttons up there...

Whatever happens, we do need to think hard(er) about "page notes" in the
future, though. There are *loads* of use cases for them...and finding them
again will be important.

**Comment by judell** [comment]
Hmm. A comment I thought I made 2 hours ago isn't here. So I'll resurrect it.

"If you have a selection, it creates a targeted annotation."

Can we distinguish between the two cases and adjust the tooltip accordingly?

**Comment by tilgovi** [comment]
If we could distinguish the two cases, we wouldn't have this problem in the
first place.

**Comment by judell** [comment]
It's not unheard of that an app knows (or can know) things it neglects to communicate effectively to the user.

So:

1. It is impossible to use the selection event to vary the tooltip.

2. It is possible to do so, but we currently don't.

**Comment by judell** [comment]
http://jonudell.net/h/ embeds a hack that does what I'm envisioning.

**Comment by judell** [comment]
https://github.com/hypothesis/h/compare/2263-tooltip-for-note-button might or might not appropriately become a PR but it seems to work.

**Comment by tilgovi** [comment]
Right on. We could change the tooltip on desktop. It suddenly occurs to me that on a touch device you wouldn't see tooltips anyway, so it's not really an issue.

**Comment by RawKStar77** [comment]
> We could change the tooltip on desktop. It suddenly occurs to me that on a touch device you wouldn't see tooltips anyway, so it's not really an issue.

+1

**Comment by judell** [comment]
https://notetip2.dokku.hypothes.is/

**Comment by judell** [comment]
Should https://github.com/hypothesis/h/compare/2263-tooltip-for-note-button become a PR?

**Comment by judell** [comment]
Closed in favor of https://github.com/hypothesis/h/pull/2363
