### ISSUE TITLE
Missing pyramid_redis_sessions dependency for building Chrome extension

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#2269]
See https://github.com/hypothesis/h/pull/2260

**Comment by seanh** [comment]
I've added installing this dependency to our private docs for building the production Chrome extension. It's not needed in this repo because the public Chrome extension docs never build with production.ini.

**Comment by tilgovi** [comment]
Solid solution.

**Comment by seanh** [comment]
It actually ended up in the public docs for building the extension too

**Comment by tilgovi** [comment]
It's webassets.debug: False that triggers the packaging, if you'd rather talk about how to create an .ini file that suits the reader's needs rather than just directing them to the prefab ones. Up to you.
