### ISSUE TITLE
Add link rel="related" href="ANNOTATION_TARGET_URL" to entries in Atom feed

### ISSUE THREAD

**Issue by judell** [hypothesis/h#2280]
As discussed [over in vision](https://github.com/hypothesis/vision/issues/170#issuecomment-108576493).

Short-term benefit: Enable an external filter to accomplish now what our site filter will do when available.

Long-term benefit: A richer Atom feed enabling other kinds of filtering on target URIs than those we directly support.

**Comment by tilgovi** [comment]
@zackw there's a button on the column to the right of the issue thread under the heading "Notifications" where you can click a button to subscribe.

**Comment by judell** [comment]
Consider an entry in the feed:
```
  <entry>
    <id>tag:hypothes.is,2015-06-03:KcZ_vhHPQmq44fMwyIOuUw</id>
    <title>Bronx Masquerade by Nikki Grimes | Youth Voices</title>
    <updated>2015-06-03T18:31:36.154046+00:00</updated>
    <published>2015-06-03T18:31:36.154013+00:00</published>
    <author>
      <name>SaulNDSS</name>
    </author>
    <link rel="alternate" type="text/html" href="https://hypothes.is/a/KcZ_vhHPQmq44fMwyIOuUw" />
    <link rel="alternate" type="application/json" href="https://hypothes.is/api/annotation/KcZ_vhHPQmq44fMwyIOuUw" />
     <content type="html">
&lt;blockquote&gt;telling me I need to be planning for some future&lt;/blockquote&gt;this is trying to say that Tyrone needs to be planning for a future for himself because he doesn't want to go to school. He says that if it wasn't for Wesley and friends he wouldn't be here working or anything. they both need to plan to have a big future 
    </content>
  </entry>
```

There's no way for a consumer to know that the annotation targets http://youthvoices.net/masquerade.

This would help, I think:

```
<link rel="related" type="text/html" href="http://youthvoices.net/masquerade" />
```

**Comment by judell** [comment]
https://github.com/hypothesis/h/blob/atom-link-related/h/atom_feed.py#L116 sorta works, but in the context of the annotation I don't know what the type of the target should be. So the output is:

 <link rel="related" type="" href="http://localhost:5000/" />

**Comment by gerwitz** [comment]
Was this implemented and then regressed? `atom.py` today shows no sign of it.
