### ISSUE TITLE
Visually distinguish private notes

### ISSUE THREAD

**Issue by judell** [hypothesis/h#2285]
I often make private notes without intending to. So do others. (From the support forum today: "When I share an annotation the link doesn't work for other people, only for me.)

An alternate background as shown below is not necessarily the solution, but we need *something* more than the Public / Only Me dropdown to alert people to the fact that Only Me may be stickily in effect when composing a note. It's way too easy to not notice the state of the Public / Only Me dropdown. (And perhaps something more than the lock icon to signal that a note is private.)

![distinguish-private-notes](https://cloud.githubusercontent.com/assets/46509/7991850/1a89a0f6-0ab0-11e5-853e-fae5a8637ada.jpg)

**Comment by dwhly** [comment]
I'd say the most effective way to communicate this is at the point of grabbing the share link.  It should state clearly there that the link is to a private annotation.

**Comment by judell** [comment]
That too. But I have repeatedly made annotations that were unintentionally private, and then been puzzled to not find them in the stream or sidebar when I'm not logged in.

**Comment by dwhly** [comment]
I think @RawKStar77's new styling that will repeat the permission with a text explanation via a banner at the bottom of the annotation when being created will help there. I really like the feel of that.

**Comment by RawKStar77** [comment]
This is what @dwhly is referring too:
![explicitely state annotation visibility setting](https://cloud.githubusercontent.com/assets/521978/7993698/c9dde27c-0abc-11e5-847d-4474304bda92.png)

**Comment by judell** [comment]
That'll help! What branch is that on, and what is it's status?

**Comment by JakeHartnell** [comment]
It's in the groups prototype. I can easily break it out into its own PR, just put it in the backlog.

**Comment by tilgovi** [comment]
@JakeHartnell in general, break out as many things as you have the patience for. It makes reviewing the eventual PR for groups easier.

**Comment by JakeHartnell** [comment]
:+1:

**Comment by JakeHartnell** [comment]
Resolved with https://github.com/hypothesis/h/pull/2322
