### ISSUE TITLE
Enable Social Authentication for Registration/Sign-in

### ISSUE THREAD

**Issue by JJediny** [hypothesis/h#2286]
we're currently supporting hypothsis on our website and I've been using the chrome plugin for awhile now. Love the concept, execution of the tool but I've noticed a major inhibitor for me using it 'all-the-time' is the need to login 'all-the-time' with a separate account. Others I've shared/endorsed hypothesis have the same immediate reaction (~1 1/2 out of 2). As a fan of what your doing I'd strongly encourage you all to figure out social-authentication (registration/signin) and/or as an intermediate step support "remember me" so that atleast users can decide if they want to have their browser remember their creds.

I'd suggest you consider the usual professional culprits:
Google/Twitter/Facebook/Linkedin/Github

Cheers and keep up all the other good stuff!

**Comment by akuckartz** [comment]
I would prefer the support for standards instead of silos.

**Comment by nickstenning** [comment]
Thanks @JJediny. This is something we're looking to support in the near future.

And to your point @akuckartz: luckily it's not an "either/or" situation. In some cases the mechanisms by which we can support third-party login are standardised (or nearly so), and even when they're not, there's nothing stopping us from supporting standard protocols as well as several major platforms.

We'll definitely be supporting open standards where we can. We're also pragmatists and will be looking to make Hypothesis as easy to use as possible for everyone and anyone.

**Comment by JJediny** [comment]
http://passportjs.org/

**Comment by judell** [comment]
Feature is planned.

**Comment by akuckartz** [comment]
Where is a link to that plan?
Why don't you simply keep this issue open and assign an appropriate milestone?

**Comment by robertknight** [comment]
@akuckartz Short answer: On a private Trello board, there is no specific milestone attached. Longer answer: Internally at Hypothesis we currently use a (private) Trello board for most organizing and scheduling tasks and use Google Docs or sometimes ordinary web pages + Hypothesis for design exploration, mockups etc. From an organizational point of view, others in the team would prefer to use issues on this repo purely for bugs.  I appreciate that's not great from the point of view of external contributors or even people who are just interested in following Hypothesis development or want notifications about a particular feature. For the moment, there is a separate 'vision' repo at https://github.com/hypothesis/vision/ for public discussion around features and ideas. In particular, see https://github.com/hypothesis/vision/issues/118

**Comment by akuckartz** [comment]
@robertknight Thanks for the detailed reply which answers my questions.
