### ISSUE TITLE
Make empty comments more clear & enticing [UX]

### ISSUE THREAD

**Issue by bnvk** [hypothesis/h#2292]
Currently, when using the Chrome Extension on a page with no comments one sees nothing save for text that reads "Sorted by location"

![screen shot 2015-06-06 at 4 28 58 pm](https://cloud.githubusercontent.com/assets/48677/8020003/577626d2-0c69-11e5-94e0-ded5268e81e9.png)

I think this can be improved upon a tiny bit by removing "Sorted by..." as that implies there is content to be sorted. Some other suggestions are:

- Simple copy "No highlights or notes on this page, yet"
- More enticing copy  "No highlights or notes on this page. Want to be the first?"

Also, you might want to show an expanded comment box just below the message as that removes some user steps of selecting text!

**Comment by dwhly** [comment]
I like this.  Easy one.

**Comment by RawKStar77** [comment]
+1

**Comment by judell** [comment]
Nice observation, @bnvk, thanks!

**Comment by bnvk** [comment]
As a follow up. I sometimes see this "This is an example annotation" by user **lampholder** on some posts... not sure what this this about, but seems related?

![screen shot 2015-06-22 at 12 25 21 pm](https://cloud.githubusercontent.com/assets/48677/8280045/f3c9fe74-18d9-11e5-93df-a49b85b637b9.png)

**Comment by tilgovi** [comment]
That's #2326

**Comment by judell** [comment]
@conordelahunty we all liked this suggestion at the time. Make it so?

**Comment by conordelahunty** [comment]
@judell Sure, but there are two (good) ideas proposed here. Shall we add a card in Trello and I will attach some designs

**Comment by capitocapito** [comment]
How is this going, @conordelahunty?  

If there is any need for additional help on this issue, I'd like to jump in.  (I don't want to step on any toes.) Or at least, I can provide some inspiration. I'm used to referring to this as an "empty state," and I think we have some room to play with making the state engaging. The enticing copy from the original comment by @bnvk is good.

Some examples here: http://emptystat.es/

**Comment by conordelahunty** [comment]
Hello @capitocapito 

Thanks for the nudge (and the link). There is a broader piece of work in play at the moment that address both this issue and also the overall structure of the tool. A fix for this is coming soon, I promise!

**Comment by nickstenning** [comment]
We've made some improvements here:

## Signed out
![screen shot 2016-02-10 at 14 20 36](https://cloud.githubusercontent.com/assets/3602/12948305/7bc17e2c-d001-11e5-945e-fd80167637f2.png)

## New user
![screen shot 2016-02-10 at 14 20 21](https://cloud.githubusercontent.com/assets/3602/12948309/7ee31f2a-d001-11e5-93b9-462383d4ee28.png)

I'm going to close this issue! Good work all, and thanks for the suggestion @bnvk.
