### ISSUE TITLE
Add user avatars next to names [UX]

### ISSUE THREAD

**Issue by bnvk** [hypothesis/h#2294]
Adding a face to a name is so essential in todays "social media" landscape. Numerous studies have shown that having faces next to names makes the content more engaging, human, and impactful!

![hypothesis suggestions - avatar](https://cloud.githubusercontent.com/assets/48677/8020160/1e127f98-0c6f-11e5-861c-cd95912c341b.png)

**Comment by tilgovi** [comment]
Related to hypothesis/vision#28

**Comment by judell** [comment]
Closed in favor of hypothesis/vision#28

**Comment by dwhly** [comment]
Added it to the checklist in vision#28
