### ISSUE TITLE
streamer websocket handshake error: Header HTTP_UPGRADE is not defined

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/h#2296]
https://app.getsentry.com/hypothesis/prod/group/61157091/

I'm not entirely sure what this error is at a glance, but it seems to be non-websocket client connections to the websocket. Needs investigation to determine if worrisome, and if not we should silence the error.

**Comment by tilgovi** [comment]
Not seeing this anymore.

**Comment by nickstenning** [comment]
All over the logs. Reopened.

**Comment by nickstenning** [comment]
Raising to P2 because the sheer volume of these is worrying.

**Comment by nickstenning** [comment]
Any insight into why we're getting so many hits at that endpoint? I ask because I don't see that this changes anything other than removing the log line...

**Comment by tilgovi** [comment]
Nope. :-(
