### ISSUE TITLE
Connection pool is full, discarding connection: 172.17.0.6

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/h#2297]
https://app.getsentry.com/hypothesis/prod/group/54250061/

This is a warning from sqlalchemy about dropping excess connections to postgres. I'm not really sure why we would be opening more than the connection pool size of connections at once, so again I think this needs a little bit of investigation to ensure we're not doing anything silly. If not, we should silence this warning.

**Comment by judell** [comment]
Still worth looking into?

**Comment by nickstenning** [comment]
This will have been fixed by #2913.
