### ISSUE TITLE
Selected text is garbled in PDF

### ISSUE THREAD

**Issue by judell** [hypothesis/h#2299]
http://memex.naughtons.org/wp-content/uploads/2015/05/TCDtext2.pdf

https://hypothes.is/a/6keaTy-TQ4yEb49stodMrw

Chrome extension, FF bookmarklet, via

**Comment by tilgovi** [comment]
Probably should be closed as "won't fix". @judell I would check that you experience the same thing when copy/paste the text to another place. That would rule out our application as being the culprit. If that's the case, check https://github.com/mozilla/pdf.js/labels/4-text-selection and if you don't find any issue there, open one.

**Comment by judell** [comment]
It's not even just PDF.js. Selection in the Chrome PDF viewer, or Foxit Viewer, gives the same result. Some how the encoding is messed up in a way that isn't evident until you select and copy. 

Sorry, should've caught that before filing this.
