### ISSUE TITLE
Atom feed invalid due to Unicode

### ISSUE THREAD

**Issue by BigBlueHat** [hypothesis/h#2301]
@seanh hopefully this is a simple tweak to the html encoding coding. ;)
http://feedvalidator.org/check.cgi?url=https%3A%2F%2Fhypothes.is%2Fstream.atom%3Fq%3Dtag%3A%2527open%2520source%2527

Here's the JSON for the culprit:
https://hypothes.is/api/annotations/6keaTy-TQ4yEb49stodMrw

And the HTML representation:
https://hypothes.is/a/6keaTy-TQ4yEb49stodMrw

It's sort of a weird highlight anyhow... Ah...it's from a PDF about Memex that @judell was testing(?) with apparently.

**Comment by BigBlueHat** [comment]
Apparently @judell just filed #2299 yesterday about the garbled text...so...probably a bigger issue. :stuck_out_tongue:

**Comment by judell** [comment]
"probably a bigger issue."

I think so. Closing this for now.
