### ISSUE TITLE
Don't Set-Cookie on every request

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/h#2302]
There's really no reason we should be setting cookie headers in:

- [ ] 404 responses
- [ ] 401/403 responses
- [ ] assets responses
- [ ] API responses

Doing so makes caching semantics unclear and is, frankly, just a bit messy.

**Comment by tilgovi** [comment]
I don't think we do. In production, almost no requests are ever setting cookies. In dev, it happens once a second at most because the session store is a default cookie-based one and refreshing it's TTL means updating the cookie.

**Comment by tilgovi** [comment]
If I'm mistaken, re-open, please.
