### ISSUE TITLE
During log-in in I lost my comment

### ISSUE THREAD

**Issue by scharf** [hypothesis/h#2308]
- I have been annotating a site (on my tablet)
- I got an email notification on a reply
- I opened it on my desktop and typed in a long answer
- when clicking the submit button, I got asked to sign in
- after signing in, my reply to the comment was empty

==> I lost the text I have been typing :-(

**Comment by tilgovi** [comment]
Is this #2078?

**Comment by scharf** [comment]
Yes it is exactly the same problem.
