### ISSUE TITLE
Local PDFs / pdf.js / Zotero / hypothes.is

### ISSUE THREAD

**Issue by PaBLoX-CL** [hypothesis/h#2319]
Ok, here's the thing. I have been using Mendeley as a reference manager, but also because I can highlight text and make annotations. I really like hypothes.is, so I was wondering if there were some way to replace mendeley with zotero + pdf.js.

If I load a local pdf through zotero UI, I get some "local" pdf, "zotero://file.pdf"... but I'm not sure if the highlights and annotations actually live in the "cloud" or not. If they are... how is that you know if it's the same file?

Sorry if this has been discussed earlier, I can't find it :(

PS.- I found a pdf.js + h repo, but it's for a local build.

**Comment by tilgovi** [comment]
If the annotations work on a zotero: URL displayed with PDF.js then the annotations are stored on the server. There is no support for offline annotation yet.

For information on how document identification works for PDFs, see this blog post: https://hypothes.is/blog/synchronizing-annotations-between-local-and-remote-pdfs/

**Comment by PaBLoX-CL** [comment]
Hm, I'm not sure if I'm understanding correctly.... but let me put an example:

A teacher sends us a couple of pdfs trought an email. I use zotero, and I open the file with it (pdf.js). I see I can annotate the file, highlights, comments, etc. But if another classmate loads the same file with pdj.js, would be able to see them?

(that's what I understand frome the screencast/blog post)

**Comment by tilgovi** [comment]
Yes, that should work fine.

**Comment by PaBLoX-CL** [comment]
Right now I have opened exactly the same file in chromium (with the extension) and in firefox (bookmarklet). In both I'm logged as my user and also both are opened locally... nevertheless, highlighting doesn't seem to appear on both "documents"

**Comment by judell** [comment]
@PaBLoX-CL does the Hypothesis sidebar app load in both cases? And, can you share a copy of the file so I can look into this?

**Comment by jeremydean** [comment]
i'm interested in picking this up where it's left off here. anything move
beyond the thread itself?
ᐧ

On Mon, Jun 22, 2015 at 9:29 PM, judell <notifications@github.com> wrote:

> @PaBLoX-CL <https://github.com/PaBLoX-CL> does the Hypothesis sidebar app
> load in both cases? And, can you share a copy of the file so I can look
> into this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hypothesis/h/issues/2319#issuecomment-114331941>.
>



-- 
Dr. Jeremy Dean
Director of Education

**Comment by PaBLoX-CL** [comment]
Sorry for taking so much time to answer. I had problems with internet access :(

I'm seeing the same behaviour, I saved the file into zotero, and opened in another computer of mine, using the "same" file. The sidebar loads in both cases, but now in my laptop I don't the highlights, nor the notes. In my stream I can see the annotations thought.

I have the file and I can share it, should I post it somewhere online? Or do you want me to send it privately?

**Comment by tilgovi** [comment]
Yo opened it on another computer from the same Zotero collection? I think I'd have to install Zotero again and do some experiments to know what's needed.

**Comment by PaBLoX-CL** [comment]
Yes, it's the same file uploaded to Zotero.

**Comment by PaBLoX-CL** [comment]
This is driving me crazy. The same file saved to zotero and then reopened, for hypothesis it looks like it's a different file. Both files, have the same checksum, so I wonder how hypothesis check if the file is the same or it isn't.

![firefox_screenshot_2015-10-12t16-57-24 456z](https://cloud.githubusercontent.com/assets/275754/10433580/6a437744-70e9-11e5-8886-c668e4b70c3c.png)

**Comment by judell** [comment]
We aim to get this sorted but for now, try creating at least one annotation for each version. They should then coalesce.

**Comment by nickstenning** [comment]
Hi all. It's not clear what the issue being described here actually is. It sounds like it might be a bug, but without reproduction steps it's difficult to tell what the expected behaviour is.

**Comment by judell** [comment]
@PaBLoX-CL if you can help us reproduce this, we'll gladly take another look.

**Comment by PaBLoX-CL** [comment]
I have been trying the same with different pdfs. Even the same "file", copied to another machine. Hypothesis doesn't track the annotations/highlighting... is there any way to solve this? or help into make it reproducible?

**Comment by tilgovi** [comment]
The same file, copied to another machine (no Zotero involvement) should work fine, but unless things have changed in the last few months you'll need to make an annotation on each copy before the service recognizes them as the same.

**Comment by dwhly** [comment]
@PaBLoX-CL We have a bit of work in flight which may solve this problem.  i.e. to use the Adobe ID / PDF Fingerprint as a primary identifier of the document.  We'll let you know when it ships.

**Comment by dwhly** [comment]
@PaBLoX-CL The work we planned here is now  done. Can you see if the problem has been resolved?

**Comment by dwhly** [comment]
Addressed by https://github.com/hypothesis/h/pull/3404.

**Comment by PaBLoX-CL** [comment]
![its_working_star_wars](https://cloud.githubusercontent.com/assets/275754/16527545/8773afb2-3f85-11e6-8fb2-ea9865575360.gif)

Thanks :)

**Comment by nickstenning** [comment]
😄 👍
