### ISSUE TITLE
"Via" bookmarklet

### ISSUE THREAD

**Issue by RaoOfPhysics** [hypothesis/h#2325]
You can add a bookmarklet for redirecting pages to the "via" proxy instead of having to go to https://hypothes.is and pasting the link:

```javascript
javascript:location.href='https://via.hypothes.is/h/'+location.href
```

[Not sure if this is the right place to post this: please let me know if I should move it to `hypothesis/vision`.]

**Comment by RaoOfPhysics** [comment]
Ugh, just got to this: https://hypothes.is/blog/farewell-to-bookmarklets/, specifically:

> – You still need a way to activate the annotation layer for the current page. (You can use a bookmarklet to redirect to the proxy, but … sigh.)

:(

**Comment by tilgovi** [comment]
We have a bookmarklet that simply adds the annotation application to the current page, already. What advantage does using via provide/

**Comment by RaoOfPhysics** [comment]
@tilgovi: It allows you to send someone a direct link with the annotations loaded -- I assumed that was the purpose of via? Sorry if I misunderstood!

**Comment by tilgovi** [comment]
Oh, certainly, but I didn't understand what story you were trying to achieve with a bookmarklet.

I understand the value of sharing an annotated page easily. We have work going on for this that will merge soon (#2215) that I think might address it better by having the user load the annotations themselves before sharing a link to them through the sidebar.

**Comment by RaoOfPhysics** [comment]
@tilgovi: :+1:
