### ISSUE TITLE
Unexpected annotation found for unannotated URLs

### ISSUE THREAD

**Issue by judell** [hypothesis/h#2326]
Pick any URL with (presumably) no H annotations. Three examples:

https://hypothes.is/api/search?uri=http://www.benkler.org
https://hypothes.is/api/search?uri=http://www.whitehouse.gov
https://hypothes.is/api/search?uri=http://microsoft.com

The same spurious annotation (a page note) appears in each case:

```
{
    "total": 1, 
    "rows": [
        {
            "updated": "2015-03-29T13:29:23.388422+00:00", 
            "created": "2015-03-29T13:29:23.388406+00:00", 
            "text": "This is an example annotation.", 
            "tags": [], 
            "uri": "http://example.com/", 
            "user": "acct:lampholder@hypothes.is", 
            "document": {
                "eprints": {}, 
                "title": "Example Domain", 
                "twitter": {}, 
                "dc": {}, 
                "prism": {}, 
                "highwire": {}, 
                "facebook": {}, 
                "link": [
                    {
                        "href": "http://example.com/"
                    }
                ]
            }, 
            "consumer": "00000000-0000-0000-0000-000000000000", 
            "id": "3ro_gCA2TjuwkDXsArDLCA", 
            "permissions": {
                "admin": [
                    "acct:lampholder@hypothes.is"
                ], 
                "read": [
                    "group:__world__"
                ], 
                "update": [
                    "acct:lampholder@hypothes.is"
                ], 
                "delete": [
                    "acct:lampholder@hypothes.is"
                ]
            }
        }
    ]
}
```

**Comment by tilgovi** [comment]
I bet this has to do with us making the wrong decision after checking for equivalent URIs and finding no URIs in the database.

**Comment by judell** [comment]
The plot thickens. memartone recently annotated either:

1 http://www.medpagetoday.com/MeetingCoverage/APSS/52026

or

2 http://www.medpagetoday.com/MeetingCoverage/APSS/52026#

Feed 1 to the API like this -- https://hypothes.is/api/search?uri=http%3A%2F%2Fwww.medpagetoday.com%2FMeetingCoverage%2FAPSS%2F52026 -- and you get the spurious example.com annotation. That's the URL the sidebar fetches, whether the browser's URL line reads 1 or 2. It fails to anchor, so the user experience is: no annotations on that page.

Feed 2 to the API like this --  https://hypothes.is/api/search?uri=http%3A%2F%2Fwww.medpagetoday.com%2FMeetingCoverage%2FAPSS%2F52026%23 -- and you get the annotation memartone made.

1 is what appears in that H payload here:

```
 "uri": "http://www.medpagetoday.com/MeetingCoverage/APSS/52026#", 
```

and here:

```
"link": [
    {
	"href": "http://www.medpagetoday.com/MeetingCoverage/APSS/52026#"
    }, 
    {
	"href": "http://www.medpagetoday.com/MeetingCoverage/APSS/52026#", 
	"type": "", 
	"rel": "canonical"
    }
],
```

**Comment by judell** [comment]
Further observations: the spurious annotation appears in case 1 below but not case 2.

URL: http://speciali.espresso.repubblica.it/pdf/laudato_si.pdf

1) FF/Via:

![image](https://cloud.githubusercontent.com/assets/46509/8260543/4fc2a112-1679-11e5-9de6-89324217e499.png)

2) FF/boomarklet:

![image](https://cloud.githubusercontent.com/assets/46509/8260560/7a2c4746-1679-11e5-9108-1db04beb51e8.png)

**Comment by bbarker** [comment]
It seems that I have some annotations I made recently not showing up, but I am getting lampholder's (and only lampholder's) annotation. Here is an example: https://hypothes.is/a/Kw6mAZSlSt-x7uko_2efyA

This was working sometime last week (at the time of the 'arXiv' annotation being created).

Note, I may delete this annotation tomorrow if that's alright, but thought I'd post it here as an extra data point.

**Comment by judell** [comment]
OK, thanks. Based on an observation I made today, I have a hunch that if you delete and recreate that annotation it will displace the spurious one. That's not a fix obviously but would be a data point so please let me know if you try that, and if so, what happens.

**Comment by nickstenning** [comment]
I've made the offending thread private for as a temporary fix.

**Comment by bbarker** [comment]
Thanks for the suggestion @judell . Deleting and recreating didn't seem to work. Furthermore, I verified that I can create, view, and delete an annotation at https://github.com/bbarker/Hypothesis-API/blob/master/xt/Testbed.md

But using the public API, I can only create annotations at
http://arxiv.org/abs/0704.0009

Viewing the annotation at that URI doesn't work in the chrome extension. I can't delete it with the API, but I can delete from the stream: https://hypothes.is/stream?q=user:arXiv

Finally, I used the same [test script](https://github.com/bbarker/Hypothesis-API/blob/master/xt/login_required.t) to try to make sure it wasn't something on my end, and just changed the value of `$test_uri` to these different URLs.

**Comment by bbarker** [comment]
A bit of a possibly interesting update; if I create an annotation at http://arxiv.org/abs/0704.0009 (you can see there are several duplicates I've made), it will pop up in the extension sidebar when it is made, but on a refresh of the page, it will disappear!

**Comment by judell** [comment]
I see one annotation currently at https://hypothes.is/api/search?uri=http%3A%2F%2Farxiv.org%2Fabs%2F0704.0009. I would expect it might briefly appear when loaded, but then vanis when it fails to anchor, because the payload included no anchoring information (values in TextPositionSelector and TextQuoteSelector are null).

**Comment by bbarker** [comment]
Ah I see, it appears the expectation is that for proper null behavior, we
should have "target": [].

On Wed, Jun 24, 2015 at 11:30 AM, judell <notifications@github.com> wrote:

> I see one annotation currently at
> https://hypothes.is/api/search?uri=http%3A%2F%2Farxiv.org%2Fabs%2F0704.0009.
> I would expect it might briefly appear when loaded, but then vanis when it
> fails to anchor, because the payload included no anchoring information
> (values in TextPositionSelector and TextQuoteSelector are null).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hypothesis/h/issues/2326#issuecomment-114911804>.
>



-- 
Brandon Barker
brandon.barker@gmail.com

**Comment by bbarker** [comment]
Or, maybe not, I'm having mixed results.

This page has problems: http://arxiv.org/abs/0704.0003

This page (now) does not (including with the old target payload):
http://arxiv.org/abs/0704.0009


On Wed, Jun 24, 2015 at 11:42 AM, Brandon Barker <brandon.barker@gmail.com>
wrote:

> Ah I see, it appears the expectation is that for proper null behavior, we
> should have "target": [].
>
> On Wed, Jun 24, 2015 at 11:30 AM, judell <notifications@github.com> wrote:
>
>> I see one annotation currently at
>> https://hypothes.is/api/search?uri=http%3A%2F%2Farxiv.org%2Fabs%2F0704.0009.
>> I would expect it might briefly appear when loaded, but then vanis when it
>> fails to anchor, because the payload included no anchoring information
>> (values in TextPositionSelector and TextQuoteSelector are null).
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/hypothesis/h/issues/2326#issuecomment-114911804>.
>>
>
>
>
> --
> Brandon Barker
> brandon.barker@gmail.com
>



-- 
Brandon Barker
brandon.barker@gmail.com

**Comment by judell** [comment]
@bbarker What were you expecting, what were you seeing?

**Comment by bbarker** [comment]
I confirmed similar behavior on another page: http://arxiv.org/abs/0704.0002

Refreshing and clicking off/on the Hypothes.is plugin icon alone didn't
help. Creating an annotation in the plugin, then refreshing the page,
allows all the annotations to show.

On Wed, Jun 24, 2015 at 12:44 PM, Brandon Barker <brandon.barker@gmail.com>
wrote:

> On the problematic page, I was expecting to see some of the annotations. I
> didn't see any of the three. Incidentally, I just manually created a 4th
> annotation ("id": "rFlHQruLRQq5n4HM9l1TyA") using the plugin, and
> subsequently all annotations show up now.
>
> On Wed, Jun 24, 2015 at 12:41 PM, judell <notifications@github.com> wrote:
>
>> @bbarker <https://github.com/bbarker> What were you expecting, what were
>> you seeing?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/hypothesis/h/issues/2326#issuecomment-114937621>.
>>
>
>
>
> --
> Brandon Barker
> brandon.barker@gmail.com
>



-- 
Brandon Barker
brandon.barker@gmail.com

**Comment by judell** [comment]
@bbarker at http://arxiv.org/abs/0704.0002 I see 4 annotations in the sidebar and also at https://hypothes.is/api/search?uri=http%3A%2F%2Farxiv.org%2Fabs%2F0704.0002. What am I missing?

**Comment by bbarker** [comment]
@judell Yes, I think that is expected based on my experience since I created an annotation using the chrome plugin after the fact. Here is a page where I have not done so:
http://arxiv.org/abs/0704.0245

There should be one annotation there at the moment. If you try to view it and don't succeed, as is my experience, what then happens if you create an annotation on that page using the plugin?

**Comment by judell** [comment]
Thanks @bbarker, that's what I needed to see.

In this situation the client makes 3 API queries, documented below.  Total says 0 but there's still one row, a reply to the spurious example.com annotation.

My hunch is that until https://github.com/hypothesis/h/issues/2240 is analyzed/fixed we'll be seeing a variety of such anomalies.

https://hypothes.is/api/search?limit=200&offset=0&order=asc&sort=created&uri=http:%2F%2Farxiv.org%2Fabs%2F0704.0245

{
    "total": 0, 
    "rows": [
        {
            "updated": "2015-06-22T20:03:17.394356+00:00", 
            "created": "2015-06-22T20:03:17.394322+00:00", 
            "text": "Hi Manu, \n\nIt's https://github.com/hypothesis/h/issues/2326, sorry about that, we are working to fix it.", 
            "tags": [], 
            "uri": "http://example.com/", 
            "references": [
                "3ro_gCA2TjuwkDXsArDLCA", 
                "xEOaD_t-TiaJ34j1wQ8aCw"
            ], 

https://hypothes.is/api/search?limit=200&offset=0&order=asc&sort=created&uri=doi:10.1088%2F1126-6708%2F2007%2F07%2F002

{
    "total": 0, 
    "rows": [
        {
            "updated": "2015-06-22T20:03:17.394356+00:00", 
            "created": "2015-06-22T20:03:17.394322+00:00", 
            "text": "Hi Manu, \n\nIt's https://github.com/hypothesis/h/issues/2326, sorry about that, we are working to fix it.", 
            "tags": [], 
            "uri": "http://example.com/", 
            "references": [
                "3ro_gCA2TjuwkDXsArDLCA", 
                "xEOaD_t-TiaJ34j1wQ8aCw"
            ], 

https://hypothes.is/api/search?limit=200&offset=0&order=asc&sort=created&uri=http:%2F%2Farxiv.org%2Fpdf%2F0704.0245

{
    "total": 0, 
    "rows": [
        {
            "updated": "2015-06-22T20:03:17.394356+00:00", 
            "created": "2015-06-22T20:03:17.394322+00:00", 
            "text": "Hi Manu, \n\nIt's https://github.com/hypothesis/h/issues/2326, sorry about that, we are working to fix it.", 
            "tags": [], 
            "uri": "http://example.com/", 
            "references": [
                "3ro_gCA2TjuwkDXsArDLCA", 
                "xEOaD_t-TiaJ34j1wQ8aCw"
            ],
