### ISSUE TITLE
atom feed includes invalid links

### ISSUE THREAD

**Issue by judell** [hypothesis/h#2327]
I hooked up a WordPress widget to https://hypothes.is/stream.atom?user=judell&tags=reading. The links in the WordPress rendering, which are of the form:

https://hypothes.is/api/annotation/c38yXdq_RcegInPvUISXlA

do not work. Also included in the feed are links of the form:

https://hypothes.is/a/c38yXdq_RcegInPvUISXlA

which does work, but isn't picked up by WordPress.

What's the purpose of the annotation_api_url at https://github.com/hypothesis/h/blob/master/h/atom_feed.py#L112?  Should it be removed or, if inaccessible, made accessible?

(Wanted to test this in staging but the timeout issue -- see next rock -- precluded that.)

**Comment by tilgovi** [comment]
Looks like a simple typo. It should be `/api/annotations` with an s at the end.

**Comment by judell** [comment]
OK. Whoever tweaks that might also do https://github.com/hypothesis/h/issues/2280?
