### ISSUE TITLE
add references to the event listeners added to the DOM to the annotator global.

### ISSUE THREAD

**Issue by soapdog** [hypothesis/h#2328]
To create a working Firefox extension we need a way to remove the event listeners added by Hipothes.is when the user decides to deactivate the annotator for a given tab. Right now, we can't remove those listeners because we have no reference to them.

A solution would be to have a new ```window.annotator.eventListenersReferences``` property holding references to all listeners so that we could iterate over them and remove everything.

**Comment by tilgovi** [comment]
`annotator.destroy()` should remove call `.destroy()` on any plugins (which would remove their event handlers) and remove any event handlers it registered.

Can you identify particular handlers we've missed?

**Comment by tilgovi** [comment]
Bump

**Comment by judell** [comment]
@soapdog is this still an issue? If so were you able to identify what handlers annotator.destroy() does not remove?

**Comment by nickstenning** [comment]
Without further detail, there's not a lot we can do here. Closing.
