### ISSUE TITLE
Firefox Nightly can't make highlights

### ISSUE THREAD

**Issue by brittanystoroz** [hypothesis/h#2331]
Using FF Nightly 41.0a1, when I first try to select text to highlight I get an error in the console:

`Error: Called getPathTo on a node which was not a descendant of @rootNode. [object HTMLBodyElement]`

and my selection is immediately discarded. Any subsequent attempts to select text produce the same behavior but now the console spits out

`Error: Selection already saved!`

I am using the pre-release version here: https://github.com/soapdog/h/releases but it seems it shouldn't be a problem with that specific repo.

UPDATE: I seem to only run into the issue on this page http://slightlyoff.github.io/ServiceWorker/spec/service_worker/ and have not run into it elsewhere so perhaps it's just an error in the DOM tree for that specific page.

**Comment by JakeHartnell** [comment]
> UPDATE: I seem to only run into the issue on this page http://slightlyoff.github.io/ServiceWorker/spec/service_worker/ and have not run into it elsewhere so perhaps it's just an error in the DOM tree for that specific page.

Please keep us posted, but I'm closing this for now. Thanks for the update!

**Comment by tilgovi** [comment]
Yeah, not seeing that either in dev edition now. Looking good. Also, stage fixes the performance issue, as expected. Everything looking snappy.
