### ISSUE TITLE
Handle PDF.js errors more gracefully

### ISSUE THREAD

**Issue by judell** [hypothesis/h#2339]
This happens when I try to use H with http://www.nature.com/neuro/journal/v17/n7/pdf/nn.3731.pdf, a paywalled article, from outside the paywall:

![image](https://cloud.githubusercontent.com/assets/46509/8442830/318b9706-1f36-11e5-9abc-4ac213f351ef.png)

A related error, which Maryann saw today when accessing from *inside* the paywall, is the dreaded "Invalid or corrupted PDF file." (I see this occasionally too.)

These errors aren't H's fault, but will be seen that way. It would be nice to trap them and handle them more gracefully.

**Comment by tilgovi** [comment]
If this happens with FF itself, not our extension, then maybe this is something we can surface upstream for the pdf.js project to see what they want to do about error messages and what we should do, if anything, to override this in a way that's sustainable and works with them.

**Comment by judell** [comment]
Given that there are >500 open issues at pdf.js, I'm guessing it'd be on us to explore this. Not high-pri but let's leave this open for now.

**Comment by tilgovi** [comment]
We have ~150!! It's not really the best metric of responsiveness. I'm not saying they would solve anything for us, but they might have advice on how we should fix it in a way that's potentially helpful to them and won't break when we update PDF.js in the future.

**Comment by tilgovi** [comment]
But, this is why I started with "If this happens with FF itself"...

We need to know:

- Is this the PDF.js upstream message?
- If so, where does it come from?
- Does FF override it?
- If we're the first to travel here, how should it be done?

**Comment by judell** [comment]
> not really the best metric of responsiveness

Indeed. I've sent a request for guidance to their mailing list.

**Comment by nickstenning** [comment]
I'm not clear on what "better" would look like here. If we try to use Hypothesis on a web page that's paywalled we'll get a 404 (or worse). If we try to use Hypothesis on a PDF that's paywalled we get this.

This situation will automatically "improve" if we are able to find a way to activate PDF.js on the basis of media type rather than file extension, but overall I think this is a WONTFIX.

**Comment by judell** [comment]
Won't fix.
