### ISSUE TITLE
On a PDF with no annotations, Hypothesis reports "message not available"

### ISSUE THREAD

**Issue by judell** [hypothesis/h#2353]
![image](https://cloud.githubusercontent.com/assets/46509/8559579/5a4cdf14-24c3-11e5-8e46-256fab2e5ca2.png)

Expected behavior: report nothing.

Tested in Chrome with release 0.4.2 and release candidate 0.4.2.106

**Comment by tilgovi** [comment]
URL?

**Comment by judell** [comment]
Any, perhaps? Here's one chosen at random: http://sonoma.courts.ca.gov/sites/all/assets/pdfs/general-info/grand-jury/2014-2015/Complete_Grand_Jury_Report_2014-2015.pdf

**Comment by tilgovi** [comment]
I don't see the error you report on that PDF. Maybe the one where you saw the problem.

**Comment by dwhly** [comment]
I don't see it either with 0.4.2.106

**Comment by nickstenning** [comment]
Can't repro.

**Comment by judell** [comment]
I now believe this was Chrome instability.
