### ISSUE TITLE
Error on first Login

### ISSUE THREAD

**Issue by frappierer** [hypothesis/h#2372]
Its mostly happening at the beginning of a new Session.
When i try to login the first time in frontend it shows:
![image](https://cloud.githubusercontent.com/assets/4376185/8761096/3118e686-2d3f-11e5-9247-43d271d3446c.png)
> Uh-oh, something went wrong! We're very sorry, our application wasn't able to load this page. The team has been notified and we'll fix it shortly. If the problem persists or you'd like more information please email support@hypothes.is with the subject 'Internal Server Error'.

When i directly try after that the login is working.

Similar errors seems to be reported [here](http://stackoverflow.com/questions/11875180/pgerror-ssl-syscall-error-eof-detected) and [here](https://github.com/jeremyevans/sequel/issues/746) . 

 The logs are showing:
{"log":"Traceback (most recent call last):\n","stream":"stdout","time":"2015-07-18T09:10:13.229075007Z"}
{"log":"  File \"/srv/h/local/lib/python2.7/site-packages/pyramid/tweens.py\", line 21, in excview_tween\n","stream":"stdout","time":"2015-07-18T09:10:13.229081538Z"}
{"log":"    response = handler(request)\n","stream":"stdout","time":"2015-07-18T09:10:13.229087577Z"}
{"log":"  File \"/srv/h/local/lib/python2.7/site-packages/pyramid_tm/__init__.py\", line 99, in tm_tween\n","stream":"stdout","time":"2015-07-18T09:10:13.229092976Z"}
{"log":"    reraise(*exc_info)\n","stream":"stdout","time":"2015-07-18T09:10:13.229098606Z"}
{"log":"  File \"/srv/h/local/lib/python2.7/site-packages/pyramid_tm/__init__.py\", line 80, in tm_tween\n","stream":"stdout","time":"2015-07-18T09:10:13.229103815Z"}
{"log":"    response = handler(request)\n","stream":"stdout","time":"2015-07-18T09:10:13.229109531Z"}
{"log":"  File \"/srv/h/local/lib/python2.7/site-packages/pyramid/router.py\", line 163, in handle_request\n","stream":"stdout","time":"2015-07-18T09:10:13.229122633Z"}
{"log":"    response = view_callable(context, request)\n","stream":"stdout","time":"2015-07-18T09:10:13.229128404Z"}
{"log":"  File \"/srv/h/local/lib/python2.7/site-packages/pyramid/config/views.py\", line 596, in __call__\n","stream":"stdout","time":"2015-07-18T09:10:13.229133742Z"}
{"log":"    return view(context, request)\n","stream":"stdout","time":"2015-07-18T09:10:13.229139197Z"}
{"log":"  File \"/srv/h/local/lib/python2.7/site-packages/pyramid/config/views.py\", line 329, in attr_view\n","stream":"stdout","time":"2015-07-18T09:10:13.229144373Z"}
{"log":"    return view(context, request)\n","stream":"stdout","time":"2015-07-18T09:10:13.229150011Z"}
{"log":"  File \"/srv/h/local/lib/python2.7/site-packages/pyramid/config/views.py\", line 305, in predicate_wrapper\n","stream":"stdout","time":"2015-07-18T09:10:13.229155075Z"}
{"log":"    return view(context, request)\n","stream":"stdout","time":"2015-07-18T09:10:13.22916055Z"}
{"log":"  File \"/srv/h/local/lib/python2.7/site-packages/pyramid/config/views.py\", line 355, in rendered_view\n","stream":"stdout","time":"2015-07-18T09:10:13.229185294Z"}
{"log":"    result = view(context, request)\n","stream":"stdout","time":"2015-07-18T09:10:13.229191731Z"}
{"log":"  File \"/src/h/h/accounts/views.py\", line 84, in wrapper\n","stream":"stdout","time":"2015-07-18T09:10:13.229196667Z"}
{"log":"    result = meth()\n","stream":"stdout","time":"2015-07-18T09:10:13.229202073Z"}
{"log":"  File \"/src/h/h/accounts/views.py\", line 109, in login\n","stream":"stdout","time":"2015-07-18T09:10:13.229207228Z"}
{"log":"    err, appstruct = validate_form(self.form, self.request.POST.items())\n","stream":"stdout","time":"2015-07-18T09:10:13.229212345Z"}
{"log":"  File \"/src/h/h/accounts/views.py\", line 44, in validate_form\n","stream":"stdout","time":"2015-07-18T09:10:13.229218036Z"}
{"log":"    appstruct = form.validate(data)\n","stream":"stdout","time":"2015-07-18T09:10:13.229223092Z"}
{"log":"  File \"/srv/h/local/lib/python2.7/site-packages/deform/field.py\", line 602, in validate\n","stream":"stdout","time":"2015-07-18T09:10:13.229228131Z"}
{"log":"    return self.validate_pstruct(pstruct)\n","stream":"stdout","time":"2015-07-18T09:10:13.229233286Z"}
{"log":"  File \"/srv/h/local/lib/python2.7/site-packages/deform/field.py\", line 637, in validate_pstruct\n","stream":"stdout","time":"2015-07-18T09:10:13.229238103Z"}
{"log":"    appstruct = self.schema.deserialize(cstruct)\n","stream":"stdout","time":"2015-07-18T09:10:13.229243149Z"}
{"log":"  File \"/srv/h/local/lib/python2.7/site-packages/colander/__init__.py\", line 1943, in deserialize\n","stream":"stdout","time":"2015-07-18T09:10:13.229247897Z"}
{"log":"    self.validator(self, appstruct)\n","stream":"stdout","time":"2015-07-18T09:10:13.229253084Z"}
{"log":"  File \"/src/h/h/accounts/schemas.py\", line 108, in validator\n","stream":"stdout","time":"2015-07-18T09:10:13.229257931Z"}
{"log":"    user = User.get_by_username(username)\n","stream":"stdout","time":"2015-07-18T09:10:13.229263083Z"}
{"log":"  File \"/src/h/h/accounts/models.py\", line 204, in get_by_username\n","stream":"stdout","time":"2015-07-18T09:10:13.229268538Z"}
{"log":"    return cls.query.filter(cls.uid == uid).first()\n","stream":"stdout","time":"2015-07-18T09:10:13.22927385Z"}
{"log":"  File \"/srv/h/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py\", line 2445, in first\n","stream":"stdout","time":"2015-07-18T09:10:13.229278807Z"}
{"log":"    ret = list(self[0:1])\n","stream":"stdout","time":"2015-07-18T09:10:13.229283958Z"}
{"log":"  File \"/srv/h/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py\", line 2281, in __getitem__\n","stream":"stdout","time":"2015-07-18T09:10:13.229288877Z"}
{"log":"    return list(res)\n","stream":"stdout","time":"2015-07-18T09:10:13.229293902Z"}
{"log":"  File \"/srv/h/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py\", line 2516, in __iter__\n","stream":"stdout","time":"2015-07-18T09:10:13.229298577Z"}
{"log":"    return self._execute_and_instances(context)\n","stream":"stdout","time":"2015-07-18T09:10:13.229303642Z"}
{"log":"  File \"/srv/h/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py\", line 2531, in _execute_and_instances\n","stream":"stdout","time":"2015-07-18T09:10:13.229308496Z"}
{"log":"    result = conn.execute(querycontext.statement, self._params)\n","stream":"stdout","time":"2015-07-18T09:10:13.229313769Z"}
{"log":"  File \"/srv/h/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py\", line 914, in execute\n","stream":"stdout","time":"2015-07-18T09:10:13.229318536Z"}
{"log":"    return meth(self, multiparams, params)\n","stream":"stdout","time":"2015-07-18T09:10:13.229323629Z"}
{"log":"  File \"/srv/h/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py\", line 323, in _execute_on_connection\n","stream":"stdout","time":"2015-07-18T09:10:13.229328358Z"}
{"log":"    return connection._execute_clauseelement(self, multiparams, params)\n","stream":"stdout","time":"2015-07-18T09:10:13.229334092Z"}
{"log":"  File \"/srv/h/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py\", line 1010, in _execute_clauseelement\n","stream":"stdout","time":"2015-07-18T09:10:13.229487607Z"}
{"log":"    compiled_sql, distilled_params\n","stream":"stdout","time":"2015-07-18T09:10:13.22950164Z"}
{"log":"  File \"/srv/h/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py\", line 1146, in _execute_context\n","stream":"stdout","time":"2015-07-18T09:10:13.22950789Z"}
{"log":"    context)\n","stream":"stdout","time":"2015-07-18T09:10:13.229513509Z"}
{"log":"  File \"/srv/h/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py\", line 1341, in _handle_dbapi_exception\n","stream":"stdout","time":"2015-07-18T09:10:13.229518636Z"}
{"log":"    exc_info\n","stream":"stdout","time":"2015-07-18T09:10:13.229524102Z"}
{"log":"  File \"/srv/h/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py\", line 199, in raise_from_cause\n","stream":"stdout","time":"2015-07-18T09:10:13.229529741Z"}
{"log":"    reraise(type(exception), exception, tb=exc_tb)\n","stream":"stdout","time":"2015-07-18T09:10:13.229545779Z"}
{"log":"  File \"/srv/h/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py\", line 1139, in _execute_context\n","stream":"stdout","time":"2015-07-18T09:10:13.229552897Z"}
{"log":"    context)\n","stream":"stdout","time":"2015-07-18T09:10:13.229559915Z"}
{"log":"  File \"/srv/h/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py\", line 450, in do_execute\n","stream":"stdout","time":"2015-07-18T09:10:13.229567337Z"}
{"log":"    cursor.execute(statement, parameters)\n","stream":"stdout","time":"2015-07-18T09:10:13.229573227Z"}
{"log":"OperationalError: (psycopg2.OperationalError) SSL SYSCALL error: EOF detected\n","stream":"stdout","time":"2015-07-18T09:10:13.229578222Z"}
{"log":" [SQL: 'SELECT \"user\".username AS user_username, \"user\".password AS user_password, \"user\".id AS user_id, \"user\".uid AS user_uid, \"user\".nipsa AS user_nipsa, \"user\".email AS user_email, \"user\".status AS user_status, \"user\".last_login_date AS user_last_login_date, \"user\".registered_date AS user_registered_date, \"user\".activation_id AS user_activation_id, \"user\".salt AS user_salt \\nFROM \"user\" \\nWHERE \"user\".uid = %(uid_1)s \\n LIMIT %(param_1)s'] [parameters: {'uid_1': u'keck', 'param_1': 1}]\n","stream":"stdout","time":"2015-07-18T09:10:13.229583961Z"}

**Comment by tilgovi** [comment]
How are you running the server?

**Comment by nickstenning** [comment]
`OperationalError: (psycopg2.OperationalError) SSL SYSCALL error: EOF detected` looks like a networking error between the web application and postgres.

Given no update here I'm going to close this. Feel free to reopen if you still have a problem you can't resolve.
