### ISSUE TITLE
Replace Makefile with Python code

### ISSUE THREAD

**Issue by BigBlueHat** [hypothesis/h#2376]
As a Windows user, I want to be able to run the commands currently in `Makefile` without extracting them by hand--due to the lack of `make` on Windows--so that I can more easily run, dev, and contribute to `h`.

My (many) attempts to installing and using `cmake` (etc) on Windows were a painful failure...I've finally switch to just running the commands by hand--using the `Makefile` as docs...

If the scripts were in pure Python (or even pure bash), I'd be able to use them without a hitch.

**Comment by tilgovi** [comment]
Happy to just ditch it entirely in favor of documentation. I'm really not a fan of the fact that we hide from the newbie the need to run `npm install` and `pip install`.

**Comment by BigBlueHat** [comment]
I'm cool with that for the most part. A handy clean script would be...
handy. :smiley_cat:

I'll think through what I'm personally using out of the Makefile, make some
proposals for doc or script changes, and we can go from there.

**Comment by nickstenning** [comment]
Personally I'm not in favour of ditching the Makefile. Make is the lowest common denominator on *nix platforms. It's installed by default pretty much everywhere, and it's discoverable: someone checking out the code can see "oh, there's a Makefile" and know how to use it. This wouldn't be true of `tools/install-hypothesis.py`.

Moreover, GNU Make is [available for win32](http://gnuwin32.sourceforge.net/packages/make.htm), and part of your problem might be that `cmake` and `make` are completely different tools.

**Comment by BigBlueHat** [comment]
Sorry. Yeah...I had tried them both (not understanding the difference). I finally got GNU Make to work, but not via that link, nor via [Chocolatey](http://chocolatey.org) ("apt-get for windows"). Apparently anything less than 3.82 throws this error (which matched my experience):
http://superuser.com/questions/375029/make-interrupt-exception-caught

So...I used the one linked there...and now am hitting issues with `find`:
```
$ make clean
find . -type f -name "*.py[co]" -delete
find: invalid predicate `-delete'
makefile:24: recipe for target 'clean' failed
make: *** [clean] Error 1
```

Apparently `-delete` is not a thing in the MinGW *nix tools for Windows...

I realize `Makefile` is a long standing thing...but so is `install.sh` and `python setup.py install` and `npm run build`...etc.

In the end, people will read the README, do what it says there, and/or be frustraited when it doesn't work for them. Likely, it won't be our "fault." Regardless, we should minimize pain and maximize productivity.

So...doubling my :+1: for providing scripts that are more cross-platform...even if we keep a `Makefile` around that runs those scripts. :grinning:

**Comment by nickstenning** [comment]
Sounds to me that basically all you're asking for is some documentation. Because the way to prepare `h` for use is:

```
pip install -e .[dev,testing,YAML]
npm install
```

Both of which are about as standard as it gets (modulo the pip extras).

**Comment by judell** [comment]
"Personally I'm not in favour of ditching the Makefile."

Me neither, even though I am mainly a WIndows user who is inconvenienced in the ways @BigBlueHat describes here.

"In the end, people will read the README, do what it says there, and/or be frustrated when it doesn't work for them."

That'd be true on *nix, but on Windows long experience has taught me not to expect that it will. And that isn't our battle to fight.

**Comment by BigBlueHat** [comment]
k.
