### ISSUE TITLE
Stream does not load more than one page of results

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#2382]
Go here:
hypothes.is/stream

Try to scroll past one page of results.

**Comment by tilgovi** [comment]
Updated issue title.

**Comment by tilgovi** [comment]
Since there were logs in the stream instance about database connection pool exhaustion, I think this may have been solved by #2381.

**Comment by tilgovi** [comment]
Tentative, optimistic closure. Seems to be holding up right now with plenty of active use.
