### ISSUE TITLE
Unanchored annotations in epic 27MB 180-page PDF

### ISSUE THREAD

**Issue by judell** [hypothesis/h#2389]
URL: http://pubs.usgs.gov/pp/pp1661f/pp1661f_text.pdf (awesome test doc)

Massively complex doc, 27MB, 180 pages, gives PDF.js a run for its money!

I successfully anchored an annotation to a selection on page 38. Tried again at page 90. The adder pops, I make a selection, but no new annotation card appears.

**Comment by judell** [comment]
Update: It *did* appear! Just took a really long time.

**Comment by tilgovi** [comment]
Lots of missing anchors, though :-(

**Comment by judell** [comment]
?

https://hypothes.is/api/search?uri=https%3A%2F%2Fhypothes.is%2Fapi%2Fsearch%3Furi%3Dhttps%253A%252F%252Fhypothes.is%252Fstream%253Fq%253Duser%253Aeitan%252343411b52-5dd5-4ecf-b5f7-da4bd8fbbd6c only shows the 1 I made.

**Comment by tilgovi** [comment]
I see 8 annotations in the sidebar on that document.

**Comment by judell** [comment]
Oh. Yep. I was looking at too many different things at the same time.

**Comment by tilgovi** [comment]
Is this also fallout from the anchoring rewrite, with positions way off? Is it the same diagnosis and solution as #2396. We've got an open PR for showing unanchored annotations in #2411. Should we close this?
