### ISSUE TITLE
Via not loading annotations on CISA PDF

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#2395]
Senator Wyden's office is suggesting that we might annotate the draft CISA bill.
http://www.openthegovernment.org/sites/default/files/cisa_2015_discussion_draft.pdf

I created a few sample annotations for his staffer to see with the Chrome extension.
I then shared the via link with her, but I realized can't see the annotations there.
https://via.hypothes.is/static/__shared/viewer/web/viewer.html?file=/id_/http://www.openthegovernment.org/sites/default/files/cisa_2015_discussion_draft.pdf

@judell pointed out that the console is reporting the following:
Could not sniff range typeRange.sniff @ hypothes.is/assets/scripts/hypothesis.min.js?c1ce7797:3

**Comment by judell** [comment]
Same error in the FF console, same result: No annos loaded.

**Comment by nickstenning** [comment]
Closing as a dupe. See #2396.

**Comment by dwhly** [comment]
Repoening per @nickstenning:  Behavior w/ via definitely different to behavior w just the chrome extension.

**Comment by judell** [comment]
Does not repro after https://github.com/hypothesis/via/commit/eedf6fe27ec181bb42e82b94a816f8172b58a778
