### ISSUE TITLE
Only one of two annotations anchors at CISA PDF

### ISSUE THREAD

**Issue by judell** [hypothesis/h#2396]
URL: http://www.openthegovernment.org/sites/default/files/cisa_2015_discussion_draft.pdf

Two annotations made, API search validates they exist.

Two annotations load, then one fails to anchor and vanishes.

The two annotations share an overlapping (almost identical) selection.

**Comment by tilgovi** [comment]
One of them has a text position that's wildly off.

**Comment by tilgovi** [comment]
Okay. One of them has a way different text position. We know this is a problem. It's probably fallout from the anchoring rewrite change.

We can write our own match function that has separate score coefficients for distance and similarity, chunk the text and set the threshold low but search with different location hints, or something else I've not yet thought of.

Regardless, this particular annotation not anchoring for this particular reason is something we're not likely to fix right now.
