### ISSUE TITLE
H activation fails at abcnews.go.com

### ISSUE THREAD

**Issue by judell** [hypothesis/h#2397]
URL: http://abcnews.go.com/Politics/lindsey-graham-destroyed-cellphone-spite-donald-trump/story?id=32621487

Symptom: Hypothesis does not activate

Console error in hypothesis.min.js:

Uncaught TypeError: Cannot read property 'Util' of undefined8.../annotation-sync @ hypothesis.min.js?bc659cac:2s @ hypothesis.min.js?bc659cac:1e @ hypothesis.min.js?bc659cac:1(anonymous function) @ hypothesis.min.js?bc659cac:1

**Comment by tilgovi** [comment]
`require('annotator')` is `undefined`. Not sure why.

**Comment by robertknight** [comment]
Minimal repro case:

```html
<html>
<meta charset="UTF-8">
<body>
<script>
self = {}; // global = {} produces the same result

// Hypothesis bookmarklet
(function(){window.hypothesisConfig=function(){return{showHighlights:true};};var d=document,s=d.createElement('script');s.setAttribute('src','https://hypothes.is/app/embed.js');d.body.appendChild(s)})();
</script>
</body>
</html>
```

Happens in any context where `self` or `global` properties exists on the global context but are not actually the global objects themselves (so their properties are not part of the global context). In this page this happens in [merlin.js](http://a.abcnews.com/assets/js/merlin.js).

This happens due to assumptions in browserify-shim about global, self and window:

```js
// require('annotator') function from hypothesis.min.js:
(function(global) { // global === window.self
  ...
  (function browserifyShim(module, exports, require, define, browserify_shim__define__module__export__) {
    (function() {
      ...
      this.Annotator = Annotator; // this === window.self
      ...
    }).call(this);

    // neither Annotator nor window.Annotator defined here
    browserify_shim__define__module__export__(typeof Annotator != "undefined" ? Annotator : window.Annotator)
  }).call(global, undefined, undefined, undefined, undefined, function defineExport(ex) {
    // sets exports of 'annotator' module,
    // called as browserify_shim__define__module__export__(), with ex being undefined
    module.exports = ex
  })
}).call(this, typeof global !== "undefined" ? global : typeof self !== "undefined" ? self : typeof window !== "undefined" ? window : {})
```

**Comment by tilgovi** [comment]
It's not straightforwardly browserify-shim. It's because browserify-shim uses `global`, assuming that browserify will take care of defining it correctly. The relevant issue is substack/insert-module-globals#48

**Comment by tilgovi** [comment]
I'll double check but don't think this can be closed yet.

My commit message said "This is one step toward removing all the browserify-shim requiring
libraries from the injected bundle, which will eventually fix #2397."

Only one step.

**Comment by tilgovi** [comment]
I don't know what fixed this but it is fixed. The repro that @robertknight posts still causes problems. I've opened thlorenz/browserify-shim#183 to discuss, but given that we don't have an actual site report here for a real-world case where `global` or `self` is a global variable I'm going to close this and we'll inherit whatever fix ends up in browserify, insert-module-globals, or browserify-shim eventually for the unlikely edge case where this does turn out to be an issue.

**Comment by robertknight** [comment]
The code which triggered the issue in the 3rd-party website was rewritten from [merlin.js](http://a.abcnews.com/assets/js/merlin.js) to [merlin-core.js](http://a.abcnews.com/assets/js/merlin-core.js), removing the assignment to the global self var in the process.
