### ISSUE TITLE
Cookie-authorized requests to the API cause 500 errors

### ISSUE THREAD

**Issue by tilgovi** [hypothesis/h#2398]
Currently, if you make a cookie-authorized request to the API then the `get_user` function of `h.api.auth` will see you as authenticated but since the OAuth machinery didn't see a token there is no `request.client`. This results in passing `None` as the user down into annotator-store.

This can happen for real clients if the token times out.

If the API were on a separate subdomain we wouldn't get cookies on these requests.

Another way to handle it would be to immediately 403 if we see an `Authorization` header but `request.verify_request()` returns `False`.

**Comment by tilgovi** [comment]
None of this addresses the problem that tokens time out and don't refresh, but it's not meant to. One would think they could make cookie-authenticated requests to the API. In any case, now that the API is not a separate application I definitely don't want to go about trying to wrangle our authentication policies into only accepting certain credentials for certain routes.

**Comment by judell** [comment]
Does this remain relevant after https://github.com/hypothesis/h/issues/1492?

**Comment by tilgovi** [comment]
The issue, as described, is not by any means fixed. We can, however, say that we won't fix it. That would be to say that authorization for API requests is only supported through OAuth tokens rather than cookies. Now that tokens are properly refreshed and refreshing the token blocks pending API requests, our client won't experience this issue. Nevertheless, the issue itself, as described, is, again, not "fixed".

**Comment by judell** [comment]
>  authorization for API requests is only supported through OAuth tokens rather than cookies

Which seems like a nice simplification, especially going forward as other token-authenticated use cases emerge. I'd support closing as WontFix, unless there's a need for cookie-authenticated requests that isn't on the table here.

**Comment by tilgovi** [comment]
I'm fine with wontfix.
