### ISSUE TITLE
Privacy Badger compatibility

### ISSUE THREAD

**Issue by pguth** [hypothesis/h#2406]
[Privacy Badger](https://github.com/EFForg/privacybadgerchrome) marks hypothesis as yellow (=allow requests but kill cookies) on my machine. This does not only log me out but makes *h* unusable (`Session is invalid. Please try again.`).

> Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36

I read somewhere that PB does classify websites as yellow when they set tracking cookies without purpose. Maybe we (myself included) could look into that since PB is a project by our fellow Jedis from the [EFF](https://www.eff.org/).

**Workaround:** Manually set Hypothe.is to green/allowed.

**Comment by tilgovi** [comment]
We have a solution that's been proposed and accepted, I think, in #914. I'm going to close this as a duplicate. Although, we should probably have phrased that other issue in terms of the problem rather than the solution, since it solves more than one problem.

Thanks for reporting it.
