### ISSUE TITLE
Annotation editor fails to appear for certain PDF selections

### ISSUE THREAD

**Issue by judell** [hypothesis/h#2418]
### Steps to reproduce:

1. Start Hypothesis on http://courses.csail.mit.edu/18.337/2015/docs/50YearsDataScience.pdf.
1. Go to page 8.
1. Select "Lost in the hoopla about such skills"
1. Adder appears, click New Note

### Expected behaviour

New, empty annotation appears for editing in the sidebar.

### Actual behaviour

Nothing appears! Note that if you select "ost in the hoopla about such skills" it seems to work just fine.

**Comment by judell** [comment]
No longer reproduces.

**Comment by judell** [comment]
A similar, maybe same, thing happens here: http://courses.csail.mit.edu/18.337/2015/docs/50YearsDataScience.pdf

Steps to reproduce:

1. Go to page 8.
2. Select "Lost in the hoopla about such skills"
3. Adder appears, click New Note
4. No new annotation appears in the sidebar
5. Select "ost in the hoopla about such skills"
6.  Adder appears, click New Note
7. New annotation appears as expected

Ditto for page 10 with "Fortunately, thereisa solid case forsome entitycalled `Data Science" vs "ortunately, thereisa solid case forsome entitycalled `Data Science"

**Comment by nickstenning** [comment]
I've reduced this to the repro steps and removed the previous description. Still appears to be a bug as of v0.8.13.

**Comment by judell** [comment]
@dwhly & @judell confirm still a bug as of 0.14.0
