### ISSUE TITLE
Buttons look funky

### ISSUE THREAD

**Issue by jtremback** [hypothesis/h#2429]
![image](https://cloud.githubusercontent.com/assets/1335122/9029846/064df182-394f-11e5-856f-ce99765f68c7.png)
Why are they abnormally tall and off vertical center?

**Comment by tilgovi** [comment]
See the discussion on #2394

**Comment by tilgovi** [comment]
I don't know what you mean by abnormally tall. What's normal?

**Comment by BigBlueHat** [comment]
@jtremback are you seeing this on all sites? or only a single site? Also, which browser are you using?

Also, it does look like our icon/text alignment is off @JakeHartnell--at least in that screenshot.

Here's how they look for me when loaded on http://via.hypothes.is/www.w3.org/DesignIssues/
![screen shot 2015-08-04 at 10 19 53 am](https://cloud.githubusercontent.com/assets/43209/9062778/7531c9ae-3a92-11e5-886d-8b472f709fd7.png)

One could get picking about the pixels, but I think this one looks "correct."

**Comment by tilgovi** [comment]
Firefox seems to look good. Chrome does not. It has to do with user agent
style for line heights on buttons.
