### ISSUE TITLE
Install with Eager button

### ISSUE THREAD

**Issue by fiatjaf** [hypothesis/h#2434]
Since there's an easy to install Eager app for Hypothes.is at https://eager.io/app/hypothesis, we could have an Eager button like

[![Install Hypothes.is with Eager, a button](https://install.eager.io/install-button.png)](https://eager.io/app/hypothesis/install?source=button)

in the "Add Hypothesis to a web site" modal of the home page. Or at least a link pointing to the Eager app, just like the Wordpress plugin link.

There are more flexible ways of generating buttons (and with more explanation, instead of a general Eager image) at https://github.com/EagerIO/DeveloperDocs/blob/master/docs/install-button.md.

**Comment by tilgovi** [comment]
I am not sure we should promote a method of installing Hypothesis that requires the user to sign up for a service that is not Hypothesis and provides nothing that is an operational dependency of Hypothesis.

It seems that installing eager means adding an embed code. That's not at all easier than installing the Hypothesis embed code. I can see the utility in an organization that wants to install a single embed code and then have a dashboard for adding and removing applications that it loads, but that seems like a decision an individual organization might wish to make based on their administrative requirements.

For a publisher just wishing to embed Hypothesis it seems like extra work.

**Comment by fiatjaf** [comment]
Your argument can be used in the same way against the Wordpress plugin, since it is much easier to just add Hypothesis embed code manually than to install Wordpress. Even if we don't go that way, for some people it may be easier to add the embed code in your own Wordpress-powered site than it is to install a Wordpress plugin.

However, you can't deny that, for people who are already Eager users, just clicking to install Hypothesis from Eager will be a much better experience than having to open the code editor, whatever it is.

You could say that you don't want to promote any other third-party services -- except for Wordpress --, even the ones that are actively promoting yours. That would make more sense, but I still wouldn't understand why you would actively prevent the adoption of Hypothesis by more users (even if they are few) using that argument.

**Comment by tilgovi** [comment]
I understand it's easier for people already using Eager, and I'm happy to have that option. Thank you for doing it.

If you fix the issues I've opened on your repository we can consider whether it's useful to promote it on our homepage. However, please understand that there is a cognitive cost placed on publishers when they are presented with more options and the global install base for Wordpress is so ridiculously large compared to Eager that to say the same argument applies to each is absurd to me.

Please understand that I do not wish to harm adoption. I do not have enough information to say whether, on balance, the addition of Eager as an option serves to confuse or assist publishers. It is not trivial to say whether it harms or helps adoption.

**Comment by fiatjaf** [comment]
There's another point to be made here: adding embed codes can be easy, but can also take some time and involve some editor and deploying logistics. In the margin, people may be not willing to do it, even when they could do it easily.

If these people see the "Eager" badge or reference, they can perhaps think: "if this is the last time I will have to add an embed code, so I'll do it".

Not that this will be lots of people, but there may be people like that (I am one example). I am not related to Eager in any way, but I think they are providing a good service in that way.

**Comment by fiatjaf** [comment]
Ok, I understand the install base argument. It makes total sense. I had ignored it before because of my pro-Eager bias.

**Comment by tilgovi** [comment]
Again, though. Thank you for adding Hypothesis to Eager. Really.

If I came across as dismissive, I definitely apologize. I purposely did not close the issue, just voiced some of my hesitations.

If you can fix the two small issues I opened on your repo I think we can probably find a place for linking to the Eager install.

**Comment by adamschwartz** [comment]
@tilgovi @fiatjaf https://github.com/fiatjaf/eager-hypothesis/issues/1 and https://github.com/fiatjaf/eager-hypothesis/issues/2 should be resolved. Please take a look as soon as it’s convenient. I deeply apologize for the delay on this.

**Comment by tilgovi** [comment]
No apologies necessary :). Thanks.

**Comment by tilgovi** [comment]
@BigBlueHat want to help me figure out a place for this?

**Comment by adamschwartz** [comment]
Here are the docs for using our styled buttons, if you’re interested:
https://github.com/EagerIO/DeveloperDocs/blob/master/docs/install-button.md

And here’s an example usage:
http://github.hubspot.com/pace/

**Comment by nickstenning** [comment]
Hi there! I'm going to close this as part of a clean-up of all issues currently open on this repo that represent ideas or features rather than reports of bugs or technical chores. 

I want to be clear that **this isn't intended to say anything at all about the content of this issue**—it certainly doesn't mean we're no longer planning to do the work discussed here—just that we don't want to use GitHub issues to track feature requests or ideas, because the threads can get long and somewhat unwieldy.

If you're interested in what we are working on at the moment, you can check out [our Trello board](https://trello.com/b/o2ungX1n/current-sprint) and, for a longer-term view, [our roadmap](https://hypothes.is/roadmap/).

And, if you're interested in following up on this issue, please do continue the discussion on our [developer community mailing list](https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev). You might also want to check out [our contributing guide](https://github.com/hypothesis/h/blob/master/CONTRIBUTING.rst).
