### ISSUE TITLE
Replied on stream, didn't save.

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#2440]
So, I replied to an annotation (https://hypothes.is/a/GJzuhwo1SHeyP6rvzMQLKw) in the stream.  

This one:

![screen shot 2015-08-11 at 10 30 46 am](https://cloud.githubusercontent.com/assets/1413074/9204933/11c184d6-4014-11e5-9277-36aec0d6edf2.png)

The reply appears to take as you can see above.  
It even has an ID, this one: https://hypothes.is/a/hfsMEcGeRcuv9Uwi148ZAQ

Then I went to the page, looked at the annotation, and my reply is not showing:

![screen shot 2015-08-11 at 10 31 52 am](https://cloud.githubusercontent.com/assets/1413074/9204956/36603cce-4014-11e5-89b0-6dc183e6cb44.png)

I went back to the stream, and my reply isn't showing there now either

![screen shot 2015-08-11 at 10 39 35 am](https://cloud.githubusercontent.com/assets/1413074/9205143/47ffaa2c-4015-11e5-9322-bdab31938c47.png)

**Comment by tilgovi** [comment]
I see it in the stream, but not if I search (because your reply isn't by marshallk). This is more or less #1713.

I see the reply when I go to marshallk's annotation directly.

I see the reply when viewing the article if I do it while logged out.

Diagnosis: the new normalized search, currently toggled on for staff but not globally, doesn't search the `uri` field. Replies have a `uri` field that matches their parent, but they don't have a `target`. They do have a `references` property that names their ancestry.

**Comment by tilgovi** [comment]
So, this should block toggling the new search normalization on for everyone.

**Comment by tilgovi** [comment]
@judell

**Comment by tilgovi** [comment]
Never mind. I'll add it to Trello.

**Comment by judell** [comment]
"So, this should block toggling the new search normalization on for everyone." Got it, thanks.

**Comment by seanh** [comment]
Another problem caused by replies being the same thing as annotations, imo.

**Comment by seanh** [comment]
> They do have a references property that names their ancestry.

Is that any use to us here? I don't think we can do a search for "any document that has a target.source_normalized that matches this URI, or that has a references[0] id that matches the id of another annotation that has a target.source_normalized that matches this URI." That doesn't seem like something we can express efficiently in an Es query.

We _could_ copy the targets (with their source_normalized fields) from the parent annotations into the reply annotations, when indexing a reply annotation.

**Comment by seanh** [comment]
> We could copy the targets (with their source_normalized fields) from the parent annotations into the reply annotations, when indexing a reply annotation. (Then we need to do a migration where we do this copy for all existing replies.)

This looks like the best short-term solution to me. Longer term, moving annotations into postgres and denormalizing them would help with this (as would modelling replies as a different type of object from annotations)

**Comment by judell** [comment]
FWIW the alt stream doesn't have this problem because it maintains an index of parent-child relationships.

**Comment by tilgovi** [comment]
What is the alt stream?

**Comment by judell** [comment]
http://h.jonudell.info:5000/stream.alt is where I'm exercising the API and
trying out some ideas for a next-gen stream.
