### ISSUE TITLE
Rendered strangely bottom right

### ISSUE THREAD

**Issue by pguth** [hypothesis/h#2444]
On: http://roots.cx/

When clicking `h` a horizontal scroller is introduced. The picture shows the bottom right corner:

![h rendered strangely bottom right](https://cdn.pbrd.co/images/2FojJftM.png)

`Chromium Version 43.0.2357.132 Built from source for Fedora release 22 (Twenty Two) (64-bit)`

**Comment by judell** [comment]
Still an issue. FF and Chrome.

**Comment by nickstenning** [comment]
Looking into this it seems to be a result of this page CSS rule:

```css
#index>div {
    position: relative;
    ...
}
```

The use of `<div>` elements for in-page parts of Hypothesis causes problems on quite a few sites. Perhaps we should mitigate (if not completely avoid) these issues by ensuring that all the parts of Hypothesis in the hosting page use custom elements (e.g. `<hypothesis-bucket-bar>`, `<hypothesis-toolbar>`) much as we've done for the adder.

**Comment by nickstenning** [comment]
Thank you for reporting this! I've folded the details into a bug to track this and a number of closely related reports: hypothesis/client#244.
