### ISSUE TITLE
Use of function-bind breaks usage on under CSP unsafe-eval restriction

### ISSUE THREAD

**Issue by judell** [hypothesis/h#2445]
Now h is broken completely on Github.

Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src assets-cdn.github.com collector-cdn.github.com".

See: https://github.com/hypothesis/h/issues/2266#issuecomment-130111445

And: https://github.com/tarruda/has/issues/5

**Comment by judell** [comment]
Observation: This works: https://via.hypothes.is/https://github.com/hypothesis/h/issues/2445 (see: https://hypothes.is/a/x75_FfmtQ-ybQvTWAVREWA)

Question: The complaint is: "unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src assets-cdn.github.com collector-cdn.github.com".  Can github.com be explicitly exempted in the extension's manifest.json?

**Comment by tilgovi** [comment]
> Can github.com be explicitly exempted in the extension's manifest.json?

Yes, but that does not solve the issue.

**Comment by robertknight** [comment]
@tilgovi posted a PR to fix the issue in frame-rpc upstream - https://github.com/substack/frame-rpc/pull/2 .

**Comment by edrex** [comment]
do you guys have a policy on forking? would be nice to get github working in the deployed version.

**Comment by robertknight** [comment]
@edrex Agreed - I'm inclined to go ahead and use a fork of `frame-rpc` in H until the issue is resolved upstream.

**Comment by nickstenning** [comment]
I'd like to bump this and suggest that if we need to fork or vendor code from frame-rpc in order to solve this problem, we go ahead and do so.

**Comment by judell** [comment]
+1.

**Comment by nickstenning** [comment]
Fixed by #2845.
