### ISSUE TITLE
Flash a warning when the text of an annotation is only whitespace

### ISSUE THREAD

**Issue by judell** [hypothesis/h#2449]
We currently allow annotations with blank bodies containing only whitespace. We should probably flash a warning about that, in the same way and for the same reasons that email programs warn about blank bodies.

**Comment by dwhly** [comment]
> We should probably flash a warning about that

If we prevent highlights, we probably should also prevent these to be public too.  There's no public value in a blank annotation.

**Comment by judell** [comment]
"There's no public value in a blank annotation." I wouldn't assume that always. On a densely-annotated page, highlights that compete with annotations are probably noise. But on a sparsely-annotated page they might be signal. If this is a hack to create public highlights we should consider the need it's expressing. (Retweet?) An effort to route around the prevention of public highlights might be telling us something important.

Or it might just be an error. So we should at least ask.

**Comment by tilgovi** [comment]
We should maybe just enable public highlights.

**Comment by tilgovi** [comment]
Tackle the issue of "noise" separately?

**Comment by lenazun** [comment]
+1 on public highlights.  In the future we could aggregate this data and show the most highlighted segments.

**Comment by tilgovi** [comment]
We can also hide highlights from the sidebar if they're not selected, i.e. if the user hasn't explicitly clicked on the highlight or the corresponding bucket tab.

**Comment by tilgovi** [comment]
Something like that.

**Comment by judell** [comment]
Not a bug. Further conversation about public highlights, elsewhere,  may be useful.
