### ISSUE TITLE
Trouble signing in and out with Internet Explorer

### ISSUE THREAD

**Issue by judell** [hypothesis/h#2463]
This iPad report came to support, was waiting for confirmation:

"The sign in doesn’t work but if one goes to hypothes.is to sign in first and goes back to our site, then the user is/stays signed in."

I saw the Edge behavior a few days back. Then the WinPhone behavior happened just now. 

They smell similar so filing as one issue for now.

**Comment by judell** [comment]
(Obviously meant P3 not P1.)

**Comment by tilgovi** [comment]
These need to be separated and mostly it's known problems, probably.

The windows issues are going to be the lack of P3P policy.
The Safari issues are going to third-party cookie issues as well, but should, I think, disappear after a first party interaction, which would make it a duplicate of #914.

**Comment by tilgovi** [comment]
The windows issues may not actually require a P3P policy. It looks like I may have fixed it with be1b33b.

**Comment by tilgovi** [comment]
Scratch that. I think we still need the P3P policy.

**Comment by tilgovi** [comment]
Re-titling this to reflect P3P, going to leave #914 as the solution for the Safari issues.

**Comment by judell** [comment]
Does not reproduce in IE.
