### ISSUE TITLE
Include annotated content in annotation views

### ISSUE THREAD

**Issue by edsu** [hypothesis/h#2464]
Being able to share annotations as URLs in tweets, facebook updates, emails, rss feeds, etc seems important. Both genius and h let you share URLs for a specific annotation, e.g.

> http://genius.com/7693847

and:

> https://hypothes.is/a/OlDtTKtkQMKB2gI9P1diQg

But see how genius shows you the annotation alongside the content that's being annotated? To me this seems much more usable and interesting, and makes me want to use the link. I wonder if h could do something similar?

**Comment by robertknight** [comment]
Agreed. I'd be very keen to see this. There is https://via.hypothes.is/ now which could facilitate it.

**Comment by dwhly** [comment]
We have an open issue for this here: https://github.com/hypothesis/vision/issues/87

We're of like minds on this.  The card for a v1 of direct linking is very high in our current backlog, and will get attention soon.

**Comment by edsu** [comment]
Thanks! I'm glad to know I'm not the only one who feels this way :-)
