### ISSUE TITLE
tag links wrap extraneous escaped single quotes around tag strings

### ISSUE THREAD

**Issue by edrex** [hypothesis/h#2469]
Tag links in the stream have extraneous `%27`s around the tag string, like https://hypothes.is/stream?q=tag:%27foo%27bar%27%27 (here the unescaped tag string  is `foo'bar'`). The view works fine without them, the problem is just with the link URL generation. https://github.com/hypothesis/h/pull/1881#issuecomment-135555320

**Comment by tilgovi** [comment]
When I follow that link in Firefox, my location bar shows the quotation marks un-encoded. Chrome is not as smart and I do not think there is anything we can do to effect that.

However, I would love to know how you got that URL. It is certainly strange that there's a quotation mark between `foo` and `bar`. Did you craft this by hand or did some action in our UI give you this URL?

**Comment by edrex** [comment]
sorry, bad test case. i added the inner single quotes to the tag to confirm that there was no ill effect with the outer quotes removed. Another example: https://hypothes.is/stream?q=tag:%27shell%27

I'm just saying that they seem completely extraneous.

**Comment by tilgovi** [comment]
Again, I'm curious how you got the URL. If you got it by clicking on a tag, for instance, than we have an issue where we are adding extraneous quotes around a tag that has no whitespace. However, if the tag has whitespace we have no choice but to quote it or we cannot parse the query string properly. It's unfortunate that Chrome does not prettify its URLs in the location bar.

**Comment by tilgovi** [comment]
Indeed we seem to quote the tag even when we don't need to. I'll update the issue title to reflect that.

**Comment by tilgovi** [comment]
Oh, wait, I re-read the title. You describe this exactly. Sorry, I'm slow today!! Thanks.

**Comment by tilgovi** [comment]
- [x] Quote tag strings in search when they contain whitespace
- [ ] Don't quote tag strings in search when they don't contain whitespace

**Comment by edrex** [comment]
Oh, I didn't realize that the tag key supports multiple space separated values, as in
https://hypothes.is/stream?q=tag:%27open%20source%27%20%27listicles%27.

Now quoting the individual tags makes sense to me. And special-casing tags with no spaces seems less simple, so I'll close. Feel free to reopen.
