### ISSUE TITLE
"Non-secure form" alert in Safari when I clicked a via link

### ISSUE THREAD

**Issue by conordelahunty** [hypothesis/h#2478]
I clicked a via link in this tweet: https://twitter.com/edsu/status/639112854679982080 and when the page loaded a I got an alert saying that this form will not be sent in a secure way.

![screen shot 2015-09-02 at 18 43 47](https://cloud.githubusercontent.com/assets/8598901/9637747/cf03ff20-51a2-11e5-8c92-82ba520340bc.png)

Full link: https://via.hypothes.is/http://www.theatlantic.com/magazine/archive/1945/07/as-we-may-think/303881/

Browser: Safari Version 8.0.7

**Comment by tilgovi** [comment]
Might be better reported at hypothesis/via.
