### ISSUE TITLE
Youtube annotation mapping broken

### ISSUE THREAD

**Issue by pguth** [hypothesis/h#2481]
Eg. [here](https://www.youtube.com/watch?v=3kEpZWGgJks). I see a lot of annotations that are clearly coming from other videos.

Youtubes URL format: `/watch?v=3kEpZWGgJks`

**Comment by tilgovi** [comment]
This is a duplicate of #2240. That was closed prematurely. The last work for that _should_ have merged now, and we'll test it out. I'm going to close this though, and you can follow that issue if you like.

**Comment by pguth** [comment]
Ok, nice!
