### ISSUE TITLE
Password reset email text incorrect.

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#2489]
Currently our password reset email includes the following line:

"If you don't want to change your password, please ignore this email message."

I believe this line is incorrect.  I recently experimented with the password reset function to see if it was working (another user was having trouble).  Because of this line, my assumption was that I could trigger a reset email to myself, and then ignore it.

My understanding is now that this is not true.  If a reset email has been triggered, you *must* follow through with it.  You can not sign into your account otherwise.

(If that is incorrect, please advise.)

**Comment by tilgovi** [comment]
That's correct. The text is wrong. Your account will be marked as inactive right now if you do this.

**Comment by JakeHartnell** [comment]
Deleted the wrong text.

**Comment by tilgovi** [comment]
Thanks, @JakeHartnell, but I don't think we should be content with this fix. As it stands, it's possible to deactivate anyone's account and force them to respond to these emails and reset their password over and over. It's still a poor experience.

If anyone wants to take on some of this, #1933 is a good place to start

**Comment by JakeHartnell** [comment]
> Thanks, @JakeHartnell, but I don't think we should be content with this fix... #1933 is a good place to start.

+1
