### ISSUE TITLE
Editing an annotation results in an error.

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#2497]
You can no longer edit an annotation.  (From any account, not just H. staff) 

Trying to edit and save results in an error saying that you cannot move annotations between groups.

![screen shot 2015-09-15 at 1 02 14 pm](https://cloud.githubusercontent.com/assets/1413074/9891623/71af8d0c-5bbc-11e5-9561-e4d5d53c4700.png)

**Comment by judell** [comment]
Confirmed. That is /very/ new.

**Comment by dwhly** [comment]
I'm changing this to a P1.  Currently you cannot edit annotations on H, period.  Must fix, immediately.

**Comment by tilgovi** [comment]
Fixed in a9da954af7c05332dbdec9b4100051841be19412
