### ISSUE TITLE
unexpected api response on delete of existing annotation (without permission)

### ISSUE THREAD

**Issue by judell** [hypothesis/h#2502]
Expected:

As per https://h.readthedocs.org/en/latest/api.html#delete, status of 401 or 403

Actual: 

status_code: 200
status: {"status": "failure", "reason": "not_found"}

**Comment by judell** [comment]
Is 404 the expected code (and 'not_found' the expected text) when a DELETE is rejected for lack of permissions?

**Comment by tilgovi** [comment]
Presently, yes.
