### ISSUE TITLE
Increase text size for annotation actions

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#2503]
The font size for annotation actions (Reply, Edit, Link) is _tiny_ and definitely smaller than accessibility guidelines would allow.

The font size for the root `<html>` element is specifies as 12px which is already borderline too small and 'small' text is then `0.8em` which computes to 9.6px.

My inclination would be to define a standard set of accessible type sizes in px and then make sure we are using them everywhere.

CC @conordelahunty

**Comment by robertknight** [comment]
Much of the font sizing in the current front-end is done with em-units, which used to be considered a best practice, but see https://mindtheshift.wordpress.com/2015/04/02/r-i-p-rem-viva-css-reference-pixel/ , including the comments, for a good overview of where things stand in 2015.

**Comment by conordelahunty** [comment]
@robertknight Agreed. As we discussed in the LRB, let's get together soon and work out what it being used where and set some new rules.

**Comment by tilgovi** [comment]
Go for it. I stuck with `ems` because I wanted to be able to modify the font size of a root element and have it be inherited. I thought that was a desirable property.

**Comment by tilgovi** [comment]
Also, just not having to change every padding, margin, etc if you decide to change the font size of one part of the UI.

**Comment by tilgovi** [comment]
That article makes a strong case that `em` is not for accessibility, because scaling the font is not a user feature we see much anymore, but it doesn't make any case against using `em` to make your UI elements proportional to your font size. I can't see a good outcome other than making the CSS harder to refactor or splattering a lot of math or extra classes around to calculate things relative to the font size when that's the whole point of `em` to begin with.

**Comment by robertknight** [comment]
> but it doesn't make any case against using em to make your UI elements proportional to your font size.

That's true and indeed the article does give that as a valid use case for `em`s. I don't propose to change those.

The goal here is to simply make sure that text sizes are consistent across different components and always large enough to be easily readable [1]. What I had in mind was just defining a standard set of font sizes as constants/variables in SCSS using `px` units and using those everywhere. In other words, extending the _Typography_ section of `variables.scss`.

[1] There are varying guidelines on what that minimum should be, but around 11-12px seems to be a common recommendation.

**Comment by tilgovi** [comment]
:+1:

**Comment by robertknight** [comment]
[Angular Material](https://material.angularjs.org/latest/#/CSS/typography) has an approach worth considering. They set the body size to 10px and then [size other text](https://github.com/angular/material/blob/v0.11.0/src/core/style/variables.scss) in `rem` units. That makes it easy to see what the typical px size is but enlarge fonts throughout the app if needed.

**Comment by robertknight** [comment]
This will be fixed when https://github.com/hypothesis/h/pull/2550 is merged.
