### ISSUE TITLE
Autolink URLs in the markdown viewer

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#2505]
The editor doesn't currently autolink URLs ie. turn URLs into links, as Github and most other markdown viewers do for example.

**Comment by tilgovi** [comment]
https://github.com/showdownjs/showdown see the options, `simplifiedAutoLink`.
Code in `h/static/script/filter/converter.js`.

**Comment by judell** [comment]
That was, indeed, a sad omission. Thanks for noticing and fixing.
