### ISSUE TITLE
chrome extension fails to load on ifixit.com

### ISSUE THREAD

**Issue by edrex** [hypothesis/h#2512]
For example https://www.ifixit.com/Teardown/Motorola+Moto+G+3G+Teardown/28088

Proxy works fine.

Didn't see any obvious culprit in the console.

Only hypothesis related error (with chrome's JS formatter)

```
hypothesis.min.js?03623e8d:formatted:7673
Uncaught TypeError: P.resolve is not a function
```

I'll provide more detail if devs can't reproduce.

**Comment by edrex** [comment]
Page has `X-Frame-Options:SAMEORIGIN` set, but no CSP stuff

**Comment by dwhly** [comment]
We think this issue may be addressed by a recent commit, which we'll push out on Monday after a bit more testing.

**Comment by edrex** [comment]
Thanks, will check after the update

**Comment by tilgovi** [comment]
@dwhly what recent commit?

**Comment by dwhly** [comment]
> @dwhly what recent commit?

We just noticed that the stage extension did not exhibit this behavior.  

From IRC on friday:

dwhly [11:20 AM] 
Noticing that https://github.com/hypothesis/h/issues/2512 appears to work w/ the stage extension.

nick [11:24 AM] 
Yep, I concur.
I'll do a version bump and deploy the latest extension on Monday.

**Comment by nickstenning** [comment]
I think we fixed this accidentally with f61c710 and 66f9047.

**Comment by edrex** [comment]
Is this released? It's still not working for me.

**Comment by nickstenning** [comment]
It is deployed, but you might not have an up-to-date extension. If you go to `chrome://extensions/` and hit the "Update extensions now" button, hopefully you'll get updated to v0.7.3.

If it *still* isn't working after that, feel free to reopen because we've obviously got something else to look into here.

**Comment by edrex** [comment]
Oh thanks, I wasn't sure how Chome extensions got updated. It works, and it fixes https://twitter.com/.* too, which AFAIR was broken in 0.7.2!
