### ISSUE TITLE
"We can't find the exact position of this annotation" shown on every annotation in the stream

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#2521]

**Comment by nickstenning** [comment]
Oh of course it bloody does. :grinning:

**Comment by nickstenning** [comment]
Just committed 98d12e8 to master, which *does not* address this bug, but it unblocks deployment by always requiring that the "show_unanchored_annotations" feature is toggled on before rendering that message.

**Comment by nickstenning** [comment]
Removed the P2 label as this isn't affecting any users at all just now.

**Comment by seanh** [comment]
I'll take a look at this now

**Comment by seanh** [comment]
Oh wait I have another wip to finish, will get to this soon..
