### ISSUE TITLE
Standalone annotation pages are broken

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#2524]
Click here:
https://hypothes.is/a/DngnrgLZS5SWow30uWL2pw

There is no annotation displayed.

**Comment by judell** [comment]
The query, https://hypothes.is/api/annotations/DngnrgLZS5SWow30uWL2pw, succeeds and returns data to the client:

Quote: "The long tail is Amazon and iTunes, Netflix, LoveFilm and eBay."
Text: "I wonder if there will ever be a Netflix type of thing for books...."
User: smalkin

A query for references (https://hypothes.is/api/search?references=DngnrgLZS5SWow30uWL2pw) also succeeds and returns data to the client. Also not displayed.

**Comment by nickstenning** [comment]
Fixed by 92010c1.

**Comment by judell** [comment]
Holy response time, Batman!

**Comment by jalperin** [comment]
40 minutes from reporting to fix. well done H team. When does the fix go live?

**Comment by nickstenning** [comment]
[Live now](https://hypothes.is/a/DngnrgLZS5SWow30uWL2pw). :fire_engine:
