### ISSUE TITLE
Saved annotation disappears

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#2525]
Go to a page, like this one.  (it seems to be worst on pages w/ the embedded client).
https://hypothes.is/blog/reputation-workshop/

Select a word.  Annotate.  Save.
The annotation disappears.
Close the sidebar.  Reopen.  The annotation is there.

Screencast:
https://drive.google.com/file/d/0B0yW-dSdEYAcM29IdG1Ta2gtMkk/view?usp=drivesdk

**Comment by judell** [comment]
I'm withdrawing the P2 label pending a bit more analysis.

**Comment by tilgovi** [comment]
https://hypothes.is/blog/reputation-workshop/ 404?

**Comment by dwhly** [comment]
Ack.  Bad example, this one exhibits the same problem:
https://hypothes.is/blog/back-from-budapest/

**Comment by judell** [comment]
@dwhly: browser?

I can repro this on several H blog articles in Chrome (Windows) but not FF.

Hmm. I noticed the same thing (Chrome/Windows not FF) for https://github.com/hypothesis/h/issues/2528 and https://github.com/hypothesis/h/issues/2527.

**Comment by dwhly** [comment]
> @dwhly: browser?

Chrome (Mac).

**Comment by judell** [comment]
Can you check 2527 and 2528 in your Chrome? 

Meanwhile let's look for an example of this one on pages other than those which (like our blog) still have the search_normalization quirk (which is sensitive to whether we're on the feature-flag list and whether we're logged in or not).

**Comment by dwhly** [comment]
So, here is a screenshot on Mac El Capitan / Chrome 45, using the extension.
https://drive.google.com/file/d/0B0yW-dSdEYAcXzljUHhtZmt1aW8/view?usp=drivesdk

Here is a screenshot on Windows 10 / FF 40, using Via.
https://drive.google.com/file/d/0B0yW-dSdEYAcdjFSZEtxcmlBX1k/view?usp=drivesdk

On this page:
http://www.defenseone.com/news/2015/09/allen-quits-isis-war-envoy-job-one-year-after-calling-groups-destruction/121706/?oref=d-topstory
I also randomly chose this article and ran the same test w/ the same result:
http://www.cnn.com/2015/09/23/africa/nigeria-troops-free-boko-haram-hostages/index.html

Both of these were done and recorded w/ Saucelabs running on pristine VMs.
Both exhibit the same behavior.

I'm going to argue here that almost everybody who is using either Via or the extension, on either Mac or Windows, and either Chrome or Firefox is seeing a situation on almost any website when they make an annotation, that that annotation immediately disappears from view.

The Saucelabs credentials are in passpack.

I think this is a P2.

**Comment by robertknight** [comment]
I had this happen twice to me yesterday whilst using the bookmarklet in Firefox creating page notes.

**Comment by seanh** [comment]
I can reproduce this on master - just create any new annotation and it disappears, seems like

**Comment by seanh** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;dKckOo63&#x2F;103-saved-annotation-disappears"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> #2525 Saved annotation disappears.</a>

**Comment by judell** [comment]
Repros for me at http://www.cnn.com/2015/09/23/africa/nigeria-troops-free-boko-haram-hostages/index.html. If it helps to track down the event flow, clicking the 1 that appears in the bucket bar after creating the annotation makes it appear.

**Comment by seanh** [comment]
I hope that https://github.com/hypothesis/h/issues/2542 fixes this

**Comment by judell** [comment]
> Fixes #2525.
> Fixes #2541.

A twofer! That'd be nice!
