### ISSUE TITLE
Hypothesis fights with Medium (Chrome/Windows)

### ISSUE THREAD

**Issue by judell** [hypothesis/h#2528]
URL: https://medium.com/@joshelman/four-questions-to-understanding-adoption-8fc499910e8a (note: same URL is subject of https://github.com/hypothesis/via/issues/48)

H mode: extension or Via

Before clicking H annotation:

![image](https://cloud.githubusercontent.com/assets/46509/10033058/d790d7be-613b-11e5-9d8d-b7a3f4b8018c.png)

After clicking H annotation:

![image](https://cloud.githubusercontent.com/assets/46509/10033071/f156c64a-613b-11e5-81f8-ceba48b3cc17.png)

Not a problem in FF.

**Comment by judell** [comment]
In this example, the H target is "I like to look for bouncebacks" and when clicked the sidebar does not open to display that annotation, instead the highlight jumps to Medium's "you have to talk to actual users"

**Comment by dwhly** [comment]
> the H target is "I like to look for bouncebacks" and when clicked the sidebar does not open to display that annotation, instead the highlight jumps to Medium's "you have to talk to actual users"

That does not happen for me.  Annotation behaves normally.  Chrome (Mac).

**Comment by judell** [comment]
i have it in Chrome/Win on 2 different machines so it's officially a thing.

**Comment by dwhly** [comment]
Not happening in FF (Mac) thru via

**Comment by judell** [comment]
Does not reproduce now.
