### ISSUE TITLE
"We can't find the exact position..." message shows on replies

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/h#2538]
The "we can't show the exact position of this annotation" message renders on all replies. The visual effect is quite pleasing, but I don't believe it's exactly what was intended.

![screen shot 2015-09-23 at 20 00 36](https://cloud.githubusercontent.com/assets/3602/10053700/cec77974-622d-11e5-815b-558e32bc61c5.png)

**Comment by judell** [comment]
"Message not available" /and/ "We can't find.." : a double bonus!

Replies don't have targets, so just suppress the message in that case?

**Comment by nickstenning** [comment]
> "Message not available"

Just so no-one is confused by this, that's me testing something else on my dev instance and is unrelated to this problem!

**Comment by seanh** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;dKckOo63&#x2F;103-saved-annotation-disappears"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> #2525 Saved annotation disappears.</a>

**Comment by nickstenning** [comment]
Fixed by 44edb50b18f5cd1a78aae32384551c74e6c19304.
