### ISSUE TITLE
Features fetcher busy-polls ajax requests when the connection fails

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/h#2547]
## Steps to reproduce

1. Open a page with the sidebar active (e.g. the development homepage)
2. Stop the development server
3. Wait for `CACHE_TTL` from `h/static/scripts/features.js` (5m by default)

## What should happen

The features fetcher should exponentially back off on trying to fetch the new features data.

## What does happen

It makes a request every time the digest cycle happens.

**Comment by robertknight** [comment]
Was just about to file this, discovered it keeping my fan busy yesterday.
