### ISSUE TITLE
"Selection" broken in v0.7.4

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/h#2553]
It seems that something in v0.7.4 (possibly earlier, I haven't checked) broke the ability to "select" one or more annotations by clicking on the "bucket bar" or on highlights.

## Steps to reproduce

1. Go to a page with many annotations, such as [this one](https://hypothes.is/blog/annotating-ocred-pdfs/).
2. Click on a highlight, or on a bucket bar arrow.

## Expected result

The sidebar narrows focus on just the "selected" annotations.

## Actual result

All annotations remain visible, even though the "Clear selection" text at the top of the sidebar appears.

**Comment by robertknight** [comment]
The logic to check whether a thread should be shown was altered in 44edb50b18f5cd1a78aae32384551c74e6c19304 to remove the check of whether the annotation is in the selected set or not. Based on the commit message, that looks like a mistake to me.
