### ISSUE TITLE
Safari doesn't display links to the original article in annotations

### ISSUE THREAD

**Issue by lenazun** [hypothesis/h#2568]
When visiting a stream of annotations or a single annotation in Safari 8.0, the link to the original article is not displayed.  See for example:

<img width="719" alt="nolinks" src="https://cloud.githubusercontent.com/assets/6117168/10222693/9ee0d7e0-6855-11e5-9788-8d55e43e18be.png">

vs Chrome

<img width="688" alt="links" src="https://cloud.githubusercontent.com/assets/6117168/10222698/a8c8315e-6855-11e5-8e6a-992f19db41c8.png">

**Comment by robertknight** [comment]
I can reproduce as a logged-out user under Safari 8 but not Safari 9.

The issue is that `String.prototype.startsWith()` does not exist under Safari 8. Errors in JS console: `Error: undefined is not a function (evaluating 'uri.startsWith("http://")')`

**Comment by robertknight** [comment]
According to https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith this method was supported only very recently in Chrome, it isn't even listed as supported in Safari there.
