### ISSUE TITLE
Broken URL references in production mode CSS

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#2571]
URL rebasing is disabled when merging and minifying CSS files for production, so the relative URLs in `styles/vendor/icomoon.css` and `styles/vendor/katex.css` are not correctly rewritten when they are 
concatenated into `styles.hypothesis.min.css` and `styles/app.min.css`.

The fonts in icomoon.css happen to work because the TTF version is inlined into the file as a data URL.

This should be fixed as part of moving the asset building pipeline out of Python.

**Comment by nickstenning** [comment]
I'm pretty sure this was fixed by #3209. Feel free to reopen if not.
