### ISSUE TITLE
Long URLs can overflow annotation text container

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#2575]
[This annotation](https://hypothes.is/a/A4iXqwpMTYG8Rf2S-3pwnQ) with a very long Google Books URL in it overflows the annotation text container in the sidebar in Chrome 47, but not Firefox 44.

See https://css-tricks.com/snippets/css/prevent-long-urls-from-breaking-out-of-container/ for a discussion of possible fixes.

**Comment by nickstenning** [comment]
We appear to correctly wrap long URLs now. Closing.
