### ISSUE TITLE
Source files failing to load in Firefox Dev Tools

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#2580]
Debugging development builds of H using the Firefox Dev Tools is annoying because the contents of many source files fail to load due to an issue related to https://github.com/thlorenz/inline-source-map/pull/15

**Steps to reproduce**

1. Setup a development build of H and run `make dev`
2. Open `http://localhost:5000` in Firefox, open dev tools, switch to the Debugger tab and try to view the contents of a CoffeeScript source file.

**Expected**

Source file contents appears in debugger

**Actual**

Error message reporting that Firefox failed to load the source file.

**Comment by tilgovi** [comment]
That should already be fixed in deeloper editino, I thought.

**Comment by robertknight** [comment]
There were related fixes in the current developer edition but it is broken for me in a current FF Nightly. My fix for the bug in `inline-source-map` has been merged so I should be able to close this issue soon, but there is still something wrong in FF itself as a single null entry in the `sourcesContent` array for a sourcemap changes URL resolution for all files.

**Comment by robertknight** [comment]
The fix for `inline-source-map` has been published. Currently waiting on https://github.com/substack/browser-pack/pull/67

**Comment by nickstenning** [comment]
I'm going to propose we close this. There's limited justification for expending effort if we're in the process of removing CoffeeScript from our codebase. What you think, @robertknight? I'll leave it up to you.

**Comment by nickstenning** [comment]
Closing as proposed in my previous comment.
