### ISSUE TITLE
Customized Embedding Trouble

### ISSUE THREAD

**Issue by BigBlueHat** [hypothesis/h#2584]
@JakeHartnell and I are working on fixing the epub.js Hypothes.is integration. The new customized embedding setup looks like it will/would work just fine, but for a couple things:
1. it's not possible to (easily) extend the default `Annotator.Sidebar` because it's not global...nor include-able afaict (without building an entirely custom `h` installation).
2. `embed.js` can't be used as a foundation for this customization as it is itself a custom setup--and not a foundation for extension.

What I (and I believe Jake) would like next is the ability to include something like `embed.js` + the ability to extend / overwrite parts of `Annotator.Sidebar`--as described here:
https://h.readthedocs.org/en/latest/hacking/customized-embedding.html

It seems it should be possible from inside a custom `h` installation, but "as a developer" I'm wanting to do this with the Hypothes.is public service attached via my CMS code, etc.

@judell might want to mix this in priorities somewhere or other. :smiley:

**Comment by tilgovi** [comment]
As I said [here](https://github.com/hypothesis/h/pull/2494#issuecomment-146343242) it's very easy to extend the default.

```js
window.hypothesisConfig = function() {
   function MySidebar(elem, options) {
       Annotator.Sidebar.call(this, elem, options);
   }
   MySidebar.prototype = Object.create(Annotator.Sidebar.prototype);

  return {
    constructor: MySidebar,
    ...
  }
};
```

And so embed.js can absolutely be used in this way.

**Comment by tilgovi** [comment]
And the solution is easy and also described in that comment. Just move the whole `hypothesisConfig` nonsense into embed.js along with the default options and the invocation inside `Annotator.noConflict().$.noConflict(true)`. Then have `h/static/scripts/annotator/main.js` just export `Annotator` and _if_ people really want to dodge all the polyfills, `hypothesisConfig`, etc and just get access to `Annotator` directly but still use live, production Hypothesis code they can include https://hypothes.is/assets/scripts/hypothesis.min.js in their code.

**Comment by BigBlueHat** [comment]
So. Here's what I'm attempting:
http://hypothesis.github.io/customized-embedding-example/

There's a separate `embed.js` file--removes `blocklist.js`, leaves polyfills, adds `hypothesisConfig`, and attempts to create a `MySidebar` (as above).

`window.Annotator` is not currently exported--assuming the check in `embed.js` is simply to make sure we're not overwriting an existing [Annotator](http://annotatorjs.org/)?

So, if I'm following this :train: of :thought_balloon: we need to:
 - [] export Annotator
 - [] (optionally) make the primary `h` `embed.js` use `hypotheisConfig` / this method also (making it easier/clearer for folks customizing)

@tilgovi sound right(ish)? :smiley:

**Comment by tilgovi** [comment]
That's almost right. The `hypothesisConfig` function is called before the `Annotator.noConflict()`, but the constructor itself is called later, in a dom ready callback.

Change it to this and it will work:

```js
window.hypothesisConfig = function () {
  var Annotator = window.Annotator;  // <--- get it here!!!
  function MySidebar() { ...}
  // ... as before ...
}

**Comment by tilgovi** [comment]
But, if you move the `noConflict` and ready callbacks, and everything else to do with `hypothesisConfig` into the embed code itself, that might be better. Then including `hypothesis.min.js` would simply leave `Annotator` around as a global, which is much easier to work with if you control your environment.

**Comment by judell** [comment]
Was this resolved?

**Comment by JakeHartnell** [comment]
Yep.
