### ISSUE TITLE
link autoactivation turns _ into <em>

### ISSUE THREAD

**Issue by judell** [hypothesis/h#2598]
### Steps to reproduce:

1. Create an annotation
2. Paste a URL into the annotation body which contains underscores, such as `https://hypothes.is/stream?q=tag:group_test_needs_card`
3. Save and view

### Expected result:

An unmodified URL in the annotation card, e.g.:

> https://hypothes.is/stream?q=tag:group_test_needs_card

### Actual result:

The underscores in the URL get turned into emphasis tags, e.g.:

> https://hypothes.is/stream?q=tag:group%3Cem%3Etest%3C/em%3Eneeds%3Cem%3Ecard

**Comment by nickstenning** [comment]
I've updated the body of this issue to make it clearer what the problem is.
