### ISSUE TITLE
Embedding not working

### ISSUE THREAD

**Issue by kewal07** [hypothesis/h#2599]
<script async defer src="//hypothes.is/embed.js"></script>
Added the above script tag to web site's HTML to load the Hypothes.is sidebar on  site.

The web page is currently hosted on GitHub @ http://kewal07.github.io/eReader/

**Comment by robertknight** [comment]
Can you clarify that the problem you see is the same as the one I see:

I do see the sidebar when open that URL in Firefox and Chrome. Pressing the 'Next' button at the bottom of the page a few times to go to a page with text and then making a selection does not show the annotation tools however, so it is not possible to create annotations.

I see no errors in the console. Tested both HTTP and HTTPS variants of the site.

**Comment by kewal07** [comment]
Yes. Same as yours. Not able to create annotations. Sorry, should have mentioned in details.If there is anything i can do to help, i would love to do. Also, would like to work on a better integration of hypothes.is with epub.js

**Comment by robertknight** [comment]
cc @JakeHartnell

**Comment by robertknight** [comment]
There has been work going on with H and epub.js integration. I don't know the details myself but I'll poke someone who does.

**Comment by kewal07** [comment]
Thanks. That would be great. I would be happy to help

**Comment by JakeHartnell** [comment]
Thanks @robertknight!

@kewal07, I see you are using epub.js. Epub.js renders books in an iframe, and thus the embed code won't work straight out of the box like you are trying. This is not a problem with the embed code however so I'm closing this issue.

There is an example here: https://github.com/futurepress/epub.js/blob/master/examples/hypothesis.html

Take note of the scripts it uses, namely: 
```
        <!-- Hypothesis -->
        <script src="../hooks/extensions/hypothesis.js"></script>
        <script src="../reader_src/plugins/hypothesis.js"></script>
```

The hook loads a guest annotator in the iframe, which the host in the parent frame listens to. Have a look at the plugin too (some more integration work is done here).

There is more work to be done here on the Hypothes.is side of things, but we're starting on that next week. In the meantime the example should give you something to play with. If you want to help out I would suggest tackling some of this issues labeled "new contributor friendly" in the Hypothesis repo, alternately epub.js has a number of open issues as well.
