### ISSUE TITLE
Creating a blank annotation returns nonsense permissions field

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/h#2614]
### Steps to reproduce

1. Get an API token
2. `curl -X POST -H 'Authorization: Bearer <token>' https://hypothesi.s/api/annotations -d '{}'`

### Expected response

An annotation is created with sensible default permissions.

### Actual response

```json
{
  "updated": "2015-10-13T16:02:48.296561+00:00",
  "group": "__world__",
  "user": "acct:nss@localhost",
  "created": "2015-10-13T16:02:48.296540+00:00",
  "id": "AVBh8JaRB4aftTDlu83O",
  "permissions": {
    "read": [
      "group:__consumer__"
    ]
  }
}
```

The default permissions field is `{"read": ["group:__consumer__"]}` which means absolutely nothing to either the Hypothesis web application or the Hypothesis client. This comes from [this behaviour of `annotator-store`](https://github.com/openannotation/annotator-store/blob/45267b04047210d26ab39b40570e3dd28179a49d/annotator/annotation.py#L144).

**Comment by tilgovi** [comment]
That's a bug in annotator-store, I would say. It shouldn't be doing that if authorization isn't enabled.

**Comment by nickstenning** [comment]
This has been fixed in recent versions of the code.
