### ISSUE TITLE
Very long Via load time for nytimes.com page

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#2630]
**Steps to reproduce**

1. On a non-superfast connection (I'm using 3G in Central London, which is still pretty fast by most standards) go to https://via.hypothes.is/http://www.nytimes.com/2015/10/18/opinion/sunday/lecture-me-really.html?smid=fb-nytopinion&smtyp=cur&_r=1
2. Wait. Then wait some more. and more.
3. Repeat steps (1) and (2) for http://www.nytimes.com/2015/10/18/opinion/sunday/lecture-me-really.html?smid=fb-nytopinion&smtyp=cur&_r=2

**Observed issue**

Page load times are much worse when loading that page via Via than via the extension or the bookmarklet

**Comment by robertknight** [comment]
See https://github.com/hypothesis/via/issues/57

**Comment by robertknight** [comment]
For contrast, here is a prototype service I created which uses much lighter page modification: http://via.robertknight.me.uk/http://www.nytimes.com/2015/10/18/opinion/sunday/lecture-me-really.html?smid=fb-nytopinion&smtyp=cur&_r=3

**Comment by judell** [comment]
Thanks! Is it worth trying a benchmark comparison?

**Comment by nickstenning** [comment]
Closing this in favour of hypothesis/via#57.
