### ISSUE TITLE
Phantom appears briefly when switching selected annotations.

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#2637]
Go here, enable show annotations, and click a highlighted annotation:
http://quod.lib.umich.edu/d/dh/13474172.0001.001/1:3/--ethical-programs-hospitality-and-the-rhetorics-of-software?g=dculture;rgn=div1;view=fulltext;xc=1

Then click another one.

Here's a video to reproduce.
https://drive.google.com/file/d/0B0yW-dSdEYAcMEtHMTA0elpxclE/view

**Comment by judell** [comment]
Does it repro in the stage extension? (Doesn't for me.)

**Comment by dwhly** [comment]
How do you successfully use the stage extension on a site that has H. embedded. (Feeling like this might be a really stupid question).

**Comment by judell** [comment]
It's one of those even-worse-than-it-appears things, evidently. The interactions between embed and extension are gnarly. On Friday, for example, I discovered that sticky settings (like group focus) are remembered differently as between embed and extension.

In this case, though, I don't see your symptom either way (i.e. with or without extension active).

**Comment by dwhly** [comment]
The behavior that *I filmed* in the video above, I can no longer personally reproduce.  Closing this until I can.
