### ISSUE TITLE
Broken UI, lost work, when creating a new group while creating or editing an annotation

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#2641]
1. Begin creating a new annotation, don't save it
2. Create a new group (opens in new tab)
3. Return to first tab, which refreshes with the new group

Result: UI goes a bit broken, typed annotation text is lost

![untitled screencast 5](https://cloud.githubusercontent.com/assets/22498/10609014/8869fa9e-7739-11e5-90fb-d94d527dffa4.gif)

**Comment by robertknight** [comment]
Current status: The UI broken-ness appears to have been fixed by the Angular 1.2.x -> Angular 1.4.x upgrade.

The issue with the annotation text being lost persists. Switching groups currently results in a route-reload which loses any unsaved changes to annotations.
