### ISSUE TITLE
Bucket bar annotation location indicators disappearing under toolbar buttons

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#2646]
Recent design changes to the sidebar's toolbar increased the height of the toolbar icons at the top. The top-most position of the annotation location indicators needs to be moved down, otherwise they currently get partially hidden underneath the toolbar icons.

![bucket-bar-markers-too-high](https://cloud.githubusercontent.com/assets/2458/10632766/40efcc5c-77de-11e5-8743-00066653b23a.png)

**Comment by tilgovi** [comment]
https://github.com/hypothesis/h/blob/master/h/static/scripts/annotator/plugin/bucket-bar.coffee#L11
