### ISSUE TITLE
Single Sign On using Parse.com

### ISSUE THREAD

**Issue by kewal07** [hypothesis/h#2649]
Is it possible to have something like a Disqus SSOm, wherein once i am signed in in my Parse application (Javascript only) then i automatically get signed on to hypothes.is

**Comment by robertknight** [comment]
@kewal07 My understanding is that we don't have any form of single-sign on support at the moment but it is an important task on our roadmap.

**Comment by tilgovi** [comment]
This is hypothesis/vision#118

**Comment by judell** [comment]
Closed in favor of hypothesis/vision#118.
