### ISSUE TITLE
Group dropdown item shifts left when invite link clicked

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/h#2653]
Safari 9.0 on Mac OS X 10.11

![](https://camo.githubusercontent.com/34107213027308c6a9de3eec77ae4b6793086cc2/68747470733a2f2f64317a6a637571666c6264356b2e636c6f756466726f6e742e6e65742f66696c65732f6163635f3337313637302f316955656a3f726573706f6e73652d636f6e74656e742d646973706f736974696f6e3d696e6c696e653b25323066696c656e616d653d53637265656e253230436170747572652532306f6e253230323031352d31302d3231253230617425323031392d35342d31382e67696626457870697265733d31343435343530343539265369676e61747572653d4f2537452d486f584c35626f72746f4c7359775038723331587a455075624d5068354a4834454e37754a63476c736d446b6359526c32626c2537456f456b707950557a334c4f3734784c316766545148304a62327a387a5561417a444c4576597567546d586570684d6a48773257776e41565478455031734a6148346a654231363731536c756f58474235596352774b5254592d6a5059324172443436316861726d5667375065455069366631684d5f264b65792d506169722d49643d41504b414a5445494f4a4d334c534d4e33335341)

**Comment by seanh** [comment]
This doesn't happen to me in Firefox or Chrome, so maybe a Safari issue

**Comment by nickstenning** [comment]
Closing as the relevant piece of UI no longer exists!
