### ISSUE TITLE
Clicking on search icon in new "top bar" does nothing

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/h#2654]
In Safari 9.0 on Mac OS X 10.11, clicking on the magnifying glass in the top bar,

![image](https://cloud.githubusercontent.com/assets/3602/10645668/3ece7c56-782f-11e5-9a9e-72bbcd47e0c2.png)

doesn't do anything. No errors logged to the console.

**Comment by robertknight** [comment]
The expansion of the search bar is done by a change in the `max-width` property when the search field is focused. Clicking on the search button should focus the search field. This is apparently not working in Safari 9 however. Manually toggling the focus state does result in the search field expanding.

**Comment by robertknight** [comment]
So it appears that in Safari, calling `.focus()` on an `<input>` with a `max-width` of 0 has no effect. Set the minimum `max-width` to 1px and the expander works.
