### ISSUE TITLE
annotations missing on local pdf

### ISSUE THREAD

**Issue by judell** [hypothesis/h#2665]
I have a local PDF with fingerprint urn:x-pdf:1e7abf0caa68296539339c7c5335dd58 

There are 20 annotations in the db: https://hypothes.is/api/search?uri=urn:x-pdf:1e7abf0caa68296539339c7c5335dd58 -> 20. 

I drag a local copy, file:///C:/Users/jon/Downloads/patent.pdf, into the extension. None of those 20 anchor. I annotate to create a 21st:

           "document": {
                "link": [
                    {
                        "href": "urn:x-pdf:1e7abf0caa68296539339c7c5335dd58"
                    },
                    {
                        "href": "file:///C:/Users/jon/Downloads/patent.pdf"
                    }
                ],
                "title": "patw11_99.PDF"
            },
 
I refresh. No annotations anchor. The client query at this point:

https://stage.hypothes.is/api/search?group=__world__&limit=200&offset=0&order=asc&sort=created&uri=file:%2F%2F%2FC:%2FUsers%2Fjon%2FDownloads%2Fpatent.pdf -> 0

Annotations do anchor to http://www.researchoninnovation.org/patent.pdf. However, only 20 do. The client query in that case:

https://stage.hypothes.is/api/search?group=__world__&limit=200&offset=0&order=asc&sort=created&uri=http:%2F%2Fwww.researchoninnovation.org%2Fpatent.pdf ->  20

vs.

https://hypothes.is/api/search?uri=urn:x-pdf:1e7abf0caa68296539339c7c5335dd58 -> 21

**Comment by judell** [comment]
Resolved by disabling the API caching the CloudFlare was (unexpectedly) doing.

**Comment by judell** [comment]
Resolved by disabling the API caching the CloudFlare was (unexpectedly) doing.

**Comment by tilgovi** [comment]
Can you expand on that a bit, @judell? You forced the cache somehow? Or ops disabled CloudFlare caching? Is there an issue open to send maybe different cache control headers for the affected API endpoints?

It's not clear from what's written here that anything was really resolved.

**Comment by tilgovi** [comment]
Never mind, I found it myself. There is a PR at #2661.
