### ISSUE TITLE
Input lag when typing in annotation editor on pages with many annotations

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#2666]
On pages with many (and I don't mean _that_ many - even 50-60) annotations, typing in the annotation editor is painfully laggy.

The reason for this is that every keystroke results in a call to `$timeout` which in turn triggers an Angular `$digest` cycle on the root scope. This runs every single watch function - in the stream on my dev environment, showing the default number of annotations that appears on first load of the stream, that is about ~1700. I believe this delay will just scale linearly as the number of annotations displayed increases.

The original change that added the `$timeout` call was in 1816527accb6a55789788d09c3b17d7760662374 . It looks like it wasn't really understood what was going on there so I think we can remove this, test and re-evaluate.

We can fix this particular call as a short-term measure but it will be very easy to inadvertently introduce new things in future that trigger every watcher in the app. Really we need to think about re-architecting things in a way that isn't susceptible to these problems.

**Comment by robertknight** [comment]
Couple of related discussions going on about limiting which scope watches are evaluated during a `$digest` cycle:

https://github.com/angular/angular.js/issues/10904 [asking for equivalent of React's `shouldComponentUpdate()`]
https://github.com/angular/angular.js/pull/10658 [PR to allow suspending and resuming of watchers]

**Comment by judell** [comment]
Any update on this?

**Comment by nickstenning** [comment]
My understanding is that this is closed by #3213. Feel free to reopen if that's inaccurate.

**Comment by robertknight** [comment]
#3213 improves the situation enough to consider it fixed.
