### ISSUE TITLE
Groups list does not always update correctly when joining and leaving groups

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#2671]
**Steps to reproduce**

1. With a groups-enabled account, open a tab with H
2. From one of the tabs, use the groups dropdown to create or leave a group
3. Repeat step (2) a few times

Extended version: Use several tabs with H instead of just one

**Expected result**

All tabs show a consistent and correct groups list

**Actual result**

The groups list does not always update properly when joining and leaving groups.

**Comment by seanh** [comment]
This looks good to me, I did a lot of leaving and joining groups with the sidebar open in multiple tabs, I found one issue: <https://github.com/hypothesis/h/issues/2677> which I don't think should block launching groups
