### ISSUE TITLE
Leaving a non-focused group changes the focused group to Public

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#2677]
This looks good to me, I did a lot of leaving and joining groups with the sidebar open in multiple tabs, I found one issue:

1. Focus a group other than the public group
2. Leave another group, not the one you had focused
3. The focused group changes to the public group

Expected: the group that you had focused should remain focused.

**Comment by robertknight** [comment]
This should be fixed by https://github.com/hypothesis/h/pull/2674
