### ISSUE TITLE
Enable highlights by default for embedded H

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#2695]
**Update: Decision here is that we should enable highlights by default for embedded H, but keep the config option to disable it. _The homepage documentation will need to be updated accordingly_**

Hypothesis is embedded in our documentation at `h.readthedocs.org` but highlights are off by default, which means that useful comments for newcomers will likely go unnoticed.

We should turn them on by default.

That also raises the question of perhaps whether the default setting should be to have highlights enabled by default and require them to be turned _off_ if users don't want that. There might already have been a long discussion on that subject that I wasn't party to. @judell ?

**Comment by dwhly** [comment]
I had proposed just this very thing to @jakehartnell for the WordPress plugin.  Makes sense to me.

**Comment by tilgovi** [comment]
I've long argued for having no option to enable/disable highlights in the UI at all. To me, it has always been a UX smell if the user a) wants annotation on but b) finds it intrusive. That's probably unfair in the publisher case, because users may disagree with the publisher about wanting annotation at all, but for the extension it never made sense to me that one would want the sidebar enabled but not want highlights.

**Comment by judell** [comment]
Yes please, I'd like them on by default in this case.

Note that we also recently added this explanation to our homepage embed
instructions:

[image: Inline image 1]

**Comment by robertknight** [comment]
@judell - One option I could take would be to turn highlights on _by default_ in the embed and require users who explicitly don't want to see them to turn them off via a config option.

So two questions:

1. Does anyone oppose a change to enable highlights by default?
2. If done in the simplest way, this would affect many sites that already have H embedded. We could probably find a way to avoid making the change for existing sites with H if that is desired. Should we?

**Comment by dwhly** [comment]
> We could probably find a way to avoid making the change for existing sites with H if that is desired. Should we?

My understanding of the partners currently implementing it is that this wouldn't be a problem.  If there are complaints, we can show them quickly how to turn it off.  What's important to me is that there *is* a config to disable the highlights.  

Agree w/ all here that on by default is the right thing.

**Comment by judell** [comment]
Yes. Highlights on is the reasonable default. And arguably the number of
people wanting to override that will be small enough that we can push the
explanation to documentation and remove the clutter we just added to the
home page.
