### ISSUE TITLE
"n replies" text displayed right next to annotation date on collapsed reply

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/h#2702]
A small visual bug -- if you collapse a reply with replies of its own you get this:

<img width="420" alt="screen shot 2015-10-30 at 18 52 55" src="https://cloud.githubusercontent.com/assets/3602/10855101/ae71566e-7f37-11e5-9ce6-10adcfb76815.png">

**Comment by seanh** [comment]
Having a look

**Comment by seanh** [comment]
How this used to look:

![screenshot from 2015-11-02 12-23-57](https://cloud.githubusercontent.com/assets/22498/10881667/aadd9612-815c-11e5-8247-18853fbacd5e.png)
