### ISSUE TITLE
annotations awol for http://www.cnn.com/2015/05/05/opinions/sutter-sea-level-climate

### ISSUE THREAD

**Issue by judell** [hypothesis/h#2711]
Expect: 16 annotations rendered in the H client

Actual: None.

Results for various queries:

*badge*:

http://www.cnn.com/2015/05/05/opinions/sutter-sea-level-climate/ -> 16
http://www.cnn.com/2015/05/05/opinions/sutter-sea-level-climate  ->  1

*api*:

https://hypothes.is/api/search?uri=http%3A%2F%2Fwww.cnn.com%2F2015%2F05%2F05%2Fopinions%2Fsutter-sea-level-climate%2F -> 16

https://hypothes.is/api/search?uri=http%3A%2F%2Fwww.cnn.com%2F2015%2F05%2F05%2Fopinions%2Fsutter-sea-level-climate -> 1

*client*:

https://hypothes.is/api/search?group=__world__&limit=200&offset=0&order=asc&sort=created&uri=http%3A%2F%2Fwww.cnn.com%2F2015%2F05%2F05%2Fopinions%2Fsutter-sea-level-climate%2Findex.html -> 0

https://hypothes.is/api/search?group=__world__&limit=200&offset=0&order=asc&sort=created&uri=http%3A%2F%2Fwww.cnn.com%2F2015%2F05%2F05%2Fopinions%2Fsutter-sea-level-climate%2Findex.html -> 0

Two questions:

1. Why does the client ask for /index.html?

2. Why does the API treat the trailing-backslash case differently?

**Comment by nickstenning** [comment]
1. Because the page contains `<link rel="canonical" href="http://www.cnn.com/2015/05/05/opinions/sutter-sea-level-climate/index.html">`.

2. This was fixed by recent URI normalisation work. Both API queries above return 15 results now.

Closing.
