### ISSUE TITLE
Raven is not configured (logging is disabled)

### ISSUE THREAD

**Issue by corti** [hypothesis/h#2722]
Hello, when I run docker build -t hypothesis/h .
I get this error (indeed the login into hypothes.is triggers the same error thereafter).
Step 18 : RUN hypothesis assets conf/production.ini
 ---> Running in 3ba23b82f5ae
Raven is not configured (logging is disabled). Please see the documentation for more information.
 ---> 42f368fbab65
Removing intermediate container 3ba23b82f5ae

**Comment by nickstenning** [comment]
This is an ignorable warning.
