### ISSUE TITLE
Annotator.Util undefined on pages that define a variable called `global`

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#2723]
**See https://github.com/hypothesis/h/issues/2397#issuecomment-126376613 for a minimal repro case of this issue**

Launching H via the extension or bookmarklet fails on http://www.thebookseller.com/futurebook/publishing-has-entered-new-and-different-era with a 'cannot read `Util` of undefined` error or variation on that.

```js
        var Annotator = require("annotator");
        var g = Annotator.Util.getGlobal(); // 'Annotator' is undefined here
```

I'm sure I investigated something similar before that was related to a site defining its own version of 'global' or something similar.

**Comment by robertknight** [comment]
This might be the same issue as https://github.com/hypothesis/h/issues/2397

**Comment by robertknight** [comment]
Update - yes, this is indeed the issue described in #2397 - the page defines a variable called `global` which breaks browserify-shim

**Comment by judell** [comment]
Closed in favor of #2397.

**Comment by robertknight** [comment]
@judell - That other issue was closed. This is a more generic issue which supersedes that one. I'm afraid my comment didn't make that clear.

**Comment by dwhly** [comment]
I've created a trello card for this: https://trello.com/c/c4iARNt9/538-bug-annotator-util-undefined-on-pages-that-define-a-variable-called-global
