### ISSUE TITLE
Share link to a group?

### ISSUE THREAD

**Issue by orschiro** [hypothesis/h#2727]
Dear all, 

Is it possible to share a publicly accessible link to a group?

Thankfully,

~ Robert

**Comment by lenazun** [comment]
Hello Robert

When you create a group you get a link to invite others to join. 
However, we don't yet have a way to publicly share that URL without giving others the ability to join the group. 
Does that make sense?

Best, 
Lena

**Comment by orschiro** [comment]
Dear Lena, 

> However, we don't yet have a way to publicly share that URL without giving others the ability to join the group. 

I understand your comment. Thank you! 

Let's take [this](https://hypothes.is/groups/E1JY3VYR/sustainable-consumption) example group on the topic of "Sustainable Consumption".

I created this group to collaborate with a number of scholars to annotate resources that link back to this topic. 

Some of these scholars don't want to edit but just analyse the existing annotations. 

Thus it would be great if the annotations of a group could be shared with others without having them to open up an account. 

Does my comment make sense, too? :)

Warmly,

~ Robert

**Comment by orschiro** [comment]
Dear Lena, 

> However, we don't yet have a way to publicly share that URL without giving others the ability to join the group. 

I understand your comment. Thank you! 

Let's take [this](https://hypothes.is/groups/E1JY3VYR/sustainable-consumption) example group on the topic of "Sustainable Consumption".

I created this group to collaborate with a number of scholars to annotate resources that link back to this topic. 

Some of these scholars don't want to edit but just analyse the existing annotations. 

Thus it would be great if the annotations of a group could be shared with others without having them to open up an account. 

Does my comment make sense, too? :)

Warmly,

~ Robert

**Comment by orschiro** [comment]
Dear Lena, 

> However, we don't yet have a way to publicly share that URL without giving others the ability to join the group. 

I understand your comment. Thank you! 

Let's take [this](https://hypothes.is/groups/E1JY3VYR/sustainable-consumption) example group on the topic of "Sustainable Consumption".

I created this group to collaborate with a number of scholars to annotate resources that link back to this topic. 

Some of these scholars don't want to edit but just analyse the existing annotations. 

Thus it would be great if the annotations of a group could be shared with others without having them to open up an account. 

Does my comment make sense, too? :)

Warmly,

~ Robert

**Comment by orschiro** [comment]
Dear Lena, 

> However, we don't yet have a way to publicly share that URL without giving others the ability to join the group. 

I understand your comment. Thank you! 

Let's take [this](https://hypothes.is/groups/E1JY3VYR/sustainable-consumption) example group on the topic of "Sustainable Consumption".

I created this group to collaborate with a number of scholars to annotate resources that link back to this topic. 

Some of these scholars don't want to edit but just analyse the existing annotations. 

Thus it would be great if the annotations of a group could be shared with others without having them to open up an account. 

Does my comment make sense, too? :)

Warmly,

~ Robert

**Comment by lenazun** [comment]
Yes! That would be very useful. 
This behavior is already in the list for our next version of the groups functionality.  
Thank you for using the feature and providing us with feedback!

Lena

**Comment by orschiro** [comment]
Dear @lenazun,

That's great to hear. I thank you!

~ Robert
