### ISSUE TITLE
Refactor AnnotationController

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#2728]
Just preserving some thoughts that @nickstenning, @robertknight and I have discussed about how we might want to refactor `AnnotationController`. At the time of writing there seems to be consensus on this:

* Have separate `domainModel` and `viewModel` objects (these currently exist as `model` and `@annotation` but are not at all used consistently as domain and view model)

* `domainModel` is the annotation as received from the server. `AnnotationController` should never modify `domainModel`.

* `viewModel` is the changes that the user has made to the annotation, that haven't been saved to the server yet. This is the object that `AnnotationController` edits. `viewModel` doesn't need to be a complete copy of `domainModel` because it only needs to contain the fields that can be edited. It doesn't need to contain exact copies of those fields either - for example it can just have a shared true/false property instead of a permissions object.

* What gets saved to the `drafts` service should be the `viewModel`, not the `domainModel`.

* When the user clicks to save the annotation we'd make a new object (local variable) that is a copy of `domainModel` with the changes from `viewModel`, that gets sent to the annotation update API, which responds with the complete annotation, which then replaces `domainModel` in `AnnotationController`.

Other small things we discussed:

* Minimising when/where drafts is used, only where it needs to be, hopefully not in `render()`
* Possibly getting rid of `render()` entirely if we can
* Plenty of scope for general tidy up and simplification of code
* The tests for `AnnotationController` are a bit of a mess

**Comment by seanh** [comment]
https://trello.com/c/FZmMPYAH/190-refactor-annotationcontroller

**Comment by robertknight** [comment]
The tests still need refactoring but I think we can say that the bulk of this has been done.
