### ISSUE TITLE
Equation viewer in document conflicts with H selection

### ISSUE THREAD

**Issue by judell** [hypothesis/h#2730]
URL: https://peerj.github.io/paper-now/

Expect: Click highlighted equation, pop sidebar to view annotation

Actual: Equation viewer pops up

![image](https://cloud.githubusercontent.com/assets/46509/11286114/03c3e84e-8ec8-11e5-9650-61fbfd31e799.png)

**Comment by nickstenning** [comment]
I'm not really sure there's anything we can do about this, either now or in the future. If a page responds to selections/click/mouseover events in a way that fundamentally conflicts with Hypothesis, there are only two options, as I see it:

1. We disable or override the page functionality. This could be seen as a bug in Hypothesis.
2. The page functionality disables or overrides Hypothesis. This could be seen as a bug in Hypothesis.

I'm going to close this as "won't fix."
