### ISSUE TITLE
"Session is invalid" error when trying to login when Privacy Badger is installed

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/h#2742]
Via our support email address, a user reports:

> I can log in at hypothes.is, but not through the bookmarklet ("Session is invalid. Please try again.")
> 
> Here are the details for today's failed connection attempt.
> 
> **Site**: http://worrydream.com/ClimateChange/
> **Browser**: Firefox 42.0
> **Bookmarklet**: `javascript:(function(){window.hypothesisConfig=function(){return{showHighlights:true};};var%20d=document,s=d.createElement('script');s.setAttribute('src','https://hypothes.is/app/embed.js');d.body.appendChild(s)})();`
> **Hypothes.is account**: XXXXXX (_check support@ if you need the details_)
> 
> I can log in directly to hypothes.is, so my password is correct and my account is working.
> 
> I do have a couple of Firefox extensions that could cause problems (Privacy Badger, Ghostery), but they haven't changed for a while and sometimes everything works fine.

We've been receiving intermittent reports of weirdness like this. It would be good to track this down once and for all.

**Comment by Aonrud** [comment]
Hi - I found this searching for the same issue.

Of the settings and extensions I have in Firefox, I found I had to turn on 3rd party cookies (at least 'from visited'), and also to manually permit Hypothes.is cookies in Privacy Badger (which I assume thinks it must be a tracking cookie when it's being loaded on lots of domains).

I'd rather not have to re-configure privacy etc. for this, but without an extension I presume there's no avoiding the need for a session cookie, so no working around it.

**Comment by robertknight** [comment]
@Aonrud - We are planning to re-work the way authentication in the client works in future to alleviate the need for 3rd-party cookies. @nickstenning tells me this causes problems in Safari . As for session cookies, I think that need might also go away in future.

**Comment by robertknight** [comment]
https://hypothesis.zendesk.com/inbox/tickets/23

**Comment by chdorner** [comment]
I just tested this now with Firefox Beta (48.0) and Privacy Badger (1.7.0) installed and it seems to be working now. We didn't change anything in terms of client authentication as far as I'm aware, so I'm not quite sure why this works now.

**Comment by katrinleinweber** [comment]
In Chrome 53.0.2785.116 with PrivacyBadger 2016.9.7, this issue occurs as well. Even when already being logged into [hypothes.is](https://hypothes.is/) by Chrome. Switching PB off "enables" the login again.

**Comment by robertknight** [comment]
@katrinleinweber - Thanks for confirming. The Hypothesis client currently uses cookies for authentication, which unfortunately means that from PB's point of view, it functions exactly like an advert using cookies to follow the user around the web. We are planning to change the authentication mechanism in future to avoid this.

**Comment by chepec** [comment]
I can confirm this issue still occurs in Firefox 49.0.2 with PrivacyBadger 1.8.1. Just enabling the domain `hypothes.is` in PB was enough to make login from the sidebar work again (there was no need to disable the PB addon).

I was trying hypothes.is in Firefox for the first time and found this issue just when I was about to give up :-) Thanks for filing it and here's hoping the solution as well as a proper Firefox addon lies in hypothes.is future.

**Comment by pchampin** [comment]
I had the same problem, and disabling PrivacyBadger did not solve it.

My problem came from the fact that I was refusing 3rd party cookies. Adding https://hypothes.is/ in the exception list ("Allow") did solve the problem.

**Comment by robertknight** [comment]
Hypothesis (as of v1.39) now detects when the browser is preventing it from storing cookies and falls back to using OAuth rather than cookies for authentication in this context. You may find that you need to click the "Log in" button each time the client loads, but as long as you are signed in to the website you won't have to re-enter your login details each time.
