### ISSUE TITLE
Got mail form hypothesis that my email client classified as scam

### ISSUE THREAD

**Issue by scharf** [hypothesis/h#2765]
Today I got an email form hypothes.is but my mail client (thunderbird) classified it as scam:

![scam](https://cloud.githubusercontent.com/assets/3731059/11590891/e32f3cbe-9a93-11e5-8e50-9aefd8799726.jpg)

**Comment by lenazun** [comment]
Hello! Thank you for reporting.

From Mozilla support:
https://support.mozilla.org/en-US/questions/1010048

"Thunderbird has a rather simplistic scam detection system. If it sees links to "other" sites in an email message it reports it as a possible scam. This affects many legitimate mails that quite reasonably offer links to other sites.
Unfortunately, your options are to suffer as it is, or switch off the scam detection altogether. There are no settings to teach it or to set safe sites. :-("

Apparently Thunderbird throws up this alert when it sees a URLs in the HTML email copy.  We'll make sure to double-check for this next time.

Thanks again!
