### ISSUE TITLE
Do annotations created through hypothesis JS emit annotationevents?

### ISSUE THREAD

**Issue by gobengo** [hypothesis/h#2767]
If someone annotates my webpage, can my webpage find out about it? Like `document.addEventListener('annotationadd', do);`

Tried to search the source code but can't tell if it's currently implemented?

**Comment by robertknight** [comment]
Yes, using the AnnotatorJS APIs. I cannot make any guarantees that this will continue to be supported in future though.

```js
window.annotator.on('annotationCreated', function(e) {
  console.log('annotation created', e);
});
```

**Comment by gobengo** [comment]
Why not?

**Comment by robertknight** [comment]
> Why not?

Because the fact that Hypothesis assigns `window.annotator` to a reference to the `Annotator` object is not something that has been officially documented as part of our public API as far as I know. I don't know of any reason why we would want to change that behavior at the moment though.

**Comment by gobengo** [comment]
Makes sense.
What's the relationship between the coffeescript in here and https://github.com/openannotation/annotator ?
