### ISSUE TITLE
Sidebar won't open on Congress.gov

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#2768]
Go here:
https://www.congress.gov/bill/114th-congress/house-bill/4038

Use either the extension or via and launch the client.
The sidebar tab will show.
But you cannot click on it and open it.
Also, selecting text and trying to make an annotation will not open the sidebar.

This failed in a demo to some folks at the GSA (US agency)... when this is closed ping us so we can follow up.

**Comment by robertknight** [comment]
I was not able to reproduce the problem in Firefox or Chrome . I just created this annotation: https://hypothes.is/a/AVFv1Uz48sFu_DXLVKtv

If you can reproduce the problem @dwhly can you have a look in the dev tools error console and see if anything is reported?

**Comment by dwhly** [comment]
These are the two errors I get in the console: 
GET https://via.hypothes.is/im_/https://smon.congress.gov/b/ss/loclegislative/1…ule%3BChrome%20PDF%20Viewer%3BShockwave%20Flash%3BNative%20Client%3B&AQE=1 net::ERR_BLOCKED_BY_CLIENT
app.html:16 GET https://www.google-analytics.com/analytics.js net::ERR_BLOCKED_BY_CLIENT

I'll see if I can do more to repro.

**Comment by dwhly** [comment]
I figured it out... uBlocker was apparently blocking something essential...

From the log it was only these two requests... 

18:09:11		/b/ss/*&aqe=	--	image	https://smon.congress.gov/b/ss/loclegislative/1/H.25.2/s21270401291549?AQB=1&ndh=1&t=4%2F11%2F2015%2018%3A9%3A11%205%20480&ce=UTF-8&ns=thelibraryofcongress&pageName=H.R.4038%20-%20114th%20Congress%20%282015-2016%29%3A%20American%20Security%20Against%20Foreign%20Enemies%20Act%20of%202015%20%7C%20Congress.gov%20%7C%20Library%20of%20Congress&g=https%3A%2F%2Fwww.congress.gov%2Fbill%2F114th-congress%2Fhouse-bill%2F4038&r=https%3A%2F%2Fgithub.com%2Fhypothesis%2Fh%2Fissues%2F2768&cc=USD&ch=Congress.gov&server=www.congress.gov&events=event40&c1=https%3A%2F%2Fwww.congress.gov%2Fbill%2F114th-congress%2Fhouse-bill%2F4038&v8=6%3A00PM&c9=PRODDEC2012-1&v9=Friday&v15=D%3Dg&v19=PRODDEC2012-1&c46=loc&c50=https%3A%2F%2Fwww.congress.gov%2Fbill%2F114th-congress%2Fhouse-bill%2F4038&c58=https%3A%2F%2Fgithub.com%2Fhypothesis%2Fh%2Fissues%2F2768&c61=bill&c62=114th-congress&c63=house-bill&s=2560x1440&c=24&j=1.6&v=Y&k=Y&bw=1390&bh=1167&p=Widevine%20Content%20Decryption%20Module%3BChrome%20PDF%20Viewer%3BShockwave%20Flash%3BNative%20Client%3B&AQE=1
18:09:11		||google-analytics.com^	--	script	https://www.google-analytics.com/analytics.js

Disabled it and working fine.

**Comment by dwhly** [comment]
Warning that folks w/ uBlocker or other adblockers might experience odd things occasionally...
