### ISSUE TITLE
No sidebar/annotation on GitHub markdown pages for some browser/Hypothesis tool combos

### ISSUE THREAD

**Issue by amandavisconti** [hypothesis/h#2769]
I've run into trouble trying to use Hypothesis to leave inline questions/comments on documentation hosted on GitHub: I can't get Hypothesis to work at all on Firefox+GitHub or Chrome+GitHub (with Hypothesis extension), but Hypothesis *does* work on Chrome+GitHub using the Via prefix. This is a limited use case. (Hypothesis is pretty cool. Thanks for making your code and principles open to the public!)

I verified Hypothesis works for me on non-GitHub pages (e.g. [this one](http://idhmc.tamu.edu/arcgrant/about/)) but not on GitHub pages (at least not on markdown pages like [this](https://github.com/amandavisconti/infinite-ulysses-dissertation/blob/master/About%20the%20Dissertation/MANIFEST.md), which are what I care about as I'd like to annotate GitHub-hosted documentation).

Tested on a Mac (OS X Yosemite 10.10.5), [using this markdown documentation page](https://github.com/amandavisconti/infinite-ulysses-dissertation/blob/master/About%20the%20Dissertation/MANIFEST.md) from one of my repos. I didn't try the bookmarklet as it seems to be deprecated?

## Latest Firefox 42.0. All extensions disabled.

- **Via**: Does not work; no sidebar appears, and highlighting text does not produce an annotator popup. *Verified Firefox+Via works fine for me with a non-GitHub webpage.*

## Latest Chrome Version 47.0.2526.73 (64-bit). All non-Hypothesis extensions disabled.

- **Via**: Hurray! Works fine.
- **Chrome Extension**: Does not work. Clicking on extension icon in browser menubar does not open annotation sidebar on this page, and highlighting text does not produce an annotator popup. *Verified Chrome+Extension works fine for me with a non-GitHub webpage.*

**Comment by robertknight** [comment]
The extension and bookmarklet are broken on GitHub.com pages (github.io works) due to Content Security Policy settings restricting where scripts, iframes and fonts can be loaded from. See #2445 . The reason Via works is because it strips this layer of security from the page.

The bookmarklet might never work but it should be possible to support this in the Chrome extension and other browser extensions in future.

**Comment by nickstenning** [comment]
Thanks for reporting this, Amanda! Given that the underlying issue is tracked by #2445 I'm going to go ahead and close this.
