### ISSUE TITLE
Permalinks to public annotations working, but not for annotations' comments

### ISSUE THREAD

**Issue by amandavisconti** [hypothesis/h#2783]
The "link" link on annotations gives me a permalinked page displaying just that annotation (yay!) but the "link" link on comments threaded under annotations gives me an empty page.

![screenshot_23](https://cloud.githubusercontent.com/assets/899033/11674757/c98aee82-9df1-11e5-8ba3-86a643031594.png)

E.g. on [this post](https://via.hypothes.is/http://literaturegeek.com/2015-12-08-WhyJekyllGitHub/), one of the annotations has a working link [https://hypothes.is/a/AVGDF2co8sFu_DXLVMt7](https://hypothes.is/a/AVGDF2co8sFu_DXLVMt7) but a comment on that annotation gives me a [link to an empty page](https://hypothes.is/a/AVGEfWBt8sFu_DXLVM8q). I set the comments to post to public instead of just to me, but perhaps there's some kind of moderation queue for comments I'm not aware of?

Awesome work! 

Latest Mac Firefox 42.0 and nearly latest Chrome 46.0.2490.86.

**Comment by lenazun** [comment]
Hello Amanda

We've noticed this is broken and we're working on it!  Keeping track of it here
https://github.com/hypothesis/h/issues/2775

Thank you for reporting!

L

**Comment by amandavisconti** [comment]
@lenazun Super! Thanks for linking me to the issue.
