### ISSUE TITLE
Annotations on touchscreen devices

### ISSUE THREAD

**Issue by RunasSudo** [hypothesis/h#2792]
On my Android devices (a Nexus 5 and a Lenovo Tab 2 A10-70, on both Chrome and Firefox), selecting text on [pages such as this](https://hypothes.is/blog/epub-js-bringing-open-annotation-to-books/) and [this](https://futurepress.github.io/epub.js/examples/hypothesis.html) does not bring up the annotations popup.

I could partially fix this by using [selectionchange-polyfill](https://github.com/2is10/selectionchange-polyfill/), which worked, but was very fiddly (responding to some selection events but not others).

**Comment by robertknight** [comment]
Thanks for the report. Our support for creating annotations on touch screen devices is terrible at the moment. Fixing it and more generally implementing a mobile-ready interface is on our roadmap. In the near-term, we're also going to be doing some work to make it easier for people who are interested in contributing or making changes to the front-end of the Hypothesis client to do so.

**Comment by akuckartz** [comment]
A very strong :+1: from me for planning to improve usability on mobile devices.

**Comment by robertknight** [comment]
https://github.com/hypothesis/h/pull/3347 implements support for showing the adder when selections are made via touch or keyboard input by listening to the 'selectionchange' event, as suggested in the original issue. I didn't use a polyfill because the primary browsers of interest (iOS Safari, Android Chrome) all support this event.

**Comment by nickstenning** [comment]
This has been fixed by #3347. Support for touch devices isn't perfect yet, but the specific issue you identify here has been addressed.
