### ISSUE TITLE
hypothes.is bookmarklet not working on github.com

### ISSUE THREAD

**Issue by jibe-b** [hypothesis/h#2794]
Hi,

The hypothes.is bookmarklet does not seem to work on github.com, though it works with launches on other different webpages as usual.

Using Firefox 42.0.

PS: Forgive a possible duplicate, looking for "github" inside a github repository is not the easiest thing to do...

**Comment by judell** [comment]
GitHub and other sites enforce [Content Security Policy](https://en.wikipedia.org/wiki/Content_Security_Policy) in a way that's incompatible with bookmarklets. It is currently possible to annotate on GitHub using the via.hypothes.is proxy, and we hope to find a solution for the Chrome extension, but we don't see a bright future for bookmarklets.

**Comment by jibe-b** [comment]
Thanks for the answer.
No problem I get the point with bookmarklets. I use it because I use Firefox.

Yet, on https://via.hypothes.is/https://github.com/hypothesis/h the hypothes.is sidebar does not load.

**Comment by jibe-b** [comment]
In Firefox, one can disable Content Protection Security by __changing security.csp.enable__ to _false_ in _about:config_

This enables bookmarklets to be executed.

 http://stackoverflow.com/questions/7607605/does-content-security-policy-block-bookmarklets

**Comment by robertknight** [comment]
@jibe-b - I really would not recommend disabling Content Security Policy globally in your browser. GitHub enables it for good reason and we will be enabling it for the Hypothesis website and activity stream soon. Having said that, I appreciate that it is frustrating not to be able to use H with certain websites in Firefox without going through Via. We intend to remedy that in future by introducing a Firefox extension.

**Comment by jibe-b** [comment]
Ok, I read a bit more about CSP and it might not be a good idea.
