### ISSUE TITLE
IP or domain used to load Hypothesis sidebar affects stored account string

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#2797]
I have two bookmarklets which I've just discovered had the embed URLs set to http://127.0.0.1:5000/embed.js and http://localhost:5000/embed.js respectively. Annotations created with one of those bookmarklets are not editable by a sidebar created by the other bookmarklet. The domain or IP used to load the bookmarklet ends up in the user ID string.

It makes sense that any data stored on the client side (eg. in local storage, cookies) would be linked to the IP or domain is used to load the embed. It shouldn't be possible for client configuration to affect the user ID data that gets associated with annotations in server storage though.
​
This issue can't happen with the public Hypothes.is service AFAIK because SSL validation will fail if you try to use the IP directly or a different domain, plus CloudFlare doesn't allow direct use of the IP. However, it could happen with someone running a private instance of H or if someone's client is not doing SSL validation.

**Comment by nickstenning** [comment]
The "domain" part of userids defaults to the request host, which can indeed be an IP address if someone hosts an installation of h on an IP address. But it's perfectly possible to force the domain part of the userid by setting the `AUTH_DOMAIN` environment variable when running the server.
