### ISSUE TITLE
Editing one annotation changes them all

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#2799]
1. Create an annotation
2. Create another annotation.
3. Edit either annotation and save it.

=> All annotations one the page are updated with the contents of the annotation you edited.

**Comment by judell** [comment]
I tried that and did not reproduce it. On production.

**Comment by judell** [comment]
I tried that and did not reproduce it. On production.

**Comment by judell** [comment]
I tried that and did not reproduce it. On production.
