### ISSUE TITLE
annotation not found by uri search

### ISSUE THREAD

**Issue by judell** [hypothesis/h#2806]
At http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4418305/ I have been adding and deleting a lot of test annotations. The most recent one I added is:  

stream: https://hypothes.is/api/annotations/AVGtJYgR8sFu_DXLVQ8f

api: https://hypothes.is/a/AVGtJYgR8sFu_DXLVQ8f

Queries:

stream: https://hypothes.is/stream?q=uri:http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4418305/

api: https://hypothes.is/api/search?uri=http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4418305/

Expect: Annotations returned from the queries

Actual: None

**Comment by judell** [comment]
Another example: http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4465714/

This annotation exists for that URL: https://hypothes.is/a/AVG2ubm78sFu_DXLVR0C

(    "uri": "http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4465714/", )

But https://hypothes.is/api/search?uri=http%3A%2F%2Fwww.ncbi.nlm.nih.gov%2Fpmc%2Farticles%2FPMC4465714%2F -> 0 results

**Comment by judell** [comment]
@seanh reports:

"Copying one of those annotations locally I can reproduce the problem on my dev instance, still don't know why it's not working though"

**Comment by seanh** [comment]
If I hack the URI normalization to not strip trailing /'s when searching then this annotation does show up in search results. Otherwise not. No idea why yet but it appears to be a uri normalization issue.

**Comment by judell** [comment]
Duplicate of https://github.com/hypothesis/h/issues/2711

**Comment by judell** [comment]
@seanh adds (elsewhere):

"seanh [1:24 PM] 
I wonder if this has something to do with the page containing a `<link rel="canonical"` that has a trailing slash"
