### ISSUE TITLE
cannot scroll in groups menu

### ISSUE THREAD

**Issue by jeremydean** [hypothesis/h#2813]
i'm a member of a lot of groups. after a certain point, i cannot see/access all my groups in the dropdown menu.

this is also going to be a problem for anyone doing this: hacking a private feedback feature by making each student in a class a group of one:

https://twitter.com/ATErickson/status/677226027526045696

**Comment by judell** [comment]
That's an valuable feature request but not a bug, so I'm closing this here and will move it to our planning board.
