### ISSUE TITLE
timestamp missing from newly created annotation

### ISSUE THREAD

**Issue by judell** [hypothesis/h#2819]
![image](https://cloud.githubusercontent.com/assets/46509/11909555/070d02ec-a59d-11e5-80c1-8d88a2361f6d.png)

The missing timestamp appears after a page refresh. Minor fallout from https://github.com/hypothesis/h/pull/2808?

**Comment by robertknight** [comment]
This happened before #2808 - that only affected the tooltip for the timestamp. It might have happened during the recent annotation refactoring. The issue is fairly simple, we're just not kicking off the periodic timestamp refresh after a new annotation is initially saved.
