### ISSUE TITLE
Perf regression when updating annotation last-displayed timestamps

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#2820]
Moment.js was recently removed in favor of using the browser's `Date` APIs in https://github.com/hypothesis/h/pull/2808 . The initial version of this was much faster than Moment. However, the revised version which actually got merged turns out to be much ~3x slower in Chrome than the Moment formatting - accounting for ~20ms of digest time (vs ~7ms for the old Moment implementation and ~2ms for the initial version of that PR) on the default `/stream` view.

A quick scan of JS profiling suggests that behind the scenes the browser is creating a new formatting object for each call to `toLocaleDateString` which is very expensive. Couple of things we can do here: 1) Cache the timestamp string, 2) Create a date formatter once and re-use it.

**Comment by robertknight** [comment]
I created a simple benchmark: https://gist.github.com/robertknight/4b697a7097f8317d98f1

Turns out that `toLocaleDateString` with options is _really_ slow:

Firefox:
```
toLocaleDateString without options: 7631 iterations test.bundle.js:7146:5
toLocaleDateString with options: 63 iterations test.bundle.js:7146:5
Moment.js: 868 iterations
```

Chrome:
```
toLocaleDateString without options: 6261 iterations
test.bundle.js:7146 toLocaleDateString with options: 64 iterations
test.bundle.js:7146 Moment.js: 1029 iterations
```

**Comment by robertknight** [comment]
I have added a benchmark using `Intl.DateTimeFormat` to re-use the internal formatter and that turns out to be much faster:

```
toLocaleDateString without options: 2947 iterations
toLocaleDateString with options: 77 iterations
Intl.DateTimeFormat reuse: 4943 iterations
Moment.js: 745 iterations
```

**Comment by mobitar** [comment]
Just ran into this issue as well. My application felt 10x as heavy and the UI was lagging. Turns out it was `toLocaleTimeString`. 

Btw, I'm getting the current locale with 
```
var locale = (navigator.languages && navigator.languages.length) ? navigator.languages[0] : navigator.language;
```

then passing it to the DateTimeFormat constructor:

```
formatter = new Intl.DateTimeFormat(locale, {...})
```
