### ISSUE TITLE
Selecting characters in an arabic word splits it apart

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#2827]
> I'm working on a project that uses Hypothesis. The texts are in Arabic, which consists of letters that have stand-alone "isolated" forms and connected forms. (https://en.wikipedia.org/wiki/Arabic_alphabet#Table_of_basic_letters)
> 
> When I select a portion of a word for highlighting or annotation, rather than selecting the whole word, it splits the connected letters apart, into their isolated forms. This makes it very difficult to read, and sloppy.
> 
> The English equivalent would be that selecting a portion of a word would insert an unrelated symbol into the text (i.e. t@ext).

Verified.

There's a sample text page here for testing: http://www.dalilusa.com/arabic_course/text01.asp

**Comment by nickstenning** [comment]
This is a side-effect of splitting DOM text nodes to render highlight `<span>` elements. In scripts such as Arabic, where characters have different initial, medial, and terminal forms, this causes problems.

I've previously played with [SVG overlays](https://github.com/nickstenning/marks) as one approach to solving this problem.

**Comment by nickstenning** [comment]
Moved to hypothesis/client#241.
