### ISSUE TITLE
Sometimes video embed works, sometimes it doesn't

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#2828]
Both @jeremydean and I have verified the following:

Load this URL in Chrome
https://via.hypothes.is/https://dlsanthology.commons.mla.org/text-analysis-data-mining-and-visualizations-in-literary-scholarship/

Open the sidebar, look for the youtube link. (https://hypothes.is/a/AVHveExj8sFu_DXLVUm0)
It seems sometimes the video is embedded and sometimes the youtube link is left as is.
Somewhere between 25-50% failure rate by our sampling.  This behavior also seems to happen when using the chrome extension at the page.

**Comment by dwhly** [comment]
An easier way to sample this error is just to reload the annotation link directly a bunch of times:
https://hypothes.is/a/AVHveExj8sFu_DXLVUm0

**Comment by seanh** [comment]
This appears to be a race condition between the `/app/features` HTTP request and the annotation search request (if the search one finishes first, videos will not be embedded).

I think @robertknight  has already fixed this with <https://github.com/hypothesis/h/pull/2807>, but it's just not deployed yet.

**Comment by seanh** [comment]
I think the fix for this should be deployed now, please re-open if it's not fixed
