### ISSUE TITLE
Show / Hide Highlights endless toggle

### ISSUE THREAD

**Issue by fchasen** [hypothesis/h#2829]
When I create a sidebar in the host page and a guest embed in a iframe, the show / hide button toggles on and off very quickly in the sidebar. Inside the iframe the body, the class `annotator-highlight-always-on` is toggled on a off.

Example here: http://fchasen.com/hypothesis/index.html

[hypothesis-test.zip](https://github.com/hypothesis/h/files/76396/hypothesis-test.zip)

**Comment by nickstenning** [comment]
Thanks a lot for filing this issue! We'll triage and take a look at it as soon as possible!

**Comment by nickstenning** [comment]
This bug appears to be fixed in recent versions of Hypothesis. We appear to have introduced new bugs, like the fact that the toggle highlights buttons doesn't seem to correctly apply to subframes, but this one at least can close.
