### ISSUE TITLE
Stream shows wrong group for annotations

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#2839]
The stream shows the name of the currently focused group as the group for all annotations, regardless of which group the annotation actually came from.

**Steps to reproduce**
1. Visit a page with H embedded, Via or use the bookmarklet to open H
2. Select a private group G from the dropdown other than Public
3. Visit the stream

**Expected**
Recently posted public annotations are shown without a group name next to them

**Actual**
All annotations in the stream are shown as being created in group G

Slack discussion: https://hypothes-is.slack.com/archives/public/p1452189656000444

**Comment by judell** [comment]
The extension is unaffected because, I suppose, it remembers things in a different place in local storage?

Is there any reason not to just remember such things server-side?

**Comment by robertknight** [comment]
I haven't checked the extension but I expect that would be the case. AFAIK we have the group information when we show the annotations, we're just not using it correctly.

**Comment by seanh** [comment]
I'll see if I can fix this tomorrow
