### ISSUE TITLE
Chrome Extension: Onboarding page is slow to load due to large number of annotations

### ISSUE THREAD

**Issue by yalamerde** [hypothesis/h#2844]
After installing Hypothesis in Vivaldi, it loaded a new tab. This was painfully slow, due to the hundreds of tabs already open and hypothesis not very lazily loading all those comments at https://hypothes.is/welcome.

Does the hook which opens the pane automatically in said tab also work for pages which have *h* in their own codebase, like http://blog.geosemantik.de or http://wiki.transformap.co ?

**Comment by robertknight** [comment]
> Does the hook which opens the pane automatically in said tab also work for
> pages which have h in their own codebase, like http://blog.geosemantik.de
> or http://wiki.transformap.co ?

Yes, it would, but the hook is currently called "firstRun" rather than "openSidebarOnLoad" or something similar - so it might end up doing something different in future. I've opened a separate issue in the hypothesis/vision repository which we use for tracking feature requests.

**Comment by almereyda** [comment]
> I've opened a separate issue in the hypothesis/vision repository which we use for tracking feature requests.

Good to know.

**Comment by robertknight** [comment]
Performance of Hypothesis on pages with large numbers of annotations is much improved in v0.24.0. There is still more work to do but the app is now usable on these pages.
