### ISSUE TITLE
There is a gap in the groups dropdown button

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#2852]
Clicks aren't detected in-between the group icon and group name:

![untitled screencast - cropped 12](https://cloud.githubusercontent.com/assets/22498/12261501/6a87662a-b919-11e5-9f59-87213ae7726d.gif)

**Comment by robertknight** [comment]
I can reproduce this issue in Chrome but not Firefox. In Chrome, when the cursor is in the space created by the right margin of the group icon (4px by default) the cursor resets to the default and the click handler is not triggered. In Firefox, this does not happen.

**Comment by robertknight** [comment]
This appears to be a bug in Chrome with handling of inline elements that contain a child with a transform applied: https://gist.github.com/robertknight/8450c09b280564df03f9

**Comment by robertknight** [comment]
I've filed an upstream issue at https://code.google.com/p/chromium/issues/detail?id=576655
