### ISSUE TITLE
"Tell me more about groups" link is broken

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#2867]
1. Go to https://hypothes.is/groups/new
2. Click "Tell me more about groups"

Expected: Details about how to use groups appears
Actual: Nothing happens

The bug is something I found when running the TypeScript compiler over our JS code, which spotted an incorrect use of `RegExp.match()` in https://github.com/hypothesis/h/blob/master/h/static/scripts/site.js#L26

**Comment by judell** [comment]
"when running the TypeScript compiler over our JS code"  :heart:
