### ISSUE TITLE
annotation-adder's z-index too low?

### ISSUE THREAD

**Issue by judell** [hypothesis/h#2869]
I can't share the page here because it is private, but I have verified that on this particular page, selection appears to produce no annotation-adder. In fact it's there but invisible. The z-index on the annotation-adder class is 999. If I bump it to 99999 for that page the annotation-adder appears.

**Comment by robertknight** [comment]
@judell - Could you share an archive of the page with my privately? Although I could create something that would reproduce the issue based on the description here trivially enough, I'd like to have a look at what else is going on on the page.

**Comment by robertknight** [comment]
Note for future reference. Rather than hardcoding zIndex to a fixed value, we could potentially just make sure we select one that is higher than the max index within the frame being annotated.

```js
zi = zindex => typeof zindex === 'number' ? zindex : 0;
maxZindex = () => [].slice.apply(document.querySelectorAll('*')).reduce((max, el) => Math.max(max, zi(getComputedStyle(el).zIndex)), 0)
```

**Comment by nickstenning** [comment]
Like this, you mean? https://github.com/openannotation/annotator/blob/258fd8822de6fca73b4f7ab4717d14556367d1ab/src/util.coffee#L154 :wink: 

I suspect that's not used because we have our own custom adder, but it's worth looking at.

The only thing I'd caution is that if there's a way to do this that doesn't involve a loop over every element in the document, that would be good. On large documents iterating over `document.querySelectorAll('*')` is going to take a non-negligible amount of time.

**Comment by robertknight** [comment]
It takes about 800-1000ms for this on the famously large [HTML5 single-page spec](http://www.w3.org/html/wg/drafts/html/master/single-page.html):
```js
(d = Date.now(), [].slice.apply(document.querySelectorAll('*')).map(el =>
getComputedStyle(el).zIndex), Date.now() - d)
```

And on what I would consider a more typical large article such as [this eLife paper](http://elifesciences.org/content/4/e08924), about 200ms.

So yes, that is expensive enough to create noticeable lag on large articles.

Given that we know where the adder is going to appear, we could search a much smaller list of elements though.

**Comment by nickstenning** [comment]
> Given that we know where the adder is going to appear, we could search a much smaller list of elements though.

Good idea. Sampling `document.elementFromPoint(x, y)` in a few places around where we want to pop up the adder and then checking those elements would probably work! (It's non-standard but IIRC it works in every major browser).

**Comment by judell** [comment]
> Sampling document.elementFromPoint(x, y) in a few places around where we
want to pop up the adder

Clever!

**Comment by nickstenning** [comment]
See also #2720, #2759.

**Comment by nickstenning** [comment]
Another report of this in #3192, where the main page container has:

```CSS
#global-viewport #pane-main {
    background: #f1f2f3;
    position: relative;
    width: 100%;
    z-index: 1000006;
}
```

I don't think we're going to be able to pick a number that is high enough. The sampling approach suggested above would seem to remain the best option.

**Comment by zachwhalen** [comment]
Hi. 

I'm chiming in to report that this is still an issue, as seen on this page where the main article text is `z-index: 9000`. http://www.english.ufl.edu/imagetext/archives/v3_2/whitson/

Was the solution described here ever implemented?

**Comment by sean-roberts** [comment]
This was something I was going to bring up after researching the client more - glad to see this ticket is here. Seems to me we can get *very* far with setting the z-index value to the highest limit that has no known problems in older browsers (2147483647) and call it a day. If we have to get smarter than that, we can reopen this or create a new ticket saying it's not good enough.

**Comment by robertknight** [comment]
> Seems to me we can get very far with setting the z-index value to the highest limit that has
> no known problems in older browsers (2147483647) and call it a day. 

That's a lot simpler than the other options - worth a try 👍 
Found this as a reference: http://www.puidokas.com/max-z-index/

**Comment by nickstenning** [comment]
Moved to https://github.com/hypothesis/client/issues/256.
