### ISSUE TITLE
"To annotate this document" banner appears on stream and individual annotation pages

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#2872]
The loud banner prompting users to create an account in order to annotate the current document is shown on the stream and individual annotation pages. It should only be shown on the sidebar.

**Comment by dwhly** [comment]
> It should only be shown on the sidebar.

In addition, only to be shown when someone tried to annotate but was not yet signed in.  However, now it shows always when a person is not signed in. Otherwise it's oddly duplicative of the text immediately to it's upper right.

**Comment by robertknight** [comment]
> Otherwise it's oddly duplicative of the text immediately to it's upper right. 

I'll address the obvious problem of it showing up in the stream to begin with. Having the banner and the text in the top sidebar matches the design, so need a discussion with Conor if we want to reconsider that.
