### ISSUE TITLE
Link in Recently annotated documents (Group page) is not clickable

### ISSUE THREAD

**Issue by lenazun** [hypothesis/h#2886]
Steps to repro:
- Join this group https://hypothes.is/groups/VarjzrAK/ports-atlantic-worl
- Try to click on the second link (Intro and Chapter 1.pdf)

Expected:
- The link should take you to the target document

Actual:
- The link is not clickable

<img width="498" alt="unclickable" src="https://cloud.githubusercontent.com/assets/6117168/12488531/e4175d84-c020-11e5-9f0f-07aba1a6b721.png">

**Comment by seanh** [comment]
A member of the group has annotated a local file (`file:///Users/alidametcalf/Library/Application%20Support/Firefox/Profiles/djy0bz4m.default/zotero/storage/ISQRSVFT/Intro%20and%20Chapter%201.pdf`) so we can't link to it. Close as won't fix?

**Comment by lenazun** [comment]
Mmm. Yeah. We could visually indicate local files differently, but I'll leave that to @conordelahunty on his redesign of this page.

**Comment by judell** [comment]
https://github.com/hypothesis/h/issues/2915 proposes a fix and pings @conordelahunty about that.
