### ISSUE TITLE
Inline embeds in addition to YouTube

### ISSUE THREAD

**Issue by jeremydean** [hypothesis/h#2888]
I want to be able to embed Tweets and SoundCloud files and Vimeo videos in my annotation.

**Comment by dwhly** [comment]
Embedded tweets, nice.

**Comment by nickstenning** [comment]
Just a note that Vimeo already works, or should.

**Comment by nickstenning** [comment]
And, now that I think about it, if we could get a card for this in the product backlog rather than in this issue tracker, that would be great. Let me know once that's done and I'll close this issue.

**Comment by dwhly** [comment]
https://trello.com/c/CILrSKAE/463-inline-embeds-for-tweets-and-soundcloud-clips At the top of capture.

**Comment by nickstenning** [comment]
Great, thank you.
