### ISSUE TITLE
Opening "welcome" page is unhelpful/confusing in school/office install settings

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/h#2890]
When the Chrome extension is installed by an administrative policy, as in a school or office setting, the fact that we auto-open the "/welcome" page on install can be unhelpful.

From a user report of this issue:

> The Chromebooks I am working with are shared among multiple users - sometimes 5 or 6 different students in a day. Part of our configuration for these CBs is that all account information is wiped off of the device when a user signs out. As a result, Hypothesis sees every time any user signs into any CB as the "first" time for that user. Suppressing that page load on "first" installation will help immensely.

It seems reasonable that we should default to *not* opening the welcome page when the Chrome extension is installed as a result of an administrative policy rather than user action. The alternative is that a tab will appear to open without any user action.

**Comment by nickstenning** [comment]
Hmm. Sadly I think I may have misread the documentation here. There are two distinct `onInstalled` events. One is available to all extensions, and that's [`chrome.runtime.onInstalled`](https://developer.chrome.com/extensions/runtime#event-onInstalled). The other is only available if your extension requests and is granted the `management` permission, and that's [`chrome.management.onInstalled`](https://developer.chrome.com/extensions/management#event-onInstalled).

I read the docs for the latter, which provides the [`ExtensionInfo`](https://developer.chrome.com/extensions/management#type-ExtensionInfo) object that includes the `installType` key.

Luckily, it seems we may be able to do this without the additional permission, because when we're installed we can call [`chrome.management.getSelf`](https://developer.chrome.com/extensions/management#method-getSelf) and get the needed info from there. (This call does not require the `management` permission declared in the manifest.)

**Comment by robertknight** [comment]
https://hypothesis.zendesk.com/inbox/tickets/75
