### ISSUE TITLE
Disappearing Quotes in Angle Brackets

### ISSUE THREAD

**Issue by Enkerli** [hypothesis/h#2896]
May be an example of a well-known issue, but I’m not seeing “brackets” in issues.
Had selected a piece of text surrounded by angle brackets as the basis for [this annotation](https://hypothes.is/a/AVKEaVUSvTW_3w8Lyjmd). The annotation worked but the quote didn’t. Pasting the same string after the Markdown closing bracket has the same effect. Maybe the text is recognized as a tag?

It might be difficult to avoid without using escape characters but it could be surprising to users.

**Comment by nickstenning** [comment]
That's an interesting bug you've found there. Thanks for reporting it, we'll take a look!

**Comment by nickstenning** [comment]
I've opened hypothesis/client#239 to fix this issue.
