### ISSUE TITLE
Sidebar is unresponsive whilst typing in heavily annotated page

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#2899]
**Steps to reproduce**

1. Open this PDF with 241 annotations and activate the extension https://pedufopenglish.files.wordpress.com/2014/02/james-paul-gee-situated-language-and-learning-a-critique-of-traditional-schooling-2004.pdf
2. Wait too long for the sidebar to fully load
3. Create a new annotation and try to type in the annotation text box

**Observed behavior**

The input field is really laggy, to the point where it is essentially impossible to create a new annotation unless you do all of the typing in a text editor and copy and paste the result in.

**Comment by nickstenning** [comment]
While there are still clearly many performance issues on this page, and typing is still a little laggy, recent changes (#3213, I guess) have improved this to the extent that I reckon we can close this issue.
