### ISSUE TITLE
Cannot edit group annotation from stream

### ISSUE THREAD

**Issue by judell** [hypothesis/h#2902]
1. Visit https://hypothes.is/a/AVKfhRt9vTW_3w8LyqLX (or any group annotation)

2. Click edit

3. Add text and/or tag

4. Post 

5. 400

![image](https://cloud.githubusercontent.com/assets/46509/12736700/75e283c6-c907-11e5-9695-6a7c734b6bbe.png)

Editing the same group annotation in the sidebar works fine.

**Comment by dwhly** [comment]
I might add that starting our warning messages with "400 OK ... " is pretty terrible. @conordelahunty Maybe we can do a bit better here. :)

**Comment by nickstenning** [comment]
This is an out and out bug. That's not a warning message anyone was every meant to see.
