### ISSUE TITLE
chrome ext won't activate on local PDFs

### ISSUE THREAD

**Issue by jeremydean** [hypothesis/h#2912]
http://screencast.com/t/6Ob0aVBF

it's working elsewhere--hosted PDFs, webpages, etc.

h: version 0.8.12 
chrome: Version 48.0.2564.97

**Comment by judell** [comment]
Works for me (for a different PDF).

Have you double-checked that Allow access to file URLs is ticked? (It might not be in the stage extension if you're testing that.)

**Comment by jeremydean** [comment]
i have. double-checked. and this is not w/ stage.

**Comment by jeremydean** [comment]
resolved by un- and re-installing ext.

likely conflict with stage ext.

**Comment by judell** [comment]
Thanks JD.
