### ISSUE TITLE
Share link autofocus on group homepage is confusing

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/h#2917]
We currently autofocus the share link on group homepages. This is fine when the page is short, but rather confusing when the group has been busy annotating lots of pages -- the page will jump down to the bottom of the page when loading.

We probably want to reconsider this behaviour.

(If you need an example groups page, ask me.)

**Comment by robertknight** [comment]
Paraphrasing myself from Slack - we definitely don't want this behavior any more. I thought it useful when originally implemented, but that was before the document list was added.
