### ISSUE TITLE
http and https flavors of URL can result in disjoint pools of annotations

### ISSUE THREAD

**Issue by judell** [hypothesis/h#2930]
I got bit twice by this today. First here (https://trello.com/c/xwyKzlwp/223-strip-via-as-part-of-normalization) and then, just now, on a support ticket. In the latter case, the two disjoint pools are attached to:

https://studiotendra.com/2013/12/17/great-text-transcends-nothing/

http://studiotendra.com/2013/12/17/great-text-transcends-nothing/

Can/should we ignore the scheme when calculating equivalence? (DId we ever?)

Update: I just fielded /another/ support ticket, it was the same thing. Seems far too coincidental, if this had been the case all along I'd expect we'd have seen many such reports.

**Comment by robertknight** [comment]
I was bitten by this when I added annotations to my blog a couple of days ago.

**Comment by nickstenning** [comment]
This has been the case [all along](https://github.com/hypothesis/h/blob/f6e5d42541fdf6e2cc78439e16ba710ea7402022/h/api/test/uri_test.py). I'm going to close this issue as it ain't a bug -- feel free to create a card to discuss treating http/https as equivalent.

**Comment by robertknight** [comment]
Fair enough. @judell do you want to put this on a card?

**Comment by judell** [comment]
"do you want to put this on a card?" Yes, I think so. Unless there's an argument for not treating http/https as equivalent?

**Comment by nickstenning** [comment]
Well, there are discussions to be had about it, but that's the purpose of the Trello "discovery" column :)

**Comment by judell** [comment]
OK, it's there.

**Comment by nickstenning** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;pN5ud6xV&#x2F;494-treat-http-https-urls-as-equivalent"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Treat HTTP&#x2F;HTTPS URLs as equivalent</a>
