### ISSUE TITLE
Errors rendering annotations without URIs on the stream

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#2939]
Our smoke tester service currently creates annotations that have no URIs and the stream fails to handle this: https://github.com/hypothesis/h/issues/2938

Is there a good reason why we could have annotations without URIs? If so, we'll need to handle that. If not, then we should avoid showing Smokey-created annotations in the stream.

**Comment by chdorner** [comment]
This should not be an issue anymore since we moved the primary storage to PostgreSQL and have a `NOT NULL` constraint on the URL. We also got rid of quite a few smokey annotations in the process of migrating to PostgreSQL.

Closing this.
