### ISSUE TITLE
Feature-flag checking causing slowdown on heavily annotated pages

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#2959]
Yesterday whilst skimming the stream I visited http://www.digitalhistory.uh.edu/disp_textbook.cfm?smtID=3&psid=79 which has ~115 annotations. Opening this page with v0.8.15 brings Chrome to a crawl.

Looking at the console there are a ton of warnings related to lookup of removed features. I think this may related to https://github.com/hypothesis/h/pull/2949

The profiler shows that a lot of the cost is attributed to `features.flagEnabled()`:

![feature-log-spam](https://cloud.githubusercontent.com/assets/2458/13027692/eefaec4c-d250-11e5-80fe-4a06d406663a.png)

![log-spam-profile](https://cloud.githubusercontent.com/assets/2458/13027693/f36e9eea-d250-11e5-9bb1-117452f56d46.png)

**Comment by nickstenning** [comment]
Are you sure this was v0.8.15 you were using? Because v0.8.15 shouldn't have any lookups for either of those features...

**Comment by nickstenning** [comment]
(Regardless of the answer to this question we should look into whether `feature.flagEnabled` is doing the right thing when feature flags are removed. In particular, we probably want to be careful that we don't stop sending the features to old clients...)

**Comment by robertknight** [comment]
> Are you sure this was v0.8.15 you were using? Because v0.8.15 shouldn't have
> any lookups for either of those features...

I must have been using a different build. I'm not seeing those errors any longer.

**Comment by robertknight** [comment]
The underlying issue still persists but the features mentioned in the original bug were removed. Closing this for the time being.
