### ISSUE TITLE
Annotation search does not find edits made in current session

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#2965]
**Steps to reproduce**

1. Create an annotation on a page
2. Create a reply to this annotation containing a keyword _K_ not found in another annotations on the page
3. Search for _K_
4. Edit the text of the reply to contain a different keyword _K2_ not found in other annotations on the page
5. Search for the keyword _K2_

**Expected results**

The reply appears in the search results in step 3 and step 5

**Actual results**

The reply does not appear in step 5

**Comment by robertknight** [comment]
This issue still exists on master but the behavior in step 5 changed. Searching for the keyword _K2_ finds no results as before. When clearing the search after step 5 however, the content of the reply reverts back to what it was before. Additionally, this issue can now be reproduced with top level annotations, not just replies. After reloading the page or switching groups however, it is clear that the change has actually been saved.

**Comment by robertknight** [comment]
This is still open, my PR comment for #3541 included the phrase "This is the first in a series of commits which will fix #2965", so GitHub naturally closed this once that was merged.

**Comment by nickstenning** [comment]
Still open...
