### ISSUE TITLE
"$sanitize:badparse" error from invalid HTML generated by showdown

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#2970]
**Steps to reproduce**

1. Create a new annotation and paste in the following text: `<one two.>`
2. Click 'Post'

**Expected**

I think we should probably disallow custom HTML tags in markdown generated by the user and just format them as plain text.

**Actual**

1. Nothing appears in the text field
2. An error appears in the console

```
Error: [$sanitize:badparse] The sanitizer was unable to parse the following block of html: <one two.></p>
http://errors.angularjs.org/1.4.7/$sanitize/badparse?p0=%3Cone%20two.%3E%3C%2Fp%3E
minErr/<@https://hypothes.is/assets/scripts/vendor/angular.min.js?310b5ef0:1:775
htmlParser@https://hypothes.is/assets/scripts/vendor/angular-sanitize.min.js?ea3db86c:1:5648
$SanitizeProvider/this.$get</<@https://hypothes.is/assets/scripts/vendor/angular-sanitize.min.js?ea3db86c:1:213
[22]</module.exports</<.link/renderMathAndMarkdown/parts<@https://hypothes.is/assets/scripts/app.min.js?910709f6:2:24260
[22]</module.exports</<.link/renderMathAndMarkdown@https://hypothes.is/assets/scripts/app.min.js?910709f6:2:23859
[22]</module.exports</<.link/ctrl.$render@https://hypothes.is/assets/scripts/app.min.js?910709f6:2:25409
ngModelWatch@https://hypothes.is/assets/scripts/vendor/angular.min.js?310b5ef0:8:28070
...
```

**Comment by robertknight** [comment]
The error reported here no longer happens in Angular 1.5. The issue is now a more minor one. If the entered text is "foo <one" with no closing tag present then nothing after the '<' is rendered. GitHub on the other hand is more tolerant about malformed markup.

At this point I don't think it is worth spending a lot of time on, so I propose to continue doing some refactoring to extract the rendering code into its own testable unit, add a test case that checks no errors occur when parsing input like this and then move on to something else.

**Comment by nickstenning** [comment]
Seeing as the reported error is now fixed... closing.
