### ISSUE TITLE
Feature request: access to jupyter kernels from h

### ISSUE THREAD

**Issue by jibe-b** [hypothesis/h#2972]
Hi there!

I love hypothes.is and I use it more and more. One feature would be great, beyond annotation: the possibility to run code inside the [h](https://github.com/hypothesis/h) sidebar.

For sure, it is already possible to paste code inside a h.is note and let people run it on their own computer. But the same way as  [jupyter](http://jupyter.org) notebooks enable to run code inside the document, it would enable to run code in the same annotation layer. It could then be used for academics to discuss a publication, or simply by fact-checkers.

Developing a plugin that would enable it would require to add a server-side dependency, of something like a fiddle. Another way (for a less broad audience unfortunately) would be to make h have access to the jupyter kernel, thus displaying the results of the calculation.

This is simply an idea of feature. If I find time, I may try to develop something like this myself.

By the way, I expect that there be javascript limitations that apply here. Are there any?

**Comment by judell** [comment]
Transplanted to https://github.com/hypothesis/vision/issues/203 because we track bugs here, feature requests there.
