### ISSUE TITLE
Returning to logged-out app after 1 hour, and attempting login, provokes "Oops, something went wrong on the server"

### ISSUE THREAD

**Issue by judell** [hypothesis/h#2976]
# Expected

* Accept offered cached credentials
* Login

# Actual

* Oops. Something went wrong on the server

# When

10:45 AM Pacific, 2/17/2016, from 

![image](https://cloud.githubusercontent.com/assets/46509/13128880/f1928f60-d58d-11e5-8934-0cc2fc462d82.png)

**Comment by seanh** [comment]
Any idea what might be happening here? I can take a look in a bit

**Comment by seanh** [comment]
This doesn't seem to be caused by an expired CSRF token. I hacked `pyramid/session.py`'s `get_csrf_token()` to always return a new token rather than the one from the session, meaning that the token in the client's request would not match, but that gets a different error message "Session is invalid. Please try again."

**Comment by seanh** [comment]
Actually I think the message "Oops, something went wrong on the server. Please try again later!" might only happen when the server 500s

**Comment by dwhly** [comment]
Are these the kinds of things that will be reported by sentry in the future?

**Comment by seanh** [comment]
If there was a server-side crash (which I think there might have been) it should actually be somewhere in Sentry now I think...

**Comment by seanh** [comment]
I just opened https://hypothes.is/docs/help in Firefox, logged out, left the tab for over an hour, came back, logged in - worked fine.

**Comment by seanh** [comment]
Actually this error could also be produced by 4xx responses from the server (such as 401 Unauthorized) which wouldn't show up in Sentry.

If an expired CSRF token doesn't seem to cause this error then I'm not sure what would

**Comment by seanh** [comment]
Ok, what I think happened is that the session timed out. Pyramid's signed session cookies time out after 20 mins by default, and that does produce the error shown in the screenshot

**Comment by seanh** [comment]
Also tried making Pyramid's session cookie timeout after 1 second (instead of the default 20 mins), but that also produces: "Session is invalid. Please try again."

**Comment by seanh** [comment]
I give up. I'm gonna close this as "Can't reproduce", if anyone knows what happened here or @judell if you can reproduce it pleas reopen
