### ISSUE TITLE
Clicking 'Reply' in stream directs to `/stream` without query if a search query is active

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#2977]
**Steps to reproduce**

1. Go to https://hypothes.is/stream
2. Perform a search, eg. 'stanza'
3. Click 'Reply' on any annotation card

**Alternate steps to reproduce**

1. Go to the activity page for any group and click 'View recent group annotations'
2. Click 'Reply' on any annotation card

**Expected result**

A new reply is created and the text field appears ready for me to type my reply

**Actual result**

I get redirected to '/stream#<id of annotation I clicked on>'

**Comment by robertknight** [comment]
The problem is that the logic for clearing the selection and search when creating new annotations in the sidebar is being triggered when creating a reply in the stream. What happens is:

1. Click 'Reply'
2. "beforeAnnotationCreated" event is emitted, which triggers clearing of the search query and annotation selection in 'app-controller.coffee'
3. When the search query changes, stream-controller.coffee reloads the current route

The root issue here  is applying sidebar-specific logic in the stream. Even in the context of the sidebar though, we don't want to clear the selection and search when creating a reply.

**Comment by nickstenning** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;8OLgPCYz&#x2F;265-refactor-annotation-card-tests"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Refactor annotation card tests</a>

**Comment by nickstenning** [comment]
Closed by #2978.
