### ISSUE TITLE
Private annotations before Friday Feb. 19 do not load 

### ISSUE THREAD

**Issue by jibe-b** [hypothesis/h#2991]
Hi,

The "Only me" annotations I made before Friday Feb. 19 do not load neither on the webpages nor through the http API. I tried to log ou-log in but they don't load.

Do you know a reason?

My hypothes.is login is jibe.

**Comment by jibe-b** [comment]
I was wrong, annotations load on webpages but not through the API. I have tried with and without a proxy.

**Comment by nickstenning** [comment]
How are you authenticating to the API?

**Comment by jibe-b** [comment]
I don't use a API key but only the sing-in + cookie identification in Firefox 44 and curl -b cookies.txt ...

**Comment by nickstenning** [comment]
Ah, ok. Cookie authentication to the API has never been documented or supported and was recently removed. I am releasing Hypothesis v0.9.0 as we speak which introduces proper developer API keys. Hopefully that will make your life a lot easier!

**Comment by nickstenning** [comment]
I'm going to close this issue pending release of v0.9.0. Hope that's ok with you.

**Comment by jibe-b** [comment]
That's totally ok, I generated a key and it works fine. Thanks!
