### ISSUE TITLE
Scope menu does not update when you delete or add a group

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#2999]
In either the browser extension, or with via:

Create a new group
Check the scope menu
The group won't be there.
If you reload the page, you'll see it.

Now delete that group
The menu won't show the change
Reload the page, it's gone.

**Comment by nickstenning** [comment]
This is simply ("simply") a side-effect of the broken websocket server, and will be fixed when #2996 is deployed.

**Comment by nickstenning** [comment]
Fixed (AFAICT) by the release of v0.9.3.
