### ISSUE TITLE
RSS Feeds for tag view is not correct

### ISSUE THREAD

**Issue by cogdog** [hypothesis/h#3003]
Here are tagged annotations for a class project just getting started:
https://hypothes.is/stream?q=tag:inf115

The RSS feed in the source is the general wide hypothesis stream

`<link rel="alternate" type="application/atom+xml" href="https://hypothes.is/stream.atom"/>`
`<link rel="alternate" type="application/rss+xml" href="https://hypothes.is/stream.rss"/>`

but the feeds I found for this tag by guessing are

`https://hypothes.is/stream.rss?tag=inf115`
`https://hypothes.is/stream.atom?tag=inf115`

So feeds are not discoverable (or identified).

**Comment by nickstenning** [comment]
Thanks a lot for filing this issue! We'll triage and take a look at it as soon as possible!

**Comment by judell** [comment]
Hi Alan,

Scanning through various channels I see that I missed this. That was a good guess! https://hypothes.is/blog/using-atom-feeds-to-receive-hypothesis-notifications-in-slack/ illustrates URL patterns for feeds but that, too, is of course not discoverable. 

I'd be interested to check in with you too see how you're using these feeds. Along with the issue of discovery, there are questions about how best to represent evolving threaded conversation in feeds, be they Atom/RSS or other. I'd appreciate your thoughts.

Jon

**Comment by cogdog** [comment]
Thanks Jon,

It was the class in Puerto Rico I was working with; we suggested students tag their annotations with a class tag so there would be URL to see them all together; I used the feed to embed activity into the Wordpress site here (the display is not quite clear, but that's a CSS issue with the theme) 

http://inf115.com/hypothesis/

In this case newest first is ok as a pulse on activity, could also be put in wordpress widget/footer. I'm not sure I would really want to pull out the threaded structure in a feed, makes more sense to see it in hypothes.is

Auto-discovery is not super critical either (to me)- I've been asking for years why Wordpress does not put a discoverable Category/tag feed into it's feeds (it only puts the blog rss feed). Personally I just want to know how to get a feed, be it an icon somewhere, embedded in source, or even just a reference of rules I can use based on URL structure,

**Comment by nickstenning** [comment]
Hi @cogdog! With [the release of our search pages](https://hypothes.is/blog/introducing-search-and-profiles/), we likely won't be making changes to our `/stream.rss` and `/stream.atom` feeds. Indeed, it's likely that over time these will be phased out and replaced by RSS and Atom feeds that correspond directly to the new search pages. As such, I'm going to close this issue.

Internal tracking issue for search RSS/Atom feeds: https://hypothes.is/blog/introducing-search-and-profiles/.
