### ISSUE TITLE
Silent failure to save highlights if logged out

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#3010]
If you have the h extension activated but aren't logged-in then when the sidebar is closed (its default state) there's nothing on screen to show you that you aren't logged in.

If you make a highlight, it looks and behaves exactly like making highlights while logged in, except that the highlights are not saved.

If you then close the tab or go to another page, you lose the highlights.

Additionally, "You must login to create annotations" annotation cards are created in the sidebar for each highlight that you created. You probably won't notice these as the sidebar is closed, and even if you open it they may be scrolled off screen.

I'm not sure what the correct behaviour here is, but the existing behaviour is clearly terrible, needs discussion and design.

**Comment by nickstenning** [comment]
Moved to https://github.com/hypothesis/product-backlog/issues/177.
