### ISSUE TITLE
via.hypothes.is of github.com pages doesn't work in Firefox

### ISSUE THREAD

**Issue by betatim** [hypothesis/h#3027]
Viewing pages on github.com via via.hypothes.is in Firefox doesn't load the annotation sidebar.

For example going to https://via.hypothes.is/https://github.com/hypothesis/h/issues/ doesn't show the sidebar in Firefox 44.0.2 on Mac OS 10.9.5

The JS console contains an error (unsure if related):

<img width="1085" alt="hypothesis" src="https://cloud.githubusercontent.com/assets/1448859/13349717/e6fcc6a2-dc7b-11e5-9ebd-a52c5a2d17de.png">

**Comment by robertknight** [comment]
Thanks for the report. I'll note that this does work in Chrome.

We will look into this but we've also made some improvements to the Chrome extension recently to support GitHub and we'll be bringing those to a new Firefox extension in the not-too-distant future.

**Comment by betatim** [comment]
Thanks. Chrome via.hypo works here too. I tried to find the FF extension but couldn't find it, is there a beta version somewhere for testing?

**Comment by robertknight** [comment]
@betatim - There's no beta available yet but we'll make an announcement via Twitter when there is: https://twitter.com/hypothes_is

**Comment by jibe-b** [comment]
@betatim In case you use irefox + bookmarklet instead of via, websites using Content Protection Policy like github.com can be annotated (in Firefox) by disabling CSP in about:config -> __security.csp.enable__ = _false_ 

see #2794

**Comment by nickstenning** [comment]
Moved to hypothesis/via#96.
