### ISSUE TITLE
share button doesn't send me to share box

### ISSUE THREAD

**Issue by jeremydean** [hypothesis/h#3043]
scrolling through annotations and then deciding to share the doc through the copy and pasteable via link activated by the share button.

clicking the share button jerks the sidebar but doesn't send me to that box, so i don't know if it's there unless i know to scroll up:

http://www.screencast.com/t/jGP1cNItMU4I

i've confirmed this to be a bug both using the extension in chrome and via in firefox.

**Comment by nickstenning** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;phJSNZgR&#x2F;528-bug-share-button-doesn-t-ensure-share-box-is-visible"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> [BUG] Share button doesn&#39;t ensure share box is visible</a>
