### ISSUE TITLE
User's account deleted or reset for mysterious reasons

### ISSUE THREAD

**Issue by lenazun** [hypothesis/h#3061]
This one is coming from support.

### Steps to reproduce
1.  Search user JamieW in our admin panel.  The account appears to be created on 2/29 and have 17 annotations.
2. Restore the ES snapshot of our annotations for 2/25.
3.  Search for JamieW.  Their account had made 30 annotations between 2/3 and 2/22.  The 2/25 is the last snapshot in which they appear.

### Expected behaviour
Our user logs in to an existing account, and finds all their annotations and group memberships in place.

### Actual behaviour
Our user logs in (or signs up again?) for an account, but the account appears new. No group memberships or annotations exist.

### Additional details
Not sure what happened here. Seems like this account got accidentally deleted or reset between 2/25 and 2/26. For that, we should check the logs. 
PS: Can we restore old annotations for this user?

**Comment by nickstenning** [comment]
I've added notes on this to the support case. There's no evidence of a bug, except for the slight issue that we don't confirm before deleting users, which is addressed by #3066.
