### ISSUE TITLE
User is unable to edit an annotation or page note in a specific web page

### ISSUE THREAD

**Issue by lenazun** [hypothesis/h#3062]
### Steps to reproduce
1.  Go here https://slate.adobe.com/cp/uOGoa/
2.  Make an annotation or page note.  
3.  Attempt to edit the annotation or page note

### Expected behaviour
Annotation is saved when clicking on post button.

### Actual behaviour
Internal server error message appears, annotation is not saved. 

### Browser/system information
I was able to repro in Mac OSx Chrome and Firefox.  User appears to be on Windows for Chrome.

### Additional details
The console shows: 
https://hypothes.is/api/annotations/AVNTLqTtH9ZO4OKSlGvq 
Failed to load resource: the server responded with a status of 500 (OK)

User error:
![500error](https://cloud.githubusercontent.com/assets/6117168/13585653/e421600c-e471-11e5-99c1-1c319a3b0e55.jpg)

**Comment by judell** [comment]
The behavior I'm seeing parallels https://github.com/hypothesis/h/issues/3060. At https://slate.adobe.com/cp/uOGoa/ the badge sees two annotations, one by me and one by you. 

And the Chrome extension receives them:

```
rows: [{updated: "2016-03-07T22:23:21.522476+00:00", group: "__world__",…},…]
0: {updated: "2016-03-07T22:23:21.522476+00:00", group: "__world__",…}
created: "2016-03-07T22:23:21.522465+00:00"
document: {link: [{href: "https://slate.adobe.com/cp/uOGoa/"}],…}
group: "__world__"
id: "AVNTLXW1H9ZO4OKSlGvl"
permissions: {read: ["group:__world__"], admin: ["acct:lenazun@hypothes.is"], update: ["acct:lenazun@hypothes.is"],…}
tags: []
target: [{source: "https://slate.adobe.com/cp/uOGoa/", selector: []}]
text: "test"
updated: "2016-03-07T22:23:21.522476+00:00"
uri: "https://slate.adobe.com/cp/uOGoa/"
user: "acct:lenazun@hypothes.is"
1: {updated: "2016-03-07T22:39:38.345173+00:00", group: "__world__",…}
created: "2016-03-07T22:39:38.345161+00:00"
document: {link: [{href: "https://slate.adobe.com/cp/uOGoa/"}],…}
group: "__world__"
id: "AVNTPF1qH9ZO4OKSlGwr"
permissions: {read: ["group:__world__"], admin: ["acct:judell@hypothes.is"], update: ["acct:judell@hypothes.is"],…}
tags: []
target: [{source: "https://slate.adobe.com/cp/uOGoa/", selector: []}]
text: "Test"
updated: "2016-03-07T22:39:38.345173+00:00"
uri: "https://slate.adobe.com/cp/uOGoa/"
user: "acct:judell@hypothes.is"
total: 2
```

But they do not display.

**Comment by chdorner** [comment]
This is one of the related Sentry reports: https://app.getsentry.com/hypothesis/prod/issues/115634690/events/4030020071/

**Comment by judell** [comment]
By way of another support request, I have also reproduced this problem for http://www.lennyletter.com/politics/a275/why-keshas-case-is-about-more-than-kesha/

**Comment by chdorner** [comment]
Okay, editing these annotations works again on staging. The fix will go out to production with the next deploy (probably on Monday).

**Comment by lenazun** [comment]
Verified this fix on staging.  Thank you!

**Comment by chdorner** [comment]
fyi: this has been pushed out to production today.
