### ISSUE TITLE
Exclude public annotations from stream

### ISSUE THREAD

**Issue by ntessore** [hypothesis/h#3071]
I'm trying to use the hypothes.is embedding on a site that is mainly a resource for university research. The site is private in the sense that one needs a particular URL in order to access a page (think Dropbox share link). I would love to be able to have public annotations, but without announcing the existence of individual pages on the public stream. Would it be possible to have an option to disable the streaming of public annotations for specific pages?

**Comment by dwhly** [comment]
Not at present.  We are imagining a range of additional visibility and sharing modes however, several of which would handle this particular case.  The first is Public Groups, which would let you create your own groups, the annotations in which would be visible by anyone, and also a "Link only" annotation view mode, which would let people see annotations to which they had the link.

Closing this for now, as this issues log is for bugs only.  

https://github.com/hypothesis/vision  is a good place for feature requests.

**Comment by ntessore** [comment]
Sorry about that, I didn't realise what the purpose of hypothesis/vision was. For anyone stumbling across this issue, the relevant discussion is at hypothesis/vision#192.

**Comment by dwhly** [comment]
Well to be fair, it's not completely clear! :)
