### ISSUE TITLE
'DELETE FROM feature WHERE feature.name NOT IN (%(name_1)s, %(name_2)s hypothesis

### ISSUE THREAD

**Issue by Piusn** [hypothesis/h#3073]
### Steps to reproduce
1.Install as described in the production deployment

### Expected behaviour
The server should run

If you have other information which might be helpful, please include it. If a
screenshot will help to illustrate the issue you are reporting, please include
one.

**Comment by lenazun** [comment]
Hello @Piusn could you give us a bit more information about what's going on?

- What are you trying to do?
- What steps did you follow to get to the point where you got stuck?
- Do you see any error messages or log messages that may be helpful?

Thank you!

Lena

**Comment by Piusn** [comment]
I got the code run on linux on azure. But am not able to expose port 5000 to the internet so that I can access it via browser.

Any help?

**Comment by nickstenning** [comment]
We can't provide support on running Hypothesis on Azure, as we have no experience doing so. You can always change the port that `gunicorn` listens on, if necessary.

If you're able to provide us with additional details, we'll try and help.
