### ISSUE TITLE
Improving the installation documentation?

### ISSUE THREAD

**Issue by lwm** [hypothesis/h#3092]
I have been able to deploy `h` locally with the following commands:

```
$ git clone https://github.com/hypothesis/h.git h && cd $_
$ make docker
$ docker run -d --name nsqd -p 4150:4150 -p 4151:4151 nsqio/nsq /nsqd
$ docker run -d --name postgres -p 5432:5432 postgres
$ docker run -d --name elasticsearch -p 9200:9200 -p 9300:9300 nickstenning/elasticsearch-icu
$ docker run -it --link postgres:postgres --rm postgres sh -c 'exec psql -h "$POSTGRES_PORT_5432_TCP_ADDR" -p "$POSTGRES_PORT_5432_TCP_PORT" -U postgres -c "CREATE DATABASE htest;"'
```

I really appreciate [the documentation][1] that has been already written. 

However, do you think we could work on making it shorter? 

If you're interested, I can submit a pull request with the following changes.

  - [ ] ~~Reduce/remove the following sections: (Docker covers us)~~
    - ~~[requirements][2] and [instally-system-dependencies][3]~~
  - [x] moving [get-the-h-source][4] section to the top (it appears out of order, IMHO).
  - [x] Changing [virtualenv][5] section to a note, and linking to, say, [this][6] (which I think we can agree is more comprehensive).

And, that's it. The rest is very useful.

[1]: https://h.readthedocs.org/en/latest/hacking/install.html
[2]: https://h.readthedocs.org/en/latest/hacking/install.html#requirements
[3]: https://h.readthedocs.org/en/latest/hacking/install.html#installing-the-system-dependencies
[4]: https://h.readthedocs.org/en/latest/hacking/install.html#get-the-h-source-code-from-github
[5]: https://h.readthedocs.org/en/latest/hacking/install.html#install-h-into-a-python-virtualenv
[6]: http://docs.python-guide.org/en/latest/dev/virtualenvs/

**Comment by nickstenning** [comment]
Hey @lwm. Thank you so much for this. I agree that the dev documentation has got a little wordy. The second and third suggestions in the above list sound great -- please do submit a PR and we'll get that merged.

Changing the documentation to suggesting using the built docker image for dev is a tricky one -- it's certainly doable, but if you're actively working on the application then you'll need to volume mount the source code into the container, which isn't easy to do for people developing on Mac OS X, as they have to run the Docker daemon inside a VM. For now, then, I think I'd prefer us to leave the dev documentation (at least the system dependencies section) as is. We do still document how to run `h` in a container in the [production install docs](https://h.readthedocs.org/en/latest/INSTALL.html).

Thoughts?

**Comment by lwm** [comment]
@nickstenning 

OK, great, so I will submit a PR for the second and third suggestions.

As regards the Docker stuff, you have a good point. In this case, I think an improved introductory paragraph on the [docs][1] would do. Which, would say, that a fully dockerized local setup is supported, and here are the relevant parts to get up and running fast. Good / bad ?

[1]: https://h.readthedocs.org/en/latest/hacking/install.html#installing-h-in-a-development-environment
