### ISSUE TITLE
New larger adder hangs off edge of page sometimes.

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#3100]
### Steps to reproduce
1. Using the stage extension
2. Go to a web page, like this one: https://theintercept.com/2016/03/16/trump-campaign-ads/
3. Select some text, like the whole paragraph beginning with "CBS chief Les Moonves ..."

### Expected behaviour
Adder should be fully within the DOM of the page, such that it's whole surface area is exposed for click/touch.

### Actual behaviour
Note that the adder hangs off the left edge.  It's still clickable here, but if the margin was smaller it's quite possible that the annotate button would be unclickable-- probably especially on mobile.

### Browser/system information
Stage / Latest Chrome

### Additional details
![screenshot 2016-03-16 11 45 07](https://cloud.githubusercontent.com/assets/1413074/13824895/36f10f9c-eb6d-11e5-9897-b21f61f5140f.png)

**Comment by JakeHartnell** [comment]
Looks nice though, like the new icons and that it has words!

**Comment by robertknight** [comment]
The adder positioning logic has been updated since this report was opened to be smarter. It should now always ensure that it appears within the bounds of the viewport.
