### ISSUE TITLE
Direct links to page note (?) not working

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#3103]
### Steps to reproduce
1. In Chrome, with a stage extension installed, go to https://bouncer-stage.hypothes.is/AVODh1WfH9ZO4OKSlQ6p

### Expected behaviour
1. Page navigates to Medium article, sidebar is injected and opens, page note annotation is displayed

### Actual behaviour
1. Page navigates to Medium article, sidebar is injected and opens.
2. The page note is selected according to the 'Clear Selection' button at the top of the sidebar but the annotation card is not visible underneath.

### Browser/system information
Chrome 50, H stage v0.12.26

**Comment by judell** [comment]
Close in favor of https://github.com/hypothesis/h/issues/3137? I don't think there's a pagenote problem in general, e.g. http://blog.jonudell.net/2015/01/22/a-federated-wikipedia/#annotations:AVNToKVKH9ZO4OKSlG8G works fine. I do think there's a Medium problem in particular, and maybe a more general problem having to do with URLs that have their own frag ids.

**Comment by robertknight** [comment]
Yes, this is a duplicate of #3137 and the broader category of sites that modify the URL fragment on page load.
