### ISSUE TITLE
Annotation not in document order

### ISSUE THREAD

**Issue by judell** [hypothesis/h#3106]
### Steps to reproduce
1. Visit https://gamesandlearning.wordpress.com/2016/03/16/playful-annotation-in-the-open-part-2/
2. Verify that sidebar sort is Location

### Expected behaviour
https://hypothes.is/a/AVOEBRmhH9ZO4OKSlQ74 appears second in the sidebar.

### Actual behaviour
It should appear about 2/3 of the way down, to match the target's location in the document.

### Browser/system information
Chrome extension 0.12.0, Windows 10.

**Comment by dwhly** [comment]
Another example: http://blog.jonudell.net/2016/04/02/owning-and-sharing-your-words/

**Comment by robertknight** [comment]
Had a quick look into this. Location sorting is indeed broken in master since 139866134378f9c5c2d41404049f128e9659a9d2 . The issue is that the sort function expects an `Annotation` but is being passed a `Thread`.
