### ISSUE TITLE
JS error at https://www.civilsprep.com, app does not load

### ISSUE THREAD

**Issue by judell** [hypothesis/h#3111]
### Steps to reproduce
1. Visit https://www.civilsprep.com
2. Activate H

### Expected behaviour
H loads

### Actual behaviour
// Polyfills
var g = Annotator.Util.getGlobal();

**Comment by nickstenning** [comment]
Thanks for the report. This seems to be another report of #2723. Closing in favour of that ticket.

**Comment by judell** [comment]
OK, thx.
