### ISSUE TITLE
Sidebar does not appear on site using `<frameset>`

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#3113]
### Steps to reproduce
1. Go to http://yusynth.net/index_en.php or any page which uses `<frameset>` as the `<body>` element.
2. Activate H
### Expected behaviour

Sidebar appears
### Actual behaviour

Sidebar does not appear
### Additional details

This page's HTML is structured as a two-column `<frameset>`.

``` html
<html>
<frameset>
<frame><!-- Code window !--></frame>
<frame><!-- Output window !--></frame>
</frameset>
</html>
```

The H client inserts the sidebar elements after the second `<frame>` element.
### Discussion

Framesets are an obsolete web standard that was removed from HTML5, but does have the advantage for authors that it provides a simple way to create a page with a few drag-resizable columns and there will still be a certain amount of content on the web using them - if we can get usage data from somewhere that might help guide our decision.

Some options:
1. Make an explicit choice not to support them, but at least show a suitable indicator in that case.
2. Inject the sidebar separately into each `<frame>`
3. Try to add an extra frame into the frameset and add H to that.

For all the same-origin frames, option (2) might be the simplest.  The code that injects H in embed.js could simply walk over `window.frames` and run its current injection code on each frame in turn.

**Comment by nickstenning** [comment]
Everything written here is true, but this is definitely new feature development rather than a bugfix. Given that only a very small fraction of websites appear to use framesets these days ([0.4% of the top million](https://trends.builtwith.com/docinfo/Frameset) according to BuiltWith) I'm going to close this.
