### ISSUE TITLE
EBSCOhost direct link not working

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#3122]
Visit https://hyp.is/AVPIPxc2H9ZO4OKSldxe with 1) In in a browser without the Chrome extension, 2) Chrome with the extension

**Expected result**

Page loads, extension activated, page scrolls to annotation

**Actual result**

In scenario 1) Works as expected, in scenario 2) Page loads, extension not activated.

The "#annotations:<id>" fragment is getting rewritten and URL-escaped when the page loads.

**Comment by judell** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;O5KyU1DN&#x2F;309-bug-fix-direct-links-from-replies"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> BUG: Fix direct links from replies</a>

**Comment by robertknight** [comment]
Interesting that this works in Via but not the Chrome extension. My guess is that when the page is loaded through Via, the `embed.js` script runs before the client-side JS that modifies the URL fragment - which presumably runs in response to the 'DOMContentLoaded' or 'load' events.

I suspect that the same would be true of many other sites that modify the URL fragment. In that case, it is mainly the Chrome extension where we'd need to change how we capture the fragment.
