### ISSUE TITLE
Sidebar not opened, annotation not selected when direct-linking to PDF annotation

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#3123]
### Steps to reproduce

With Chrome extension installed, visit a direct link to an annotation on a PDF, eg. https://bouncer-stage.hypothes.is/AVOaGmMVH9ZO4OKSlVVr

### Expected behaviour

PDF loads, Extension activated, Hypothesis PDF viewer loads, sidebar opens and scrolls to annotation

### Actual behaviour

PDF loads, Hypothesis PDF viewer activated but sidebar does not open and does not scroll to annotation

**Comment by judell** [comment]
Observation: The redirected URL in Chrome becomes, e.g., 

chrome-extension://iahhmhdkmkifclacffbofcnmgkpalpoj/content/web/viewer.html?file=http%3A%2F%2Fwww.katecrawford.net%2Fdocs%2FFollowingYou.pdf%23annotations%3AAVOe9U8uH9ZO4OKSlWMQ

Change to:

chrome-extension://iahhmhdkmkifclacffbofcnmgkpalpoj/content/web/viewer.html?file=http%3A%2F%2Fwww.katecrawford.net%2Fdocs%2FFollowingYou.pdf#annotations:AVOe9U8uH9ZO4OKSlWMQ

Now the sidebar opens and acts like an annotation is selected (i.e. Clear Selection appears) but no annotation displays.

**Comment by robertknight** [comment]
This now works with the latest stage extension, however the viewer does not automatically scroll to the annotation when I tested it now. I'll file that as a separate issue.
