### ISSUE TITLE
direct link fails for reply

### ISSUE THREAD

**Issue by judell** [hypothesis/h#3127]
### Steps to reproduce
1.Visit http://www.nytimes.com/2016/02/22/us/politics/delegate-count-leaving-bernie-sanders-with-steep-climb.html?_r=0
2. Click bouncer link on the annotation: OK
3. Click bouncer link on its reply: Nada.

### Expected behaviour
Sidebar opens, annotation focused, reply expanded.

### Actual behaviour
Sidebar displays Clear Selection and says 1 selected annotation, but nothing displays.

**Comment by robertknight** [comment]
@judell - Can you label any new direct linking related bugs with the 'Feature: Direct Linking' label please. That will make it easier to track possible blockers to shipping this.

**Comment by judell** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;O5KyU1DN&#x2F;309-bug-fix-direct-links-from-replies"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> BUG: Fix direct links from replies</a>

**Comment by judell** [comment]
Yep, will do, thx.

**Comment by dwhly** [comment]
A design note (@conordelahunty) here is that when we search for a term in the sidebar, when results come back that are in replies, we collapse the thread both above and below the results. This focuses the user in on exactly which parts are matching, but then lets them click to expand the thread at their direction.  We should do the same here for direct linked replies.

![screen shot 2016-03-26 at 8 41 50 am](https://cloud.githubusercontent.com/assets/1413074/14060905/485747e6-f32f-11e5-97a8-17d7960afdb9.png)
