### ISSUE TITLE
Share a link to an annotation in the proxy view context

### ISSUE THREAD

**Issue by jean** [hypothesis/h#3128]
Use case: I want to share an annotation with someone who isn't necessarily using hypothes.is yet.

### Steps to reproduce
1. Go to e.g. https://via.hypothes.is/https://zachholman.com/posts/deploying-software and make an annotation.
2. (a) Get the link to that annotation, or (b) the _share_ link of the proxy view.
3. Send it to someone.

### Expected behaviour
- 2. (a) The annotation should include a link back to the proxy view filtered to that annotation, or with that annotation selected.
- 2. (b) The recipient should see the link in context on the original article.

### Actual behaviour
The recipient sees https://hypothes.is/a/AVOhqKYVH9ZO4OKSlXB9 which does not show the annotation in context. There is a link back to the original page *without* annotations, but no link to the annotated proxy view.

The [proxy view](https://via.hypothes.is/https://zachholman.com/posts/deploying-software) includes a _share_ icon which shares only the same unfiltered [proxy view](https://via.hypothes.is/https://zachholman.com/posts/deploying-software).

### Browser/system information
Firefox on Linux Mint, no hypothes.is bookmarklet.

**Comment by robertknight** [comment]
As it happens, we're working on this right now. The feature is called "direct links". You can get a flavor of what the experience will look like by visiting this example annotation: https://bouncer-stage.hypothes.is/AVOLZdukH9ZO4OKSlTJX (the actual URL will change to `https://hpt.is/<annotation ID>` soon).

**Comment by robertknight** [comment]
We keep track of feature requests in the hypothesis/vision repository. The existing issue is at https://github.com/hypothesis/vision/issues/87 and we're currently aiming to ship this in a couple of weeks time. Please feel free to add any comments on that issue.

**Comment by jean** [comment]
AWESOME
