### ISSUE TITLE
Sidebar icons busted using bookmarklet in FF on Medium 

### ISSUE THREAD

**Issue by judell** [hypothesis/h#3136]
### Steps to reproduce
1. Visit https://medium.com/@idarosesylvester/when-your-cousin-is-the-supreme-court-nominee-e966f709a41e#.51qhwbwly
2. Activate H bookmarklet
### Expected behaviour

Normal icons
### Actual behaviour

Busted icons
### Browser/system information

FF / Windows

**Comment by nickstenning** [comment]
Another case here, @robertknight, of where moving the bucket bar inside the main client iframe would fix a problem -- in this case CSP-related.

**Comment by nickstenning** [comment]
Thank you for reporting this! I've folded the details into a bug to track this and a number of closely related reports: hypothesis/client#244.
