### ISSUE TITLE
Unable to create annotation in PDF viewer that spans multiple pages

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#3147]
### Steps to reproduce
1. In Firefox, go to https://discovery.csc.ncsu.edu/pubs/CODASPY12.pdf and active Hypothesis
2. Scroll down to the bottom of the first page and make a selection that spans the end of the first page and the start of the second page
3. Click "Annotate" in the adder to create an annotation

### Expected behaviour
A new annotation is created, the sidebar opens and I can enter text for the annotation

### Actual behaviour
The adder (Annotate/Highlight) buttons appear but clicking them does not create a new annotation

### Browser/system information
Tested with Firefox 48a1 on Ubuntu 15.10

### Additional details
Creating a highlight or annotation within a single page works on the same system. In addition to the failure to create an annotation, I see this message in the console: `Rejected untrusted message from https://hypothes.is`

**Comment by nickstenning** [comment]
I'm not sure of the value of tracking this here as a bug. From [the source code](https://github.com/hypothesis/h/blob/83ee8909b70f29ff5810f771cccd5d7a88f67473/h/static/scripts/annotator/anchoring/pdf.coffee#L227-L228), it's clearly a known limitation of the PDF support.

If we want to plan and schedule work to improve this, please feel free to make a card somewhere.
