### ISSUE TITLE
Direct link does not appear if annotation fails to anchor

### ISSUE THREAD

**Issue by judell** [hypothesis/h#3154]
### Steps to reproduce
1. Visit https://hyp.is/ECE1ZsWeS6S2fpf4oM4Qiw
### Expected behaviour

Sidebar open, annotation selected/focused
### Actual behaviour

Sidebar open, no annotation visible, "1 selected annotation"

**Comment by robertknight** [comment]
Anchoring this annotation fails, which is why it doesn't show up in the sidebar. In this case, the annotation was created in late 2014 and the page text has changed completely since then.

**Comment by robertknight** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;5oArw7S6&#x2F;557-what-should-the-client-display-when-a-direct-linked-annotation-fails-to-anchor"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> What should the client display when a direct-linked annotation fails to anchor?</a>

**Comment by nickstenning** [comment]
Noting for @sheetaluk's benefit that this will likely be fixed by the "orphans tab" work.

**Comment by nickstenning** [comment]
Also verified fixed by the orphans tab work /cc @ajpeddakotla.
