### ISSUE TITLE
Some activation emails are failing to be sent

### ISSUE THREAD

**Issue by lenazun** [hypothesis/h#3158]
This one comes from support:

### Steps to reproduce
1.  As an admin, go check on user Elliot, and look at his signup date
2.  Go to our Mandrill outgoing reports, search for his email. No outgoing emails appear.
3.  Somehow this email has failed to send. This has happened to other users (as they've told us via support email)

### Expected behaviour
When the user signs up, an activation email should be sent to their email address.

### Actual behaviour
When the user signs up, we don't send an activation email in all cases.

### Additional details
Happy to provide other users and email addresses as examples, in private.

**Comment by lenazun** [comment]
lightning fast fix from @nickstenning partially addressed by https://github.com/hypothesis/h/pull/3156 (mailer worker had crashed)

**Comment by nickstenning** [comment]
Worth noting I've also added an Icinga check to monitor the length of the mail queue so we should be notified if this happens again.
