### ISSUE TITLE
Broken share link on https://www.eventoring.com/events/view/the-art-of-co

### ISSUE THREAD

**Issue by orschiro** [hypothesis/h#3165]
Dear all, 

I just encountered a broken share link for the following site:

https://www.eventoring.com/events/view/the-art-of-co

The generated share link is https://via.hypothes.is/https://www.eventoring.com/theme/beaut/.

I assume it should be https://via.hypothes.is/https://www.eventoring.com/events/view/the-art-of-co

Warmly,

~Robert

**Comment by nickstenning** [comment]
Hi Robert. This page contains the following metadata:

`<link rel='canonical' href='/theme/beaut/' />`

That's picked by Hypothesis and interpreted as being the correct "canonical" link to the document. If you want to fix the share link, you'll need to fix the page metadata.

**Comment by orschiro** [comment]
Dear @nickstenning,

Thanks for the finding.

I will pass it on to the Eventoring people!

Thankfully,

~Robert
