### ISSUE TITLE
"You do not have permission to see this annotation" shown briefly before annotation appears

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#3167]
### Steps to reproduce

1. Run h locally
2. Run bouncer locally
3. Serve a PDF file at localhost (using `python -m SimpleHTTPServer`)
4. Open the localhost PDF file in the browser, activate h, make an annotation, get and follow the direct link to the annotation

I've only been able to reproduce the annotation using a PDF, though I'm not sure the file being a PDF has anything to do with the bug.

### Expected behaviour

The annotation should just be shown, with no "You do not have permission to see this annotation" card shown in its place before it appears.

### Actual behaviour

A "You do not have permission to see this annotation" card appears briefly in the sidebar, then is replaced by the annotation:

![](https://cloud.githubusercontent.com/assets/22498/14187219/e33afc8c-f779-11e5-90ca-1a6fcbff6865.gif)

### Browser/system information

Chrome 49.0.2623.75 (64-bit), Ubuntu Gnome 15.10, Hypothesis master branch.

### Additional details

It looks like we don't distinguish between annotations that are unavailable because they haven't been received or threaded yet, and ones that the user doesn't have permission to see: <https://github.com/hypothesis/h/blob/932c06a14fc9444fdb0f7b49fc833990e10b4a63/h/static/scripts/widget-controller.js#L208>.

**Comment by robertknight** [comment]
This should be partially resolved by https://github.com/hypothesis/h/pull/3169 . There is still a period of time between annotations being loaded and them being anchored in the page which could result in this message being displayed, but that is much shorter than the potentially arbitrary delay whilst making an API call.

Could you test with that branch @seanh ?

**Comment by nickstenning** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;gXYtlAja&#x2F;569-misleading-message-while-an-accessible-direct-link-annotation-loads"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Misleading message while an accessible direct-link annotation loads</a>

**Comment by seanh** [comment]
Confirm that I can still reproduce this on master today
