### ISSUE TITLE
Direct link into PDF annotation does not reliably scroll to content

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#3174]
### Steps to reproduce
1. Follow the original steps to reproduce in https://github.com/hypothesis/h/issues/3123

### Expected behaviour
PDF viewer loads, sidebar opens, annotation is selected and viewer is scrolled to the annotation.

### Actual behaviour
PDF viewer loads, sidebar opens, annotation is selected but viewer does not scroll to annotation.

### Browser/system information
Chrome with Hypothesis v0.15.0.27

**Comment by nickstenning** [comment]
Can't repro.
