### ISSUE TITLE
document.link is undefined error 

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#3205]
### Steps to reproduce
Visit http://networkedlearningcollaborative.com/wp-content/uploads/2016/01/elementary-literacy_1301429871069-1.pdf through Via or the Chrome extension and wait a painfully long time for the annotations to load. The issue is also visible at https://via.hypothes.is/http://langsci-press.org/public/site/pdf/MuellerOpenReview1.pdf

### Actual behaviour
Eventually, a series of `...document.link is undefined` error messages appear in the console

### Browser/system information
Firefox 48

### Additional details
Seen at https://app.getsentry.com/hypothesis/prod-client/issues/122403203/

This annotation has a `uri` field but the `document` field is empty: https://hypothes.is/api/annotations/SzJR06pBS8qPmzB9xJsvBQ

**Comment by robertknight** [comment]
I tested this just now and could not reproduce. It seems possible this might have been fixed by the Postgres migration @chdorner ?

**Comment by chdorner** [comment]
Yes, we know [always add at least an empty array](https://github.com/hypothesis/h/blob/master/h/api/presenters.py#L160) in the presenter.
