### ISSUE TITLE
Post annotation button not activating

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#3212]
Someone been messing with AnnotationController? :)

![untitled screencast 12](https://cloud.githubusercontent.com/assets/22498/14530008/efbd65b4-024e-11e6-90d0-4e8e0365f936.gif)

(When you create a new annotation and type something in the textarea that post button does not become active, clicking on it does nothing. In the gif you can see it activate when I click elsewhere in the window to turn off screencastify)

**Comment by robertknight** [comment]
I think this is related to some recent changes in the markdown editor. I'm looking into it.
