### ISSUE TITLE
Setting up for a production

### ISSUE THREAD

**Issue by Piusn** [hypothesis/h#3223]
I am new to linux but I know a few administration tasks and would like install h in a production environment. I have looked at the documentation for production setup but I have a couple of questions:

1. What environment do I need to install the production h. Windows or linux? What would be an ideal one environment?

2. Where do I se the API_URL and SECRET_KEY?

3. Also in the production procedure it is indicated that you also need to set up the following:
    -  ALLOWED_ORIGINS 
    - CLIENT_ID 
    - CLIENT_SECRET 
    -  ELASTICSEARCH_INDEX 
    - MAIL_DEFAULT_SENDER

 Where exactly should I set the above configuration settings?

4. Is there a way I can set up the development deployment and still use for production purposes?

5. Can I set h in azure linux vm?

You response is highly regarded.

**Comment by nickstenning** [comment]
Hi @Piusn. I don't know if you're still having problems, and I'm sorry this appears to have slipped through the cracks, but I'd suggest emailing [our developer mailing list](https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev) if you still need help. We're trying to keep the issue tracker for bugs only.
