### ISSUE TITLE
Internal server error when saving updated annotation on IETF RFC

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#3239]
### Steps to reproduce
1. Create a new annotation on https://tools.ietf.org/html/rfc6454#page-12
2. Edit the annotation, changing the tags or text

### Expected behaviour
The annotation edit should be successfully saved

### Actual behaviour
Saving the update fails with a 500 error, which looks like it is this Sentry report: https://app.getsentry.com/hypothesis/prod/issues/115634690/

**Comment by robertknight** [comment]
Slack discussion: https://hypothes-is.slack.com/archives/public/p1461234277000541

**Comment by lenazun** [comment]
I may have another example of what was mentioned in the Slack discussion, with a different error. 

When trying to annotate http://www.mayoclinicproceedings.org/article/S0025-6196(15)00319-5/fulltext 
I get a 500 error. 

This is the Sentry report:
https://app.getsentry.com/hypothesis/prod/issues/124187353/

In this case: 
TransportError(500, u'IllegalArgumentException[Document contains at least one immense term in field="_all" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped. Please correct the analyzer to not produce such terms. The prefix of the first immense term is: \'[50, 48, 49, 54, 45, 48, 52, 45, 50, 49, 84, 49, 55, 58, 53, 49, 58, 48, 48, 46, 48, 54, 57, 48, 56, 52, 43, 48, 48, 58]...\', original message: bytes can be at most 32766 in length; got 46390]; nested: MaxBytesLengthExceededException[bytes can be at most 32766 in length; got 46390]; ')

**Comment by seanh** [comment]
I can't reproduce this locally or on prod with either URL. Close?

**Comment by robertknight** [comment]
I cannot reproduce any either, including with the original annotation where I experienced the problem.
