### ISSUE TITLE
erroneous document equivalence at http://www.digitalpedagogylab.com

### ISSUE THREAD

**Issue by judell** [hypothesis/h#3249]
### Steps to reproduce

1.  Visit (as one example) http://www.digitalpedagogylab.com/hybridped/teaching-in-our-right-minds/ 

2. Check annotations returned for it: https://hypothes.is/api/search?uri=http%3A%2F%2Fwww.digitalpedagogylab.com%2Fhybridped%2Fteaching-in-our-right-minds%2F

3. Note differing values in the source field:

"source": "http://www.digitalpedagogylab.com/hybridped/values-driven-framework-digital-humanities-pedagogy/",

"source": "http://www.digitalpedagogylab.com/hybridped/in-public-the-shifting-consequences-of-twitter-scholarship/",

"source": "http://www.digitalpedagogylab.com/hybridped/the-discussion-forum-is-dead-long-live-the-discussion-forum/"

"source": "http://www.digitalpedagogylab.com/hybridped/working-inat-public/",

"source": "http://www.digitalpedagogylab.com/hybridped/breaking-binary-facebook-teachable-moments/",

### Expected behaviour
Only annotations for http://www.digitalpedagogylab.com/hybridped/teaching-in-our-right-minds/  should appear.

### Actual behaviour
None do but annotations from other http://www.digitalpedagogylab.com articles show up.

### Additional details
The site declares:

&lt;link rel="alternate" type="application/rss+xml" title="Hybrid Pedagogy &raquo; Feed" href="http://www.digitalpedagogylab.com/hybridped/feed/" />

I don't think that's a change, but I wonder if it interacts badly with https://github.com/hypothesis/h/pull/3241

**Comment by nickstenning** [comment]
The problem here is that "return all canonical URIs" is still problematic if all those canonical URIs are bound together in a single document object by some other URI that we should be ignoring for equivalence purposes.

**Comment by judell** [comment]
Is the RSS feed in fact the bridging URI in this case?

**Comment by nickstenning** [comment]
Not sure at the moment. That'll require a bit more investigation.
