### ISSUE TITLE
"links" field appearing in new Es index

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#3261]
`AnnotationJSONPresenter` adds a (generated, not stored in db) "links" fields to the annotations we return from the API. <https://github.com/hypothesis/h/pull/3256/commits/fff6df028f1c524559569da120ead615ba385a64> makes sure this field doesn't get into the Pg database. But the "links" field is still appearing in the new Es index (but not in the legacy index). The reason is that `AnnotationJSONPresenter` is used to dictize the annotations for going into the new Es index.

Design problem?

Using `AnnotationJSONPresenter` for both means a 1:1 mapping between what annotations look like in Es and what our API returns.

Seems we probably want two different presenter classes?

**Comment by seanh** [comment]
@nickstenning @chdorner What do we want to do about this? How about the suggestion to add a new `AnnotationSearchIndexPresenter` for presenting annotations? Or instead of a presenter class just add a new `h.api.search.transform.transform()` function for converting an annotation to a dict? (Will need to add the `transform` module as well)

**Comment by seanh** [comment]
The problem is this line: https://github.com/hypothesis/h/blob/master/h/api/search/index.py#L31

**Comment by seanh** [comment]
Actually it looks like there's only one `index()` function where this annotation -> dict for search indexing transformation needs to be done, so it can just be done inline in that function, or as a private helper function of that function, doesn't need a `transform` module

**Comment by chdorner** [comment]
@seanh I'm just working on the second place where that is needed: https://github.com/hypothesis/h/blob/pg-es-reindex/h/indexer.py#L93

I generally like the idea of a specific search presenter, the only problem I see at the moment is that we still return the JSON returned by ElasticSearch back to the client, so if we decide to create a search presenter it will have to stay in sync with the `AnnotationJSONPresenter`.

**Comment by seanh** [comment]
Right. Until the postgres migration is finished and the legacy Es storage is gone I think the annotations in the new Es search index should be exactly the same as the annotations in the legacy Es database. Then once the migration is finished and the legacy Es storage is gone we'll no longer be returning data from Es to the user (not even indirectly by passing it through `AnnotationJSONPresenter` first or anything), we'll be getting the Postgres annotation model object(s) and presenting them with `AnnotationJSONPresenter` and returning them. So at that point a search presenter could diverge from `AnnotationJSONPresenter` as much as we wanted. But for now it would be the same except without the "links" field.

I'm actually a little confused about what our presenter classes are for. Are they just for turning annotations into different kinds of dicts? They all have `asdict()` methods. Or are they meant to be objects that wrap an annotation and provide a bunch of convenience properties and methods? They all have some of those too. I guess it's both?

Presenters does seem to be the place where we put methods that return dicts of model objects, so that argues for a new search index presenter class. On the other hand all we need is a function that takes an annotation and returns a dict, we don't really need a class.

**Comment by chdorner** [comment]
I'm fine with waiting until we successfully switched over, having the `links` in the ElasticSearch index is not great but it isn't the end of the world. Even when querying the new index, we still parse these annotation JSON structures with `elastic.Annotation` and then run them through the presenter, right? 

> I'm actually a little confused about what our presenter classes are for. Are they just for turning annotations into different kinds of dicts? They all have asdict() methods. Or are they meant to be objects that wrap an annotation and provide a bunch of convenience properties and methods? They all have some of those too. I guess it's both?

It is both, yes. It is used to turn an annotation model into a dict for JSON serialization (or other uses), and easier implementation is a class wrapping the annotation and providing properties. These properties can and should also be used in other parts of the code if they provide some value over directly using the annotation class properties themselves.
