### ISSUE TITLE
Via proxy fails on AMS PDFs

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#3266]
### Steps to reproduce
1. Open https://via.hypothes.is/http://journals.ametsoc.org/doi/pdf/10.1175/JAMC-D-15-0287.1

### Expected behaviour
App should be visible

### Actual behaviour
PDF displays, but app doesn't show

### Browser/system information
Chrome

**Comment by nickstenning** [comment]
Closing as I can't replicate this, because the PDF is paywalled. If you have another example, please feel free to reopen.
