### ISSUE TITLE
Sidebar cards don't scroll on Safari

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#3268]
### Steps to reproduce
1. On iOS (9.3.1) Safari
2. Load via.hypothes.is/example.com
3. Open the sidebar
4. Try to scroll the cards with your finger
### Expected behaviour

The cards should scroll up so that you can see ones further down.
### Actual behaviour

The background page (example.com) scrolls up and down instead, but the cards stay fixed in the sidebar.
### Browser/system information

Current Safari, iOS 9.3.1
### Additional details

Screencast: https://www.youtube.com/watch?v=xEvTE3n9Vcw

**Comment by robertknight** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;zvmbTi4a&#x2F;328-spike-suggest-improvements-to-mobile-touch-support"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> [SPIKE] Suggest improvements to mobile&#x2F;touch support</a>

**Comment by nickstenning** [comment]
Moved to https://github.com/hypothesis/client/issues/250.
