### ISSUE TITLE
Via proxy fails on https://hyp.is/AVR15vOHFtPwhMO7DeOd/www.justinobeirne.com/essay/what-happened-to-google-maps

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#3269]
### Steps to reproduce
1. Visit https://hyp.is/AVR15vOHFtPwhMO7DeOd/www.justinobeirne.com/essay/what-happened-to-google-maps in a browser without the H extension
### Expected behaviour

Annotation shown in context
### Actual behaviour

Page content not shown, annotation not displayed.

![squarespace-via](https://cloud.githubusercontent.com/assets/2458/14979295/5084dc50-1119-11e6-86eb-2230e3aafb2f.png)

**Comment by nickstenning** [comment]
Perhaps open this issue against via?

**Comment by nickstenning** [comment]
The issue with the underlying website appears to have been resolved. The annotation has gone walkies, but that's because the URL changed from `/essay/what...` to `/what...`.

Closing.
