### ISSUE TITLE
Focusing annotation does not scroll page in Firefox

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#3270]
### Steps to reproduce
1. Visit http://www.justinobeirne.com/essay/what-happened-to-google-maps#annotations:AVR15vOHFtPwhMO7DeOd in Firefox
2. Click the annotation
### Expected behaviour

Page scrolls to annotated content
### Actual behaviour

Annotated content is highlighted by clicking the annotation does not scroll the page
### Browser/system information

Tested with Firefox v49 and v46 on Linux.
### Additional details

In Chrome 50, the page does scroll to the annotation.

**Comment by nickstenning** [comment]
Moved to https://github.com/hypothesis/client/issues/246.
