### ISSUE TITLE
Inner ranges not highlighted when anchoring nested annotations using quotes or text positions

### ISSUE THREAD

**Issue by judell** [hypothesis/h#3278]
## Update

_When anchoring two or more annotations using quote or position selectors, such that one annotation is partially or entirely contained within another, anchoring fails to wrap the inner annotation in a highlight span. As a result, clicking the inner text does not display the corresponding annotation in the sidebar. See https://github.com/hypothesis/h/issues/3278#issuecomment-217466106 for a minimal test case._

## Original Description

At http://jonudell.net/h/sitc-sulfate.html, consider two paragraphs. Para 1 begins "Under the anaerobic conditions..." and para 2 (immediately following) begins "Sulfate in sewage..."

Para 1 contains this annotation: http://jonudell.net/h/sitc-sulfate.html#annotations:AVPS1ONYH9ZO4OKSlgOL. That direct link does the expected thing (i.e. the card is selected in the sidebar, the doc scrolls to the highlight).

![image](https://cloud.githubusercontent.com/assets/46509/15030031/1807b266-1205-11e6-9a32-293e44a20a22.png)

But there's a nested annotation that we cannot see (i.e., that does not appear with a darker highlight) and that does not sync with the sidebar when following the direct link:

![image](https://cloud.githubusercontent.com/assets/46509/15030204/ccae2588-1205-11e6-88eb-50af1493f511.png)

http://jonudell.net/h/sitc-sulfate.html#annotations:AVPS1PxNH9ZO4OKSlgO3

```
                {
                    "type": "TextQuoteSelector",
                    "prefix": "fide in gravity sewer sections, ",
                    "exact": "sewage pumping stations",
                    "suffix": ", and inlet structures of wastew"
                }
```

Contrast this with para 2 where the sentence beginning "Coagulation plays an important role" has a nested annotation on "disinfection by-products".

A direct link to the outer annotation: 

http://jonudell.net/h/sitc-sulfate.html#annotations:AVPS1Nu2H9ZO4OKSlgN9

![image](https://cloud.githubusercontent.com/assets/46509/15030324/88913cea-1206-11e6-8e30-cfd8f1d96b4c.png)

To the inner annotation:

http://jonudell.net/h/sitc-sulfate.html#annotations:AVPS1NUHH9ZO4OKSlgNx

![image](https://cloud.githubusercontent.com/assets/46509/15030356/ab8a37c4-1206-11e6-94c7-89daa0eb778f.png)

Why the difference between para 1 and para 2?

**Comment by judell** [comment]
More data: pairs of annotations on that page that do (Yes) and don't (No) exhibit this behavior:

Yes

AVPS1ONYH9ZO4OKSlgOL, AVPS1POgH9ZO4OKSlgOn

AVPS1ObGH9ZO4OKSlgOR, AVPS1PKdH9ZO4OKSlgOl

AVPS1Nu2H9ZO4OKSlgN9, AVPS1PtSH9ZO4OKSlgO1

AVPS1ORZH9ZO4OKSlgON, AVPS1OjfH9ZO4OKSlgOV

AVPS1Nu2H9ZO4OKSlgN9, AVPS1OEtH9ZO4OKSlgOH

AVPS1Nu2H9ZO4OKSlgN9, AVPS1OnvH9ZO4OKSlgOX

AVPS1ONYH9ZO4OKSlgOL, AVPS1PxNH9ZO4OKSlgO3

AVPS1Nu2H9ZO4OKSlgN9, AVPS1OxaH9ZO4OKSlgOb

AVPS1ObGH9ZO4OKSlgOR, AVPS1PGAH9ZO4OKSlgOj

No

AVPS1NGSH9ZO4OKSlgNr, AVPS1PllH9ZO4OKSlgOx

AVPS1PcBH9ZO4OKSlgOt, AVPS1Pf9H9ZO4OKSlgOv

AVPS1NUHH9ZO4OKSlgNx, AVPS1Nu2H9ZO4OKSlgN9

**Comment by robertknight** [comment]
The problem with the pair of annotations in the example, AVPS1ONYH9ZO4OKSlgOL (outer) and AVPS1PxNH9ZO4OKSlgO3 (inner) happens when all other annotations are excluded from the page and only if the annotations are loaded in that order. If the order in which the annotations are anchored is reversed, the problem does not occur.

**Comment by robertknight** [comment]
Minimal HTML document which demonstrates the problem:

```html
<html>
  <head>
    <link rel="canonical" href="http://scienceintheclassroom.org/research-papers/254/university">
  </head>
<body>
<div>
	Under the anaerobic conditions common in sewage, sulfate is reduced to hydrogen sulfide by sulfate-reducing bacteria (<a href="http://www.sciencemag.org/content/345/6198/812.full#ref-3" id="xref-ref-3-1">3</a>).
 The emission of hydrogen sulfide in gravity sewer sections, sewage 
pumping stations, and inlet structures of wastewater treatment plants 
induces sulfide oxidation to form corrosive sulfuric acid on concrete 
surfaces exposed to air (<a href="http://www.sciencemag.org/content/345/6198/812.full#ref-4" id="xref-ref-4-1">4</a>,&nbsp;<a href="http://www.sciencemag.org/content/345/6198/812.full#ref-5" id="xref-ref-5-1">5</a>).
 The presence of sulfate in wastewater and its conversion to sulfide in 
anaerobic sewers are generally considered unavoidable, and water 
utilities around the world have been focusing on the removal of sulfide 
after its formation (<a href="http://www.sciencemag.org/content/345/6198/812.full#ref-3" id="xref-ref-3-2">3</a>,&nbsp;<a href="http://www.sciencemag.org/content/345/6198/812.full#ref-5" id="xref-ref-5-2">5</a>–<a href="http://www.sciencemag.org/content/345/6198/812.full#ref-7" id="xref-ref-7-1">7</a>), incurring mitigation costs comparable to the value of asset losses (<a href="http://www.sciencemag.org/content/345/6198/812.full#ref-3" id="xref-ref-3-3">3</a>).</div>
</body>
</html>
```

In this paragraph, the phrase "sewage pumping stations" should be highlighted twice and two annotations should appear when the phrase is clicked. However it is highlighted only once.

**Comment by robertknight** [comment]
It appears that having two overlapping annotations with only text quote selectors triggers the problem. Minimal versions of the annotations that trigger the issue with the above document:

```js
[{
  id: 'outer',
  uri: 'http://scienceintheclassroom.org/research-papers/254/university',
  target: [{
    selector: [{
      type: 'TextQuoteSelector',
      exact: 'sections, sewage pumping stations, and inlet structures'
    }],
  }],
},{
  id: 'inner',
  uri: 'http://scienceintheclassroom.org/research-papers/254/university',
  target: [{
    selector: [{
      type: 'TextQuoteSelector',
      exact: 'sewage pumping stations',
    }],
  }],
}];
```

**Comment by robertknight** [comment]
The same problem occurs if the annotations only have text position selectors. The following does not show overlapping highlights:

```js
[{
  id: 'outer',
  uri: 'http://scienceintheclassroom.org/research-papers/254/university',
  target: [{
    selector: [{
      type: 'TextPositionSelector',
      start: 10,
      end: 100,
    }],
  }],
},{
  id: 'inner',
  uri: 'http://scienceintheclassroom.org/research-papers/254/university',
  target: [{
    selector: [{
      type: 'TextPositionSelector',
      start: 30,
      end: 80,
    }],
  }],
}];
```

With a range selector however, overlapping highlights are seen:

```js
[{
	id: 'outer',
	uri: 'http://scienceintheclassroom.org/research-papers/254/university',
	target: [{
		selector: [{
			type: 'RangeSelector',
			startContainer: '/div[1]',
			startOffset: 10,
			endContainer: '/div[1]',
			endOffset: 100,
		}],
	}],
},{
	id: 'inner',
	uri: 'http://scienceintheclassroom.org/research-papers/254/university',
	target: [{
		selector: [{
			type: 'RangeSelector',
			startContainer: '/div[1]',
			startOffset: 20,
			endContainer: '/div[1]',
			endOffset: 80,
		}],
	}],
}];
```

**Comment by robertknight** [comment]
I have an integration test which reproduces the problem. The issue occurs when anchoring the nested annotations concurrently, ie. by calling `Guest#anchor` (in guest.coffee) for each annotation and then waiting for anchoring for all of the annotations to complete. If on the other hand each annotation is anchored in turn then the result is correct.

**Comment by robertknight** [comment]
So the root issue here is that when overlapping annotations are highlighted concurrently, the DOM can be mutated in between an annotation being located and its corresponding ranges being highlighted.

## Approach 1

Remove the concurrency when anchoring annotations in response to an 'annotationLoaded' event and instead locate and then highlight each annotation in turn. This I think could be relatively simple to implement but I'm uncertain about the consequences for anchoring performance.

## Approach 2

_If_ there is a performance problem with the first approach, this would mitigate that by anchoring concurrently where possible and serializing anchoring only for overlapping annotations.

One approach to fixing this problem would be to separate out the location of annotations and the highlighting into two separate passes. In the first pass, locate the annotations in the document without making any DOM changes and partition the annotations into non-overlapping subsets. The non-overlapping subsets can be anchored concurrently. Within each subset, annotations need to be anchored one by one.

1. Locate all annotations in the document without making any modifications to the DOM
2. Split resulting annotations into subsets with non-overlapping ranges
3. Concurrently anchor each subset

Where _anchoring each subset_ involves:

1. Removing one annotation from the set, locating it in the document and adding highlights
2. If the set is non-empty, go to step 1

Another approach would be to make the anchoring process entirely synchronous which would avoid the problem by making sure that the DOM is not mutated between an annotation being located in the document and the resulting ranges being highlighted.

**Comment by judell** [comment]
The solution here was to sort annotations by range size, largest to smallest, then anchor them.
