### ISSUE TITLE
Hypothes.is zotero 

### ISSUE THREAD

**Issue by bijang** [hypothesis/h#3292]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen.

### Actual behaviour
Tell us what happens instead.

### Browser/system information
Tell us which browser, browser version, and operating system you were using when
you encountered this issue.

### Additional details
If you have other information which might be helpful, please include it. If a
screenshot will help to illustrate the issue you are reporting, please include
one.

**Comment by bijang** [comment]
Hi I'm a non programmer outsider and just found a separate discussion here after searching zotero hypothes.is as I thought it would be a good idea to,  someday , have private and or public hypothes.is generated annotations, highlights and notes, exported into zotero the way zotfile does for certain pdf viewers currently. I think it's important to consider where annotations will be used and was inspired by docear which imports annotations from certain pdf viewers, into an outliner in the form of a mindmap (freemind)  with jabref integration taking care of citation, and export to Word (Microsoft only so far). Zotfile provides similar tools, with them plain text export to, for one, emacs orgmode for outlining and further work. This is a superior method I think for many reasons. Integration with hypothes.is would be a dream, to selectively export the private/ones own /or entire collaborative annotations, into zotero, like zotfile with appropriate citation and page indexing etc. Would this be possible? If my question is out of turn out in the wrong place or this is an inappropriate use of a thread, apologies, i'm just very excited about this concept being developed, as much as I am about hypothes.is coming to Firefox and epub.js + hypothes.is! 
Thank you for your time and work on this amazing project

**Comment by nickstenning** [comment]
Hi @bijang, and thanks for your enthusiasm for the project! The subject of Zotero integration has come up a couple of times in the past, and it's certainly something we'd like to provide in the future, although we're not in a position to make any commitments on timelines at the moment.

As we don't use this issue forum to keep track of feature requests, I'm going to close this issue.

**Comment by akuckartz** [comment]
It probably would be helpful to provide information where this feature request is tracked.

**Comment by katrinleinweber** [comment]
@akuckartz: They're tracked in https://github.com/hypothesis/product-backlog/issues :-)
