### ISSUE TITLE
Client reporting wrong (cached?) document uris when historyPushState is used

### ISSUE THREAD

**Issue by chdorner** [hypothesis/h#3297]
### Steps to reproduce
1. Go to https://docs.angularjs.org/guide
2. Activate the sidebar
3. Click on "Controllers" in the TOC on the left (this is using historyPushState rather than loading the new page)
4. Create an annotation

### Expected behaviour
The annotation should look like this:

```javascript
{
  # ...
  "uri": "https://docs.angularjs.org/guide/controller",
  "document": {
    # ...
    "link": [
      { "href": "https://docs.angularjs.org/guide/controller" }
    ]
  }
}
```

### Actual behaviour
The annotation looks like this:

```javascript
{
  # ...
  "uri": "https://docs.angularjs.org/guide/controller",
  "document": {
    # ...
    "link": [
      { "href": "https://docs.angularjs.org/guide/controller" },
      { "href": "https://docs.angularjs.org/guide" }
    ]
  }
}
```

### Browser/system information

```
Version: 0.21.0
User agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36
URL: https://docs.angularjs.org/guide
Username: chdorner
Date: 09 May 2016 18:36:11 +0200
```

**Comment by robertknight** [comment]
Just repeating some notes I posted on the eng@ mailing list:

This is not so much a bug as a missing feature. Right now the client essentially does not support single page applications that do client-side routing. The most obvious problem is that the loaded
annotations do not change as you navigate around an app, the client does not load annotations that correspond to the new URL. You can see this if you try to annotate a page on GitHub and then navigate to another part of the GitHub UI via links on the page.

**Comment by chdorner** [comment]
Moving this into a card and closing the issue: https://trello.com/c/juStn6l5/600-support-single-page-applications-that-use-client-side-routing
