### ISSUE TITLE
Sidebar tutorial title CSS broken

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#3325]
Recording this now so I don't forget (I don't have time to fix it now).

The title got bigger:

![screenshot from 2016-05-12 19-00-23](https://cloud.githubusercontent.com/assets/22498/15224936/ceda7e0a-1873-11e6-8140-c70529fc76c6.png)

How it used to look:

![](https://cloud.githubusercontent.com/assets/22498/12206960/d2863eee-b63b-11e5-9724-6b6431775545.png)

**Comment by robertknight** [comment]
This is one of the first things a new user sees so important to get this fixed. Possibly separately the design needs to be updated to match the new style for annotation cards.

**Comment by conordelahunty** [comment]
Good catch Sean, thank you.
