### ISSUE TITLE
Lists aren't displayed correctly

### ISSUE THREAD

**Issue by tech4david** [hypothesis/h#3331]
### Steps to reproduce
1. Add a new annotation
2. Include a list (ordered or unordered) in markdown format
3. Confirm the annotation

### Expected behaviour
The bullet points / numbers should be displayed in the annotation.

### Actual behaviour
Bullet points / numbers aren't displayed, only shown when editing the annotation.

### Solution
Change `ul,li{padding:0;margin:0;list-style:none}` to `ul,li{padding:0;margin:0}` in `/assets/styles/app.css`

### Browser/system information
Version 0.22.0 in Chrome 52

### Additional details
If you have other information which might be helpful, please include it. If a
screenshot will help to illustrate the issue you are reporting, please include
one.

**Comment by nickstenning** [comment]
Thank you for taking the time to report this bug. I've checked it out and I can confirm the issue you're seeing. We'll try and get this fixed as soon as we can.

**Comment by nickstenning** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;PNFAzZtH&#x2F;607-bug-lists-aren-t-displayed-correctly-3331"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> [Bug] Lists aren&#39;t displayed correctly #3331</a>

**Comment by nickstenning** [comment]
This bisects to 9be804d.
