### ISSUE TITLE
a ":" in the tag name does not get used properly when searching

### ISSUE THREAD

**Issue by satra** [hypothesis/h#3338]
### Steps to reproduce
1. https://hypothes.is/stream
2. search for CRNC:training (this is a tag i used)

### Expected behaviour
Should only return the tagged articles

### Actual behaviour
the colon gets stripped and essentially you got CRNC or training annotations

### Browser/system information
chrome

@yarikoptic - reported issue

**Comment by yarikoptic** [comment]
possibly related so decided to file here:  https://hypothes.is/stream?q=tag:CRNC doesn't include posts with 3 levels separated with two :s, e.g. those like https://hypothes.is/stream?q=tag:CRNC:TRD3:resource

**Comment by nickstenning** [comment]
Hi, thanks for reporting this. If you search for "CRNC:training" on its own then it will be treated as a full-text search and split up into its component parts: "CRNC" and "training".

If you want to search just by a tag, then you can search for "tag:CRNC:training", [like this](https://hypothes.is/stream?q=tag:CRNC:training) and it will do what you want.

If you want to search for components of a tag, then you can just use the full-text search option, @yarikoptic.

So this is all working as expected at the moment. To summarise:

- If you want to search for an exact tag, use "tag:<tagname>"
- If you want to be more lenient, use a full-text search by searching for "<tagname>" on its own.

**Comment by yarikoptic** [comment]
got it -- thanks!

On Fri, 10 Jun 2016, Nick Stenning wrote:

>    Hi, thanks for reporting this. If you search for "CRNC:training" on its
>    own then it will be treated as a full-text search and split up into its
>    component parts: "CRNC" and "training".

>    If you want to search just by a tag, then you can search for
>    "tag:CRNC:training", like this and it will do what you want.

>    If you want to search for components of a tag, then you can just use the
>    full-text search option, @yarikoptic.

>    So this is all working as expected at the moment. To summarise:

>      * If you want to search for an exact tag, use "tag:"
>      * If you want to be more lenient, use a full-text search by searching
>        for "" on its own.

-- 
Yaroslav O. Halchenko
Center for Open Neuroscience     http://centerforopenneuroscience.org
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik
