### ISSUE TITLE
Clicking on a tag within stream shouldn't open a new tab/window

### ISSUE THREAD

**Issue by yarikoptic** [hypothesis/h#3339]
### Steps to reproduce
1. go to /stream
2. click on any tag within any post
### Expected behaviour

Should open the target page in the same browser page.
It is up to the user to decide when to open a new tab/window, especially the ones leading to the same site/page
### Actual behaviour

Clicking on a tag (e.g. CRNC:TRD3:resource here) within a post e.g. on https://hypothes.is/stream?q=tag:CRNC:TRD3:resource opens a new tab leading to the same page.  
### Browser/system information

chromium 
Version 50.0.2661.94 built on Debian stretch/sid, running on Debian stretch/sid (64-bit)
### Additional details

Some might consider this not a bug and a feature and thus worth discussing on a mailing list first, but IMHO it is as a feature as would be bike wheels on a car these days 

great job otherwise! ;)

**Comment by nickstenning** [comment]
Thanks for reporting this issue, @yarikoptic! You'll be glad to know that our new [search pages](https://hypothes.is/blog/introducing-search-and-profiles/) no longer open tag searches in a new window.

The issue you describe with the `/stream` pages remains, but these are "legacy" pages which will slowly be phased out as we improve the search pages.
