### ISSUE TITLE
New annotations not moved to current group when switching groups

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#3380]
### Steps to reproduce
1. Create a new annotation whilst a group _A_ is selected, but don't publish it
2. Switch groups

### Expected behaviour
Annotation should move to new group

### Actual behaviour
Annotation does not move to new group.

### Browser/system information
Firefox 48

### Additional details
- Behavior should be the same whether or not the annotation has any text
- This looks like a regression with the new threading implementation

**Comment by nickstenning** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;nRaDXSdL&#x2F;606-bug-new-annotations-not-moved-to-current-group-when-switching-groups-3380"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> [Bug]New annotations not moved to current group when switching groups #3380</a>
