### ISSUE TITLE
Larger gap between share and reply buttons

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#3386]
### Steps to reproduce
1. Open an annotation card

### Expected behaviour
spacing should be identical between all buttons

### Actual behaviour
it's not

![screenshot 2016-05-30 09 55 47](https://cloud.githubusercontent.com/assets/1413074/15654886/bb92adf4-264c-11e6-96c9-93a1e4ee1f81.png)

**Comment by nickstenning** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;QPzkIJLB&#x2F;365-bug-icon-spacing"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> [BUG] Icon spacing</a>
