### ISSUE TITLE
Top and bottom margins not the same on cards

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#3387]
### Steps to reproduce
1. Open a card (on master)

### Expected behaviour
Margins should be the same (I believe).

### Actual behaviour
Lower one is larger.

![screenshot_2016-05-30_09_44_21](https://cloud.githubusercontent.com/assets/1413074/15654915/03e8bbe8-264d-11e6-965b-bb1216470573.png)

**Comment by nickstenning** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;4yQ7AHK4&#x2F;366-bug-annotation-card-margin"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> [BUG] Annotation card margin</a>
