### ISSUE TITLE
"Failed to construct uri" error when rendering annotations with an invalid URI

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#3389]
### Steps to reproduce
1. Visit this page http://sumitz.pythonanywhere.com/static/web/viewer.html
2. Observe console logs
### Actual behaviour

Many `TypeError: Failed to construct 'URI'` messages. See https://app.getsentry.com/hypothesis/prod-client/issues/130149490/
### Browser/system information

Firefox 48

**Comment by robertknight** [comment]
The offending annotations have `[object URL]` in the 'uri' field:

```json
{
  "uri": "[object URL]",
  "id": "AVHQRcBA8sFu_DXLVTQb"
}
{
  "uri": "[object URL]",
  "id": "AVHQRO0w8sFu_DXLVTQZ"
}
{
  "uri": "[object URL]",
  "id": "AVHQQ5NQ8sFu_DXLVTQW"
}
{
  "uri": "[object URL]",
  "id": "AVHQQggD8sFu_DXLVTQU"
}
```

**Comment by nickstenning** [comment]
Not reproducible as the website in question has gone away. Closing.
