### ISSUE TITLE
"Show all annotations" button just makes annotation disappear

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#3390]
![untitled screencast 20](https://cloud.githubusercontent.com/assets/22498/15683931/b5dc83a6-275c-11e6-9710-24d5e69cfaa7.gif)

In this case I'm looking at a "You don't have permission" card. Clicking "Show all annotations" simply makes that card disappear. No annotations appear. The reason is presumably because there are no public, anchoring annotations on that page. Seems confusing but I'm not sure what the correct behaviour should be.

If I had been looking at an actual annotation and it was the only public anchorable annotation of the document then I guess clicking "Show all annotations" would make the button disappear but nothing else change (still looking at the same one annotation), also seems a little confusing,

**Comment by seanh** [comment]
@conordelahunty @robertknight

**Comment by nickstenning** [comment]
Moved to https://github.com/hypothesis/product-backlog/issues/179.
