### ISSUE TITLE
Unhelpful error messages for invalid usernames

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#3391]
We don't say what is required of a valid username nor what is wrong with the one given:

![screenshot from 2016-05-31 17-54-21](https://cloud.githubusercontent.com/assets/22498/15684242/2281f350-275e-11e6-8b5a-2c959ecb5a98.png)

**Comment by nickstenning** [comment]
Wow. That's pretty bad.

**Comment by seanh** [comment]
Also "String" and "pattern"

**Comment by seanh** [comment]
Also see https://github.com/hypothesis/h/issues/3391
