### ISSUE TITLE
Adder doesn't launch editor

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#3412]
### Steps to reproduce
1. Go here: http://www.rp-online.de/wirtschaft/unternehmen/vattenfall-klage-koennte-bund-ueber-fuenf-milliarden-kosten-aid-1.4758533
2. Select first paragraph
3. Enable chrome extension
4. Click "Annotate" on adder
### Expected behaviour

Editor should launch
### Actual behaviour

Sidebar opens but editor doesn't show
### Browser/system information

Current chrome
### Additional details

Here is a screencapture of the problem.
https://drive.google.com/file/d/0B0yW-dSdEYAcZTFwRkxTSUoyMmc/view

**Comment by nickstenning** [comment]
This looks to me to be much more fundamental than just the adder/editor. The Hypothesis sidebar (launched from the Chrome extension) doesn't complete its boot for me: doesn't complete login, fails to display an annotation that the bucket bar displays, etc.

**Comment by robertknight** [comment]
I see a different issue to both @nickstenning and @dwhly . For me the extension launches correctly, the adder appears, although it is vertically offset by ~100px from where it should be. Clicking the 'Annotate' button results in an annotation being created and the sidebar opens. However the quote field in the editor is empty.

This last issue, with the empty quote, only happened when I made the selection _before_ activating the extension.

**Comment by nickstenning** [comment]
I can't reproduce this problem any more. Feel free to reopen (ideally in the client repo) if you can.
