### ISSUE TITLE
Instructions of how to install h locally missing

### ISSUE THREAD

**Issue by ifol** [hypothesis/h#3427]
I was trying to find instructions how to install hypothes.is locally to play around with it, but the link in wiki is broken and the file it refers to does no longer exists.

Wiki page:
https://github.com/hypothesis/h/wiki/installation

Missing file:
https://github.com/hypothesis/h/blob/master/docs/INSTALL.rst

Is it moved somewhere else? If so, the link should be updated.

**Comment by robertknight** [comment]
Thanks for the report! The current version of the documentation lives on our Read the Docs page at http://h.readthedocs.io/en/latest/ .

Are you interested in running/playing around with the service, the browser-based annotation tool or both? They currently live together but we're in the process of separating them out.

**Comment by ifol** [comment]
Thank you for the prompt reply, the first step is to install it locally - then I might tinker with any component to try things out so I do not know. The link should be corrected nonetheless, if I have any further questions/issues I'll address them to appropriate places, thanks!

**Comment by ifol** [comment]
Why was this closed? The issue is still not resovled and the installation page on the wiki still points to non-existing file.

**Comment by nickstenning** [comment]
The wiki is outdated. I've just archived it entirely and replaced the homepage with a link to the documentation. The link referenced by @robertknight above is the appropriate installation documentation.
