### ISSUE TITLE
Multiple unrelated Hypothesis frames on one page causes havoc

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/h#3433]
### Steps to reproduce
1. Create an HTML document with multiple frames, each containing an instance of Hypothesis. For example, create multiple iframes to different https://via.hypothes.is pages. The frames must all be hosted on the same origin.
### Expected behaviour

Each independent Hypothesis instance can be used on its own without interfering with the others.
### Actual behaviour

The "magic" autodiscovery features cause complete havoc. Specifically:
- frames disagree on who is the "host" and who is the "guest" causing ["A second Discovery server has been detected"](https://app.getsentry.com/hypothesis/prod-client/issues/120271030/) errors.
- frames which contain different documents receive page metadata from the other frames and end up loading the wrong annotations
- messages bounce endlessly between frames causing problems similar to that described in #2829.

**Comment by robertknight** [comment]
I think this might be the same issue as seen in #2829

**Comment by nickstenning** [comment]
Moved to https://github.com/hypothesis/client/issues/249.
