### ISSUE TITLE
Selection styling and quoted text styling no longer match.

### ISSUE THREAD

**Issue by dwhly-proj** [hypothesis/h#3435]
### Steps to reproduce
1. Quote some text in the body of an annotation
2. Compare that styling to the selection of that annotation.

### Expected behaviour
They should be the same

### Actual behaviour
They're not. One is serif the other is sans.

### Browser/system information
Chrome extension

### Additional details
![screenshot 2016-06-09 06 36 23](https://cloud.githubusercontent.com/assets/18405130/15931479/c3e42dda-2e0c-11e6-9a15-4e9630145a03.png)

@conordelahunty ^

**Comment by conordelahunty** [comment]
Yep, this text styling should not be there anymore. It should be that same text treatment as the main quote (but without the hover state).
