### ISSUE TITLE
Selection + adder click doesn't reliably open sidebar on PDFs.

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#3439]
### Steps to reproduce
1. Launch extension.
2. Go to test PDF: https://www.dropbox.com/s/gezpy0becgl8959/THIS%20MY%20FRIENDS%20IS%20A%20TEST%20PDF.pdf?dl=0
3. Select "Like this candidate for worst poem ever"
4. Click adder
### Expected behaviour

Sidebar should open
### Actual behaviour

It does not
### Browser/system information

Chrome extension 0.27
### Additional details

I've been seeing this intermittently for weeks.  This is the first time I've successfully reproduced.  Here is a screencast:  https://drive.google.com/file/d/0B0yW-dSdEYAcTUQ2TVRJbDl2MXM/view

**Comment by nickstenning** [comment]
I can't reproduce this one any more. Feel free to reopen in the client repo if you have new reproducible examples. I'm sure we haven't seen the last of this kind of bug.
