### ISSUE TITLE
promise not working and fails to create a constructor for AnnotationResource 

### ISSUE THREAD

**Issue by Forethinker** [hypothesis/h#3442]
cross-frame.coffee:31 Uncaught TypeError: store.AnnotationResource is not a constructor

### Steps to reproduce
1. checkout latest master (27980d9dff4cf7efba75084f5e0d17c09a726500)
2. start the services
3. log in and click annotate after highlighting some text.

### Expected behaviour
The text box to show up on the sidebar so you can start writing notes.

### Actual behaviour
There is no textbox on the sidebar, the note gets highlighted and the number tab shows up.
After a refresh, nothing is saved

### Browser/system information
Tell us which browser, browser version, and operating system you were using when
you encountered this issue.
I tested on chrome 51.0.2704.84 m, firefox 46 with the same error.
Windows 10

### Additional details

I found a potentially related problems on angularjs2, so I tinkered with adding es6-shim to store.js
https://github.com/blacksonic/angular2-esnext-starter/issues/1#issuecomment-196838211

**Comment by robertknight** [comment]
> checkout latest master (27980d9)
> start the services
> log in and click annotate after highlighting some text.

Can you clarify what you mean by "start the services"?

> I found a potentially related problems on angularjs2, so I tinkered with
> adding es6-shim to store.js blacksonic/angular2-esnext-starter#1 (comment)

We are using Angular 1 rather than Angular 2. However, the problem is much more likely to be in our own code rather than Angular. When the sidebar loads, what happens is:

1. The client makes a call to the `https://hypothes.is/api` endpoint which returns a JSON object describing the Hypothesis API
2. In `store.js`, ngResource resources are created using this description object, one of which is `store.AnnotationResource`.

So this error can happen if some code tries to use `store.AnnotationResource` before the API description has been fetched and processed, or if there is an error processing the API description.

**Comment by Forethinker** [comment]
"start the services" mean running the following commands with no error
`sudo service postgresql start`
`sudo service rabbitmq-server start`
`sudo service elasticsearch start`
`gunicorn --paste conf/app.ini`

You are right. I had the following error:

`angular.js:11442 GET http://notes.example.com/api/token?assertion=57c4f697e1f84b5e407644a1489e8096c78093f1 500 (Internal Server Error)`

so the string after assertion is CSRF token, right? When I debugged that particular line, I got `post == ""` So the client is not sending anything. Is there a way for me to disable CSRF so I can verify things?

**Comment by Forethinker** [comment]
I had to specify

    h.client_id: 
    h.client_secret: 

in app.ini

Thanks for helping out this newb.

**Comment by Forethinker** [comment]
@robertknight 
But the annotation disappearing after a refresh has not been fixed. It gets saved to the database, because I can retrieve via the generated share link.
I see that you have experienced some issues regarding search https://github.com/hypothesis/h/issues/2965
In my case, it seems like it never gets saved in elasticsearch. I feel a bit sheepish about filing another bug because it might be a simple configuration problem. If you could guide me in the right direction, that would be awesome. 

app.ini
     ....
    es.host: http://localhost:9200  
    es.index: hypothesis            
    h.search.autoconfig: True       
    #legacy.es.index: annotator     

h/api/search/core.py:39 def search
request

    GET /api/search?_separate_replies=true&limit=20&offset=0&user=admin HTTP/1.1
    Accept: application/json, text/plain, */*
    Accept-Encoding: gzip, deflate, sdch
    Accept-Language: en-US,en;q=0.8
    Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJub3N1Y2hpZCIsImlhdCI6MTQ2NTU5MTE3OCwiYXVkIjoiaHR0cDovLzEyNy4wLjAuMTo1MDAwIiwiZXhwIjoxNDY1NTk0Nzc4LCJzdWIiOiJhY2N0OmFkbWluQDEyNy4wLjAuMSJ9.b-1jrXeaeur6WW73L0n7s6iJQxeUOWIKYpo1mcvzLLs
    Connection: keep-alive
    Cookie: _t=b0ce13a6a43be10c7721a5f32f67fbe8; __utma=96992031.1291393111.1440010213.1441864318.1453884917.14; __utmz=96992031.1440010213.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); sessionid=uoxqt0qjhq30h8p3hbbab813qa2uwxg9; XSRF-TOKEN=6e8c28dd65e1b673fcb8aa8bf6a571e8b1e20040; __atuvc=343%7C19%2C10%7C20%2C0%7C21%2C0%7C22%2C159%7C23; __atuvs=575b1ffc00ba4229005; mp_da3036a309cb0c32f238ffa7c4b51cdd_mixpanel=%7B%22distinct_id%22%3A%20%2214ef66f807929-04f142a25-3b74035d-232800-14ef66f807ad2%22%2C%22%24initial_referrer%22%3A%20%22%24direct%22%2C%22%24initial_referring_domain%22%3A%20%22%24direct%22%7D; csrftoken=sR2ElPzvrLPKqSEaAGHmBKSu6dJTkTme; mp_mixpanel__c=170; mp_mixpanel__c3=192704; mp_mixpanel__c4=156276; mp_mixpanel__c5=1091; session=ROR5JADm27SrR8OVFOzN2-NAZQjCS9ZJWVPpIVKUb2p-a8-cfJnjdrz7rUdSqawdwP3NlvqsQyOJ3EGQ0d35-IACSoolW1dHQdXWGzAltgd9cQEoVQdfY3NyZnRfcQJYKAAAADZlOGMyOGRkNjVlMWI2NzNmY2I4YWE4YmY2YTU3MWU4YjFlMjAwNDBxA1ULYXV0aC51c2VyaWRxBFgUAAAAYWNjdDphZG1pbkAxMjcuMC4wLjFxBXWHcQYu
    Host: 127.0.0.1:5000
    Referer: http://127.0.0.1:5000/stream?q=user:admin
    User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36
    X-Client-Id: 5dfccdb0-1b07-46d0-826e-961f20f51725
    X-Csrf-Token: 6e8c28dd65e1b673fcb8aa8bf6a571e8b1e20040

h/api/search/core.py:44 def search
results

    {u'hits': {u'hits': [], u'total': 0, u'max_score': None}, u'_shards': {u'successful': 5, u'failed': 0, u'total': 5}, u'took': 6, u'timed_out': False}

h/api/view.py:162 def create
annotation_dict

    {'updated': '2016-06-10T20:41:23.278153+00:00', 'group': u'__world__', 'target': [{'source': u'http://127.0.0.1:8000/engineering/computer/algorithms/introduction/', 'selector': [{u'conformsTo': u'https://tools.ietf.org/html/rfc3236', u'type': u'FragmentSelector', u'value': u'fullpage'}, {u'type': u'RangeSelector', u'startContainer': u'/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/p[1]', u'endContainer': u'/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/p[1]', u'startOffset': 0, u'endOffset': 27}, {u'start': 17, u'end': 44, u'type': u'TextPositionSelector'}, {u'type': u'TextQuoteSelector', u'prefix': u'\n    \n      \n    ', u'exact': u"Welcome. I'm Bob,", u'suffix': u' professor of computer science a'}]}], 'links': {'json': 'http://127.0.0.1:5000/api/annotations/scgGhi9LEeaSkJsGn6CRyg', 'html': 'http://127.0.0.1:5000/a/scgGhi9LEeaSkJsGn6CRyg'}, 'tags': [], 'text': u'testing', 'created': '2016-06-10T20:41:23.278081+00:00', 'uri': u'http://127.0.0.1:8000/engineering/computer/algorithms/introduction/', 'user': u'acct:admin@127.0.0.1', 'document': {'link': [{'href': u'http://127.0.0.1:8000/engineering/computer/algorithms/introduction/'}], u'title': [u'Introduction - YFunnel ']}, 'id': 'scgGhi9LEeaSkJsGn6CRyg', 'permissions': {'read': [u'acct:admin@127.0.0.1'], 'admin': [u'acct:admin@127.0.0.1'], 'update': [u'acct:admin@127.0.0.1'], 'delete': [u'acct:admin@127.0.0.1']}}

curl -XGET 'http://localhost:9200/annotator/_search?q=test'

    {"took":3,"timed_out":false,"_shards":{"total":5,"successful":5,"failed":0},"hits":{"total":0,"max_score":null,"hits":[]}}
