### ISSUE TITLE
Annotations don't load on PDFs thru via on Safari

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#3471]
### Steps to reproduce
1. Open Safari Browser
2. Browse to https://via.hypothes.is/http://jeremydean.org/blog/wp-content/uploads/2016/06/Long_Live_the_Web.pdf

### Expected behaviour
Annotations should load

### Actual behaviour
They don't

### Browser/system information
Recent Safari

### Additional details
No console output other than PDF fingerprint.

**Comment by robertknight** [comment]
I can reproduce. It looks like the fingerprint URI is being generated slightly differently in Safari. See the fingerprint in the "About" pane below in Safari vs. Firefox and note the trailing hash at the end of the URI in Safari:

![screen shot 2016-06-15 at 15 11 39](https://cloud.githubusercontent.com/assets/2458/16083172/f5ae8abe-330b-11e6-9e75-24ed4bb2684e.png)

**Comment by robertknight** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;KEU6XOHD&#x2F;380-pdf-annotations-created-in-non-safari-browsers-not-appearing-in-safari"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> PDF annotations created in non-Safari browsers not appearing in Safari</a>

**Comment by robertknight** [comment]
The URI difference is due to the way Safari is serializing `URL` objects compared to other browsers:

```js
var url = new URL('urn:x-pdf:ff88aa', 'https://foobar.com/page.html');
url.hash = '';

// Prints "urn:x-pdf:ff88aa" in Chrome/Firefox but "urn:x-pdf:ff88aa#" in Safari
console.log(url.toString());
```

**Comment by robertknight** [comment]
This looks like a bug in Safari. According to the [spec for URL#hash](https://hyp.is/6cNB3DRoEea4LaOhkZCYQQ/url.spec.whatwg.org/) assigning an empty string sets the URL's `fragment` property to null and according to the [spec for URL#toString](https://hyp.is/KxzUNjRpEeaO8yuWAxSJhw/url.spec.whatwg.org/) serializing a URL with a null fragment should not output '#'.
