### ISSUE TITLE
Adder doesn't show on PDFs thru via on Safari

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#3472]
### Steps to reproduce
1. Open Safari Browser
2. Browse to https://via.hypothes.is/http://jeremydean.org/blog/wp-content/uploads/2016/06/Long_Live_the_Web.pdf
3. Make a selection.

### Expected behaviour
Adder should show

### Actual behaviour
It doesn't

### Browser/system information
Recent Safari

### Additional details
No console output other than PDF fingerprint.

**Comment by robertknight** [comment]
I did not experience the same issue testing under Safari 9.0. I could reproduce the other issue where annotations failed to load in Safari.

**Comment by dwhly** [comment]
Tried to recreate again this morning, could not.
