### ISSUE TITLE
client fingerprint query fails for bmj pdf

### ISSUE THREAD

**Issue by judell** [hypothesis/h#3473]
http://bmjopen.bmj.com/content/6/2/e009630.full shows (currently) one annotation in the badge, which matches one in the sidebar when H loads.

The document says: 

&lt;meta content="http://bmjopen.bmj.com/content/6/2/e009630.full.pdf" name="citation_pdf_url" />

So at http://bmjopen.bmj.com/content/6/2/e009630.full.pdf we should see the same: 1 in the badge, 1 in the sidebar. Instead it's 1 in the badge, 0 in the sidebar. The client query in this case:

https://hypothes.is/api/search?uri=urn:x-pdf:190710c99307fdfac3bddff1d87dba81 -> 0

Other observations:

https://hypothes.is/api/search?uri=http://bmjopen.bmj.com/content/6/2/e009630.full.pdf -> 1

https://hypothes.is/api/badge?uri=http://bmjopen.bmj.com/content/6/2/e009630.full -> 1

https://hypothes.is/api/badge?uri=http://bmjopen.bmj.com/content/6/2/e009630.full.pdf -> 1

https://hypothes.is/api/badge?uri=urn:x-pdf:190710c99307fdfac3bddff1d87dba81 -> 0

Trick question:

https://hypothes.is/stream?q=urn:x-pdf:190710c99307fdfac3bddff1d87dba81 -> many

**Comment by dwhly** [comment]
Afaik right now we don't *also* fetch annotations for the URL of the PDF, we only fetch them for the fingerprint.  It was mentioned as a possible later stage, but not implemented I think.
Discussion: https://github.com/hypothesis/h/pull/3404#issuecomment-223521428

The badge of course still does query the URL though, which is why you're seeing that behavior I think.

**Comment by judell** [comment]
"Afaik right now we don't also fetch annotations for the URL of the PDF, we only fetch them for the fingerprint."

The above documents the reverse of that, though. 

https://hypothes.is/api/search?uri=urn:x-pdf:190710c99307fdfac3bddff1d87dba81 -> 0

https://hypothes.is/api/search?uri=http://bmjopen.bmj.com/content/6/2/e009630.full.pdf -> 1

**Comment by dwhly** [comment]
I'm assuming the HTML page was annotated first.  In it's metadata it references the .pdf URL, so that association was created  when it was annotated.  Thus when you search the stream you see the .pdf URL as having one annotation.  

The PDF itself was never annotated.  

My guess.

**Comment by nickstenning** [comment]
This wasn't really a bug, as @dwhly pointed out. If the PDF itself has never been annotated, then the fingerprint association won't have been made.

But now we've fixed this "properly" in v0.30.0 -- searches [can now include multiple URIs at once](https://github.com/hypothesis/h/pull/3517) and [we search by URI and fingerprint at the same time when on a PDF](https://github.com/hypothesis/h/pull/3524).

**Comment by dwhly** [comment]
\o/
