### ISSUE TITLE
Share link for web-hosted PDFs now presents urn:x-pdf instead

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#3491]
### Steps to reproduce
1. Browse to a web-hosted PDF, like this: https://library.educause.edu/~/media/files/library/2015/12/eli7127-pdf.pdf
2. Enable the extension
3. Click the share icon

### Expected behaviour
Share icon should offer this link: https://via.hypothes.is/https://library.educause.edu/~/media/files/library/2015/12/eli7127-pdf.pdf

### Actual behaviour
Share icon offers this link instead: https://via.hypothes.is/urn:x-pdf:72ff19c2a26145a59cfb13f15200929b

### Browser/system information
Chrome / extension

**Comment by robertknight** [comment]
Implementation note: This should probably use the same logic that we have on the stream for getting the document title and domain from an annotation whose primary URI might be a URN.

**Comment by robertknight** [comment]
Fixed in Hypothesis v0.30
