### ISSUE TITLE
Confusing behaviour when double-clicking annotation adder icon

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#3502]
I recently got a new touchpad and the drivers apparently aren't tuned very well because I often double-click when I meant to single-click. Double-clicking when you only need to single-click is also something that I think many users often do either deliberately because they think they need to double-click on things, or accidentally because they lack excellent motor control, or simply out of habit (you don't have to double-click on links and buttons in browsers, but doing so does no harm).

Here's an example of one thing that can happen when double-clicking instead of single-clicking to create a new annotation:

![untitled screencast 21](https://cloud.githubusercontent.com/assets/22498/16191447/20c05d6c-36dc-11e6-9ab9-8e2843b87619.gif)
1. The sidebar quickly opens and then closes again, I've made a separate issue for that here https://github.com/hypothesis/h/issues/3551
2. The adder popup disappears and reappears in a different location with different selected text. Let's discuss this part in this github issue'

I think the adder reappearing in a different location is because the browser responds to the second-click by creating a new selection. Since this click happened on our adder icon while it was still displayed, can we swallow the click to prevent it?

**Comment by dwhly** [comment]
> if you have the sidebar open and you make a selection in order to annotate, when you make the selection the sidebar closes and then when you click the annotate button it opens again.

Perhaps that's a behavior we might address specifically?

Clicking away to close something is a widespread UX behavior.  Eliminating it (I assume) means that users need to be precise about clicking the chevron to close.  Personally I'd find that annoying, but obviously we need to address usability issues like the one you're highlighting.

**Comment by seanh** [comment]
I think clicking away to close something is usually reserved for modal dialogs, not sidebars?

If we had a modal dialog that appeared over the document and prevented you from interacting with the document, and you wanted to interact with the document, then clicking away from the modal dialog to get rid of it makes sense.

But in the case of our sidebar, it doesn't prevent you from interacting with

**Comment by dwhly** [comment]
> I think clicking away to close something is usually reserved for modal dialogs, not sidebars?

Try this (first one I found googling "sliding sidebar UX examples"):
NY Times.  
Click "Sections" at the upper left.
Sidebar slides out from left.
Click away onto the page.
Sidebar slides back.

> But in the case of our sidebar, it doesn't prevent you from interacting with the document, and you're supposed to click on the document in order to interact with the sidebar.

Perhaps we should distinguish between a single click and a click and drag to select?

**Comment by seanh** [comment]
> > if you have the sidebar open and you make a selection in order to annotate, when you make the selection the sidebar closes and then when you click the annotate button it opens again.
> 
> Perhaps that's a behavior we might address specifically?

We may be able to distinguish between:

1. Just a tap on the document that doesn't modify the selection, and
2. A tap that modifies the selection

1 is only possible when there is no existing selection, because the way to clear a selection in browsers is to tap on the document, so I'd vote that a tap while there is a selection (which clears the selection) should not cause the sidebar to open or close. A subsequent tap when there 1. is no existing selection that got cleared by the tap and 2. after the tap is released it didn't make any new selection, might be able to close the sidebar without creating any bad interactions?

**Comment by seanh** [comment]
But you don't have to click on the document in order to interact with that NY Times sidebar :) That's the thing - in normal usage of Hypothesis, trying to read an annotate a document, that sidebar is constantly opening and closing again when I don't want it to, and even frequently closing only to open again moments later, every time you make an annotation! Maybe it's just me but I find this really annoying.

**Comment by seanh** [comment]
Actually the logic for this should be fairly simple: if there is some selected text then don't close the sidebar. That'll stop it from closing when the user clicks and drags to create a new selection or change an existing selection to another. But it won't stop a simple tap on the document from closing the sidebar, even if that tap happens to clear a selection that did exist.

**Comment by dwhly** [comment]
@conordelahunty ^

**Comment by conordelahunty** [comment]
Need to split this conversation because we are now taking about two separate things.

Generally, how I would like it to work:

1. When a user clicks in the document it hides the sidebar.
2. If the user has the sidebar open and makes a new selection, don’t close the sidebar.

As for the original issue you raised about double clicking, this may require some input from @robertknight as to what we can do here. We could solve it with a change to how the adder works?

**Comment by seanh** [comment]
I've created a new issue for this: https://github.com/hypothesis/h/issues/3551

Gonna delete comments from this issue that are actually talking about #3551, leaving the issue to be about the original double clicking problem.

**Comment by nickstenning** [comment]
Moved to https://github.com/hypothesis/product-backlog/issues/188.
