### ISSUE TITLE
Bug: Inserting Links on texts with colons

### ISSUE THREAD

**Issue by DaWalda** [hypothesis/h#3513]
As soon as a colon is connected directly to a word in a text I want to insert a link into, the editor asks not for the link, but the description.

I created a gif:
![colon and link](https://cloud.githubusercontent.com/assets/20053165/16210674/97d81352-373d-11e6-80c3-f751ca59df55.gif)

**Comment by robertknight** [comment]
Thank-you for the report. It looks like the logic that determines whether the selection is a URL or not is indeed far too loose. It matches one or more letters followed by a colon anywhere in the selection.

**Comment by DaWalda** [comment]
Your're awesome. Thank you; thumbs up!
