### ISSUE TITLE
Notes that are posted via the API are saved in relation to the right content, but are not shown in the sidebar. 

### ISSUE THREAD

**Issue by oliversauter** [hypothesis/h#3518]
### Steps to reproduce
1. Access "relevant articles" group [here](https://hypothes.is/groups/KG9bL1Bm/related-articles)
2. Go on page: http://www.theguardian.com/politics/2016/jun/21/boris-johnson-will-make-tv-apology-if-brexit-triggers-recession
3. Open group, see no annotations. 

### Expected behaviour
We posted some elements via the api in this group related to the guardian article. 
As it does with most other pages, those elements should show up there. 

### Actual behaviour
On some pages, like this guardian article, the elements dont show up. 
Weirdly, when I look on the dashboard they are shown. They are also retrievable via the api and the indicator of the plugin shows 9 elements. 

### Browser/system information
OSX yosemite, Chrome Version 51.0.2704.103 (64-bit)

### Additional details
Sidebar:
![image](https://cloud.githubusercontent.com/assets/7870039/16238474/e1bf4546-37e0-11e6-82e8-48efa8453556.png)

Dashboard, see link in the bottom left corner
![image](https://cloud.githubusercontent.com/assets/7870039/16238508/0080ce1e-37e1-11e6-8d87-56d84487cad3.png)

**Comment by nickstenning** [comment]
Hi Oliver. Can you gives us an example of the annotation format you're posting to the API?

**Comment by lenazun** [comment]
@oliversauter an example would be great! when an annotation doesn't show up on the sidebar (but shows up everywhere else) it is often because it has failed to anchor to the content on the page.  maybe that's it?

**Comment by oliversauter** [comment]
Hey guys,

its not an annotation itself, it is just a note, so has no anchor except for being related to the URL.

`{"updated":"2016-06-21T16:36:14.766020+00:00","group":"KG9bL1Bm","target":[{"source":"http://www.theguardian.com/politics/2016/jun/21/boris-johnson-will-make-tv-apology-if-brexit-triggers-recession"}],"links":{"json":"https://hypothes.is/api/annotations/RViz3jfOEeaw3j8xD-Ag3w","html":"https://hypothes.is/a/RViz3jfOEeaw3j8xD-Ag3w","incontext":"https://hyp.is/RViz3jfOEeaw3j8xD-Ag3w/www.theguardian.com/politics/2016/jun/21/boris-johnson-will-make-tv-apology-if-brexit-triggers-recession"},"tags":[],"text":"#####[**We should stay in EU and improve it, says Jeremy Corbyn**](https://www.theguardian.com/politics/2016/jun/20/we-should-stay-in-eu-and-improve-it-says-jeremy-corbyn)\n\n*Labour leader tells Sky TV audience he is hoping for a remain vote but that he is ‘not a lover’ of the European Union*\n\nvia: **The Guardian**\n","created":"2016-06-21T16:36:14.766012+00:00","uri":"http://www.theguardian.com/politics/2016/jun/21/boris-johnson-will-make-tv-apology-if-brexit-triggers-recession","selector":{"type":"TextQuoteSelector","exact":""},"user":"acct:WorldBrain@hypothes.is","document":{"link":[{"href":"http://www.theguardian.com/politics/2016/jun/21/boris-johnson-will-make-tv-apology-if-brexit-triggers-recession"}]},"id":"RViz3jfOEeaw3j8xD-Ag3w","permissions":{"read":["group:KG9bL1Bm"],"update":["acct:WorldBrain@hypothes.is"],"delete":["acct:WorldBrain@hypothes.is"],"admin":["acct:WorldBrain@hypothes.is"]}}`

**Comment by oliversauter** [comment]
Just found another one, including the header this time:

`:authority:hypothes.is
:method:PUT
:path:/api/annotations/kIz_ajqwEea1jisJVOt0JQ
:scheme:https
accept:application/json, text/plain, */*
accept-encoding:gzip, deflate, sdch, br
accept-language:en-US,en;q=0.8,de;q=0.6
authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDAiLCJpYXQiOjE0NjY4NDQzNDEsImF1ZCI6Imh0dHBzOi8vaHlwb3RoZXMuaXMiLCJleHAiOjE0NjY4NDc5NDEsInN1YiI6ImFjY3Q6V29ybGRCcmFpbkBoeXBvdGhlcy5pcyJ9.kxSV9IDF7v0qpgLi0ryfM8wpSzBTzGUe8Q4bp4aX9Fo
content-length:1304
content-type:application/json;charset=UTF-8
cookie:__cfduid=d4cef3b9601a1bfd52c2a06bb4bf96c591463512341; XSRF-TOKEN=d8aefb250474ea866871b936f5d24ae297735608; session=30f4addd2004ee40f0178e6d3a871afa1bd86727gAJVQGMxNjFiMjg4YzBhZDM0N2NkMGQ1NjkyYjViY2Q3MDMwYThjMTEzOTY0ZDA4Mjg4NGU3MDNmZWUyODg5YTlhODRxAS4=
origin:https://hypothes.is
referer:https://hypothes.is/stream?q=user:WorldBrain
user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
x-client-id:5ba8d8d4-d49f-4a65-8180-3d0c9210a69c
x-csrf-token:d8aefb250474ea866871b936f5d24ae297735608
Request Payload
view parsed
{"updated":"2016-06-25T08:45:51.109453+00:00","group":"KG9bL1Bm","target":[{"source":"http://www.theguardian.com/politics/2015/oct/25/eu-exit-vote-no-means-no-says-pm"}],"links":{"json":"https://hypothes.is/api/annotations/kIz_ajqwEea1jisJVOt0JQ","html":"https://hypothes.is/a/kIz_ajqwEea1jisJVOt0JQ","incontext":"https://hyp.is/kIz_ajqwEea1jisJVOt0JQ/www.theguardian.com/politics/2015/oct/25/eu-exit-vote-no-means-no-says-pm"},"tags":[],"text":"#####[**Michael Howard: EU is flawed and failing and we should leave**](http://www.theguardian.com/politics/2016/feb/26/michael-howard-eu-flawed-failing-leave-tory-danger-european-union)\n\n*Senior Tory challenges ministers’ warnings about economic dangers for Britain of leaving the European Union*\n\nvia: **The Guardian**","created":"2016-06-25T08:41:09.524877+00:00","uri":"http://www.theguardian.com/politics/2015/oct/25/eu-exit-vote-no-means-no-says-pm","selector":{"type":"TextQuoteSelector","exact":""},"user":"acct:WorldBrain@hypothes.is","document":{"link":[{"href":"http://www.theguardian.com/politics/2015/oct/25/eu-exit-vote-no-means-no-says-pm"}]},"id":"kIz_ajqwEea1jisJVOt0JQ","permissions":{"read":["group:KG9bL1Bm"],"update":["acct:WorldBrain@hypothes.is"],"delete":["acct:WorldBrain@hypothes.is"],"admin":["acct:WorldBrain@hypothes.is"]}}'

**Comment by robertknight** [comment]
@oliversauter When posting multi-line code snippets, use triple-backticks or gists rather than single backticks:

```
  ``` << Start of code block
  <Your code here>
  ``` << End of code block
```

**Comment by robertknight** [comment]
Looking at this annotation: https://hypothes.is/api/annotations/RViz3jfOEeaw3j8xD-Ag3w (requires group membership) the URL in the `target.source` field is:

http://www.theguardian.com/politics/2016/jun/21/boris-johnson-will-make-tv-apology-if-brexit-triggers-recession

In the `document.links` list there is a canonical URL which points to the *HTTPS* link.

When visiting the page, the client makes a search request for the HTTPS version of the URL but receives no annotations.

An annotation created manually in the client has a `target.source` field matching the HTTPS URL.

**Comment by oliversauter** [comment]
@robertknight ah thanks will do the next time.

When requesting the annotation  "RViz3jfOEeaw3j8xD-Ag3w" via the API, I get the following result:

I suspected an http/https mismatch as well before, but could not find that difference.
>>>'target': [{'source': 'http://www.theguardian.com/politics/2016/jun/21/boris-johnson-will-make-tv-apology-if-brexit-triggers-recession'}], 

>>> 'document': {'link': [{'href': 'http://www.theguardian.com/politics/2016/jun/21/boris-johnson-will-make-tv-apology-if-brexit-triggers-recession'}]}


````
{'total': 1, 'rows': 
[{'text': '#####[**We should stay in EU and improve it, says Jeremy Corbyn**](https://www.theguardian.com/politics/2016/jun/20/we-should-stay-in-eu-and-improve-it-says-jeremy-corbyn)\n\n*Labour leader tells Sky TV audience he is hoping for a remain vote but that he is ‘not a lover’ of the European Union*\n\nvia: **The Guardian**\n', 
'uri': 'http://www.theguardian.com/politics/2016/jun/21/boris-johnson-will-make-tv-apology-if-brexit-triggers-recession', 
'target': [{'source': 'http://www.theguardian.com/politics/2016/jun/21/boris-johnson-will-make-tv-apology-if-brexit-triggers-recession'}], 
'created': '2016-06-21T16:36:14.766012+00:00', 
'permissions': {'admin': ['acct:WorldBrain@hypothes.is'], 
'update': ['acct:WorldBrain@hypothes.is'], 
'read': ['group:KG9bL1Bm'], 
'delete': ['acct:WorldBrain@hypothes.is']}, 
'id': 'RViz3jfOEeaw3j8xD-Ag3w', 
'tags': [], 'selector': {'exact': '', 'type': 'TextQuoteSelector'}, 
'group': 'KG9bL1Bm', 
'links': {'html': 'https://hypothes.is/a/RViz3jfOEeaw3j8xD-Ag3w', 
'json': 'https://hypothes.is/api/annotations/RViz3jfOEeaw3j8xD-Ag3w', 
'incontext': 'https://hyp.is/RViz3jfOEeaw3j8xD-Ag3w/www.theguardian.com/politics/2016/jun/21/boris-johnson-will-make-tv-apology-if-brexit-triggers-recession'},
 'user': 'acct:WorldBrain@hypothes.is', 
'document': {'link': [{'href': 'http://www.theguardian.com/politics/2016/jun/21/boris-johnson-will-make-tv-apology-if-brexit-triggers-recession'}]}, 'updated': '2016-06-25T08:31:19.959763+00:00'}]}```

**Comment by chdorner** [comment]
There are currently 9 page notes showing up for me in the sidebar. We do treat http/https URIs as the same document since [v0.32.0](https://github.com/hypothesis/h/releases/tag/v0.32.0). Closing this.

**Comment by oliversauter** [comment]
Works! thanks
