### ISSUE TITLE
Adder stops working after rapid clicking on page

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#3521]
**Steps to reproduce**

1. Go to a page and activate Hypothesis
2. Click repeatedly and rapidly on the same word on the page

After a few clicks, I see a `TypeError: t is null` error reported in `injector.js` and the adder stops responding to selection changes.

Error stacktrace:

```js
Adder/this.target()
injector.bundle.js:8
[8]</Guest</n.prototype._onSelection()
injector.bundle.js:23
n/this.selections<.next()
injector.bundle.js:23
[65]</</</<.next()
injector.bundle.js:208
[65]</</</<.map/</<.next()
injector.bundle.js:208
[65]</</</<.next()
injector.bundle.js:208
merge/</r</<.next()
injector.bundle.js:77
[65]</</</<.next()
injector.bundle.js:208
t()
```

**Browser**: Firefox Nightly v50a1

**Comment by robertknight** [comment]
I distilled down the original page where I experienced the issue to this, where I can still reproduce in Firefox Nightly v50a1:

```html
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body>
<p>We've mentioned that Haskell is a purely functional language.</p>
</body>
</html>
```

I could not reproduce the issue in Firefox (stable) or Chrome (52.0.2716.0).

**Comment by seanh** [comment]
Hmm, I can't seem to reproduce this on master, will let someone else have a go
