### ISSUE TITLE
Adder stops working after making a selection that does not include any text

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#3523]
### Steps to reproduce
1. Go to a page with an image on it and activate H
2. Select the image, _being careful not to select only the image and not any whitespace or text around it_. Depending on the page this can be tricky with the mouse.
3. Select a piece of text elsewhere on the page

### Expected behaviour
The adder should appear after step 3.

### Actual behaviour
The adder does not appear and a console error is logged, the same as #3521

### Browser/system information
Tested with Chrome v52 but the issue should be the same for any browser.

### Additional details
Any other means of making a non-empty selection which does not include any text should also trigger the issue.

**Comment by seanh** [comment]
This looks similar to an issue that I mentioned that I couldn't reproduce, in the P.S. at the bottom of this comment: https://github.com/hypothesis/h/issues/3502#issue-161169799
