### ISSUE TITLE
Annotation highlights not working on PDFs

### ISSUE THREAD

**Issue by lenazun** [hypothesis/h#3530]
### Steps to reproduce
1.  Go to a cool PDF.  say, http://www.supremecourt.gov/opinions/15pdf/14-1373_83i7.pdf
2.  Annotate a little
3. See annotation highlight disappear before your eyes :(

### Expected behaviour
After annotating, the selected text should remain highlighted. 

### Actual behaviour
After annotating, the selected text is no longer highlighted.  Clicking on a annotation card (sometimes?) focuses on the annotation, but there's no highlight.

### Browser/system information
Version:
0.29.0
User agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
URL:
urn:x-pdf:0906f5d5c8ec3bb0a29606126c6f9c6d
PDF fingerprint:
0906f5d5c8ec3bb0a29606126c6f9c6d
Username:
wikinotes
Date:
22 Jun 2016 10:43:46 -0700

### Additional details

<img width="868" alt="nohighlights" src="https://cloud.githubusercontent.com/assets/6117168/16277165/a100b054-3866-11e6-94b0-3fe71adc9983.png">

**Comment by robertknight** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;PlbhteX9&#x2F;384-implement-tests-for-pdf-anchoring"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Implement tests for PDF anchoring</a>
