### ISSUE TITLE
How to share comments that require an account profile?

### ISSUE THREAD

**Issue by orschiro** [hypothesis/h#3533]
Dear all, 

I wanted to share my comments for a page that requires an account profile via [https://via.hypothes.is/http://wwoof.pl/user/Ranczo](https://via.hypothes.is/http://wwoof.pl/user/Ranczo). 

However, the recipient cannot view the comment, nor can he login via this `via.hypothesis` page. 

Is there any way to still share such comments for non-public pages?

Thankfully,

~Robert

**Comment by orschiro** [comment]
Just an idea: Maybe an export comments as PDF?

**Comment by robertknight** [comment]
At the moment the only supported mechanisms for sharing comments on non-public pages is for both parties to have the Hypothesis browser extension installed or for the publisher of the page to embed Hypothesis on it.

If you have permission to mirror the content with a publicly accessible URL you could also do that and use `<link rel="canonical" href="<URL of original page>">` to make comments on the original page appear at the mirrored URL.

**Comment by orschiro** [comment]
Dear @robertknight,

Thanks for your suggestions!

> If you have permission to mirror the content with a publicly accessible URL you could also do that and use <link rel="canonical" href="<URL of original page>"> to make comments on the original page appear at the mirrored URL.

I will try this one since I don't think that the owner will install Hypothesis, unfortunately...

~Robert

**Comment by robertknight** [comment]
I'm closing this as it is a discussion rather than a bug but feel free to post any follow up questions or comments here.

**Comment by orschiro** [comment]
Thank you, I will!

Robert
