### ISSUE TITLE
Scrolling PDFs with annotation selected snaps doc back to point of selection.

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#3537]
### Steps to reproduce
1. With the extension, browse here: https://hyp.is/nZkR7DlyEeaH6sfmQWfRVA/www.hewlett.org/sites/default/files/Open_Educational_Resources_December_2015.pdf
2. Scroll down about twenty pages, or to approximately page 6 in the main document (after the exec summary).
### Expected behaviour

The document should continue to scroll
### Actual behaviour

It snaps back to the selected annotation
### Browser/system information

Chrome extension

cc @jeremydean

**Comment by nickstenning** [comment]
Moved to https://github.com/hypothesis/client/issues/253.
