### ISSUE TITLE
Selecting a pre-created annotation results in permission error being shown

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#3547]
### Steps to reproduce
1. Activate H in a page, select text and click the 'Annotate' button
2. After the sidebar opens, click on the highlight for the new annotation in the page

### Expected behaviour
The annotation card for the new annotation should remain visible in the sidebar

### Actual behaviour
The annotation card for the new annotation disappears and is replaced by a 'You do not have permission ...' error.

### Additional details
This is happening because the selection mechanism currently does not support selecting annotations which have not yet been created on the server, which I refer to here as "pre-created". We should either fix this mechanism or at least implement some better behavior.

**Comment by chdorner** [comment]
I can't reproduce this anymore, clicking on the text quote in the pre-created annotation even scrolls to the place in the document.

Tested on:
```
Version: 0.36.0.2
User agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36
URL: http://nokogiri.org/tutorials/installing_nokogiri.html
Username: chdorner
Date: 05 Aug 2016 17:55:45 +0200
```
