### ISSUE TITLE
Hypothes.is proxy not rewriting xlink URL

### ISSUE THREAD

**Issue by rdmpage** [hypothesis/h#3549]
### Steps to reproduce
1. Go to https://via.hypothes.is/http://www.gbif.org/species/7753250
### Expected behaviour

The logo for GBIF should appear 

![screenshot 2016-06-27 11 15 18](https://cloud.githubusercontent.com/assets/83306/16376518/872c76e0-3c58-11e6-925e-07c22927e33a.png)
### Actual behaviour

The logo for GBIF should appear but it does not 

![screenshot 2016-06-27 11 15 03](https://cloud.githubusercontent.com/assets/83306/16376519/87af34f4-3c58-11e6-987f-f0d50ca45373.png)
### Browser/system information

Safari 8.05 Mac OS X 10.10.3 (Yosemite)
### Additional details

I think the relevant code in the GBIF site is here:

`<a href="https://via.hypothes.is/http://www.gbif.org/" class="logo">
<svg width="245" height="52">
<image xlink:href="/img/header/GBIF-2015-full.svg" src="/img/header/GBIF-2015-full-ie8-fallback.png" width="245" height="52" title="GBIF.org - Free and open access to biodiversity data" alt="Logo of GBIF"></image>
</svg>
</a>`

As far as I can tell what is happening is that the xlink:href link to the SVG image is not being treated as a relative URL but as an absolute URL, hence the website fails to find the image http://www.gbif.org/img/header/GBIF-2015-full.svg when displayed using the proxy.

**Comment by nickstenning** [comment]
Moved to https://github.com/hypothesis/via/issues/97.
