### ISSUE TITLE
Editing: Link to prior version(s) of edited annotations

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#355]
Generally, a placeholder for more detailed thinking about editing, how to show versioning, how to signal to the community that an annotation is not original, etc.

**Comment by JakeHartnell** [comment]
Closing this as there are other issues open now relating to this topic that have had more recent discussion:
https://github.com/hypothesis/h/issues/950
https://github.com/hypothesis/h/issues/2151
https://github.com/hypothesis/h/issues/2150
