### ISSUE TITLE
When you select text to annotate the sidebar closes and then opens again

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#3551]
If the sidebar is already open and then you select some text in the document in order to make an annotation, the sidebar closes when you select the text and then opens again when you click the annotae button:

![3f6fa208-36dd-11e6-921d-c58d8f5c10c5](https://cloud.githubusercontent.com/assets/22498/16384934/c882a9be-3c82-11e6-8f81-390fadf2ceb6.gif)

Based on previous discussion, the suggested aims for a fix are:
1. When a user clicks in the document it hides the sidebar.
2. If the user has the sidebar open and makes a new selection, don’t close the sidebar.

Possible implementation:

If there is some selected text after a click on the document has happened then don't close the sidebar. Otherwise do close the sidebar. That should mean that:
- If there is no selection and then the user clicks and drags to create a new selection, then there will be a selection so the sidebar won't close.
- If there is an existing selection and then the user clicks and drags to destroy this selection and replace it with a new selection, then there will be a selection so the sidebar won't close.
- If there is no selection and the user just clicks on the document, then there will be no selection after this click so the sidebar will close.

Potential issues with this implementation:
- If there is a selection and the user clicks on the document this will clear the selection but not make a new selection, after this click there is no selection anymore, so the sidebar will close. Did the user mean to close the sidebar? Or where they just unselecting the text, and actually they were using or reading the sidebar and still wanted it?
  
  We _could_ decide that in order for a click to close the sidebar there has to be both no selection before and no selection after the click. Then in this case of clearing a selection the sidebar would not close (if the user were to subsequently click again then it would close). But that just reverses the problem: what if the user was trying to close the sidebar? It would be annoying that it didn't close, and the user may not realise that this is because they had to clear their selection first (the selection may not even be on screen).
- In browsers a double-click will select the word under the cursor, and a triple-click will select the paragraph. In both cases after the first click nothing is selected (yet) so the sidebar will close only to quickly open again if the user clicks the annotate button. Can we distinguish a genuine single click from the first click of a double or triple click?

Another implementation thought:

"If there is some selected text" seems to be synonymous with "the popup adder is shown", might be helpful in implementation.

For completeness I'll just suggest again that the simple behaviour _don't close the sidebar unless the user clicks the close button on the sidebar_ avoids any guessing of user intent with "if this then that except if else" type issues (but as noted in previous discussion requires actually clicking on a button rather than just anywhere on the doc).

**Comment by seanh** [comment]
See also <https://github.com/hypothesis/h/issues/3502>, a double-click on the annotate button seems to cause the sidebar to open and then suddenly close again (it opens because you created a new annotation with the first click, presumably the second click is counted as a click on the document which closes the sidebar again).

**Comment by seanh** [comment]
> In browsers a double-click will select the word under the cursor, and a triple-click will select the paragraph. In both cases after the first click nothing is selected (yet) so the sidebar will close only to quickly open again if the user clicks the annotate button. Can we distinguish a genuine single click from the first click of a double or triple click?

Assuming we can distinguish single from double and triple clicks:

- We definitely shouldn't close the sidebar after the first click of a double or triple click

- But if the user is double or triple clicking on an empty part of the document, they may be trying to close the sidebar by doing so. If there's no selection after a double or triple click is finished, then we should probably close the sidebar.

**Comment by nickstenning** [comment]
Moved to https://github.com/hypothesis/product-backlog/issues/189.
