### ISSUE TITLE
via links not working for https?

### ISSUE THREAD

**Issue by jeremydean** [hypothesis/h#3554]
### Steps to reproduce
1. Open this via link to an https but public web page:

https://via.hypothes.is/https://www.edsurge.com/news/2015-06-24-5-essential-steps-to-building-community-for-your-online-course

Or open the below bouncer link to the same page after joining the group--but open in Firefox so via is activated and not the ext:

https://stage.hypothes.is/groups/ymXLXdi4/hybrid-online-summer-16

https://hyp.is/YWJrhD13EeaK1U-rOq2onQ/www.edsurge.com/news/2015-06-24-5-essential-steps-to-building-community-for-your-online-course
### Expected behaviour

Page should open with sidebar in case 1--no annotations bc group not selected but can be found if scope toggled.

In case two, page should open with group annotation displayed if a member of the group. It does in chrome bc it's not using via. It doesn't in Firefox bc it is.
### Actual behaviour

I am presented with a completely blank page with no error message.
### PS for context

https://twitter.com/clonghb/status/747929111054553089

**Comment by dwhly** [comment]
Related to: https://github.com/hypothesis/via/issues/20

**Comment by dwhly** [comment]
Verified that this is still an issue.

**Comment by nickstenning** [comment]
I don't know what changed here but this now works fine.
