### ISSUE TITLE
Replies should not move between groups

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#3559]
1. Make an annotation and save it.
2. Make a reply to that annotation, don't save it yet.
3. Change the focused group.

Expected: the reply _does not_ go with the user when they change to another group. If they change back to the original group, the reply should still be waiting there (with the annotation editor open, and any unsaved edits preserved).

Actual: the reply does move with the user to the new group, is displayed as a reply to a _Message not available_ annotation. If you save the reply to the server at this point it saves to the original group not the focused one.

![untitled screencast - edited 19](https://cloud.githubusercontent.com/assets/22498/16457516/b551b122-3e13-11e6-91cd-e57948e5f9f5.gif)

**Comment by seanh** [comment]
I'll take this onto the same issue for now - it's differently broken when editing a saved reply and changing groups without saving the edits:

![untitled screencast - edited 20](https://cloud.githubusercontent.com/assets/22498/16457765/8bb7c5f8-3e14-11e6-9bcf-0d98c8a8f252.gif)

**Comment by seanh** [comment]
Re-opening as this is not actually fixed yet

**Comment by nickstenning** [comment]
This is fixed now.
