### ISSUE TITLE
Allow to rate (up/down vote) annotations

### ISSUE THREAD

**Issue by yarikoptic** [hypothesis/h#3566]
This will allow to crowd source the curation.

If necessary, can expand on the idea

**Comment by nickstenning** [comment]
Hi, thanks for your contribution. When you created your issue you will have seen the following text in the issue template:

> 1. Only report **bugs** with Hypothesis here. If you want to discuss potential
>   new features, please use our developer mailing list:
>
>       https://groups.google.com/a/list.hypothes.is/forum/#!forum/dev

We'd be happy to discuss this idea on the mailing list, but I'm going to close this issues as we use GitHub issues for defect tracking only.
