### ISSUE TITLE
no equivalence between http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4688937 and http://europepmc.org/articles/PMC4688937

### ISSUE THREAD

**Issue by judell** [hypothesis/h#3595]
The two URLs share these equivalences:

&lt;meta name="dc:identifier" content="info:pmcid/PMC4688937"/>
&lt;meta name="citation_doi" content="10.1186/s13036-015-0022-z"/>

http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4688937 has 3 private and 1 public annotations

The badge says 4 for both URLs.

The client receives annotations for http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4688937 as expected: 3 in a group, 1 in public. 

(Query: https://hypothes.is/api/search?_separate_replies=true&group=__world__&limit=200&offset=0&order=asc&sort=created&uri=http%3A%2F%2Fwww.ncbi.nlm.nih.gov%2Fpmc%2Farticles%2FPMC4688937%2F)

The client receives nothing for http://europepmc.org/articles/PMC4688937. 

(Query: https://hypothes.is/api/search?_separate_replies=true&group=__world__&limit=200&offset=0&order=asc&sort=created&uri=http%3A%2F%2Feuropepmc.org%2Farticles%2FPMC4688937%2F)

**Comment by chdorner** [comment]
The documents are linked together. When I expand http://europepmc.org/articles/PMC4688937 I do get http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4688937/ amongst other URIs.

But the other way around I don't, because http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4688937/ is a `rel-canonical` URI, which [we don't expand](https://github.com/hypothesis/h/blob/master/h/api/storage.py#L208-L214).

**Comment by judell** [comment]
OK.

Some questions:

1. How are they linked? I see nothing in either referring to the other. Do we know what the intermediary was/is?

2. In the EuropePMC article I see, e.g.,  &lt;link rel="alternate" type="application/rss+xml" title="Europe PMC: Content Holdings" href="/contentrss"> That kind of thing has caused problems in the past. How do we handle link rel="alternate" now?

3. In situations like this, where content is syndicated, how can we best advise publishers to express cross-linkage?

**Comment by nickstenning** [comment]
1. Both pages include DOI metadata, and (in general) document equivalence is transitive (i.e. if A is equivalent to B and B is equivalent to C then A is equivalent to C).

2. We [ignore RSS and Atom feeds as sources of equivalent URIs](https://github.com/openannotation/annotator/blob/258fd8822de6fca73b4f7ab4717d14556367d1ab/src/plugin/document.coffee#L114-L115).

3. Probably the way they're doing here, by agreeing on a universal identifier for the document (in this case, a DOI) and ensuring they include standard metadata (such as `DC.Identifier`) which references that identifier.

**Comment by nickstenning** [comment]
> If they want transitivity, how do they achieve it?

At the moment, by neither end using a `<link rel=canonical>`. 

But that's probably temporary, even if I can't guarantee how long it's "temporary" for. The reason for not expanding queries for `<link rel=canonical>`, if you recall, was actually precisely to avoid problems where a site had the same DOI on about 100 pages, and thus we were trying to load 1000s of annotations on a single page, most of which weren't relevant.

Eventually, it should be possible for us to add rules to the database to handle those nasty edge cases, and then perhaps we can turn off the "don't expand a `<link rel=canonical>`" behaviour.
