### ISSUE TITLE
Icon, title and form not left-aligned on new login form

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#3644]
<img src="https://cloud.githubusercontent.com/assets/22498/17257125/844f5c2a-55b8-11e6-9121-41f04b09814f.png">

**Comment by seanh** [comment]
@robertknight @nickstenning It looks like this issue was overlooked on https://github.com/hypothesis/h/pull/3640

**Comment by nickstenning** [comment]
Ok. I saw your comment, didn't think it was a blocker, given the feature flag. Thanks for opening this issue.
