### ISSUE TITLE
Long unknown email error message overruns container on forgot password form

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#3645]
![screenshot from 2016-08-02 11-53-48](https://cloud.githubusercontent.com/assets/22498/17326237/e97e2db4-58a7-11e6-903d-16457cd757ae.png)

**Comment by seanh** [comment]
A simple solution to this might be to just shorten that particular error message.

More complex solution: use JavaScript to detect when this happens and increase the `<input>`'s padding so that the error message is within the border. I think that's still going to look silly though, so maybe also move the error message below the user's text as we already do on smaller screens.

**Comment by seanh** [comment]
This is even worse on small screens:

![screenshot from 2016-08-02 11-57-17](https://cloud.githubusercontent.com/assets/22498/17326296/4aea936c-58a8-11e6-9536-4d9b8130a8d1.png)

**Comment by seanh** [comment]
Related, we show two different error messages on this form: "Invalid email address" if we don't think the user entered a well-formed email address, or the long error message above if we think the email is well-formed but we just don't have it in our db. This seems unnecessary: either we have the email address in our db and can send a reset email to it or not, there's no need to check whether the email address is well-formed here.

**Comment by robertknight** [comment]
> A simple solution to this might be to just shorten that particular error message.

👍 - IMO not having that much space for the error message is actually a feature, it will force us to make validation messages short.

In this case, repeating the email address which appears in the form input is redundant. Telling the user to change it is also unnecessary.

**Comment by robertknight** [comment]
> More complex solution: use JavaScript to detect when this happens and increase
> the <input>'s padding so that the error message is within the border.

If it turns out that lengthy validation messages are unavoidable, then we could do this. Another approach would be to enforce a very small length limit on validation message length and then separate any lengthier descriptions into a separate hint which could be shown using the "form hint" mechanism described at https://trello.com/c/gGtgaRg9

**Comment by robertknight** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;gY8mnzZk&#x2F;409-review-error-messages-generated-by-logged-out-forms-and-check-that-they-make-sense-with-the-new-form-designs"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Review error messages generated by logged-out forms and check that they make sense with the new form designs</a>

**Comment by seanh** [comment]
Fixed by https://github.com/hypothesis/h/pull/3646
