### ISSUE TITLE
No way to get from "Reset your password" page back to "Log in" page

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#3649]
![untitled screencast 30](https://cloud.githubusercontent.com/assets/22498/17329362/3b329db8-58ba-11e6-9d91-1446d19483e8.gif)

**Comment by robertknight** [comment]
1. I'm not sure this is an issue. The user can just use the Back button on their browser.
2. I would assume that we'll be re-doing the home page in future and we can then include a more prominent login link from there.

**Comment by seanh** [comment]
Hmm, well `/login` has links to `/forgot_password` and `/register`, and `/register` has a link back to `/login`, but `/forgot_password` (and `/reset_password`) don't have any link back to `/login` (or to anywhere else). Just seemed odd.

I think "It's not safe to use the back button on forms" is a rule that many users have internalized (learned from online shopping sites or internet banking sites, for example) so they might feel lost if they ended up at `/forgot_password` accidentally, or went to it and then changed their mind.

Not a huge deal though.

**Comment by seanh** [comment]
Suggestion: a footer with an "Already know your password? Log in" link (matches "Already have an account? Log in" on `/register`)

**Comment by conordelahunty** [comment]
I think @seanh 's suggestion is fair.
