### ISSUE TITLE
CORS issue with annotator.js

### ISSUE THREAD

**Issue by cwbuecheler** [hypothesis/h#3654]
Hi guys,

I saw there was a CORS problem already addressed in the closed issues, but I'm still having a problem and I'm not quite sure if it's something I'm doing wrong, or an issue with hypothesis itself.

I'm trying to use annotator.js 1.2.10 -- I don't want to use the hypothesis client as it contains more UI than I need at the moment. I'm trying to use Annotator's auth and store plugins to connect to the hypothesis API, and I have them up and running on my local machine (standard OSX apache). It seems to retrieve my (empty) list of annotations all right, but when I try to save an annotation, I get the following error:

`XMLHttpRequest cannot load https://hypothes.is/api/annotations. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost' is therefore not allowed access. The response had HTTP status code 404.`

Does this perhaps have something to do with the fact that I'm running on localhost?
### Steps to reproduce
1. Create a simple page using annotator.js with the auth and store plugins enabled, and serve it from apache on OSX.
2. Highlight some words, annotate them, and attempt to save the annotation
3. Look for the error in the 
### Expected behaviour

Connection to the hypothesis API is established and a save attempt is made
### Actual behaviour

CORS error with no save attempt
### Browser/system information

Chrome 52.0.2743.82 (64-bit) on OSX El Capitan (latest)
### Additional details

I get this same error if I try to manually post with the following code, which is why I think this might be a hypothesis error and not an annotator.js error:

```
    $.ajax({
        url: 'https://hypothes.is/api/annotations',
        headers: { 'Authorization': 'Bearer myAPIkeythatIdontwanttopasteingithub' },
        method: 'POST',
        dataType: 'json',
        data: testData,
    })
    .done(function(resp) {
      console.log(resp);
    });
```

**Comment by nickstenning** [comment]
Hi @cwbuecheler -- sorry for the slow response here. This isn't a CORS bug in Hypothesis, I'm afraid, but an incompatibility between Annotator 1.2.x and the current Hypothesis API. The former expects it can load recent annotations from `/api/annotations`, but that's not how the Hypothesis API works.

You might be able to get a little further by using Annotator 1.2.x's `loadFromSearch` option and passing it a search URL like `https://hypothes.is/api/search?uri=https://...`, but I suspect you'll probably run into more issues, as the Hypothesis API is not fully backwards compatible with the Annotator HTTP API (which is now going on 10 years old).

**Comment by cwbuecheler** [comment]
No problem. Thanks for the answer. I ended up going a different direction to meet the project's requirements.
