### ISSUE TITLE
Logging in with new password results in session error.

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#3752]
### Steps to reproduce
1. Login to the sidebar (i.e. establish a new session)
2. Logout.
3. Click Log In again. 
4. Click forgot your password?
5. Submit your email to reset.
6. Get your reset code from email.
7. Enter your reset code and new password.
8. Go back to the original login form and enter your username and password.

Fun mod:
If for 8. you enter an invalid username you get a full server error and a Sentry report.

### Expected behaviour
You should be logged in.

### Actual behaviour
You get a session invalid error.

### Browser/system information
Tell us which browser, browser version, and operating system you were using when
you encountered this issue.

### Additional details
This was reported by a user, here: https://hypothesis.zendesk.com/inbox/conversations/511

**Comment by dwhly** [comment]
Ok, now I'm struggling to reproduce this.  Arg.

**Comment by nickstenning** [comment]
The issue reported by the user was fixed by #3754.

**Comment by dwhly** [comment]
ty!
