### ISSUE TITLE
When using f.lux i cannot see highlights because they are yellow. 

### ISSUE THREAD

**Issue by oliversauter** [hypothesis/h#3765]
### Steps to reproduce
1. install and enable f.lux
2. make highlight
3. not seeing highlight

### Expected behaviour
Abiltiy to distinguish between highlight and background

### Actual behaviour
To to f.lux ability to remove the blue color scale from the screen, you don't see the yellow highlights anymore because the screen is completly red-ish.

Maybe a change in color for the highlight does the trick.

### Browser/system information
Tell us which browser, browser version, and operating system you were using when
you encountered this issue.

### Additional details
If you have other information which might be helpful, please include it. If a
screenshot will help to illustrate the issue you are reporting, please include
one.

**Comment by dwhly** [comment]
@oliversauter Hola!  Just a friendly note that this is a place to record issues with the Hypothesis application that you can replicate--i.e. ones that are defects in the software we've shipped. Steps to reproduce should focus on our application. If there's an interaction issue with f.lux and H, you'll probably want to debug that on your side.

I'm going to close this for now.  Feel free to open a fresh issue for any issues with H.

**Comment by oliversauter** [comment]
hey! ah ok, should I post such things then as a feature request?
