### ISSUE TITLE
Form field error messages overlap scroll bars

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#3777]
![screenshot from 2016-08-24 19-16-49](https://cloud.githubusercontent.com/assets/22498/17942464/62dd3658-6a2f-11e6-91e2-bc3d12fb3fe3.png)

**Comment by seanh** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;D5kUsmPr&#x2F;671-move-activity-pages-error-messages-under-form-fields"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Move activity pages error messages under form fields</a>

**Comment by chdorner** [comment]
This does not happen anymore:
![2016-09-29-125654_518x190_scrot](https://cloud.githubusercontent.com/assets/112063/18951210/45e7582c-8644-11e6-9b68-299a89efaffe.png)

Closing.

**Comment by seanh** [comment]
@robertknight @sean-roberts Do either of you know what's happened here? ^ It's good that the error message no longer overlaps the scrollbar, and I notice that the user's text no longer overlaps with the error message either, but now it seems that the error message squashes down the user's text into about half the width of the space available.

Anyway, iirc we decided to [move the error messages outside of the form fields](https://trello.com/c/D5kUsmPr/671-move-activity-pages-error-messages-under-form-fields) which should hopefully fix this.

**Comment by sean-roberts** [comment]
yeah, I am not sure what changed to cause the new behavior but, as you sad, it will be gone with that other ticket.
