### ISSUE TITLE
Paginator control < > icons needed

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#3787]
The current implementation uses `<` and `>` characters but these don't look quite the same as what's in the mockup, icon image files are needed instead.

**Comment by seanh** [comment]
The mockup:

![pagination_-_in_context](https://cloud.githubusercontent.com/assets/22498/18792350/0c42ebe4-81ae-11e6-996d-4495898ba2d6.png)

On master:

![screenshot from 2016-09-23 16-51-49](https://cloud.githubusercontent.com/assets/22498/18792354/14b75f4e-81ae-11e6-85a1-d191ee2c43a1.png)

@conordelahunty do you have an icon for this?

**Comment by conordelahunty** [comment]
@seanh Yo:

[pagination icons.zip](https://github.com/hypothesis/h/files/493048/pagination.icons.zip)
