### ISSUE TITLE
Image annotation

### ISSUE THREAD

**Issue by csillag** [hypothesis/h#380]
Annotorious is an Open Source image annotation toolkit written in JavaScript. 

https://github.com/annotorious/annotorious

We should integrate it to get this feature.

**Comment by oliversauter** [comment]
@tilgovi @dwhly @judell  Hey guys I wanted to pop in and know what happened with this feature? 

here are the feature requirements I wrote: https://github.com/WorldBrain/VISION-ROADMAP-FEATURES/issues/14
