### ISSUE TITLE
Adder doesn't appear on onlinelibrary.wiley.com PDF files

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#3828]
If you launch h on one of these PDF files and select some text, no adder popup appears. No error in console.

https://via.hypothes.is/http://onlinelibrary.wiley.com/doi/10.1890/070037/pdf

https://via.hypothes.is/http://onlinelibrary.wiley.com/doi/10.1111/geb.12295/pdf

https://via.hypothes.is/http://onlinelibrary.wiley.com/doi/10.1890/12-0370.1/pdf

**Comment by dwhly** [comment]
Sean, this is working for me.
https://drive.google.com/file/d/0B0yW-dSdEYAcZk9KLTRVNlR2ZFE/view

**Comment by dwhly** [comment]
I am seeing a difference between Chrome and FF.  When I browse to the via link with FF, there is an iframe wrapped around the PDF, and it looks like this:

![screen shot 2016-09-05 at 2 36 21 pm](https://cloud.githubusercontent.com/assets/1413074/18257310/41547028-7376-11e6-97e8-1721e72ec1f3.png)

When I browse with Chrome, no iframe is shown, and I can annotate just fine.

![screen shot 2016-09-05 at 2 37 50 pm](https://cloud.githubusercontent.com/assets/1413074/18257317/6933a5fa-7376-11e6-8456-a9f94bd5e824.png)

**Comment by seanh** [comment]
@dwhly It also differs between Ff and Chrome for me, but they are both different from what you see.

* Chrome: with either Via or the Chrome extension I am getting the iframe that you are getting in Ff. I cannot annotate the PDF, but I can annotate the HTML above the PDF / outside of the PDF's iframe

* Firefox: with Via I get the iframe, same as you, but Ff does not render the PDF for me at all, it downloads it as a file! I see the site with an empty iframe where the PDF should be. h launches and I can annotate the HTML outside of the iframe.

**Comment by ethanwhite** [comment]
I see the same behavior as @seanh on Chrome (Chromium 51.0.2704.79 Ubuntu 15.10).

My behavior on Firefox (Mozilla Firefox 47.0, Ubuntu 15.10) is the same as the Chrome behavior. The pdf displays, I can edit annotate the HTML above the pdf, but not the pdf itself.

**Comment by dwhly** [comment]
cc our contacts at Wiley,  @BigBlueHat :)

**Comment by BigBlueHat** [comment]
Do you all have a preferred way of handling this and similar scenarios?

What's in my head right now is a `<link rel="canonical" href="..." />` that matches the `<iframe />` URL and (if this is even possible) the Add-on (at least) could avoid injecting in the main page, but rather inject into the `iframe` instead.

There's some session/cookie handling on these URLs that's unlikely to survive the Via proxy scenario, but perhaps something like the above would work for the Add-on?

Also, it should be noted that I'm not personally connected to the team(s) that work on that bit of code, so my influence is limited. However, I'm happy to make a case for "Annotation Enablement" (as ever!). :wink:

**Comment by nickstenning** [comment]
As detailed above, the page embeds the PDF in an iframe when visited using Firefox. At the moment, Hypothesis has no way to embed its client into arbitrary frames of a page.

Closing as this isn't a bug.
