### ISSUE TITLE
proper citations on standalone annotation pages

### ISSUE THREAD

**Issue by csillag** [hypothesis/h#383]
When showing an annotation on it's standalone, linkable page, we should show a proper citation for the original document, if it has one.

**Comment by JakeHartnell** [comment]
> What do we want?
> In fact I am not sure. IIRC, @ianmulvany (of the eLife fame) was the original source of this idea. Maybe he can chip in the discussion?

And though this issue has been open for almost another year, it's still unclear. Closing.
