### ISSUE TITLE
Prevent double-submitting of user registration form

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#3830]
It's possible to create an `IntegrityError` by double-clicking on the submit button on the user account registration form: https://sentry.io/hypothesis/prod/issues/154374560/activity/

Suggest solution: disable the submit button the first time it's clicked.

Presumably this much be done in JavaScript? And the no-js fallback behaviour is to just not have this feature (and continue to allow potential multiple submitting)?

What happens if the request is submitted but the browser doesn't receive a response. Do we _want_ to allow resubmitting of the form when that happens?

**Comment by robertknight** [comment]
> Presumably this much be done in JavaScript?
> And the no-js fallback behaviour is to just not have this feature (and continue to allow potential multiple submitting)?

You could generate random one-time usage tokens for the form that are kept for say, 24 hours or so and include that as a hidden form field.

Adding client-side logic to just disable the button after submission is probably _simple enough_™ though

**Comment by nickstenning** [comment]
> You could generate random one-time usage tokens for the form that are kept for say, 24 hours or so and include that as a hidden form field.

This doesn't solve the problem, because the problem is two transactions executing in parallel on different application servers trying to make the same change.

There is fundamentally no way of solving this problem on the server side short of suppressing the error. Disabling the form submit button so it can't be double-submitted is the only actual fix here.

**Comment by robertknight** [comment]
> This doesn't solve the problem, because the problem is two transactions executing in parallel
> on different application servers trying to make the same change.

Yes it does - it prevents the same rendered version of a form being submitted twice, assuming the token storage is shared between app servers. I'm not recommending spending time on such a thing because the client-side solution is fine, but I thought I'd just note it.

**Comment by nickstenning** [comment]
No it doesn't! The whole point is that the transaction that (in your suggested solution) would mark the token as having been used wouldn't commit until after the second request was already being processed.

The unique constraint on the username field serves exactly the same purpose and yet we still have to deal with the possibility that two requests for the same form are submitted at the same time.
