### ISSUE TITLE
Public annotation fails to direct link with permission error

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#3837]
### Steps to reproduce
1. Follow this link: https://hyp.is/BQXja0cFTTCfIM5S-OVT1g/smartdatacollective.com/tamaradull/298401/pii-anonymized-data-and-big-data-privacy

### Expected behaviour
The annotation should be visible and anchored to the page.  Clearly the annotation (https://hypothes.is/a/BQXja0cFTTCfIM5S-OVT1g) is a public one.  And the sentence it's anchored to is plainly visible on the page.

### Actual behaviour
The sidebar opens and a permission error shows: "You do not have permission to view this annotation."

### Browser/system information
Modern Chrome.

### Additional details
Was originally shared via this tweet: https://twitter.com/dbarthjones/status/772612941359222784

**Comment by robertknight** [comment]
There is a missing URL equivalence here.

The annotation was originally made on http://smartdatacollective.com/tamaradull/298401/pii-anonymized-data-and-big-data-privacy but the page now redirects to, and has a `<link rel="canonical">` pointing at [http://**www.**smartdatacollective.com/tamaradull/298401/pii-anonymized-data-and-big-data-privacy](http://www.smartdatacollective.com/tamaradull/298401/pii-anonymized-data-and-big-data-privacy )

**Comment by dwhly** [comment]
ugh.

**Comment by dwhly** [comment]
Closing as wontfix for now.
