### ISSUE TITLE
Web of ideas (multiple threads / traits knotted together)

### ISSUE THREAD

**Issue by csillag** [hypothesis/h#386]
Since we are already talking about these ideas, let's add a ticked for the real meat, too: add support for building / presenting the web of ideas.

( This could be considered an advanced version of #385 .)

Background:

Just like the concept of narratives / threads, this idea goes back (at least) as far as 1945, to [the seminal article of Vannevar Bush](http://www.theatlantic.com/magazine/archive/1945/07/as-we-may-think/303881/), describing the mythical Memex.

Short version: as a "narrative" / "thread" is a linear sequence of annotations, presented in a specific order, with possible connecting text segments, this "web" proposed here is a network of annotations, connected by association (or some other kind of connection).

Quoting (some of) the relevant parts of the original article:

  * * * *

The human mind [...] operates by association. With one item in its grasp, it snaps instantly to the next that is suggested by the association of thoughts, in accordance with some intricate *web of trails* carried by the cells of the brain. [...] Man cannot hope fully to duplicate this mental process artificially, but he certainly ought to be able to learn from it. [...] Consider a future device [...] When the user is building a trail, he names it [...] Before him are the two items to be joined, [...] The user taps a single key, and the items are permanently joined. [...] Thereafter, at any time, when one of these items is in view, the other can be instantly recalled [...] Moreover, when numerous items have been thus joined together to form a trail, they can be reviewed in turn, rapidly or slowly [...] It is exactly as though the physical items had been gathered together from widely separated sources and bound together to form a new book. It is more than this, for *any item can be joined into numerous trails*. [...] The owner of the memex, [...] runs through an encyclopedia, finds an interesting but sketchy article [...] Next, in a history, he finds another pertinent item, and ties the two together. Thus he goes, building a trail of many items. Occasionally he inserts a comment of his own, either linking it into the main trail or joining it by a side trail to a particular item. [...] he branches off on a side trail [...] And his trails do not fade. Several years later, [...] Tapping a few keys projects the head of the trail. [...] runs through it at will, stopping at interesting items, going off on side excursions.

  * * * *

Most of the considerations about #385  ( which is essentially a simplified, linear-only version of this ) are valid here, too.

What is radically different is the UI that is required for interacting with the data.

Some considerations about this:

- Considering all the diverse connections, we might be talking about an infinite web here, so (unlike the case with "simple", linear narratives) it's not a realistic aim to present all the items in the whole web on the screen at the same time. Instead, we should just present the element at our current focus, and it's connections (to some degree). The user should have the ability to navigate along the connections of the web freely. As the focus changes, the system could add new elements to the view. (Basically, this would be like a viewport / window moving on an infinite plane.)

- There are (at least) 3 different views that could/should be displayed:

1. The currently selected item, in it's original context
2. The currently selected item in a standalone page, with links to adjacent items.
3. The (visible part of) the visualized web itself, with short summary of the items.

It probably makes sense to use a split-display solution (like we do currently), combining several of the above aspects. For example, here are a few examples about how a such a split display solution might look like:

![example 1](https://f.cloud.github.com/assets/2093792/401858/4d50995e-a8ec-11e2-856e-0517a66519da.png)
![example 2](https://f.cloud.github.com/assets/2093792/401859/4d69efc6-a8ec-11e2-8f52-bf4e19833899.png)
![example 3](https://f.cloud.github.com/assets/2093792/401860/4d9af56c-a8ec-11e2-8b0c-99666cf7049b.png)

This is just one possibility; there are obviously several other options, too.

(Disclosure: I am shamelessly promoting my earlier work here - because I believe that some parts of it could benefit Hypothes.is :)

**Comment by nickstenning** [comment]
Going to close this. Any discussion about these topics is probably better suited to a mailing list or a design meeting than GitHub issues at this stage.
