### ISSUE TITLE
None is shown on search page when document has no title

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#3860]
If the document has `None` for its title then `"None"` is displayed on the search page:

![screenshot from 2016-09-13 14-45-25](https://cloud.githubusercontent.com/assets/22498/18476137/d2d6f4a8-79c0-11e6-8444-6d5fb37d9f8f.png)

**Comment by chdorner** [comment]
Exciting! (we have a few more of these)

**Comment by seanh** [comment]
@chdorner Was going to ask you if this is really an issue? The model can't guarantee that a document does actually have a title, can it? So it's always a possibility that the title can be `None`, and the presentation code has to deal with this? Or can we do something about this in the model?

**Comment by chdorner** [comment]
You're right, there isn't much we can do to guarantee a title. But it shouldn't show "None" :)

**Comment by seanh** [comment]
Yeah, I think something like "Untitled document" should be fine

**Comment by seanh** [comment]
This was fixed by https://github.com/hypothesis/h/pull/3908
