### ISSUE TITLE
Documents annotated with Via have via.hypothes.is as their domain name

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#3887]
![screenshot from 2016-09-19 20-00-13](https://cloud.githubusercontent.com/assets/22498/18645102/c47a35a4-7ea3-11e6-8815-fe90053b87d8.png)

**Comment by nickstenning** [comment]
I don't think this is true in general, because I've just made a bunch of annotations through via and they don't show up this way. There must be specific circumstances under which we (incorrectly) end up storing the via prefix on the annotations.

**Comment by seanh** [comment]
Hmm, just made a test private annotation on prod via and it does show up like this. I'll see if I can reproduce locally

**Comment by chdorner** [comment]
#3910 fixed this.
