### ISSUE TITLE
Export annotations in various formats

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#394]
HTML, TXT, JSON, CSV, ZIP?  How can we allow users to get their data out of our system most easily--- and in a format that's most useful to them later.  Data portability is the theme.

**Comment by nickstenning** [comment]
Closing as a feature that will come down the product prio and design pipeline.

**Comment by timeknows** [comment]
This thread has been closed for a year, yet I can't find a way to export my notes. Is this still in development? I don't see the difference in using evernote webclipper, instapaper etc if I can't control my own notes. Thanks!

**Comment by judell** [comment]
Hi @timeknows, 

We are exploring a few different approaches to viewing and exporting sets of annotations. Here is one prototype that you can use to export your notes in several formats:

http://jonudell.net/h/facet.html?facet=any

We'd love to know your thoughts on how you'd want to select, export, and reuse your notes.

**Comment by timeknows** [comment]
@judell Thank you, this is actually great. As I'm interested in the data, even this prototype solves my needs (cvs is great, json would also be super handy). For the moment, I personally don't have many annotations, so the `select` property is great. But one can imagine that it will clutter fast (not to mention public tags that don't belong to me). In this case, I would say that a sort of advanced search would be needed (specific user + specific tag + specific tag + etc). But I know that can be more complicates and will use more resources. I think the project is awesome, great work!
