### ISSUE TITLE
Sourcemap build errors

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#3941]
**Steps to reproduce**
1. Set the `NODE_ENV` env var to `production`
2. Run `gulp build-js`

**Results**

Output: Includes a ton of unexpected warnings:

```
 ~/h/r/h > set -x NODE_ENV production
 ~/h/r/h > gulp build-js
[08:26:43] Using gulpfile ~/hypothesis/repos/h/gulpfile.js
[08:26:43] Starting 'build-vendor-js'...
[08:26:49] Finished 'build-vendor-js' after 5.88 s
[08:26:49] Starting 'build-js'...
WARN: Couldn't figure out mapping for ?:11,0 → 1,549 []
WARN: Couldn't figure out mapping for ?:11,4 → 1,552 []
WARN: Couldn't figure out mapping for ?:11,32 → 1,561 []
WARN: Couldn't figure out mapping for ?:11,21 → 1,579 []
WARN: Couldn't figure out mapping for ?:11,73 → 1,588 []
WARN: Couldn't figure out mapping for ?:11,53 → 1,604 []
WARN: Couldn't figure out mapping for ?:11,60 → 1,612 []
WARN: Couldn't figure out mapping for ?:11,84 → 1,621 []
WARN: Couldn't figure out mapping for ?:11,94 → 1,630 []
```

**Notes**

This may relate to https://github.com/hughsk/uglifyify/issues/56

**Comment by carl1218** [comment]
`<launch>
  
  <node name="hokuyo_node" pkg="hokuyo_node" type="hokuyo_node">
    <param name="port" type="string" value="/dev/ttyACM0"/>
    <param name="min_ang" value="-1.7" />
    <param name="max_ang" value="1.7" />
    <param name="min_range" value="0.18" />
    <param name="hokuyo_node/calibrate_time" value="true" />
    <param name="tracking_frame" type="string" value="laser_link" />
    <remap from="scan" to="/laser_scan"/>
  </node>

  <node name="cartographer_node" pkg="cartographer_ros"
      type="cartographer_node" args="
          -configuration_directory $(find cartographer_ros)/configuration_files
          -configuration_basename hokuyo.lua"
      output="screen">
    <remap from="scan" to="/laser_scan" />
  </node>
</launch>`

**Comment by carl1218** [comment]
`<launch>
  
  <node name="hokuyo_node" pkg="hokuyo_node" type="hokuyo_node">
    <param name="port" type="string" value="/dev/ttyACM0"/>
    <param name="min_ang" value="-1.7" />
    <param name="max_ang" value="1.7" />
    <param name="min_range" value="0.18" />
    <param name="hokuyo_node/calibrate_time" value="true" />
    <param name="tracking_frame" type="string" value="laser_link" />
    <remap from="scan" to="/laser_scan"/>
  </node>

  <node name="cartographer_node" pkg="cartographer_ros"
      type="cartographer_node" args="
          -configuration_directory $(find cartographer_ros)/configuration_files
          -configuration_basename hokuyo.lua"
      output="screen">
    <remap from="scan" to="/laser_scan" />
  </node>
</launch>`

**Comment by carl1218** [comment]
**`<launch>
  
  <node name="hokuyo_node" pkg="hokuyo_node" type="hokuyo_node">
    <param name="port" type="string" value="/dev/ttyACM0"/>
    <param name="min_ang" value="-1.7" />
    <param name="max_ang" value="1.7" />
    <param name="min_range" value="0.18" />
    <param name="hokuyo_node/calibrate_time" value="true" />
    <param name="tracking_frame" type="string" value="laser_link" />
    <remap from="scan" to="/laser_scan"/>
  </node>

  <node name="cartographer_node" pkg="cartographer_ros"
      type="cartographer_node" args="
          -configuration_directory $(find cartographer_ros)/configuration_files
          -configuration_basename hokuyo.lua"
      output="screen">
    <remap from="scan" to="/laser_scan" />
  </node>
</launch>`**

**Comment by leedenison** [comment]
Obsolete.
