### ISSUE TITLE
Admin panel "delete user" didn't ask for confirmation

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#3951]
### Steps to reproduce
1. Go to admin panel
2. Put in a username (presumably one without annotations?)
3. Click delete

### Expected behaviour
Confirmation should be requested

### Actual behaviour
Delete happened w/o confirmation

### Browser/system information
Chrome

### Additional details
I presume that perhaps this only works this with accounts that have zero annotations (hard to test that premise!), but I think it's quite dangerous for this button to work without any confirmation whatsoever, since "Delete" could easily be clicked by accident given that the "change username" button is also close by.  My presumption was that confirmation was always required (I know it has been before).

Filing this as a bug in case it wasn't our intention to allow user deletes without confirmation.  If it was, we might want to reconsider.

**Comment by chdorner** [comment]
It should always ask, we had that issue once and fixed it. I will look into it today

**Comment by chdorner** [comment]
I talked to @robertknight and it looks like the bug got introduced with 90e4a7192e6d72dec983b122f0cfa2428e5435b6. Namely the variable [`window_`](https://github.com/hypothesis/h/blob/master/h/static/scripts/controllers/admin-users-controller.js#L6) is not actually the window, so the call later to `window_.confirm` fails and thus not showing a confirmation dialog.

He's going to take this on tomorrow.
