### ISSUE TITLE
Error upgrading Notifications form when activity_pages flag is not enabled

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#3965]
**Steps to reproduce**
1. Log in to hypothes.is with an account that does not have activity_pages enabled
2. Go to https://hypothes.is/account/settings/notifications

Related Sentry issue: https://sentry.io/hypothesis/prod/issues/163855938/

**Result**
Error message such as `Failed to upgrade element [object HTMLFormElement] with controller function t() : TypeError: e is undefined` in console. This happens because we try to enable inline editing but the form is missing the required controls because the activity_pages flag is off.

The `use_inline_editing` flag should not be set on this form if activity_pages is off.

**Comment by nickstenning** [comment]
> The use_inline_editing flag should not be set on this form if activity_pages is off.

It's probably simpler to adjust the deform templates to only output markup which will be upgraded if `activity_pages` is on *and* the `use_inline_editing` flag is set on the form.

**Comment by nickstenning** [comment]
Closing as `activity_pages` is now fully shipped.
