### ISSUE TITLE
h rss feed doesn't pass feedvalidator check

### ISSUE THREAD

**Issue by judell** [hypothesis/h#3976]
### Steps to reproduce
1. http://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fhypothes.is%2Fstream.rss%3Furi%3Dhttp%3A%2F%2Fblog.jonudell.net
### Expected behaviour

Feed should validate
### Actual behaviour

It doesn't, the validator reports a couple of problems.

**Comment by chdorner** [comment]
Do we need to ensure backwards compatibility here? I'm guessing that there are people out there that are already using the feeds from scripts and fixing the validation issues (especially the date format and `guid`) could break these existing integrations.

**Comment by judell** [comment]
@chdorner missed this when you first posted, my $0.02, not much use of our feeds (esp. since they don't support groups), I wouldn't worry about back-compat for invalid feeds.
