### ISSUE TITLE
Flash on deleting lozenges

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#3987]
When you delete a lozenge, there is sometimes a noticeable "flash" when all the remaining lozenges seem to disappear for a sec and then reappear

![peek 2016-10-20 18-35](https://cloud.githubusercontent.com/assets/22498/19570969/12326dbc-96f4-11e6-9ac6-21d922884feb.gif)

**Comment by sean-roberts** [comment]
This is worse than just a flash. The flash is the result of a delay between clicking and the page getting reloaded. This also introduces a race condition of the page being reloaded and the input being used to type a new parameter. Really annoying UX

**Comment by seanh** [comment]
I'm going to be rewriting how deleting lozenges work, coming soon...

**Comment by nickstenning** [comment]
Looks like this is fixed.
