### ISSUE TITLE
Too many lozenges overflow the search box

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#3988]
![screenshot from 2016-10-20 18-37-14](https://cloud.githubusercontent.com/assets/22498/19571052/7910558a-96f4-11e6-9683-a0e0b52211d0.png)

Or one really long one:

![screenshot from 2016-10-20 18-37-46](https://cloud.githubusercontent.com/assets/22498/19571056/7d3affb6-96f4-11e6-9117-b201e4ea1a7b.png)

This also makes it difficult to put the keyboard focus into the search box.

I'm not sure what the desired design for this is?

**Comment by seanh** [comment]
A simple fix for this would be a horizontal scroll bar. Although I think that once the search box is full (and a horizontal scrollbar has appeared) it's difficult to click on the search box in order to put the keyboard focus into it, because the lozenges are in the way. Would have to watch out for that.

**Comment by seanh** [comment]
@robertknight noted that while this is a (semi) extreme case on desktop, on mobile this can happen as soon as you have a single lozenge.

Following the meeting, I think this one is blocked waiting on design?

**Comment by sean-roberts** [comment]
I saw recently, (on a google site (trends? maybe)  I can no longer find), the lozenges were presented as filters below the search input. Allowing the lozenges to grow as needed and allowing the input to always stay in the same place. So the search input would never change width and the lozenge container was below the search input - so adding new lozenges places it below the input. Trying to put them inline causes plenty of headaches - especially for mobile. @conordelahunty @ajpeddakotla

**Comment by conordelahunty** [comment]
I think we need to be careful not to try and redesign the search bar at this stage, we need to focus on shipping. I think for one we can increase the width of the search bar, there is lots of room in the nav bar currently on desktop. I think we then need to think about some other constraints we have. This has to work on mobile so I think that the way we would do it there is have the search bar always be the same width and height but allow the users to drag/scroll the facets from left to right. The pinterest ios app is a good example of this in action. This might feel a bit weird on desktop though so I think we need to have a quick conversation on Monday to see what we can do quickly so we can get this thing out the door.

**Comment by sean-roberts** [comment]
I agree and it's just a suggestion to our problem. But I wouldn't say placement of lozenges warrants "redesigning the searchbar".

**Comment by sean-roberts** [comment]
After talking it over with the team and trying out some different options, we are going to go with keeping the lozenges where they are now and having the input wrap to a new line at the break point. We need to truncate the lozenges to limit have far they will grow.

**Comment by seanh** [comment]
Sounds like a good plan
