### ISSUE TITLE
x icon needed for lozenges

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#3989]
This should be an svg icon, not the letter x:

![screenshot from 2016-10-20 18-52-37](https://cloud.githubusercontent.com/assets/22498/19571672/d6228c28-96f6-11e6-8ab2-7da9e19ec7e5.png)

**Comment by sean-roberts** [comment]
@conordelahunty  got something for this?

**Comment by conordelahunty** [comment]
[x icon.zip](https://github.com/hypothesis/h/files/550098/x.icon.zip)

**Comment by sheetaluk** [comment]
https://github.com/hypothesis/h/pull/4015

**Comment by chdorner** [comment]
This is now fixed.
