### ISSUE TITLE
Lozenges have an unwanted trailing space

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#3993]
The content string is "lozenge " rather than "lozenge" (in the HTML looks like there may be a newline?)

![peek 2016-10-20 19-18](https://cloud.githubusercontent.com/assets/22498/19572470/4dfd61a2-96fa-11e6-9905-cf3f152a8aca.gif)

**Comment by sean-roberts** [comment]
I reproduced this and inspected the Range of the selection. The endContainer is the x container. So it's overflowing the selection into the close node. That said, there is no whitespace that we can take away that can fix this.

We can probably close this unless you think there is something to be done

**Comment by seanh** [comment]
Ok, if you don't think there's anything to be done lets just close it
