### ISSUE TITLE
Potential injection vulnerability in Lozenge Controller

### ISSUE THREAD

**Issue by sean-roberts** [hypothesis/h#3996]
Potential injection vulnerability in Lozenge Controller

https://github.com/hypothesis/h/blob/0e7ba167d5d36429869fbfa0e49c546bbbcf164c/h/static/sc
ripts/controllers/lozenge-controller.js#L23

which at the time of reporting is:

```
      '<div class="js-lozenge__content lozenge__content">'+
      options.content+
      '</div>' +
```

As it is right now, the only injection that I can make happen is injecting some HTML. The only thing preventing this from being a full-blown vulnerability right now is that the SearchTextParser is splitting the content on spaces before it gives it to the HTML. We should be more defensive here and not assume that the content being passed into this module has been sanitized.

**Comment by sheetaluk** [comment]
https://github.com/hypothesis/h/pull/4017
