### ISSUE TITLE
Search page content is not centered on page

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#4018]
Once the group and user sidebars are in on the search page, let's center the page contents (including the contents of the nav bar at the top):

![screenshot from 2016-11-01 17-12-25](https://cloud.githubusercontent.com/assets/22498/19899041/7daea1f8-a056-11e6-8983-80cc54708d2c.png)

**Comment by sean-roberts** [comment]
It's a pretty significant design decision to center content like that. We need to make sure we are doing this correctly and are weighing the UX impacts it has.

**Comment by seanh** [comment]
This was a request from Conor so I think it has been thought through / was always the intention. The idea is to take the combined width (on full-size screens) of the search results, sidebar, and gap in-between them, make that the max width of the page and center it. Also use the same max width for the contents of the nav bar at the top of the page, and center those contents within the nav bar. Seems fairly sensible?
