### ISSUE TITLE
Search bar style update

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#4019]
The search bar isn't supposed to look quite like this:

![screenshot from 2016-11-01 18-06-04](https://cloud.githubusercontent.com/assets/22498/19901135/f15fa762-a05d-11e6-9ea6-363faa72cbbb.png)

Here's a mockup from Conor showing how he wants the search box to look, now that it needs to be tall enough to contain lozenges. The search box takes up the entire height of the nav bar:

![user_page](https://cloud.githubusercontent.com/assets/22498/19901213/42f74ae4-a05e-11e6-9cf1-8e93deba1f67.png)

And this is how the dropdown menu is supposed to look with the above search bar design:

![search](https://cloud.githubusercontent.com/assets/22498/19901243/5f43b372-a05e-11e6-86a8-71bdec89a460.png)

**Comment by nickstenning** [comment]
I don't think this is a bug, as the design we have was signed off on and shipped. If we want to make changes to the design in future we will, and I don't think tracking divergence from a past mockup here is going to help us with that.
