### ISSUE TITLE
Searching for a URL from the dropdown is not properly working

### ISSUE THREAD

**Issue by sean-roberts** [hypothesis/h#4035]
https://hypothes.is/search?q=url%3Ahttps%3A%2F%2Fwww.donaldjtrump.com

https://hypothes.is/search?q=url%3Ahttps%3A%2F%2Fwww.hillaryclinton.com

Both of these searches are returning bad result sets - nothing to do with the urls and if we do not have any annotations for them, we should see no results at all

**Comment by judell** [comment]
The correct query uses uri: not url:

https://hypothes.is/search?q=uri%3Ahttps%3A%2F%2Fwww.donaldjtrump.com

**Comment by sean-roberts** [comment]
This still needs to be fixed

**Comment by judell** [comment]
Yep, I missed the part where actually using the dropdown fails :-)

We've been around the block a few times on this. Can we alias url: to uri: so both will work? (As we did with tag and tags.)
