### ISSUE TITLE
Activity page layout broken on iOS

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#4048]
What I see when visiting https://stage.hypothes.is/users/robertknight/search on my iPhone 5 with iOS 10.1.1:

![activity-pages-ios](https://cloud.githubusercontent.com/assets/2458/20215653/be8ee520-a80d-11e6-9619-65e552a622a6.png)

Issues include:

- [ ] Search input and navbar overlap
- [ ] User profile widget link should be displayed just above search results but is not visible
- [ ] Focusing the search input and typing "tag:" does not display any suggestions, but it does on desktop

**Comment by seanh** [comment]
I don't seem to be seeing this anymore on master...

**Comment by robertknight** [comment]
Indeed. I don't see this with the latest deployment on stage. I have a feeling that whatever the issue is will come back to bite at some point in future but we can close for the moment.
