### ISSUE TITLE
Some cards in /search are narrower

### ISSUE THREAD

**Issue by chdorner** [hypothesis/h#4051]
_Copied from hypothesis/client#166._

### Steps to reproduce
1. Go here: https://hypothes.is/users/dwhly/search?q=uri%3Ahttps%3A%2F%2Fmyhealthonline.sutterhealth.org%2Fmho%2Finside.asp%3Fmode%3Dlabdetail%26orderid%3D2
2. Click on the document to expand

### Expected behaviour
The card should be wider

### Actual behaviour
It's narrow.

### Browser/system information
Chrome

**Comment by seanh** [comment]
Closing as dup of https://github.com/hypothesis/h/issues/3975
