### ISSUE TITLE
Usernames in document buckets aren't linked

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#4059]
![screenshot from 2016-11-11 20-07-22](https://cloud.githubusercontent.com/assets/22498/20228766/ccef46ea-a84a-11e6-8e49-42cd0e9eed42.png)

The username(s) under _Annotators_ on the right here. Options: link to that user's search page? (This is what the username in the top left of each annotation card links to.)

**Comment by ajpeddakotla** [comment]
Agree w/ this: `Options: link to that user's search page`

**Comment by dwhly** [comment]
Why wouldn't these behave the same way that usernames in the user panel do?  i.e. add that user to the search?

**Comment by seanh** [comment]
This is blocked waiting on a decision (from @ajpeddakotla I think?) about whether clicking on one of these usernames should add that user into the current search query, or simply link you to that user's page.

**Comment by robertknight** [comment]
@sheetaluk implemented this in #4086. Usernames replace rather than augment the current query. Let's give this behavior a try and see if it feels intuitive.

**Comment by robertknight** [comment]
Ah, no - I misread the description. The usernames in the annotation card are now linked but not the usernames in the 'Annotators' panel.
