### ISSUE TITLE
No direct link to annotation on annotation card

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#4061]
![screenshot from 2016-11-11 20-07-22](https://cloud.githubusercontent.com/assets/22498/20228853/3486696e-a84b-11e6-9546-a8ec6f12618c.png)

The annotation cards don't contain any direct link to the annotation. The date in the top-right of the annotation card links to the annotation's page, but there's no bouncer direct link to the annotation in context.

**Comment by dwhly** [comment]
Mockups here: https://projects.invisionapp.com/share/B88RCLRFN#/screens

**Comment by dwhly** [comment]
@conordelahunty Can you supply the "arrow to the upper right" icon file?

**Comment by conordelahunty** [comment]
[up-right-arrow.zip](https://github.com/hypothesis/h/files/592747/up-right-arrow.zip)

**Comment by robertknight** [comment]
Most of the work here is already done in order to implement the direct links in the bucket sidebar. Small size.

**Comment by seanh** [comment]
@robertknight @sheetaluk This is done isn't it? (The share link is a separate issue https://github.com/hypothesis/h/issues/4113 )

**Comment by robertknight** [comment]
Yes, this is done.
