### ISSUE TITLE
Dropdown suggests faceting by the group whose page you're already on

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#4065]
Similar to <https://github.com/hypothesis/h/issues/4064> if I go to group foo's page (so the search is already faceted by group foo) then the dropdown will still show group foo as a suggested facet to add to the search. Suggestion: don't show the already-faceted group as a suggestion.

![peek 2016-11-14 13-44](https://cloud.githubusercontent.com/assets/22498/20266997/96651bea-aa70-11e6-9408-4dfb8aa51eb0.gif)

**Comment by sean-roberts** [comment]
I'd suggest closing as duplicate

**Comment by nickstenning** [comment]
Closing as a dupe of #4064.
