### ISSUE TITLE
The logic for redirecting from search to user or group search and back is wrong

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#4066]
1. Go to a group search page: `https://hypothes.is/groups/<pubid>/search` (user search pages have this same issue). You'll see the group sidebar.

2. Add something else into the search box. Could just be a keyword "foo", or you can facet the search by a user and/or some tags. You're now searching for annotations that are in the group _and_ have the keywords/tag/users. The URL will still be the `/groups/<pubid>/search` one, and the group sidebar will still be shown.

All of the stats in the sidebar will now be wrong. For example, the number of annotations is not the group's number of annotations but the num. that matched the whole query. Also the list of members is only those who have annotations that matched the whole search query.

**Solution**: I talked to @conordelahunty about this and the intended design, at least for a first version, is that **the group sidebar is shown only when the search query contains the group facet and nothing else**. As soon as you add anything else, even just a keyword, into the search box and submit the form it should redirect you back to the general `hypothes.is/search` page which will mean that the group sidebar will disappear.

Same thing for user pages and the user sidebar.

So fixing this should be a server-side only change to the redirecting logic, should not require any template or frontend changes.

**Comment by seanh** [comment]
If we wanted to keep showing the user or group sidebar when doing a "sub-query" within the user or group - I'll just note that there are hidden complexities here and it's not as simple as it might seem at first. I recommend doing the change suggested above for now!

**Comment by nickstenning** [comment]
The numbers in the sidebar have since been fixed to accurately reflect the stats for the group or user in question rather than the current search.
