### ISSUE TITLE
List of group members is incorrect

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#4067]
Even when the group facet is the only thing in the search query, the members list in the groups sidebar is not a list of all the group's members. It's a list of all the creators of the annotations that matched the search query - the shared annotations in the group. So:

* Group members who haven't created a shared annotation in the group are missing
* People who have created a shared annotation in the group and then left the group, are still listed as group members

**Comment by nickstenning** [comment]
Huh? So this was implemented using an aggregation? You can get a list of the group members of the group ORM object.

**Comment by seanh** [comment]
It just uses the users aggregation that was already there, yes. It does seem like this would be easy to fix
