### ISSUE TITLE
Tags are are all lower cased in tags module

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#4068]
### Steps to reproduce
1. Go to activity pages
2. search for annotations that have upper case chars in tags

### Expected behaviour
Tags that have upper case chars in them, should show them as upper case-- like tags in the document module do.

### Actual behaviour
Tags are all lower cased\

**Comment by ajpeddakotla** [comment]
IMO, Not a blocker for release, but we will track for a future release (in the near-term)

**Comment by robertknight** [comment]
What is happening is that both the tags module and the suggestions group together tags that have variations in accents and case into a normalized version which is all lower-case and which has accents stripped. eg. If you have made annotations tagged "CLIMATE" and "climate", you'll see just one tag and one suggestion for "climate".
