### ISSUE TITLE
Annotation cards in activity pages not showing their groups

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#4069]
### Steps to reproduce
1. Go to activty pages
2. Search for annotations that belong to a group
3. Click to expand the document

### Expected behaviour
Annotations inside groups should indicate that they are 

### Actual behaviour
The annotation cards that show won't indicate that they are within a group

**Comment by ajpeddakotla** [comment]
We can reuse the style from the stream for this feature.

**Comment by robertknight** [comment]
This is already implemented.
