### ISSUE TITLE
Removing lozenges from search input does not work in Internet Explorer

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#4075]
The 'X' button to remove lozenges in the search input does nothing when clicked in IE 11. Additionally, the lozenge background does not cover the full width of the lozenge:

![ie-lozenge](https://cloud.githubusercontent.com/assets/2458/20298707/4d57b04e-ab0f-11e6-89dd-672d351f8e54.png)

**Comment by seanh** [comment]
I'm guessing this is for the dynamic lozenges only? Since the plan is to fix deleting dynamic lozenges to work in the same way as deleting the static lozenges does, doing that should fix this issue as well.

**Comment by robertknight** [comment]
Possibly related to https://sentry.io/hypothesis/prod/issues/191207278/ (Element#remove is not implemented in IE)
