### ISSUE TITLE
Filtering view by tag or user using sidebar buttons does not work in IE

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#4077]
### Steps to reproduce
1. In IE, go to a page that displays a sidebar, eg. a group overview page at `/groups/id/search`
2. Click on a member name or tag in the sidebar to filter the results by that name or tag

### Expected behaviour
The selected tag or member name should be added to the search query

### Actual behaviour
Nothing happens. Works in other browsers.

### Browser/system information
Internet Explorer 11, Windows 10.

### Additional details
If you have other information which might be helpful, please include it. If a
screenshot will help to illustrate the issue you are reporting, please include
one.

**Comment by seanh** [comment]
Ah, I honestly thought I had fixed this. I know of a fix that I think should work...
