### ISSUE TITLE
Matching of facet type is case sensitive

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#4080]
### Steps to reproduce
1. Go to `/search`, focus input field
2. Type "Tag:" (note upper case 'T') or "User:"

### Expected behaviour
Search suggestions should appear

### Actual behaviour
No search suggestions appear

### Browser/system information
Firefox v52, iOS 10

### Additional details

I came across this issue because in iOS Safari, the search field by default makes the first letter of the user's input upper case, so if they arrive at `/search` and type "tag:" the input will contain "Tag:".

While we should be able to give the browser a hint that it should not capitalize the first letter of the input in the search input, matching of the facet term should be case-insensitive.

**Comment by chdorner** [comment]
The same applies for `Group:`
