### ISSUE TITLE
Deleting a user facet results in a bad facet

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#4101]
If the search query is already faceted by a user then clicking on that user in the sidebar again _removes_ them from the query. If there is also at least one other user in the query then this results in a bad facet. For example `user:chdorner` turns into `user:['chdorner']`:

![peek 2016-11-21 18-24](https://cloud.githubusercontent.com/assets/22498/20495158/d70b63dc-b017-11e6-922a-f25da4937cab.gif)

**Comment by chdorner** [comment]
This is the same issue as we were having with tags (#4076), which got fixed in #4095. I'll have a look at this now, it's probably the exact same bug.
