### ISSUE TITLE
No share link to annotation on annotation card

### ISSUE THREAD

**Issue by ajpeddakotla** [hypothesis/h#4113]
Need to add the share icon that allows users to share the annotation over social channels on the activity pages implementation of the annotation card. 

**See Mockup:** 
<img width="625" alt="screen shot 2016-11-23 at 4 19 39 pm" src="https://cloud.githubusercontent.com/assets/7463523/20580567/a8a19b38-b198-11e6-9446-6bc94c2ea86c.png">

**Current production view**
<img width="902" alt="screen shot 2016-11-23 at 4 20 51 pm" src="https://cloud.githubusercontent.com/assets/7463523/20580598/d3de6902-b198-11e6-88c2-a5e5f4adc652.png">

**Comment by robertknight** [comment]
What is the design (desktop & mobile) here and what channels do we need to support? The same as on the stream?

Medium size.

To whoever is implementing this - have a look at the group sidebar and the sharing link there. That has a bunch of usability details for desktop & mobile that we need to preserve here as well.

**Comment by ajpeddakotla** [comment]
@conordelahunty can you provide some input here for this issue?

**Comment by ajpeddakotla** [comment]
Notes:

**Comment by dwhly** [comment]
I assume this is what we want?  Note the special language in the case that the annotation is in a group.
  
![screenshot 2016-11-28 17 51 13](https://cloud.githubusercontent.com/assets/1413074/20693439/4cbe3318-b593-11e6-9c92-aaed16e9c3a9.png)

**Comment by robertknight** [comment]
@conordelahunty - Do you still have Twitter, Facebook, G+ and Mail icons for this? I can probably extract them from the icon font in the client but if you still have the originals that would be better.

**Comment by conordelahunty** [comment]
[icons.zip](https://github.com/hypothesis/h/files/630705/icons.zip)
