### ISSUE TITLE
Searching within a user or group is broken on iOS

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#4116]
I can only reproduce this on iOS (iPhone 5) Safari, not in Chrome (not even in dev tools iPhone 5 device mode):

1. Go to a user or group's page:

![img_0637](https://cloud.githubusercontent.com/assets/22498/20600279/b3439390-b24a-11e6-9574-6b497dbe6105.PNG)

2. Type something else after the user or group name in the search and submit. In this case I typed "goo":

![img_0638](https://cloud.githubusercontent.com/assets/22498/20600300/d3e1c6a8-b24a-11e6-9a94-a21f5183a583.PNG)

Problems:

* My "goo" lozenge is truncated after one letter, but that's a [separate issue](https://github.com/hypothesis/h/issues/4115)
* The "user:Sean Hammond" lozenge has disappeared (and I'm no longer on the user page, it has redirected back to `/search`, which it doesn't do in other browsers)

**Comment by chdorner** [comment]
Just investigating this. The same happens on a group search.

**Comment by chdorner** [comment]
Ah! So this is the path that Safari on iOS calls after hitting Enter in the search form: `/users/chdorner?delete_lozenge=&q=goo`
