### ISSUE TITLE
Remove the unnecessary `?q=` from activity search URLs when there's no search query

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#4141]
It sometimes appears, not sure exactly when and when not.

This was split out from https://github.com/hypothesis/h/issues/4004

**Comment by dwhly** [comment]
Also, is the "q=" necessary even when we do need a query string?

**Comment by nickstenning** [comment]
> we're not currently using it on the stream.

Yes, we are! And yes, it is necessary: https://en.wikipedia.org/wiki/Query_string

**Comment by seanh** [comment]
I think I'm a bit too nackered at the end of the week to really think about this, but the situations in which this `?q=` appears are now reduced: https://hypothes-is.slack.com/archives/public/p1480699670008861 But you can still get it by, for example:

* Going to `/search` and hitting `Enter` in the search field without typing in anything (this seems not worth fixing to me, and I think it could only be fixed by some js to prevent submission of an empty form)

* Clicking to delete the last lozenge on the `/search` page

* Clicking to delete the second-last lozenge (after the user or group lozenge) on a user or group search page

* Clicking to delete the user or group lozenge on a user or group search page when that's the only lozenge present and getting redirected back to `/search?q=`

* On mobile, on a user or group search page, clicking the more info and back buttons when there's no search query

On user and group pages "clicking to delete lozenge" means clicking on either the x on the lozenge or a tag or username in the sidebar.

So an empty `?q=` may appear in a variety of ways when you're clicking and searching around on the search page. But it no longer appears when you click on a simple link to the search page or to a user or group's page.

So I think the severity of this issue has been reduced somewhat at least
