### ISSUE TITLE
Console error when toggling notification settings

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/h#4179]
### Steps to reproduce
1. Go to your user [notification settings page](https://hypothes.is/account/settings/notifications).
2. Quickly toggle the "Email me when..." checkbox on and off

### Expected behaviour
The thing should not emit warnings/errors in the console.

### Actual behaviour
We see a `TypeError: Cannot read property 'length'` error in the browser console.
<img width="632" alt="screen shot 2016-12-07 at 16 38 05" src="https://cloud.githubusercontent.com/assets/3602/20974290/fa8dccba-bc9b-11e6-9732-caa914cd0408.png">

**Comment by ajpeddakotla** [comment]
notes from sprint planning: A significant refactoring doesn't need to be done here to write the tests. The work still be done is test and merge. 

Points given: 2
