### ISSUE TITLE
The 'search' input box moves to the next line even if there is space to accommodate it.

### ISSUE THREAD

**Issue by sheetaluk** [hypothesis/h#4180]
1. Input the following lozenges:
user:sheetaluk
my friend
ther arer e
akjsdlajsd
https://hypothes.is/users/sheetaluk?q=my+friend+%22ther+arer+e+%22+akjsdlajsd

2. Reload the page

3. The search input box grows taller and the actual input moves to the next line even though there is space to accommodate it.

### Browser/system information
Chrome

### Additional details
https://www.dropbox.com/s/jz639jt2cxsb4bj/Screenshot%202016-12-07%2010.49.59.png?dl=0

**Comment by nickstenning** [comment]
This is a function of the `min-width` of the `<input>` that holds the `Search...` placeholder text. It currently has a `min-width` of 30% -- when it must occupy less than 30% of the search element, it breaks to the next line.

I'm not really sure whether this is a bug or whether it's working exactly as designed.

Thoughts @sheetaluk? @robertknight?

**Comment by robertknight** [comment]
@nickstenning - This is working as designed. The `min-width` exists, I believe, to make sure the input is always a decent size for a tap/click target.
