### ISSUE TITLE
Pressing ⌘C/⌘V on activity pages focuses search box, breaks copy/paste

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/h#4181]
### Steps to reproduce
1. Visit a search page, e.g. <https://hypothes.is/search?q=reading>
2. Select some text
3. Use the keyboard shortcut to copy text: ⌘C

### Expected behaviour
The text should be copied and should remain selected.

### Actual behaviour
The text isn't copied to the system clipboard, the search box is focused, and the selected text is deselected.

### Browser/system information
Chrome 56.0.2924.10 dev (64-bit) on Mac OS X 10.12.1.

**Comment by robertknight** [comment]
The logic to autofocus the search field should ignore any keys pressed when a modifier key is also pressed. The code ignores ctrl and Alt keys but it doesn't ignore the meta key, which according to https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/metaKey means the command (⌘) key on Mac.

**Comment by nickstenning** [comment]
Do we even need this functionality? Is there a compelling reason to include it?

**Comment by robertknight** [comment]
> Do we even need this functionality? Is there a compelling reason to include it?

So the original problem I was trying to solve was enabling users to start typing a search query as soon as the page loads (which remember, also occurs any time they submit a query), without having to click into the search box. I think _that_ is a compelling UI behavior.

Why not just autofocus the search input on page load? That triggers the suggestion dropdown, hides the "Search..." placeholder and may also obscure content with the on-screen keyboard (if any. Obviously users on mobile can't take advantage of this trick). It might also be unhelpful if the content of the page wants to autofocus a different control.

**Comment by chdorner** [comment]
The actual issue is fixed now, I suggest that if you want to behaviour to change (removing this feature, some other solution) open a new ticket.
