### ISSUE TITLE
Updating search results from dropdown menu suggestions is awkward and non-obvious, especially on mobile

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#4186]
Testing the search page on mobile Safari:

1. Tap in the search box, dropdown menu appears
2. Tap on _Group:_ or _Tag:_ from the dropdown menu, dropdown menu updates with group or tag suggestions
3. Tap on a group or tag suggestion

What happens: group or tag facet is added to search query but search results are not updated. Search input loses focus, onscreen keyboard disappears. To update the search results you need to tap in the search input again then tap _Go_ on the onscreen keyboard - it's awkward to have to do this extra tapping but worse, users probably will not know they have to do it and will not realise that the search results haven't changed.

What should happen: search results should update automatically after the tap in step 3.

A lesser version of this issue also happens on desktop - after clicking the mouse button or <kbd>Enter</kbd> to accept a suggestion the user has to click <kbd>Enter</kbd> again to update the results.

**Comment by ajpeddakotla** [comment]
Timebox this to 2 days of research.

**Comment by seanh** [comment]
I've updated the title of this ticket to reflect:

- This is specifically about updating search results _after accepting a suggestion from the dropdown menu_ being awkward (because you have to press <kbd>Enter</kbd> twice in a row)

- This is not exclusive to mobile, it's awkward on desktop as well (it's just even worse on mobile because the onscreen keyboard disappears)

- This isn't a spike to investigate partial page updates @sean-roberts is gonna write up a separate card for that.

   Once the spike card is written might go and find all the individual issues, such as this one, that partial updates would fix and close them all in favor of just having the one partial updates issue. Currently the different user issues that partial updates touches are spread around several github issues (and some of them probably have no issues at all), we'll tidy that up

**Comment by nickstenning** [comment]
What happened here? It looks like we scheduled this as a spike, but I don't see any output from that spike.

**Comment by sean-roberts** [comment]
@nickstenning #4219 is where the spike work happened. This was identified as a ticket that would be fixed by implementing of that spike

**Comment by seanh** [comment]
I'm not sure whether this got done or not but this is an ancient issue that we're clearly not working anymore so I'm closing this
