### ISSUE TITLE
Event.key error in Safari

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#4187]
### Steps to reproduce
1. Open https://hypothes.is/search in Safari
2. Start typing letters without focusing the search box

### Expected behaviour
Search input is focused and letters go to search input

### Actual behaviour
JS error: https://sentry.io/hypothesis/prod/issues/189275185/

### Browser/system information
See Sentry report.

**Comment by nickstenning** [comment]
As with #4181, there are *so many* corner cases that have to be considered when intercepting all browser input like this. Unless there's a really compelling case to be made for this functionality, I vote we strip it out entirely for now.

**Comment by nickstenning** [comment]
And yes, I confirm the bug in Safari 10.0.1 on OS X 10.12.1.
