### ISSUE TITLE
(Spike) Support Partial Results Updates

### ISSUE THREAD

**Issue by sean-roberts** [hypothesis/h#4219]
Summary:
Use ajax to update the search results live while the user is interacting or finishing with adding lozenges.

Issues solved by handling partial page updates:

- slight performance improvements
  - big perceived performance improvements with an immediate indication of processing and no re-rendering of the content that is unchanged
  - not having to have the page reinitialize all of the javascript on the page improves performance
- no worry about inputs on deadman inputs (upon deleting a lozenge the form is submitted, you can still input into the form while it is loading but this input is dead and is entirely replaced on load)
- search results are only stale while loading the new results - in which case, there will be a visual indication of this
- selecting a suggestion from the autosuggest will create a lozenge - resulting in updating the results (especially painful on mobile when onscreen keyboard goes away - adding more steps to the process #4186)
- no need to press enter twice to submit the lozenge and update the results
- any FOUC or jumps do to rendering the initial state of the page is only incurred once on initial load

Steps needed to implement (add any if missed):

- create a searchResultsController and wrap `.search-result-container` on the server template
- upon create/delete of a lozenge on SearchController determines the url and fetches the content
  - strip out the contents of `.js-group-suggestions` and `.js-tag-suggestions` and update the list
  - do a `window.postMessage('update-results', responedHTML);`
  - searchResultsController is listening for message and will process the html how it needs
- on message, searchResultsController will strip all but the `<div class="search-result-container">...</div>` contents (the root `.search-result-container element` should remain.
- string#replace('search-result-container', 'search-result-container is-hidden-when-loading') to make it hidden by default
- call `this.options.reload('updatedHTMLFromServer')` to update the on page contents and intialize the controllers
- update the url for the form action
- history#pushState to add the updated location to the users address bar/history

- the url used is determined by grabbing the form action and adding a condition to handle scoping
  - if the url contains users/{username} make sure the user facet is in the input query
  - if the url contains groups/{groupPubId} make sure the group facet is in the input query
  - if either of the conditions above have that url but are missing the respective value in the input query, then we should fall back to url == 'search/?q={remaining query input}'

- on requesting the new content, if there is a request already in-flight abort that request and submit the new one

Going this route allows us to dynamically update the search results contents on create/delete of a lozenge and it will keep the patterns in place that are used to exit groups and add queries to the search. Note, we will have a follow-up ticket that can make interactions on the sidebar (adding tags from links, users, etc.) flow more seamlessly so we want to make sure that those interactions still do page refreshes and updates the content correctly as it does today

**Comment by robertknight** [comment]
> big perceived performance improvements with an immediate indication of processing and no re-rendering of the content that is unchanged

Even though this is about perceived as much as actual performance improvements, it would be great if as part of the spike, this can be quantified with some actual numbers/estimates.

>  Use ajax to update the search results live while the user is interacting or finishing with adding lozenges.

I suggest that the summary of a spike should primarily emphasize what we are trying to learn over what the spike will involve doing. In this case, demonstrating the UX improvements listed in the next paragraph.

> strip out the contents of .js-group-suggestions and .js-tag-suggestions and update the list

The suggestions are currently rendered as part of the navbar. I suggest that we can skip updating the suggestions as part of this spike and figure out how to do that separately.

> the url used is determined by grabbing the form action and adding a condition to handle scoping

I suggest that we probably want to handle determining the final URL after updating the search results on the server rather than the client to ensure consistency and facilitate code reuse. It could be part of the payload from the AJAX request for example.

**Comment by ajpeddakotla** [comment]
@sean-roberts a couple of questions: 

1. will handling partial page updates fix issues like this as well (or issues pertaining to lozenge creation) https://github.com/hypothesis/h/issues/3995

2. The work that you've outlined here seems to have a clear path for implementation so that we can support partial page updates. If we're comfortable, we can create an implementation ticket and include some of the details you've listed above.

**Comment by sheetaluk** [comment]
Breaking it down into 3 parts:

start the fetch:
create/delete lozenge and create an event to indicate a fetch request has been made
listen to update results event and update the groups and tags lists
listen to update results event to get the form action and update the form thats bound to the search bar

respond to the fetch:
create a search-results controller
listen for the fetch request start event and apply a class that increases the search results container opacity
listening for the update results event and calling reload on itself with the new content - See: this.options.reload(elem, html) and remove the opacity class.
Handle the race condition where multiple fetches can be requested and we only need to handle the latest fetch.

Create utility to update browser history and update browser history with the updated form action

**Comment by ajpeddakotla** [comment]
Broke down this work into three issues 
- [#134](https://github.com/hypothesis/product-backlog/issues/134)
- [#135](https://github.com/hypothesis/product-backlog/issues/135)
- [#136](https://github.com/hypothesis/product-backlog/issues/136)

**Comment by sean-roberts** [comment]
https://github.com/hypothesis/h/issues/3995 will be fixed with this
