### ISSUE TITLE
Hypothesis brand is broken on logged-out forms pages, when activity pages feature flag is off

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#4231]
![screenshot from 2016-12-16 13-46-21](https://cloud.githubusercontent.com/assets/22498/21264825/4697026a-c396-11e6-9e9a-e2e2dd34d219.png)

(If the window is wider the login box remains centered, but the Hypothes.is floats all the way to the left.)

**Comment by lenazun** [comment]
Activity pages is now on for everybody
