### ISSUE TITLE
Footer appears in middle of page in IE

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#4236]
On the `/search` page (or any page that has the [new footer](https://github.com/hypothesis/h/pull/4234), in IE 11, at smaller window sizes, the footer appears in the middle of the page (behind the search results) instead of at the bottom of the page. Doesn't seem to happen in any other browser (not even Edge).

**Comment by nickstenning** [comment]
Verified. Doesn't even have to be a particularly small window:

![screen shot 2017-02-22 at 13 12 56](https://cloud.githubusercontent.com/assets/3602/23211107/b134a2ea-f900-11e6-84b5-01a79a830a2b.png)
