### ISSUE TITLE
New annotations from NIPSA-d users appearing in public feed

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#4278]
I NIPSA-d a couple of users yesterday (27/12/16). New annotations created by them since they were NIPSA-d have however been appearing in the public feed. Re-applying the NIPSA status to the user from the admin control panel resulted in those new annotations disappearing from the public feed.

**Comment by robertknight** [comment]
I tested the following locally, which did not reproduce the problem:

1. Create account "spammer1"
2. Add annotations using this account
3. NIPSA the user, verify that their annotations are no longer visible to other users
4. Add more annotations using this account.

Expected & actual result: Annotations hidden in step 4 are hidden from other users

On the live site however, this user shows public annotations despite being NIPSA-d - https://hypothes.is/users/emmajohnsan

**Comment by robertknight** [comment]
I was however able to reproduce the problem in production:

1. Create a test account (I used `robertknight_spammer`)
2. Add annotations using this account
3. NIPSA this user using my normal admin account. Verify that the "spammer"'s annotations are no longer visible to other users.
4. Add more annotations using this account

**Expected:** Annotations added in step 4 are not visible to other users
**Actual:** Annotations added in step 4 are visible to other users

**Comment by dwhly** [comment]
@robertknight How did you discover the spam annotations?

**Comment by robertknight** [comment]
I noticed them on `/search`. Helpfully we only have one group of spammers at the moment who always promote the same thing.

**Comment by robertknight** [comment]
OK, figured out what is going on. See https://hypothes-is.slack.com/archives/backend/p1483380412001586 . The NIPSA service (of which each app server maintains one instance per Celery worker) has a cache invalidation problem.
