### ISSUE TITLE
Tasks fail silently when running dev server

### ISSUE THREAD

**Issue by fatbusinessman** [hypothesis/h#4291]
### Steps to reproduce
1. Have a task that fails. I encountered this as part of #4290, but you could force a failure with this patch:
    ```diff
    diff --git a/h/tasks/indexer.py b/h/tasks/indexer.py
    index 1dd2e3f..dd8aed1 100644
    --- a/h/tasks/indexer.py
    +++ b/h/tasks/indexer.py
    @@ -10,6 +10,7 @@ from memex.search.index import delete

     @celery.task
     def add_annotation(id_):
    +    raise RuntimeError('Ohnoes!')
         annotation = storage.fetch_annotation(celery.request.db, id_)
         if annotation:
             index(celery.request.es, annotation, celery.request)
    ```

2. Start up the app with `make devserver`
3. Trigger the task (in my example, by creating an annotation)

### Expected behaviour
Something should crop up in the `worker` logs for the app, mentioning that the task threw an exception.

### Actual behaviour
The task fails silently. Even if running with `DEBUG`-level logs on the worker, there is no description of the exception thrown.

### Additional details

I’m not 100% sure whether this qualifies as a bug or a feature request, but the lack of reporting on failed tasks here makes other bugs (e.g. #4290) rather harder to track down.

**Comment by seanh** [comment]
Appreciate the very helpful error report, made the pull request easier for a lazy developer to review
