### ISSUE TITLE
New highlights delete previous ones.

### ISSUE THREAD

**Issue by PaBLoX-CL** [hypothesis/h#4298]
I'm on this webpage: http://www.iep.utm.edu/medicine/

I'm trying to use hypothesis with chromium extension (though I tested it too in the bookmarklet on firefox 50). And sometimes, kind of randomly, when adding a new highlight:

![hypothesis_bug](https://cloud.githubusercontent.com/assets/275754/21896208/51802808-d8c4-11e6-84d1-c21002ec3101.gif)

**Comment by ajpeddakotla** [comment]
Thanks for notifying us of this issue @PaBLoX-CL - and especially appreciate the screencast. 

Was this reproducible w/ the FF bookmarklet as well (wasn't quite sure if that's what you were getting at)? 

In any case, we'll try to reproduce this on our end and do some digging to figure out what the problem might be.

**Comment by PaBLoX-CL** [comment]
Glad to be of help :).

In fact, it presents the same behaviour on the chromium extension and firefox bookmarklet. It is the first time I run into this error, so I don't know if the specific website ( http://www.iep.utm.edu/) has something to do.

**Comment by sheetaluk** [comment]
This other user is running into the same issue:
https://hypothesis.zendesk.com/agent/tickets/907

**Comment by jeremydean** [comment]
https://hypothesis.zendesk.com/agent/tickets/930

**Comment by claudinec** [comment]
I am also seeing this behaviour (inconsistently) on Chrome 55.0.2883.95 (64-bit), macOS 10.12.3.

**Comment by ajpeddakotla** [comment]
Point given 5

**Comment by sean-roberts** [comment]
Hey everyone, I have identified that this problem has to do with our saving logic being tied to our rendering of annotations logic. Now that we have identified the issue we will get it rectified soon. But as a workaround - if you keep running into this issue, you can open the sidebar and scroll all the way to the bottom to load all of the annotations. This will allow you to create new highlights until it gets a backed up again. But you can repeat this to get saving. We are actively working on a fix but this should get around any issues if it comes up.
