### ISSUE TITLE
Old annotations are anchoring in the wrong context

### ISSUE THREAD

**Issue by lenazun** [hypothesis/h#4328]
### Steps to reproduce
1.  Go to https://hypothes.is/jobs/
2. This annotation https://hyp.is/4fD2qZSYTRKneIx8iJWhbg/hypothes.is/jobs/ anchors in the fragment " developers and desi" when the original selected text was "Developer, Frontend".  
3. Seems to me like the prefix, postfix and even the selected fragment are very different.

### Expected behaviour
This annotation should not anchor in the new text, since it's clearly different.

### Actual behaviour
This annotation anchors in new text, that is very different from the old text. 

### Browser/system information
Version:
0.52.0
User agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36
URL:
https://hypothes.is/jobs/
Date:
25 Jan 2017 17:35:12 -0800

### Additional details
I have a couple of user tickets talking about this behavior. I think reanchoring is inevitable in some cases, but it seems like the context of the text is different enough that we may want to adjust what's going on here.

**Comment by robertknight** [comment]
Hi @lenazun - Could you add links to any relevant user tickets you know of here. I'm currently reading up on the string matching algorithm that our fuzzy anchoring uses so this may be an interesting thing to look at as part of that.

**Comment by nickstenning** [comment]
Moved to https://github.com/hypothesis/client/issues/258.
