### ISSUE TITLE
Incompatible annotation anchoring on PDFs between Bookmarklet and Chrome Extension/Bouncer

### ISSUE THREAD

**Issue by adam3smith** [hypothesis/h#4361]
### Steps to reproduce
1. Open https://www.gpo.gov/fdsys/pkg/PLAW-110publ252/pdf/PLAW-110publ252.pdf in Firefox, launch Hypothes.is via Bookmarklet, add public annotation. 

### Expected behaviour
The annotation should be linkable and should display correctly when opening the Chrome Extension on that page or when viewing the page through the proxy, i.e. via.hypothes.is/https://www.gpo.gov/fdsys/pkg/PLAW-110publ252/pdf/PLAW-110publ252.pdf 

### Actual behaviour
The link https://hyp.is/CdCuPO4PEeaqhXMekdWCFQ/www.gpo.gov/fdsys/pkg/PLAW-110publ252/pdf/PLAW-110publ252.pdf displays the annotation, but anchoring and highlighting is lost.
Equally, when opening the PDF in Chrome and starting the Hypothes.is extension, the annotation is displayed, but not anchored. Same for the proxy.

### Browser/system information
Windows 10, Firefox 51.0.1, Chrome 56.0.2924.87

### Additional details
Best I can tell this is a general issue (I have replicated this on at least 3 very different PDFs)

The issue also exists in reverse:
https://hyp.is/izKDBu4PEeaZjJ_UouigbQ/www.gpo.gov/fdsys/pkg/PLAW-110publ252/pdf/PLAW-110publ252.pdf was created in the Chrome Extension on the same page and heading. As you can see, anchoring works via the Bouncer link, and it works in Chrome and going through the proxy, but when using the bookmarklet in Firefox on https://www.gpo.gov/fdsys/pkg/PLAW-110publ252/pdf/PLAW-110publ252.pdf anchoring is lost.

**Comment by nickstenning** [comment]
Thanks for reporting this! I've verified the bug and moved it to https://github.com/hypothesis/client/issues/259.
