### ISSUE TITLE
Hypothesis sidebar not appearing when opening PDFs in Firefox via Zotero

### ISSUE THREAD

**Issue by RaoOfPhysics** [hypothesis/h#4362]
### Steps to reproduce
1. Add PDF to Zotero library.
2. With Zotero settings configured to open PDFs within the browser, double-click on PDF in Zotero add-on within Firefox to launch PDF in a separate tab.
3. Use JS bookmarklet to load hypothesis layer.

### Expected behaviour
I would expect the hypothesis sidebar to appear upon clicking the bookmarklet.

### Actual behaviour
The sidebar doesn't appear. However, hypothesis itself loads -- the buttons for "highlight" and "annotate" appear when selecting text in the PDF. But I cannot actually annotate the text itself (although highlights seem to persist).

### Browser/system information
- Firefox 51.0.1
- macOS 10.12.3
- Zotero add-on 4.0.29.16

### Additional details
The issue only appears with PDFs opened via Zotero, which uses  `zotero://` in the URL bar to identify the PDF. If I open the same PDF using the "Open file" command (i.e., with `file://` in the URL bar), hypothesis works perfectly -- see screenshots to compare the two.

- Using `zotero://`: Buttons appear, but I cannot annotate. Sidebar is missing.
<img width="1070" alt="firefox - - screen shot 8 feb 2017 17 14 27" src="https://cloud.githubusercontent.com/assets/7623019/22746197/4f85abe4-ee23-11e6-8bb6-45dea729d740.png">

- Using `file://`: Hypothesis fully loaded.
<img width="1070" alt="firefox - - screen shot 8 feb 2017 17 14 33" src="https://cloud.githubusercontent.com/assets/7623019/22746210/5825f6b4-ee23-11e6-8e12-d0f899c0908e.png">

**Comment by nickstenning** [comment]
@RaoOfPhysics and @jibe-b: thanks for registering your interest in integration with Zotero.

I've recorded your request on an issue (currently only available internally, I'm afraid): https://github.com/hypothesis/product-backlog/issues/192

**Comment by RaoOfPhysics** [comment]
Thanks, @nickstenning. Just FYI, a few weeks/months ago I was able to load Hypothesis perfectly even with `zotero://`. Used it quite a bit with my research literature. Seems to have lost the feature recently.

**Comment by nickstenning** [comment]
Oh! That's interesting @RaoOfPhysics -- I didn't realise that. I don't suppose you happen to know more precisely when the change occurred, do you?

**Comment by RaoOfPhysics** [comment]
I can't say, I'm afraid. And I don't know whether this has occurred as a result of changes to Firefox, Zotero or Hypothesis. :(

**Comment by nickstenning** [comment]
Ok, well thank you for clarifying, anyway. I'll make sure to update our internal tracking issue to note that this used to work.

**Comment by idatalyst** [comment]
I would also like to see hypothesis and zotero integration.  An ability to coordinate my citations from zotero to annotations in hypothesis.  

Ideally, I would find an item: document, webpage, etc using my web browser.   Use hypothes.is to annotate the item then snapshot it with the zotero plugin icon in chrome.   When I am ready, I can then export my zotero citations and associated hypothes.is annotations to a word processor to write my document.

**Comment by adam3smith** [comment]
FYI @RaoOfPhysics -- I can use Hypothes.is in Firefox 52.02 with zotero: URLs
Might be worthwhile checking on your other extensions. 
![image](https://cloud.githubusercontent.com/assets/128986/25204184/1cbd1498-2511-11e7-9ecb-ec5615e74a6d.png)

**Comment by idatalyst** [comment]
I was hoping for something for non-pdfs

**Comment by RaoOfPhysics** [comment]
@adam3smith: As of Firefox 53.0, I can no longer open *any* Zotero PDF attachments natively in the browser, so looks like it's a bigger problem than I expected. I've disabled all add-ons and the problem persists. In any case, once I get it working, I'll come back to test this. Thank you for reporting that it's working for you!

**Comment by RaoOfPhysics** [comment]
@adam3smith: https://forums.zotero.org/discussion/65348/cannot-display-pdf-from-zotero-in-firefox-53

Also, this discussion may be moot as Zotero is deprecating the Firefox add-on as of v5. :( That is going to be such a bummer for me as I like working within the browser.

**Comment by RaoOfPhysics** [comment]
@nickstenning: I can confirm that I can annotate `zotero://` files in Firefox 53.0 using the latest version of the Zotero plugin.

Thanks to @adam3smith for pointing this out!
