### ISSUE TITLE
503 error: https://via.hypothes.is/http://www.aei.org/

### ISSUE THREAD

**Issue by volth** [hypothesis/h#4371]
### Steps to reproduce
1. Open https://via.hypothes.is/http://www.aei.org/ or https://via.hypothes.is/https://www.aei.org/publication/venezuelas-health-crisis-including-zika-outbreak-threatens-the-region/

### Expected behaviour
HTTP 200

### Actual behaviour
HTTP 503

### Browser/system information
I tried different browsers

**Comment by nickstenning** [comment]
Thanks for reporting this! I've confirmed the bug and have moved it to https://github.com/hypothesis/via/issues/98.
