### ISSUE TITLE
Dev install: instance not accessible from remote

### ISSUE THREAD

**Issue by jibe-b** [hypothesis/h#4372]
### Steps to reproduce
1. installed h on a VPS
2. make dev (with --https enabled)

### Expected behaviour
No firewall rule is activated on the VPS so the website and API should be reachable by visiting the IP:5000.

### Actual behaviour
On the VPS, `curl -k http://localhost:5000` etc works fine.

Visiting the IP (say 123.123.123.123) with `curl -k https://123.123.123.123:5000` returns `Connection refused`, when running this from a terminal on the VPS or from a remote machine.

### Browser/system information
Ubuntu 16.04 on both my machine and VPS where h is installed

### Additional details
No firewall is activated on the VPS, so I guess the dev install is blocking connections from the internet. I didn't find documentation about this. How can I make h accept connections?

**Comment by nickstenning** [comment]
Hi @jibe-b -- the dev install isn't blocking connections, the dev server listens on the local interface, AKA "localhost" by default. If you wanted it to serve requests from the public internet, you'd probably be best off configuring a web server such as nginx to act as a reverse proxy to the local port. There are numerous guides available online that can help you do this: here's [one from the nginx project](https://www.nginx.com/resources/admin-guide/reverse-proxy/).

**Comment by jibe-b** [comment]
Ok, thanks for the clarification.

**Comment by anushaharish538** [comment]
Hi @jibe-b ,
I'm also having same issue, it is working fine on local machine but I'm unable to access it using IP. Did you fix it.
Thank you.
