### ISSUE TITLE
Inline analytics script on /docs/help prevents enabling strict CSP

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#4408]
### Steps to reproduce
1. Go to https://qa.hypothes.is/docs/help
2. Check console for script-related CSP errors

### Expected behaviour
No script errors.

### Actual behaviour
An inline script for tracking a Google Analytics page hits results in a CSP violation.

Once we fix this issue we should be able to enable a strict CSP policy for at least script resources on the website.

**Comment by nickstenning** [comment]
Fixed by #4415.
