### ISSUE TITLE
Difference in email case sensitivity between sign-up and login

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#4443]
### Steps to reproduce
1. Create a user account using the email "bob@gmail.com"
2. Attempt to create a second account using the email "BOB@gmail.com"
3. Sign in to the account created in step (1) using the email "bob@gmail.com"
4. Attempt step (3) but with "BOB@gmail.com"

### Expected behaviour
Steps (2) and (4) are consistent with respect to whether they consider email addresses with different casings different or not.

### Actual behaviour
Step (2) disallows creation of two accounts with email addresses that differ only in case. Step (4) only allows login when using an email that matches the original case. The behaviour in step 4 can be confusing for users who are used to other systems ignoring case in the input email address.

### Additional details
Issue reported in https://hypothesis.zendesk.com/agent/tickets/1041 . It looks like the user is used to systems being lax with respect to case-sensitivity for email addresses and as a result ended up with autocomplete entries on different systems having different cases stored.

There is a **valid argument that we shouldn't change the current behaviour** - the username part of the email address is managed by the email provider so they could in theory make two usernames with different casings refer to different mailboxes. However, AFAIK this doesn't happen in practice and anyway, we require the user to prove their ability to access the account before they login for the first time.

Either way - if we decide not to change the behaviour then this issue can at least serve as a record of that decision.

**Comment by nickstenning** [comment]
As you've noted, this isn't really a bug [the relevant RFC](https://tools.ietf.org/html/rfc5321#section-2.4) is quite clear that assuming any semantics about the "local-part" of an email address (e.g. that `john.smith` and `John.Smith` refer to the same mailbox) is incorrect.

**Comment by nickstenning** [comment]
Gah, I misread. So there is a bug here, at signup...

**Comment by nickstenning** [comment]
https://github.com/hypothesis/h/blob/732dc4db96cadc68f348e5dcbffe54f7d76b5ea0/h/models/user.py#L325

**Comment by robertknight** [comment]
While you're clearly right about what the standard says, in practice it appears that at least some services treat email addresses as case-insensitive for login purposes. I tested with Twitter and GitHub with my gmail account.

In this case, the user appears to have been inconsistent in the use of case when entering their email across different devices and has gotten used to this.

**Comment by sean-roberts** [comment]
I 100% agree that meeting user expectations vastly outways any purity to the spec on this. Most mailbox clients (including gmail) do not allow this anymore and it's extremely uncommon that applications allow case sensitive email variants as well. This is simply asking for useless support tickets
