### ISSUE TITLE
Can't create admin - hypothesis: command not found

### ISSUE THREAD

**Issue by hb-shanmuk** [hypothesis/h#4569]
### Steps to reproduce
1. Set up three Docker containers running the PostgreSQL, RabbitMQ, and Elasticsearch services.
2. Start a development server by Creating and Activating a Python virtual environment
3. Create a new account by signup
4. Run command below
 `hypothesis user admin <username>`

### Expected behavior
`hypothesis` command should work and create an admin access to given username.

### Actual behavior
Currently, it is showing below error.
`hypothesis: command not found`

### Browser/system information
I am using Ubuntu 16.04

### Additional details
I have followed step by step instructions given here in below link and the services, application started successfully. But not able to create admin access.
https://h.readthedocs.io/en/latest/developing/install/

**Comment by tianlantianlan95** [comment]
I was confused at some point too. Simply enter the h directory and type "./bin/hypothesis user admin <username>", or you can add it to path. Also you will need to create a user before that.

**Comment by hb-shanmuk** [comment]
Thanks for your reply! it's my mistake, I have not used "./bin/" before the hypothesis command. 

Actually, I didn't find it in documentation as like that, so better to update [here](https://h.readthedocs.io/en/latest/developing/install/) to avoid others to get misunderstood like me. :)
