### ISSUE TITLE
Link to home in main navbar is broken

### ISSUE THREAD

**Issue by taniki** [hypothesis/h#4570]
1. Be logged in or go on the search page
2. Click on the brand on the top left

### Expected behaviour
This should certainly be a link to the root of the search page `https://hypothes.is/search`

### Actual behaviour
Link to `web.hypothes.is`

**Comment by dwhly** [comment]
Our thinking was that this should provide a way to get to the marketing site for Hypothesis-- since you can always clear the search facets with one or more clicks.  

How would you expect to get to be able to get to the marketing site?

**Comment by taniki** [comment]
With a link in the footer or maybe with a link around or in the settings in the top right.

Ok. https://web.hypothes.is now goes to the marketing website. It was going nowhere and showed me a connexion error page an hour ago. My bad 😅
