### ISSUE TITLE
API for annotations search using group parameter not fully working

### ISSUE THREAD

**Issue by tianlantianlan95** [hypothesis/h#4576]
### Steps to reproduce
1. Post an annotation in an existing group.
2. Use the hypothesis search API to make a GET request using 'group' parameter to search for the annotation just made in the group like this: "https://hypothes.is/api/search?group=<groupname>"
3. Get the json response.

### Expected behaviour
The json response contains the annotation.

### Actual behaviour
The json response does not contains the annotation.

### Browser/system information
Chrome and Firefox

**Comment by robertknight** [comment]
Hello @tianlantianlan95 - Did you include an [API key](https://hypothes.is/account/developer) in your query? Since group annotations are private, you have to supply an API key in the request for a user who is a member of that group in order to be able to fetch those annotations.

**Comment by tianlantianlan95** [comment]
Hi @robertknight - I did include the API key in my request header. Sorry for not mentioning it in the reproduction. I was hosting h locally and I get the API token through 'localhost:5000/profile/developer'. My try to make query via ajax and my header look like this:
`headers: {
	        "Accept" : "application/json",
	        "Authorization": "Bearer 6879-JPaTEW-Et0AimwI7wykJh8yx3MLc9e6CB5P6fw1iJE0"
}`.
It works for user query but not group query (but that's probably because user query does not require API token).

**Comment by robertknight** [comment]
Can you verify that the headers are being sent correctly via the dev tools. Do you get different results (see the "total" field) with and without the token in:

```sh
 curl -H 'Authorization: Bearer $YOUR_API_KEY' 'https://hypothes.is/api/search?user=$YOUR_USERNAME'
```

?

**Comment by tianlantianlan95** [comment]
@robertknight - I tried the curl command and that did not work for the group query (tried that for towards my local server and hypothes.is site with corresponding API tokens).
It worked for user query though.

**Comment by tianlantianlan95** [comment]
@robertknight - I have figured it out: the string after 'group=' should be the string in the sharing url but not the group name. Thanks for your help still!
