### ISSUE TITLE
Collapsing search result bucket loses scroll position

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#4577]
### Steps to reproduce
1. Go to https://hypothes.is/search
2. Scroll down the page and click a document title to expand a bucket of annotations
3. Click the document title again to collapse the bucket

### Expected behaviour
When collapsing the bucket, the scroll position should be preserved.

### Actual behaviour
When collapsing the bucket, the browser scrolls back to the top of the page, losing my position.

### Browser/system information
Tested in Safari 10, Chrome Dev (M61).

**Comment by sheetaluk** [comment]
👍 This also fixes a minor bug where clicking on a bucket to expand it would scroll up first before scrolling back down to the newly opened bucket.
