### ISSUE TITLE
Saving Annotation Failed in Internet Explorer 11

### ISSUE THREAD

**Issue by wprue** [hypothesis/h#4610]
![ie11 issue](https://user-images.githubusercontent.com/26881125/28540815-095eb218-708d-11e7-883b-2d74a0f5dee5.png)
### Steps to reproduce
1. Browse a page where Hypothesis is available using Internet Explorer 11
2. Log into Hypothesis
3. Attempt to post an annotation

### Expected behaviour
The annotation would save as expected.

### Actual behaviour
An error is displayed - "Saving annotation failed 400: document.link.0: 'href' is a required property"

### Browser/system information
Internet Explorer 11.0.9600.17420 on Windows 7
Internet Explorer 11.1000.15014.0 on Windows 10

### Additional details
Annotation will successfully save when logging with the same account on a different browser within the same OS.

**Comment by robertknight** [comment]
Hello. Thank-you for the report, I can reproduce the problem. I have moved this to the GitHub repository where we track issues with Hypothesis client software at https://github.com/hypothesis/client/issues/506
