### ISSUE TITLE
Development server fails to start

### ISSUE THREAD

**Issue by kanishkdudeja** [hypothesis/h#4646]
### Steps to reproduce
1. Follow the 'Setting up the dev environment doc' exactly on Debian 8 in Vagrant on Linux (Ubuntu 17.04)

### Expected behaviour
Development server should start after running 'make dev'

### Actual behaviour
After around 2 minutes after running 'make dev', the script fails (last few lines of log pasted below):

```
13:06:54 assets | [13:06:54] Starting 'build-images'...
13:06:55 assets | [13:06:55] Finished 'build-images' after 16 ms
13:06:55 assets | Killed
13:06:55 system | assets stopped (rc=137)
13:06:55 system | sending SIGTERM to worker (pid 29606)
13:06:55 system | sending SIGTERM to web (pid 29610)
13:06:55 system | sending SIGTERM to beat (pid 29607)
13:06:55 system | sending SIGTERM to ws (pid 29609)
13:06:55 ws     | 2017-09-09 13:06:55,205 [29619] [gunicorn.error:INFO] Handling signal: term
13:06:55 ws     | 2017-09-09 13:06:55,212 [29619] [gunicorn.error:INFO] Shutting down: Master
13:06:55 worker | 
13:06:55 worker | worker: Warm shutdown (MainProcess)
13:06:55 web    | 2017-09-09 13:06:55,192 [29715] [gunicorn.error:INFO] Worker exiting (pid: 29715)
13:06:55 web    | 2017-09-09 13:06:55,216 [29621] [gunicorn.error:INFO] Handling signal: term
13:06:55 web    | 2017-09-09 13:06:55,294 [29621] [gunicorn.error:INFO] Shutting down: Master
13:06:55 system | ws stopped (rc=-15)
13:06:55 system | web stopped (rc=-15)
13:06:56 system | worker stopped (rc=-15)
13:06:56 system | beat stopped (rc=-15)
Makefile:29: recipe for target 'dev' failed
make: *** [dev] Error 137
```

When I run 'docker ps', the ElasticSearch container no longer shows up. I can't run 'make dev' again until I restart the container again. Not sure whether the script is causing ElasticSearch to die or maybe some connection error with ElasticSearch is making the development server to die.

### Browser/system information
Development environment set up is being attempted on Debian 8 inside Vagrant VM on Ubuntu 17.04.

**Comment by robertknight** [comment]
How much memory does your VM have? Can you have a look at the output of `dmesg` in case there are any related errors?

**Comment by kanishkdudeja** [comment]
Thanks a lot. Looks to be a memory issue only. I see an 'out of memory' error when I run the command dmesg. Let me re-run the VM with more memory and then try.

Maybe, we can add a 'Memory required' note in the docs so that the newer contributors can make sure of it before trying to set up the development environment?

**Comment by robertknight** [comment]
Hi @kanishkdudeja - Thanks for letting us know. What was the reason for using a VM? Most of us just use Docker to run the various services required and then run the dev server directly on the host machine. In production the "h" service is itself a Docker container which connects to the other containers running the services.

**Comment by kanishkdudeja** [comment]
Hi Robert,

No specific reason for using a VM. My host operating system is MacOS. I trust the Linux runtime more for development, that's why I do all my development inside the VM.

After I had set up most of the stuff in the VM, I realized that most of it runs on Docker and can be run on Mac as well :)
