### ISSUE TITLE
Deleting a user does not delete their annotations from ElasticSearch

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#4652]
### Steps to reproduce

1. Create a user account in a local h instance
2. Make an annotation using that account
3. Delete the user using the admin panel
4. Query ElasticSearch for annotations using:
    ```
    curl 'http://localhost:9200/_all/annotation/_search?q=user:<username>' | jq
    ```

### Expected behaviour
No annotations should be returned.

### Actual behaviour
The annotation made in step 2 is returned in the JSON response in step 4. If you go to the annotated page and reload, the annotation is still visible.

### Additional notes

It looks like `h.views.admin_users.delete_user` does not issue the same annotation "delete" event that `h.views.api.delete` does, which notifies the indexer and streamer about the deletion.

If after performing the steps above, you then try to recreate and re-delete the account, the second deletion attempt fails:

1. Follow all the steps for the first issue
2. Create a new user account with the same username after deleting the account
3. Try to delete that user account. This fails with a 500 error.

**Comment by judell** [comment]
Nice catch.
