### ISSUE TITLE
Editing of fields in Account Settings page initiated automatically by Chrome's autocomplete

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#4656]
When I go to https://hypothes.is/account/settings in Chrome 62.0.3202.18, editing of the email address field is triggered automatically. Clicking the "Cancel" button briefly dismisses the modal but then re-triggers it a moment later. This prevents me from interacting with any of the other elements on the page.

I do not encounter this problem if I visit this page in an Incognito profile, where Chrome does not attempt to auto-complete the fields in this form.

**Comment by dwhly** [comment]
Looks like not an issue in Chrome 64+

**Comment by robertknight** [comment]
I can't reproduce in Chrome 115.
