### ISSUE TITLE
Third party annotations are appearing on activity pages

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#4697]
Third-party annotations are appearing on the https://hypothes.is/search page, and their user account, group, share, etc links are all broken. Document titles are all _Untitled document_ too, though I'm not sure whether that's to do with them being third-party.

Third-party annotations should _not_ show on activity pages, activity pages don't support them yet

**Comment by dwhly** [comment]
Can't see this, can you share a pic?

**Comment by seanh** [comment]
![screenshot from 2017-11-23 18-05-21](https://user-images.githubusercontent.com/22498/33185199-e83064d2-d078-11e7-9bc4-699926f9f186.png)
