### ISSUE TITLE
Unable to delete group admin from admin interface.

### ISSUE THREAD

**Issue by sheetaluk** [hypothesis/h#4719]
### Steps to reproduce
1. In the admin interface, search for a user who happens to be a group creator
2. Click on delete user

### Expected behaviour
We should be able to delete the user

### Actual behaviour
We can't delete the user because they are a group creator/admin

### Additional details
There are 4 cases for deleting a group creator documented here: https://github.com/hypothesis/h/pull/4706#issuecomment-347831252

Cases 1, 2 and 3 are uncontroversial. Case 4 needs to be thought through.

There is also an open PR here:
https://github.com/hypothesis/h/pull/4706

**Comment by sheetaluk** [comment]
@ajpeddakotla could you please take a look and prioritise this card for when you see fit?

**Comment by robertknight** [comment]
This is now resolved for 3 of the 4 cases outlined in https://github.com/hypothesis/h/pull/4706#issuecomment-347831252 , which has accounted for all of the requests we've needed to deal with so far. On that basis, I'm going to close this for now.
