### ISSUE TITLE
Broken user page links in eLife notification emails

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#4720]
Notification emails, for example reply notifications, for eLife accounts contain links to `https://hypothes.is/users/<USERNAME>` pages. These pages don't work for third-party accounts, they 404.

Example reply notification email:

![screenshot from 2017-12-07 14-39-20](https://user-images.githubusercontent.com/22498/33720690-ad9a3160-db5c-11e7-8908-c577dae07ad3.png)

The [non-human-friendly usernames are a separate issue](https://github.com/hypothesis/h/issues/4721). This issue is about the fact that those usernames are links to Hypothesis user pages that 404.

Suggestion: just don't link to these user pages in the emails. (I don't think we have a way to link to the eLife user pages for these.)

**Comment by robertknight** [comment]
> I don't think we have a way to link to the eLife user pages for these.

No. We've handled several "non-working links" issues over the last few days.

In order to solve this I think we are going to need to make third party authorities a first-class concept in h so we can associate configuration information with them such as the links that should be used for users, tags, signup etc.

Until we do that, all we can really do is remove this from the emails.

**Comment by seanh** [comment]
We'd also need to change our API with eLife so that they provide us with a static HTML URL for each user, rather than the current system where they give us a JavaScript function that the client calls to open a user's profile page (that of course only works in the client and not in email notifications or on activity pages etc)

**Comment by robertknight** [comment]
> We'd also need to change our API with eLife so that they provide us with a static HTML URL for each user

I don't think we will. In the context of the client we've seen that they wanted control over the behaviour of the link as well as the destination. In the context of an email however, there is just the destination of the link that we need.
