### ISSUE TITLE
Non-human-friendly usernames appearing in eLife notification emails

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#4721]
Email notifications (for example reply notifications) currently contain usernames, not display names. In some cases, such as users created by eLife, the username is a nonsense string (`xyz123` type of thing) whereas the display name is something proper like Sean Hammond.

Example of what an eLife reply notification email looks like:

![screenshot from 2017-12-07 14-39-20](https://user-images.githubusercontent.com/22498/33720653-836c1b2e-db5c-11e7-8269-5cc349733318.png)

On eLife's site this username uh5qvwsm is never shown in the client, it shows the display name instead.

Suggestion: can we just always use the display name instead of the username in email subject lines and bodies, whenever a display name is present? (For both eLife and normal Hypothesis users)

**Comment by dwhly** [comment]
> Suggestion: can we just always use the display name instead of the username in email subject lines and bodies, whenever a display name is present? (For both eLife and normal Hypothesis users)

That works for me.  If only username present, stick with username.  it's sufficiently limited to private correspondence to the user that it doesn't equate to a platform decision to adopt display names over usernames at UI level.
