### ISSUE TITLE
Frequent Elasticsearch request timeout warnings

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#4734]
We are seeing about ~200 `ReadTimeout` warnings from Elasticsearch per day in production. These are a significant contribution towards our Sentry event quota. ES is configured to automatically retry such requests so users won't see an error unless the request times out repeatedly. Given the ratio of `ReadTimeout` _warnings_ vs _errors_ on Sentry, actual failures are not happening frequently at the moment.

We should deal with this one way or another, eg. by:

- Deciding that the warning doesn't matter for the moment and filtering it out
- Increasing the timeout from the current 0.2s
- Other infrastructure changes to reduce the frequency (we are using Amazon's managed Elasticsearch, so some of this may be out of our control)

https://sentry.io/hypothesis/h/issues/218088571/

```
ReadTimeout: HTTPSConnectionPool(host='search-hypothesis-2marq57xdwzqpon3xq5gc5nt3a.us-west-1.es.amazonaws.com', port=443): Read timed out. (read timeout=0.2)
(1 additional frame(s) were not displayed)
...
  File "requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "raven/breadcrumbs.py", line 297, in send
    resp = real_send(self, request, *args, **kwargs)
  File "newrelic/api/external_trace.py", line 124, in dynamic_wrapper
    return wrapped(*args, **kwargs)
  File "requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "requests/adapters.py", line 499, in send
    raise ReadTimeout(e, request=request)

GET https://search-hypothesis-2marq57xdwzqpon3xq5gc5nt3a.us-west-1.es.amazonaws.com:443/hypothesis/annotation/_search?_source=false [status:N/A request:0.205s]
```

**Comment by fatbusinessman** [comment]
One extra piece of context: we also have [instrumentation in the code](https://github.com/hypothesis/h/blob/5140713ee900c9b5294dd0a37499699a524b2fb9/h/search/core.py#L126-L145) that reports these timeouts to `statsd`, so we can see them in Grafana. I’m not 100% sure whether this also reports the non-error timeouts (the ones that trigger a retry within the Elasticsearch library). If it does report these, that’s an argument for us being able to discard these messages entirely; if it doesn’t report them, it might offer us a useful pattern for intercepting these messages within the app and reporting them to `statsd` ourselves.

**Comment by hmstepanek** [comment]
Potentially relevant commit back when we first added sentry logging: https://github.com/hypothesis/h/commit/f3a0678da1675165d9a82ca7086baae5b7e79899#diff-927cc473e1580ad47a1c348333d239e1

**Comment by hmstepanek** [comment]
It looks like this is what we need to do to ignore these warnings "right way" : https://github.com/getsentry/raven-python/issues/851

**Comment by hmstepanek** [comment]
Some fyi's for testing this locally in the dev env: in h/search/client.py the following line must be added in get_client(settings) before the 'if have_aws_creds':

kwargs['connection_class'] = RequestsHttpConnection

This tells elasticsearch to use http_request instead of urllib3. They are pretty much identical in what their implementation but for the sake of reproducing this error exactly as it occurs in prod...

We need to run with the logging configured as it would be in production (aka use the conf/app.ini file rather than the conf/developement-app.ini) with a couple modifications. I made my own personal sentry account which made things easy for testing and hooked it up to my personal dsn. Note in the attached file you will need to configure the dsn.
[app-dev-sentry.ini.txt](https://github.com/hypothesis/h/files/1647194/app-dev-sentry.ini.txt)

If we were to use the recommended approach from getsentry/raven-python#851 we would make this change in h/sentry.py where an inst of the raven client is returned.

**Comment by hmstepanek** [comment]
As part of this fix I will also be adding monitoring/alerting via one of our many other monitoring tools we have hooked up so if this does become a significant problem/something we don't want to ignore in the future we will still continue to get alerts about it but it won't eat into our sentry quota.

**Comment by robertknight** [comment]
I did a bit more digging into where the exception report comes from. The week before last I think I said it was coming from raven's integration with the "requests" library. Re-reading the source for `raven.breadcrumbs` where this hook is I think that's wrong. It captures details of the request but doesn't log the exception there.

Instead it looks like the exception is logged by `elasticsearch.connection.http_requests.RequestsHttpConnection.perform_request` if a timeout occurs, although the request is subsequently retried by the `elasticsearch.transport.Transport.perform_request` method further up the stack if the client is configured to retry requests on timeouts, which it is in production if the `es.client.retry_on_timeout` app setting is `True` (mapped to the `ELASTICSEARCH_CLIENT_RETRY_ON_TIMEOUT` env var).

If that is correct, then it suggests that it ought to be possible to filter this using the usual filtering infrastructure in the logging package.
