### ISSUE TITLE
A few annotations not returned in the search results

### ISSUE THREAD

**Issue by nlisgo** [hypothesis/h#4741]
### Steps to reproduce
1. We created 1348 public annotations in a publisher group for 896 users in a short space of time. Only 4 annotations were not discoverable in the search results. We were using a test authority. As these were the only public annotations in the publisher group, it was easy to discover that there were 4 annotations missing from search because the total was 1344.
2. After posting all of the annotations had been created I confirm that they exist by hitting the `/annotations/{id}` endpoint.
3. Gather all of the annotation ids from the `/search?group=[GROUP_ID]` endpoint and ensure that each annotation id for the annotations that you created is present in the search results. I found 4 that were not. I also checked to see if the annotations were present if search was filtered by username and they still were not returned.
4. Wondering whether it was just an issue with the search index, I updated one of the annotations that was missing from the search and it did not fix the problem.

**Comment by nlisgo** [comment]
Update: I deleted all of the annotations and created them again and the same 4 were created but couldn't not be found in the search results.

Then I deleted the annotations and created only the 4 annotations plus their parent annotations. This left me with 8 annotations and I had the same result with 4 rows in the search results and 4 additional annotations had been created but could not be found in the search results.

This rules out it being a random failure and caused by there being a high number of annotations created in a short amount of time.

**Comment by robertknight** [comment]
> Update: I deleted all of the annotations and created them again and the same 4 were created but couldn't not be found in the search results.

Oh, that's interesting.

I'm currently running a script to check the status in ES of a subset of annotations in Postgres. So far I found from an initial check of the 1000 most recent additions:

```
7f6b545a-fd0c-11e7-be6a-a78f6dd2598c / f2tUWv0MEee-aqePbdJZjA is missing from Elasticsearch
7d6dde48-fd0c-11e7-99b0-332752c1bd75 / fW3eSP0MEeeZsDMnUsG9dQ is missing from Elasticsearch
7b6cf566-fd0c-11e7-b877-9bd9def938d2 / e2z1Zv0MEee4d5vZ3vk40g is missing from Elasticsearch
7a13d8a6-fd0c-11e7-9788-fbd549f991e8 / ehPYpv0MEeeXiPvVSfmR6A is missing from Elasticsearch
```

**Comment by robertknight** [comment]
Possibly related: https://sentry.io/hypothesis/h/issues/242530914/ (`h.tasks.indexer.add_annotation` failed with `RequestError: TransportError(400, u'RemoteTransportException[[Stegron][inet[/x.x.x.x:y]][indices:data/write/index]]; nested: IllegalArgumentException[Document contains at least one immense term in field="_all" (whose UTF8 encoding is longer than the max length 32766)`))

**Comment by robertknight** [comment]
Indeed, the text field of the first annotation in that list is longer than 32KB:

```sh
 ~/h/tools > curl -s 'https://hypothes.is/api/annotations/f2tUWv0MEee-aqePbdJZjA' | jq '.text | length'
36064
```

This is not true of the second annotation however:

```
 ~/h/tools > curl -s 'https://hypothes.is/api/annotations/fW3eSP0MEeeZsDMnUsG9dQ' | jq .
{
  "flagged": false,
  "updated": "2018-01-19T11:32:54.284507+00:00",
  "group": "ijDGibQE",
  "target": [
    {
      "source": "https://continuumtest--journal.elifesciences.org/articles/23570"
    }
  ],
  "links": {
    "json": "https://hypothes.is/api/annotations/fW3eSP0MEeeZsDMnUsG9dQ",
    "incontext": "https://hyp.is/fIN6sP0MEeeNAndL0oOTWw/continuumtest--journal.elifesciences.org/articles/23570"
  },
  "imported_id": "disqus-import:3357085204",
  "text": "Dear Henry,\n\nAs you can read, the final version of the paper now duly cites your paper. Thanks for catching this oversight before the manuscript was final (hence the great advantage of publication ahead of print).\n\nBest,",
  "tags": [],
  "uri": "https://continuumtest--journal.elifesciences.org/articles/23570",
  "created": "2018-01-19T11:32:54.284507+00:00",
  "user_info": {
    "display_name": "Benoît Kornmann"
  },
  "references": [
    "fIN6sP0MEeeNAndL0oOTWw"
  ],
  "user": "acct:g84st3rt@test.elifesciences.org",
  "hidden": false,
  "document": {
    "title": [
      "Functional mapping of yeast genomes by saturated transposition"
    ]
  },
  "id": "fW3eSP0MEeeZsDMnUsG9dQ",
  "permissions": {
    "read": [
      "group:__world__"
    ],
    "admin": [
      "acct:g84st3rt@test.elifesciences.org"
    ],
    "update": [
      "acct:g84st3rt@test.elifesciences.org"
    ],
    "delete": [
      "acct:g84st3rt@test.elifesciences.org"
    ]
  }
}
```

One thing I do notice about the second, third and last annotations is that the display names all contain accented characters in the display name. This could be related to https://github.com/hypothesis/h/issues/4733

**Comment by robertknight** [comment]
Another case, where the length of the selected text in the annotation exceeds 32KB:

```
 ~/h/tools > curl -s 'https://hypothes.is/api/annotations/HleSZvy_EeeKgqsO7-n89g' | jq '.target[0].selector[] | select(.type=="TextQuoteSelector") | .exact | length'
70621
```

**Comment by robertknight** [comment]
Of 10K recent annotations checked so far, I've found 7 missing from Elasticsearch. The tool I'm using to check a list of IDs dumped from Postgres is https://gist.github.com/robertknight/3bed5b33cc3255e6dddcdcf20ba06e8f

**Comment by robertknight** [comment]
After checking 55K recently added annotations, I've so far found these missing from Elasticsearch:

```
7f6b545a-fd0c-11e7-be6a-a78f6dd2598c / f2tUWv0MEee-aqePbdJZjA is not in Elasticsearch
7d6dde48-fd0c-11e7-99b0-332752c1bd75 / fW3eSP0MEeeZsDMnUsG9dQ is not in Elasticsearch
7a13d8a6-fd0c-11e7-9788-fbd549f991e8 / ehPYpv0MEeeXiPvVSfmR6A is not in Elasticsearch
7b6cf566-fd0c-11e7-b877-9bd9def938d2 / e2z1Zv0MEee4d5vZ3vk40g is not in Elasticsearch
1e579266-fcbf-11e7-8a82-ab0eefe9fcf6 / HleSZvy_EeeKgqsO7-n89g is not in Elasticsearch
0426730c-fc66-11e7-8249-9fc14d6349a2 / BCZzDPxmEeeCSZ_BTWNJog is not in Elasticsearch
e1012a70-fc65-11e7-8c76-d35964edbf81 / 4QEqcPxlEeeMdtNZZO2_gQ is not in Elasticsearch
4fb9a232-f95d-11e7-87e9-039533d63e8b / T7miMvldEeeH6QOVM9Y-iw is not in Elasticsearch
ea083ae8-f939-11e7-9357-778338cb26a5 / 6gg66Pk5EeeTV3eDOMsmpQ is not in Elasticsearch
8be23e68-f8bd-11e7-bf76-6740a4622b6d / i-I-aPi9Eee_dmdApGIrbQ is not in Elasticsearch
e1927d6a-f8bc-11e7-9c1e-df6f2a34ea3f / 4ZJ9avi8EeecHt9vKjTqPw is not in Elasticsearch
e0fd03fe-f8ba-11e7-9797-9f68c1a9f160 / 4P0D_vi6EeeXl59owanxYA is not in Elasticsearch
a0bc2f06-f872-11e7-afbf-cbcdfd0f5e97 / oLwvBvhyEeevv8vN_Q9elw is not in Elasticsearch
57f749d6-f872-11e7-98ff-d34a77cac0d8 / V_dJ1vhyEeeY_9NKd8rA2A is not in Elasticsearch
656c07fa-f7f5-11e7-afce-fbe2463a4611 / ZWwH-vf1EeevzvviRjpGEQ is not in Elasticsearch
109b738c-f7f5-11e7-ad07-5769b8090e1f / EJtzjPf1EeetB1dpuAkOHw is not in Elasticsearch
0bd88948-f7f5-11e7-80ba-1b6e33cd5ffb / C9iJSPf1EeeAuhtuM81f-w is not in Elasticsearch
8a086482-f7f5-11e7-a513-53d1f34541d4 / ighkgvf1EeelE1PR80VB1A is not in Elasticsearch
288dd8e0-f7f5-11e7-9f66-b3a839e0947e / KI3Y4Pf1EeefZrOoOeCUfg is not in Elasticsearch
1bcd5dfc-f637-11e7-98db-a37185ebf61c / G81d_PY3EeeY26Nxhev2HA is not in Elasticsearch
eca8610c-f636-11e7-93a7-dff9c89445a6 / 7KhhDPY2EeeTp9_5yJRFpg is not in Elasticsearch
eece110a-f520-11e7-bebf-5b355c7856e9 / 7s4RCvUgEee-v1s1XHhW6Q is not in Elasticsearch
c46572a0-f520-11e7-b8a9-bb68a7daffc4 / xGVyoPUgEee4qbtop9r_xA is not in Elasticsearch
a429c13a-f51b-11e7-b722-f70cdd88803b / pCnBOvUbEee3IvcM3YiAOw is not in Elasticsearch
cdb84eb6-f487-11e7-b568-7f4293a3c4ca / zbhOtvSHEee1aH9Ck6PEyg is not in Elasticsearch
50057a3e-f487-11e7-8d0f-7f4838aa1e21 / UAV6PvSHEeeND39IOKoeIQ is not in Elasticsearch
fce049c8-f482-11e7-a59b-fb682f198fa4 / _OBJyPSCEeelm_toLxmPpA is not in Elasticsearch
c89843ce-f3ff-11e7-b4f9-b3bb72f1c945 / yJhDzvP_Eee0-bO7cvHJRQ is not in Elasticsearch
1010ec7a-f3e6-11e7-9eb8-6fb52bce2cf8 / EBDsevPmEeeeuG-1K84s-A is not in Elasticsearch
9d4a93c2-f3e4-11e7-883f-df827ca7adae / nUqTwvPkEeeIP9-CfKetrg is not in Elasticsearch
1d2b7dfa-f3e4-11e7-bfea-4f7db41f4661 / HSt9-vPkEee_6k99tB9GYQ is not in Elasticsearch
e1952d5e-f3e3-11e7-a5b7-53c61fa38c3f / 4ZUtXvPjEeelt1PGH6OMPw is not in Elasticsearch
ca4299c2-f23d-11e7-b8a9-335ec49d5366 / ykKZwvI9Eee4qTNexJ1TZg is not in Elasticsearch
25ae6f26-f23d-11e7-8af4-177888a6dd4e / Ja5vJvI9EeeK9Bd4iKbdTg is not in Elasticsearch
eb3c40a2-f23c-11e7-bf02-afd2c5efa599 / 6zxAovI8Eee_Aq_Sxe-lmQ is not in Elasticsearch
```

**Comment by robertknight** [comment]
In testing locally I verified that if replying to an annotation as a user with a non-ASCII display name AND if `pyramid.debug_all` is turned _off_ in "h" as it is in production, then the reply gets created in the DB but an exception occurs when generating the reply notification (#4733) _after_ the DB commit happens and also the annotation does not get indexed in Elasticsearch.

**Comment by robertknight** [comment]
> Quite why the reply notification generation failing interferes with indexing into ES is not immediately obvious to me, I'm still looking into that.

Ah I see, this is because reply notifications and indexing are both implemented as subscribers to `h.events.AnnotationEvent`. If one of the subscribers in the queue generates an exception then this appears to prevent other subscribers from executing.

**Comment by robertknight** [comment]
I split the long annotation body/quote issue out into a separate GH issue (#4751) and am making this issue about the Unicode handling problem with replies.
