### ISSUE TITLE
Replies do not appear in user profiles

### ISSUE THREAD

**Issue by ntnsndr** [hypothesis/h#4747]
I use Hypothesis in my [Hacker Culture](https://nathanschneider.info/wiki/school/hacker_culture) course at the University of Colorado, among others, and my observant students immediately noticed that their replies to each other's annotations are not included in their profiles. This is a problem because I rely on their profiles for evaluating their work, and I want to incentivize active conversation through the platform.

Is there any way this could be corrected?

### Steps to reproduce
1. Using any of the Hypothesis tool, see another user's annotation you want to reply to
2. Reply to it, see that the reply was posted
3. Try and fail to find it on one's own profile.

### Expected behaviour
The profile should include replies in the list of a user's annotations.

### Actual behaviour
The profile treats replies—one's own, or other users' replies to one's annotations—as nonexistent.

### Browser/system information
I use Firefox via and bookmarklet on Ubuntu 17.10, but this does not appear to be context-dependent.

**Comment by klemay** [comment]
Closing in favor of https://github.com/hypothesis/product-backlog/issues/378
