### ISSUE TITLE
Logging out on one tab doesn't log all tabs out

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#475]
Plus, you can still create and save annotations on the other tabs. This came up in usability testing.  (from @RawKStar77)

**Comment by nickstenning** [comment]
I can't think of a single web service I use that pushes logouts to other clients in realtime. If I have two Gmail tabs open, and log out in one, the other one will stop working. If I have two GitHub tabs open, and log out in one, the other will stop working.

Closing as WONTFIX.
