### ISSUE TITLE
headline formatting wrong on activity page cards

### ISSUE THREAD

**Issue by judell** [hypothesis/h#4790]
Example:

https://hyp.is/bXuwwA1eEeiDzduvpClbyA/www.ncbi.nlm.nih.gov/pubmed/17397525

![image](https://user-images.githubusercontent.com/46509/36048332-b85b25e6-0d93-11e8-821f-f596fba9c1d9.png)

https://hypothes.is/search?q=387679

![image](https://user-images.githubusercontent.com/46509/36048358-cc6bdac6-0d93-11e8-85d8-fc9fecc7e0c5.png)

Maybe should be line-height:1 ?

![image](https://user-images.githubusercontent.com/46509/36048491-466c4892-0d94-11e8-87ac-7ac1f20d3f57.png)

/cc @dawariley

**Comment by dawariley** [comment]
![screen shot 2018-02-22 at 09 56 44](https://user-images.githubusercontent.com/5212631/36545534-1fd29d9e-17b7-11e8-9cd8-bf93e48cd5d7.png)

**Issues observed:** 

Not just the compacted layout between lines that is an issue but the size of the headline text is unnecessarily large.

**Proposed Solution:**

1. Reduce the header size
2. Increase the line spacing 

Further investigation is required to determine what the optimum values for these will be.

**Comment by klemay** [comment]
This was [brought up today](https://hypothesis.zendesk.com/agent/tickets/4240) by Europe PMC. Some of the annotations on their site contain h2 tags, which result in overlapping text. Example: https://hyp.is/dIePJH44EeiOlXM7IVNyXg/europepmc.org/abstract/MED/21334061

**Comment by klemay** [comment]
Changed the title of this so that it reflects line spacing for headers on activity pages. There is a separate card for line height on annotation cards here: https://github.com/hypothesis/product-backlog/issues/162
