### ISSUE TITLE
Improper handling of Unicode characters while displaying annotations URL?

### ISSUE THREAD

**Issue by ChillarAnand** [hypothesis/h#4841]
### Steps to reproduce
1. Visit any url with unicode characters like https://te.wikipedia.org/wiki/చలం_రచనల_జాబితా
2. Create annotation.
3. Checkout your annotation at https://hypothes.is/

### Expected behaviour
It should show human readable url in url field.

### Actual behaviour
It shows encoded url.

![screenshot from 2018-03-01 13-26-24](https://user-images.githubusercontent.com/4463796/36833452-67824ec0-1d55-11e8-9562-8c7096916f66.png)

### Browser/system information

**OS**: Ubuntu 16.04.4 LTS ( Linux 4.13.0-36-generic )
**Browser**: Google Chrome	64.0.3282.186 (Official Build) (64-bit)

**Comment by robertknight** [comment]
This now appears to be resolved. https://hypothes.is/search?q=url%3Ahttps%3A%2F%2Fte.wikipedia.org%2Fwiki%2Fచలం_రచనల_జాబితా renders as:

![Image](https://github.com/user-attachments/assets/97876880-ff4e-4bee-92d4-cada4bb5a394)
