### ISSUE TITLE
Share url not working

### ISSUE THREAD

**Issue by keerthi-26** [hypothesis/h#4882]
Sharing of all and individual annotations is not working. After getting the share link, it is not opening and is showing an error. 

Browser: Chrome
Version 65.0.3325.162 

![hypothesis issue](https://user-images.githubusercontent.com/36663187/37459584-9212a936-286e-11e8-96b5-acd08a9c2762.JPG)

**Comment by klemay** [comment]
Hi @keerthi-26 - looks like you're trying to share annotations made on a locally-saved PDF. You will need to either (a) host that PDF somewhere on the web (i.e., docdrop.org or a website you own) or (b) share the PDF itself and view it in your browser [see instructions here](https://hypothesis.zendesk.com/hc/en-us/articles/360001360753-Annotating-locally-saved-PDFs).

If you have further questions please contact support@hypothes.is and reference this Github issue.
