### ISSUE TITLE
Current layout is unusable with pages that have no margin

### ISSUE THREAD

**Issue by csillag** [hypothesis/h#491]
If the document takes 100% of horizontal page, our sidebar hides lots of content. 
Therefore it's impossible to comfortably work with those pages.

This was probably discussed many times, but this is definitely not solved yet.

Suggestion: could we provide an option, that would change the layout so that we actually push back the content to the left? This should not be the default way (since we try to avoid changing the document, even the layout, and I agree with that), but I think we could have this as a fallback, for really badly designed pages.

**Comment by jbshirk** [comment]
![Screenshot_20191228_105610](https://user-images.githubusercontent.com/3949396/71546515-8e0eed00-2965-11ea-847c-3ef65b7ad2cd.png)
