### ISSUE TITLE
Use or deprecate yapf

### ISSUE THREAD

**Issue by jmcarp** [hypothesis/h#4942]
Running `yapf` on `h` yields a 37k-line diff, so I'm guessing it's not used regularly. For clarity, it might be helpful to drop the `yapf` docs and config if it's not being used, or use it more consistently if it is (for example, by providing a pre-commit hook, or verifying in CI).

**Comment by robertknight** [comment]
We switched to using Black for formatting Python code across all of our projects some time back.
