### ISSUE TITLE
Need documentation: how to deploy a local hypothesis service?

### ISSUE THREAD

**Issue by fishfree** [hypothesis/h#4998]
I searched everywhere, found no documentation on deploying a local hypothesis service. :-(

**Comment by seanh** [comment]
Hi @fishfree , you can find the development install docs here: http://h.readthedocs.io/en/latest/developing/install/

**Comment by fishfree** [comment]
@seanh Thank you! I followed this doc, but it can only be accessed in localhost. How can I configure a domain name and letsencrypt cert?

**Comment by robertknight** [comment]
> How can I configure a domain name and letsencrypt cert?

The development server is not meant to be used outside of localhost. For production deployments you'll need to build and run the h Docker image and expose it to the web or whatever network you want it to be accessible on. Can you tell us a bit more about what you are trying to use the service for?
