### ISSUE TITLE
Using the text "<script>" in an annotation prevents anything starting with "<" from showing

### ISSUE THREAD

**Issue by teodorlu** [hypothesis/h#5071]
### Steps to reproduce
1. Create a new annotation containing the text <Script> and some text after it
2. View the whole

### Expected behaviour
The whole annotation shows

### Actual behaviour
The annotation is shown until the <Script>. From `<` and onwards, nothing is shown.

### Browser/system information
Vivaldi 1.15.1147.42 (Stable channel) (64-bit), Ubuntu Linux

### Personal comment
I guess you're avoiding XSS. Consider doing HTML escapes instead of just removing anything that can be dangerous?

And Hypothesis is great :heart:

**Comment by robertknight** [comment]
Annotation content in Hypothesis is Markdown, which can contain [HTML tags for formatting](https://spec.commonmark.org/0.28/#html-blocks). This is why we don't just HTML-escape everything. If you need to render HTML code which contains `<script>`, you can do this using code blocks:

````
Some text

```
<script>
foo
</script>
```

Some more text with an inline `<script>` code span.
````

**Comment by teodorlu** [comment]
That makes sense. Thanks for the clarification.
