### ISSUE TITLE
I continuously set the wrong privacy settings on my annotations, and then have to go back and mark them public on by one, which is frustrating

### ISSUE THREAD

**Issue by equivalentideas** [hypothesis/h#5111]
This is a design/UX bug :)

User story: _As a user, when I'm making an annotation, make the privacy settings of the annotation clear to me, so that I can select the correct settings for my purposes._

The clarity of the person’s understanding of this setting and how/when to configure it, is a really important part of using the tool successfully. When they get it wrong, it's frustrating at best, and dangerous at worst (publicly sharing that I was reading something in personal or political contexts where where that knowledge might make me a target of abuse).

I've repeatably gotten this setting wrong, which has been frustrating, causing me to go back and update each annotation in a document.

I believe the main cause of this experience is that difference between the public and private state are minimally communicated:

When it will be **private**:
![screen shot 2018-06-29 at 2 36 02 pm](https://user-images.githubusercontent.com/1239550/42073414-e334c388-7ba9-11e8-9a57-7c87e44180ef.png)

When it will be **public**:
![screen shot 2018-06-29 at 2 35 53 pm](https://user-images.githubusercontent.com/1239550/42073412-df7deea4-7ba9-11e8-88d7-190b4fb03a22.png)

The most obvious difference between the states is the change in text from 'Post to Only Me' to 'Post to Public'. This text very easy to glance past, which is encouraged by the low contrast color choice (which [doesn't meet accessibility standards](https://webaim.org/resources/contrastchecker/?fcolor=969696&bcolor=626262)).

Majority keyboard users, like me, might also just hit the enter bar and not look at the submit button.

The other differences are that the private state has a lock icon under the name of the poster in the top left. But this communication is made really confusing by it's place after the word 'Public'. I understand this is partly to do with the concept of groups in this tool.

There's also a notice about the creative commons status of public annotations after the form when in the public state. Having it after the form is out of the area the person is focused on, and this text is also [very low contrast](https://webaim.org/resources/contrastchecker/?fcolor=969696&bcolor=FFFFFF) and very small. It is designed to be unobtrusive or noticeable so isn't a good communicator of the state here.

Overall, I would call the communication of states here very minimal. I don't think this is appropriate for such an important interaction moment—and personally, it's led me astray a bunch of times. The result of having to individually correct each one is a real pain :)

It seems to be currently defaulting to private, which seems safe, but I think the lack of clarity undermines this default as a tactic. I imagine this is why I've only had this experience where something intended to be public was private, which is good :).

I'm happy to help brainstorm potential solutions if that's helpful—I've held back from making any suggestions, as I know that's not always helpful.

### Steps to reproduce

1. Post an annotation or highlight on a page

### Expected behaviour
That my highlights be viewable to people I share the link with.

### Actual behaviour
The highlights are only visible to me.

### Browser/system information
Firefox, desktop.

**Comment by dwhly** [comment]
We agree.  Duplicate issue, here: https://github.com/hypothesis/product-backlog/issues/200

**Comment by equivalentideas** [comment]
> Duplicate issue

Thanks @dwhly 👍

**Comment by equivalentideas** [comment]
:) Lol just realised I did this again on 20 annotations a while back https://via.hypothes.is/http://www.lancaster.ac.uk/fass/resources/sociology-online-papers/papers/suchman-agenciestechnodesign.pdf

**Comment by equivalentideas** [comment]
I see this goes way back :) https://github.com/hypothesis/h/issues/1691
