### ISSUE TITLE
Remove organization logo character limit

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#5137]
h currently enforces the organization logo files be 10,000 characters or less. This limit is problematic and should be removed.

We should just remove `ORGANIZATION_LOGO_MAX_CHARS` entirely, it was put there to prevent maliciously large uploads but we've no need to worry about those because only Hypothesis admins can add logos.

In the future, if we have self-serve organization creation, we may need validation of organization logos. But that feature isn't on our immediate roadmap. We may never implement it. If / when we do, we'll have to implement good SVG validation with realistic restrictions and good, helpful error messages. The current code doesn't achieve that - it gives an incorrect error message when the file is too long, and rejects the kinds of SVGs that our partners want to use as invalid. Let's keep it simple and not try to solve this validation problem prematurely.

## Incompatible with SVG files we receive from partners

This is causing us a problem because we don't create the organization logo SVGs ourselves, we receive them from partners. Partners don't always provide clean and short SVG files and we're having trouble getting clean and short ones from all of them - different partners have their own ways of creating SVG files. For an example of the problem, see <https://stackoverflow.com/c/hypothesis/questions/77/81>.

## Incorrect error message

Additionally the Hypothesis admin is shown the error message "Logo is not valid SVG" when they try to enter SVG longer than 10,000 characters. This error message is incorrect - it is valid for an SVG file to be longer than 10,000 characters. The 10,000 character limit is an arbitrary limit applied by us.

The model-level validation actually [does give specific error messages for specific problems](https://github.com/hypothesis/h/blob/a1275c9c5eca0c85cb4d1d80abbaffe11f46a08c/h/models/organization.py#L50-L66) with the SVG, including "logo must be less than 10000 characters long", but the form validation [swallows the specific error messages](https://github.com/hypothesis/h/blob/a1275c9c5eca0c85cb4d1d80abbaffe11f46a08c/h/schemas/forms/admin/organization.py#L14-L18) and turns them all into the generic and not-always-correct "Logo is not valid SVG".

## P.S. Avoid complex validation in models

As an aside, and going beyond the organization logo max length issue, I think the complex `validate_logo()` method on the `Organization` model (validates the logo's length, that it parses with `ElementTree`, that its root tag is `svg`, and gives different error messages for different failures) should be removed as it's not needed (only Hypothesis admins can add logos), or failing that should at least be moved into `h/schemas` where validation is supposed to be done in h.

For one thing this `validate_logo()` method is being run twice each time a logo is added (the admin form schema [creates a throw-away `Organization` object in order to validate the logo](https://github.com/hypothesis/h/blob/a1275c9c5eca0c85cb4d1d80abbaffe11f46a08c/h/schemas/forms/admin/organization.py#L16) and then the actual `Organization` object that is going to be saved is created later.

But also, part of the design of the h code is that we [keep our model code as simple and thin as possible](https://github.com/hypothesis/h/blob/master/docs/arch/adr-002.rst), removing as much logic as possible from the models, and putting it instead into services (`h/services/*`), into validation schemas (beginning to be collected all together in `h/schemas/*`, see for example <https://github.com/hypothesis/h/pull/5100>), into traversal contexts and roots (`h/traversal/*`, see <https://github.com/hypothesis/h/issues/5015>), etc.

Some of the reasons for wanting to keep models as simple and focused as possible - models should be a persistence layer only and should just know how to save the data to the database, and not know anything about for example the user interface (and validation error messages), or have many dependencies - include making the model code as reusable as possible, allowing model objects to be used as something close to "value objects" in tests for non-model code, keeping the tests for the models themselves short and simple, and allowing validation to be handled by the parts of the code that have what they need to do really good validation with specific error messages and form fields etc (`h/schemas` makes use of Colander/Deform and JSONSchema).

It's also usually better to do validation at the edges of the system when data is coming in, rather than doing it in the core of the system. Views receive data from forms or API requests, and the first thing the view does is call the schemas layer to validate that data, and if it's valid we then pass it on to the models and services or whatever else needs to happen. Keeping all, or at least most, "validation" logic in one place in `h/schemas` instead of distributing it throughout the code is nice too.

**Comment by hmstepanek** [comment]
One thing I would suggest is running these files through a minifier before uploading them. I ran the larger one through a minifier and it reduced it from 432.4 KB to 7.8 KB. The EPMC one was a size issue. The other one doesn't appear to be failing the validate function on the model so I'm not sure what's wrong with that one yet. @ajpeddakotla Can you run the EPMC one through a minifier and upload it and I'll keep debugging the other one?

**Comment by ajpeddakotla** [comment]
@hmstepanek after minifying the UW Madison logo, it succesfully uploaded to the site. 

The Europe PMC logo is still giving me trouble. I minified it, and when I tried to upload the new logo to the organization it still gave me the `logo is not valid SVG` error. 

Here's the original svg file: 
https://drive.google.com/open?id=1gh0JehWI4bUruyDyN-u2bR0TAEo5tbEq

And the minified file: 
https://drive.google.com/open?id=1gh0JehWI4bUruyDyN-u2bR0TAEo5tbEq

I used this site to minify: https://jakearchibald.github.io/svgomg/

**Comment by hmstepanek** [comment]
Ok @ajpeddakotla. Use this minifier: https://www.svgminify.com/
The one you used didn't minify the svg under 10k. That being said I don't think it's unreasonable to increase the limit as well since it seems kinda tight.

**Comment by hmstepanek** [comment]
In summary things I would like to do for this to be completed: 

1.  fix the too large error message as it's wrong (just accidentally used the wrong constant)
1.  update the tests to check for the message part of the error not just the error type
1.  increase the allowed size by an order of magnitude
1.  pass the error message to the client admin page so the user actually knows why the svg is invalid

**Comment by seanh** [comment]
You want to be careful with how the error messages look on the page, unfortunately our form design fails if the error message isn't really short (not super important for admin pages though)

> update the tests to check for the message part of the error not just the error type

Alternatively define a custom `SVGValidationError` class with subclasses `SVGInvalidErrror`, `SVGTooBigError`, etc. That way the tests, and the code, can just catch different classes, rather than switching based on the human-readable error message (which is awkward and in non-test code might even fail is we ever localized h).

What do you think about moving this validation into the view or into schemas? Keep all validation in one place there, and I really think there are good reasons for keeping our models thin and keeping things like validation and user-visible error messages out of them.

**Comment by hmstepanek** [comment]
I’m fine with moving it somewhere else, and the error types seems good too. I’ll make the changes then add you on the review. 👍

**Comment by seanh** [comment]
See this thread on error types: https://hypothes-is.slack.com/archives/C1MA4E9B9/p1531484200000291

**Comment by robertknight** [comment]
> One thing I would suggest is running these files through a minifier before uploading them. I ran the larger one through a minifier and it reduced it from 432.4 KB to 7.8 KB. The EPMC one was a size issue. 

I think this shows a good reason for having the length limit in the first place! Remember that we will display these SVGs in the client and on the website so it is good to consider the needs of end users and avoid shipping unnecessarily bloated resources to them.

> In the future, if we have self-serve organization creation, we may need validation of organization logos. But that feature isn't on our immediate roadmap. 

I disagree that we should avoid or minimize validation simply because a feature is only exposed to site admins. One purpose of validation is to limit the entry of data into the system which causes problems now or in the future. It is much easier to relax a constraint if we decide it is inappropriate than to go back and add one later on.

**Comment by ajpeddakotla** [comment]
Closing as this has been completed
