### ISSUE TITLE
Optimize search reindexing task

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#5168]
As the size of our production DB grows, so does the amount of time taken to reindex annotations after making changes to the schema or data that is indexed in Elasticsearch. I recently had to [bump the timeout](https://github.com/hypothesis/deployment/pull/24) as it exceeded the 2-hour threshold.

The current reindexing rate on an `m4.large` h production app instance is about ~430 annotations/sec. Elasticsearch reported a mean indexing time of ~0.5s / document for a recent reindexing operation, which suggests that most of the overhead is elsewhere.

----

**Implementation notes**

Some thoughts on ways we could improve the situation:

1. Parallelize reindexing. We have multiple h app instances running but run the entire reindexing task on a single instance. There are some setup and finalization steps which really need to be done on a single instance, but most of the work could be spread across instances, probably using the Celery task queue and workers that we already have in place.
2. Overlap database reads and Elasticsearch writes. The current task loads a bunch of annotations from the DB, then "presents" them into a dict for indexing, then makes a query to Elasticsearch to index them. It would be more efficient if DB reads for the _next_ batch were overlapped with the ES query to write the current batch.
3. Profile reindexing in production and optimize whatever is slow.

My current thoughts are that we could do something like this:

1. A "master" indexing CLI command (`hypothesis search reindex`) creates the new index.
2. The master command loads batches of annotation IDs from the DB and dispatches Celery tasks to index those annotations, probably with some upper limit on the number of outstanding tasks.
3. Once tasks have been dispatched for all annotation IDs, and once all of those tasks have been completed [1], the master indexing task finalizes the reindex operation.

[1] AFAIK we don't currently have any code in h that executes a task and then waits for it to finish. However Celery does support returning results for certain backends, including RabbitMQ. The other option is to write acknowledgements to the DB and poll them from the master task.

**Comment by hmstepanek** [comment]
Possible cause of this slowdown:
https://github.com/hypothesis/product-backlog/issues/836
I think we should address ^ then re-evaluate performance.

**Comment by seanh** [comment]
This reindexing task got completely replaced by the new periodic sync task, closing this
