### ISSUE TITLE
Internal server error when specifying text-valued field as sort parameter in search request

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#5242]
### Steps to reproduce

Make a request to `/api/search` with a text-valued field as the "sort" parameter: eg. `https://hypothes.is/api/search?sort=user`

See [h/search/config.py](https://github.com/hypothesis/h/blob/ced0b17c0fab6ab5edd0ea743fa861fbdd78630b/h/search/config.py#L30) for the list of `text` fields.

### Expected behaviour

The result should be a 4xx error and a helpful explanation. At the very least no error should occur.

### Actual behaviour

500 server error. Locally more detail is given:

```
    return func(*args, params=params, **kwargs)
  File &#34;/Users/robert/.virtualenvs/h-py3/lib/python3.6/site-packages/elasticsearch/client/__init__.py&#34;, line 655, in search
    doc_type, &#39;_search&#39;), params=params, body=body)
  File &#34;/Users/robert/.virtualenvs/h-py3/lib/python3.6/site-packages/elasticsearch/transport.py&#34;, line 314, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File &#34;/Users/robert/.virtualenvs/h-py3/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py&#34;, line 180, in perform_request
    self._raise_error(response.status, raw_data)
  File &#34;/Users/robert/.virtualenvs/h-py3/lib/python3.6/site-packages/elasticsearch/connection/base.py&#34;, line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, &#39;search_phase_execution_exception&#39;, &#39;Fielddata is disabled on text fields by default. Set fielddata=true on [quote] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead.&#39;)
```

**Comment by hmstepanek** [comment]
A field not listed in the sort enums yields the following error message:
![image](https://user-images.githubusercontent.com/30059933/44941395-55e7a200-ad51-11e8-9ecf-b287a65c32ec.png)
A valid field returns annotations:
![image](https://user-images.githubusercontent.com/30059933/44941406-98a97a00-ad51-11e8-9fc5-1e23ec30e82b.png)
