### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'userid'

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#5280]
This has been happening on production h for a while, lets get it fixed:

https://sentry.io/organizations/hypothesis/issues/848452475/?project=37293&referrer=RegressionActivityEmail&statsPeriod=14d&utc=false

```
AttributeError: 'NoneType' object has no attribute 'userid'
(22 additional frame(s) were not displayed)
...
  File "oauthlib/oauth2/rfc6749/endpoints/base.py", line 64, in wrapper
    return f(endpoint, uri, *args, **kwargs)
  File "oauthlib/oauth2/rfc6749/endpoints/token.py", line 118, in create_token_response
    request, self.default_token_type)
  File "oauthlib/oauth2/rfc6749/grant_types/refresh_token.py", line 68, in create_token_response
    self.request_validator.save_token(token, request)
  File "oauthlib/oauth2/rfc6749/request_validator.py", line 246, in save_token
    return self.save_bearer_token(token, request, *args, **kwargs)
  File "h/services/oauth_validator.py", line 194, in save_bearer_token
    oauth_token = models.Token(userid=request.user.userid,

AttributeError: 'NoneType' object has no attribute 'userid'
```

**Comment by seanh** [comment]
Sentry issue: [H-1PE](https://sentry.io/organizations/hypothesis/issues/897931676/?project=37293&referrer=github_plugin)

**Comment by seanh** [comment]
Closing this because it doesn't seem to have happened since February and for some reason we no longer seem to have any tracebacks in Sentry

**Comment by hmstepanek** [comment]
It's back! (I'll leave this here and maybe we can re-open/work on this next sprint.)
https://sentry.io/organizations/hypothesis/issues/1095952398/?project=37293&query=is%3Aunresolved&statsPeriod=14d

**Comment by hmstepanek** [comment]
Actually come to think of it this might correspond with @judell's token debugging. So it may be that this is the result of some kind of malformed token auth.
