### ISSUE TITLE
Clicking on annotation label throws "annotator is not defined" exception

### ISSUE THREAD

**Issue by renehamburger** [hypothesis/h#5300]
I'm using the most recent Chrome extension and have tested this on a couple of websites, including your own [FAQs](https://web.hypothes.is/faq/): 

Clicking on an annotation label in the bucket-bar on the right does not open the sidebar and show the details of the corresponding annotations, but rather crashes with an uncaught exception:

```
Uncaught ReferenceError: annotator is not defined               bucket-bar.coffee:1
```

**Comment by klemay** [comment]
Hi @renehamburger, thanks for reporting this! We're already tracking this at https://github.com/hypothesis/product-backlog/issues/704, so I'm going to close this issue in favor of that one
