### ISSUE TITLE
Strip 'https://via.hypothes.is/' for external links

### ISSUE THREAD

**Issue by lguariento** [hypothesis/h#5301]
1. I have a `<a target="_blank" href="https://externallink"> Link</a>` in my page.
2. hypothes.is automatically prepends 'https://via.hypothes.is/' to that link
3. When clicked, a new tab opens - blank.

### Expected behaviour
I'd like to open the external page, without any 'https://via.hypothes.is' appended.

### Actual behaviour
I see a blank page.

### Browser/system information
Firefox 62, OSX 10.13

Is it possible to strip the 'via' instruction, at least for external links?

**Comment by robertknight** [comment]
> Is it possible to strip the 'via' instruction, at least for external links?

I'm afraid not. The current implementation of the proxy service rewrites all links. This is an artefact of its origins in the [Webrecorder](https://webrecorder.io) project rather than because we decided it was the best thing to do for Hypothesis' proxy service.
