### ISSUE TITLE
Investigate "ssl in write" timeouts in h

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#5311]
We've been getting a lot of these. What is happening here? Is there anything we can do to fix this?

Sentry issues:

* https://sentry.io/hypothesis/h/issues/499114248/?query=is%3Aunresolved
* https://sentry.io/hypothesis/h/issues/619609210/?query=is%3Aunresolved
* https://sentry.io/hypothesis/h/issues/507065335/?query=is%3Aunresolved
* https://sentry.io/hypothesis/h/issues/639991801/?query=is%3Aunresolved
* https://sentry.io/hypothesis/h/issues/512238945/?query=is%3Aunresolved
* https://sentry.io/hypothesis/h/issues/658769063/?query=is%3Aunresolved
* https://sentry.io/hypothesis/h/issues/637895251/?query=is%3Aunresolved
* https://sentry.io/hypothesis/h/issues/657533512/?query=is%3Aunresolved

Possibly related github issue:

* ~~[Fix non-performant database queries on activity pages #812](https://github.com/hypothesis/product-backlog/issues/812)~~ - _This is not related - robertknight_
* ~~[Investigate why fetch_annotations is so slow #811](https://github.com/hypothesis/product-backlog/issues/811)~~ - _This is not related - robertknight_

Possibly related on-call incident reports:

* ~~[Incident report: Metabase queries are timing-out](https://docs.google.com/document/d/1gwcLAUbogRJ95tTW0tbxSonDim7itolqUVnLow-USyw/edit#heading=h.gv8wgsbi3v4m)~~
* ~~[Incident report: Transaction database time (Baseline Deviation)](https://docs.google.com/document/d/1gefQl1KBHFc4WMrt1vsWBrKYqRxc5bfU9AFbIbecyRw/edit#heading=h.3de8xgxrwmfo)~~ 

(_Neither of the above are related AFAICS, they are issues with the database. The issues here are all to do with the message queue - robertknight_)

Possibly related Slack discussions:

* https://hypothes-is.slack.com/archives/C0LUWQQJJ/p1536985326000100
* https://hypothes-is.slack.com/archives/C0LUWQQJJ/p1536761370000100

**Comment by robertknight** [comment]
I looked at the top linked Sentry issue. The SSL write failure was in writing to AMQP. I think this could be related to https://github.com/hypothesis/h/issues/5227

**Comment by robertknight** [comment]
Sean and me have been triaging Sentry issues in h just now. This cluster of issues is the most frequent by far.

**Comment by seanh** [comment]
If this is expected to be fixed in Kombu, then I'd lean towards ignoring it, and keeping an eye out for the Kombu release.

**Comment by robertknight** [comment]
From grepping through the Celery code, it looks like the Kombu module where the problem is happening (`kombu.pidbox`) is used as part of Celery's "remote control" tools, which none of us actively use. See also the "pidbox" mention in the [Celery glossary](http://docs.celeryproject.org/en/latest/glossary.html).

On that basis I think we can afford to just ignore this for now.

**Comment by robertknight** [comment]
The Sentry issues related to the second, less frequent cause of this error in `kombu.pidbox` have been ignored until next year as per the comments above, by which time Kombu 4.3 will hopefully have been released.
