### ISSUE TITLE
Celery tasks intermittently not running.

### ISSUE THREAD

**Issue by sheetaluk** [hypothesis/h#5328]
Occasionally, a top-level annotation is not getting reindexed after toggling the hidden status of it’s reply. It looks like the celery task to reindex the root annotation is being dispatched but not run.
See: https://github.com/hypothesis/h/blob/a91ed6dc11a94ae32786aa2ac35c944ea879edba/h/tasks/indexer.py#L25
Continuing to toggle the hidden status of the reply seems to eventually fix things and starts working as expected again.

It is possible that the task is not being dispatched correctly or the task not  being pulled from the queue.

To investigate locally:
If we’re using docker-compose to run the services, the RabbitMQ image we  use is `rabbitmq:3.6-management-alpine`. The “management” part means that it is a RabbitMQ Docker image which includes the management console.
Details on  how to access the management UI are in the README for the rabbitmq image we use: https://hub.docker.com/_/rabbitmq/

**Comment by lyzadanger** [comment]
Removing `Added to sprint` label as this is moving into a new sprint...on purpose!

**Comment by sheetaluk** [comment]
Could not reproduce this locally.

**Comment by seanh** [comment]
@robertknight Closing this on the assumption it's fixed. Reopen if necessary!
