### ISSUE TITLE
Annotation from one page with title from another page

### ISSUE THREAD

**Issue by kael** [hypothesis/h#5357]
### Steps to reproduce
Using the bookmarklet, I've just bookmarked a link, and the title of the link doesn't refer to the bookmarked page but to another page (very odd bug).

- The annotation: https://hyp.is/5KZFPMyHEeiDGz90ghxuyw/davidwalsh.name/web-extensions

- The bookmarked page link: https://davidwalsh.name/web-extensions
- The bookmarked page title: _"Create a Simple Web Extension"_

- The link after being bookmarked: https://via.hypothes.is/https://davidwalsh.name/web-extensions#annotations:5KZFPMyHEeiDGz90ghxuyw
- The displayed bookmarked title on the Hypothesis website: _"TypeScript, WTF?!"_
- The page which title refers to the unexpected one: https://davidwalsh.name/typescript

Firefox 62: Ubuntu (NoScript, uBlockOrigin, etc).

No idea how it happened and how to reproduce it.

**Comment by dwhly** [comment]
I was just able to reproduce this.

Using FF + bookmarklet.

Annotated: https://en.wikipedia.org/wiki/Major_League_Soccer
Then this almost immediately after: https://www.npr.org/2018/10/12/656849482/hurricane-michael-death-toll-rises-to-11-as-southeast-reels-from-storms-power

You can see them both here: https://hypothes.is/users/dwhly

2nd page got the title "Hidden Brain", no idea where that is coming from.

**Comment by klemay** [comment]
I don't think this is Firefox-specific, and I don't think it's related to how soon you've previously annotated a different page. 

If you annotate https://arlap.hypotheses.org/9537 from the Chrome extension, I get the same page title:

"Open Data Citation for Social Sciences and Humanities – The companion blog to the Humanities at Scale Winter School in Prague: 24th-28th October 2016"

This is an issue where H isn't picking up page titles correctly, which we've also seen here:
https://github.com/hypothesis/product-backlog/issues/535

**Comment by klemay** [comment]
Yep, this is site specific. For example, try annotating these two in quick succession using FF + Bookmarklet:

1. https://en.wikipedia.org/wiki/Major_League_Soccer
2. https://web.hypothes.is/blog/apa-psycnet/

It works just fine!

<img width="893" alt="screen shot 2018-10-12 at 1 08 45 pm" src="https://user-images.githubusercontent.com/12087705/46883403-fab0d100-ce1f-11e8-998b-7f9b4c78116a.png">

This is likely site-specific for NPR and arlap.hypotheses.org

**Comment by klemay** [comment]
We've got an open issue for this in our product backlog, so I'm going to close this in favor of https://github.com/hypothesis/product-backlog/issues/535
