### ISSUE TITLE
documentation for the docker version

### ISSUE THREAD

**Issue by awcoding** [hypothesis/h#5368]
Running a 3rd party hypothesis install is inaccessible and unnecessarily complicated. It would be nice if effort was made to make it easy for users to run it in self hosted env.

**Comment by zeigerpuppy** [comment]
agreed this would be great!

also.. link to related issue: https://github.com/hypothesis/h/issues/4899

**Comment by zeigerpuppy** [comment]
Strange that this is closed.  Does this mean the devs don't want better docs?

**Comment by hmstepanek** [comment]
Hi @zeigerpuppy, unfortunately we don't have the time and resources to dedicate to fixing this at this time. We would love better documentation and an easier deployment process but as a team we don't anticipate that this will be addressed within the next year. In an effort to keep our backlog relatively up-to-date and achievable we've closed this. We are in the process of shifting our internal deployment to terraform so it's possible some useful documentation/scripts will come out of that. Smaller, concise, and more actionable issues will be more likely to make it onto the list. This is just too broad for us to do.

**Comment by Stvad** [comment]
@hmstepanek was there any progress on publishing self-hosting instructions?
