### ISSUE TITLE
Add another 'assignment' readme example

### ISSUE THREAD

**Issue by Celebrimbor-forge** [hypothesis/h#5376]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen.

### Actual behaviour
Tell us what happens instead.

### Browser/system information
Tell us which browser, browser version, and operating system you were using when
you encountered this issue.

### Additional details
If you have other information which might be helpful, please include it. If a
screenshot will help to illustrate the issue you are reporting, please include
one.

**Comment by robertknight** [comment]
I'm going to assume this was opened in error.
