### ISSUE TITLE
Unrecognized distinct URLs

### ISSUE THREAD

**Issue by kael** [hypothesis/h#5401]
### Steps to reproduce
1. Bookmark https://reactjs.org/tutorial/tutorial.html
2. Try to bookmark https://reactjs.org/docs/thinking-in-react.html
3. https://reactjs.org/docs/thinking-in-react.html appears already bookmarked, referenced by the first URI.

Same happens when bookmarking two YouTube links, one after another, or one after a search after another.

For the bookmarklet, seems related to non-detection of URI updates with client-side routing (eg. SPA apps). For the API via.hypothes.is not sure why it happens, unless it uses the same logic than the bookmarklet.

Happens with the bookmarklet and with via.hypothes.is.

**Comment by klemay** [comment]
Hi @kael! We're tracking examples of these together here: https://github.com/hypothesis/product-backlog/issues/493

I'm going to close this issue in favor of that one to avoid duplicates.
