### ISSUE TITLE
Remove jQuery and Bootstrap from the admin pages

### ISSUE THREAD

**Issue by dwolfe** [hypothesis/h#5435]
The UI of the administration pages in `h` has been slightly broken since the last update to Bootstrap, as the markup was written against the previous major version.

This effort will remove Bootstrap entirely, and replace it with base styles from the nascent Hypothesis Design System. (Also, more research is needed, but assuming that jQuery is only in the codebase because it's a Bootstrap dependency, jQuery will be gone too.)

**Comment by robertknight** [comment]
> Also, more research is needed, but assuming that jQuery is only in the codebase because it's a Bootstrap dependency, jQuery will be gone too

Bootstrap is indeed the only reason jQuery is used in h. The main h / admin site JS code (see `h/static/scripts/{site.js, admin.js}`) doesn't use it.

**Comment by dwolfe** [comment]
@robertknight I assume this is okay to close, but if this is still relevant, could you create a new issue so I'm not subscribed? Thanks.
