### ISSUE TITLE
Usernames showing up incorrectly in LMS context 

### ISSUE THREAD

**Issue by jeremydean** [hypothesis/h#5486]
I've now seen or had this issue reported in 3 different LMSs: Sakai, Blackboard, and Schoology. The recipe for reproduction below is done for Sakai.

Login into a Sakai course and open a Hypothesis-enabled reading (in Lessons in Sakai) using two browser windows, one incognito. In this case I'm logged in as a Sakai Admin in one* and a student named Bhaktavatasalam in the other.  

Create an annotation as user 1 and everything looks good on their end:

![image](https://user-images.githubusercontent.com/3261902/50998523-48a3a680-14ed-11e9-9834-4c9b61154fa9.png)

As user 2, refresh the Hypothesis enabled doc using the red icon in sidebar and user 1's annotation appears with user 2's name:

![image](https://user-images.githubusercontent.com/3261902/50998555-6b35bf80-14ed-11e9-9e83-246779a33ea9.png)

A hard refresh in user 2's window fixes the issue:

![image](https://user-images.githubusercontent.com/3261902/50998625-a9cb7a00-14ed-11e9-8a7d-9e3a3282f5ed.png)

If I hard refresh initially, then the username for the new annotation shows up correctly.
 
*I also was able to reproduce using a regular student level account as user 1 instead of admin.

**Comment by klemay** [comment]
I just wanted to add that this also seems to be causing some wonky behavior in Blackboard when multiple people are annotating a document at once. As [reported in Zendesk](https://hypothesis.zendesk.com/agent/tickets/3744): 

> Basically in the pane at the right with the annotations, it keeps showing them then hiding them sporadically. There isn't enough time to read more than one before they disappear and then reappear. There is a little circle icon at the top of the window that indicates when the annotations are loading - it keeps loading them, removing them, then loading them again. Sometimes they kind of flicker on and off the screen really fast.
