### ISSUE TITLE
Bookmarklet Non-functional Firefox 64 (Linux)

### ISSUE THREAD

**Issue by dixonge** [hypothesis/h#5509]
Just noticed that the bookmarklet is no longer functional. Clicking it results in absolutely no function happening.

**Comment by robertknight** [comment]
What is the URL of the document that you are trying to use the bookmarklet on? There is a known issue where the PDF viewer in Firefox was upgraded recently and the Hypothesis client needs an update to function on the built-in viewer.

**Comment by dixonge** [comment]
It was not a PDF - but the bookmarklet started working again - possibly a javascript issue...

**Comment by dixonge** [comment]
This should have been closed a long time ago
