### ISSUE TITLE
WordPress plugin non-functional 

### ISSUE THREAD

**Issue by dixonge** [hypothesis/h#5510]
Wordpress 4.9.8 - just noticed that hypothes.is is no longer loading on my site. Has your service gone down?

**Comment by robertknight** [comment]
Our service is up. What is the URL of your site?

**Comment by dixonge** [comment]
https://glenn.thedixons.net

**Comment by robertknight** [comment]
I can load the bookmarklet on https://glenn.thedixons.net/ in Firefox 64. Do you mean a particular URL on your site?

**Comment by dixonge** [comment]
It was my understanding (and experience) that the WordPress plugin meant that the Hypothes.is tools would appear on the right side for all visitors sitewide. That is not happening any more.

**Comment by dixonge** [comment]
This should have been closed a long time ago
