### ISSUE TITLE
Make sure that any usages of the builtins ascii, map, filter, hex, oct and zip are Python 3 compliant

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#5515]
Look at usages of `ascii`, `map`, `filter`, `hex`, `oct` and `zip`. These are different in Python 3. Haven't looked into this yet. We may want to use [future_builtins](https://docs.python.org/2/library/future_builtins.html).

**Comment by robertknight** [comment]
I've had a look at these.

- `map` was used only in a couple of places, both of which were unnecessary
- `filter`, `hex` and `oct` builtins were not used (there are other functions called `filter`, but they are not the builtin)
- `zip` is used in one place which explicitly converts the result to a `list`
- `ascii` is a Python 3-only function. I looked at uses of `repr` in case they would be affected by a change in escaping behaviour. They all looked fine.
