### ISSUE TITLE
Convert Python 2 code to Python 2/3 compatible with futurize

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#5519]
Run [`futurize`](http://python-future.org/automatic_conversion.html). This converts Python 2 code to Python 2/3-compatible code.

Note `futurize` will want to add stuff to the `click` CLI modules that probably won't work, we'll have to ignore that.
  
Deploy each of these one at a time:

- [x] Stage 1 ("safe" fixes): `futurize -wn1 h tests`. Of all the changes that stage 1 suggests, I think this is the only one we should / need to make: https://github.com/hypothesis/h/pull/4960
- [x] Add `unicode_literals` to every file that doesn't have it yet: `futurize --unicode-literals -wn1 h tests`. If there are any strings that we actually want to be byte strings we'll need to prefix them with `b` at this stage. Pull request: https://github.com/hypothesis/h/pull/4962
- [ ] Add other future imports to all files: `futurize --all-imports -wn1 h tests`.
- [ ] Stage 2 ("mostly safe" changes): `futurize -wn2 h tests`. I'm not sure that we actually need or want everything that this does, but we should take a look.

**Comment by robertknight** [comment]
I had a look at the "Stage 2" changes. It makes a lot of code modifications which are superfluous given our existing Python 2/3 compatibility shims (in `h/_compat.py`) and the fact that we have a pretty comprehensive set of unit tests for h that have been running under Python 2 + 3 for some time.

On that basis I'm going to recommend we don't apply those changes.
