### ISSUE TITLE
Add all future imports and use flake8-future-import to enforce them

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#5520]
Add `flake8-future-import` to Travis to check that we have all the future imports in every file and that it stays that way. `pip install flake8-future-import` and then run `flake8 --ignore FI12,FI13,FI15,FI16,FI17,FI50,FI51,FI52,FI53,FI54,FI55,FI56,FI57 h tests | ag '__future'`.

`flake8-future-import` can also be used later to check / enforce removal of future imports once we've moved to Python 3.

**Comment by robertknight** [comment]
This is now obsolete as we've moved to Python 3 and there are no remaining references to `__future__` in the code.
