### ISSUE TITLE
Value Error: No JSON object could be decoded

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/h#5543]
https://sentry.io/organizations/hypothesis/issues/896183933

Looks possibly like an issue with the handler for the `PATCH /api/profile` endpoint choking on a missing value for user prefs.

Related to https://github.com/hypothesis/h/issues/5514

**Comment by hmstepanek** [comment]
It looks likes preferences is expected to be a dict here but instead it's an empty string.  I imagine this is a very one-off case as this occurred during the time we were having a db connection incident and all the connections got closed. If we were to try to prevent this from happening in the future we would need to verify preferences along with other keys we expect are the correct type.

**Comment by seanh** [comment]
@lyzadanger @hmstepanek If this looks to be a very one-off thing shall we just close it? Both here and in Sentry

**Comment by hmstepanek** [comment]
I think that's reasonable.
