### ISSUE TITLE
WebSocket HandshakeError: HTTP method must be a GET

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#5607]
https://sentry.io/organizations/hypothesis/issues/847655302/?project=37293&referrer=github_plugin

```
HandshakeError: HTTP method must be a GET
(3 additional frame(s) were not displayed)
...
  File "pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "h/streamer/views.py", line 30, in websocket_view
    return request.get_response(app)
  File "webob/request.py", line 1299, in send
    application, catch_exc_info=False)
  File "webob/request.py", line 1263, in call_application
    app_iter = application(self.environ, start_response)
  File "ws4py/server/wsgiutils.py", line 95, in __call__
    raise HandshakeError('HTTP method must be a GET')
```

**Comment by seanh** [comment]
This error just needs to be silenced in the Python code (don't report it to Sentry). It can be done by broadening the match in this function: https://github.com/hypothesis/h/blob/eeea2a69efb530231c00bc84be754f1d9a63c81f/h/sentry/helpers/filters.py#L22-L31

**Comment by robertknight** [comment]
The issue is no longer available in Sentry and I don't see any reports of this there.
