### ISSUE TITLE
Don't report exceptions to Sentry if the request will be retried by pyramid_tm

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/h#5645]
ConcurrencyErrors inherit from transaction.interfaces.TransientErrror. TransientErrors are retried 2 times in H by pyramid_tm (3 attempts are made). ConcurrencyErrors typically occur when to concurrent write operations race each other to the database. The first request successfully writes the data while the second one fails with an Integrity error, typically due to unique constraints on the db table. 

Currently ConcurrencyErrors are getting reported to Sentry even though the request was reattempted by pyramid_tm and ultimately successful. We would like to not report ConcurrencyErrors unless all retry attempts are exhausted and the request is unsuccessful.

**I think all `TransientError`s (and their subclasses) are being reported when they still have retries left, and none of them should be reported unless the final retry fails** -- seanh

<del>The plan is to implement this using [view-predicates](https://docs.pylonsproject.org/projects/pyramid-retry/en/latest/#view-predicates) once [pyramid_tm has been upgraded](https://github.com/hypothesis/h/issues/5646)</del> I think we just want to call `pyramid_retry.is_last_attempt(event.exception)` from one of our Sentry event filter functions, see <https://github.com/hypothesis/h/pull/5644#issuecomment-503490200> - seanh

See https://github.com/hypothesis/h/issues/5495 for details on ConcurrencyErrors.
See https://github.com/hypothesis/h/pull/5644#issuecomment-503490200 for thoughts on how to implement this <del>using [view-predicates](https://docs.pylonsproject.org/projects/pyramid-retry/en/latest/#view-predicates).</del>

**Comment by seanh** [comment]
Sentry issue: [H-1PF](https://sentry.io/organizations/hypothesis/issues/899979481/?referrer=github_plugin)

**Comment by robertknight** [comment]
Can this be closed following the merge of https://github.com/hypothesis/h/pull/5731?

**Comment by seanh** [comment]
Yes, I believe this is fixed now
