### ISSUE TITLE
nginx rate limiting is kicking in for a class of ~15 students when they all try to signup at once.-need a repro case and then need to modify nginx rate limiting accordingly.

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/h#5652]
Login and registration are endpoints that we probably just shouldn't rate limit. We currently rate limit all other api requests to 1 request per second with a queue of up to a certain amount per user (see nginx config in h). The problem with this is when students are registering all at once in a classroom for example, it thinks they are all the same user because it defaults to rate limiting by ip address. Once they login, then it recognizes them as individual users but they have to get over the hump of registering first.

**Comment by robertknight** [comment]
> The problem with this is when students are registering all at once in a classroom for example, it thinks they are all the same user because it defaults to rate limiting by ip address.

@hmstepanek was there a specific report from a user that this led you to file this issue?

**Comment by hmstepanek** [comment]
Yes a teacher reported it at Iannotate.

**Comment by hmstepanek** [comment]
This is covered by https://github.com/hypothesis/h/issues/5649 so I'm closing this.
