### ISSUE TITLE
Fail to connect extension on new dev server

### ISSUE THREAD

**Issue by baldoarturo** [hypothesis/h#5655]
### Steps to reproduce
1. Spin up dev instance using git clone
2. make services
3. make docker
4. make dev
5. Clone extension repository, tweak settings for the local instance
6. Install extension and login

### Expected behaviour
User should be logged in and annotations should work

### Actual behaviour
Extension tries to connect to a service on port 5001 which i don't see on netstat under the hypothesis services

### Browser/system information
Tell us which browser, browser version, and operating system you were using when
you encountered this issue.

### Additional details
If you have other information which might be helpful, please include it. If a
screenshot will help to illustrate the issue you are reporting, please include
one.

![image](https://user-images.githubusercontent.com/30608412/61242860-21889480-a71d-11e9-9b5d-75e4cc2720d0.png)

**Comment by robertknight** [comment]
The highlighted message shows that the client is connecting to port 5000, not 5001. The relevant error message here is `net::ERR_SSL_PROTOCOL_ERRROR`, which means that the client is trying to establish a secure connection, but the h dev server does not use SSL by default. Try changing `wss://` to `ws://` in the configuration.
