### ISSUE TITLE
Icon missing next to group name on web app

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#5656]
### Steps to reproduce
1. Go to web app (https://hypothes.is/users/dwhly)
2. Open an annotation card

### Expected behaviour
There should be an icon next to the group name

### Actual behaviour
There is no icon, the interface shows "In   Public" (for instance)

### Browser/system information
Chrome

### Additional details
![Screen Shot 2019-07-16 at 7 20 40 AM](https://user-images.githubusercontent.com/1413074/61305816-5984eb80-a7a0-11e9-9315-2291ad5f0f4a.png)

**Comment by robertknight** [comment]
There is an SVG icon there in the DOM tree, but it isn't being rendered. The icon hasn't been changed at all recently, and we haven't done any work on h recently either. This might be a regression due to a dependency update.
