### ISSUE TITLE
make dev failure : /versions/3.6.9/bin/pip: not found

### ISSUE THREAD

**Issue by m0107** [hypothesis/h#5687]
I have installed Pyenv, followed all the steps to download and install it in my Ubuntu Machine.
When I am running cmd: make dev it produces the following error:

./bin/install-python: 31: ./bin/install-python: pyenv: not found
./bin/install-python: 34: ./bin/install-python: pyenv: not found
./bin/install-python: 36: ./bin/install-python: pyenv: not found
./bin/install-python: 36: ./bin/install-python: /versions/3.6.9/bin/pip: not found
Makefile:157: recipe for target 'python' failed
make: *** [python] Error 127

I have checked the file it exists, I am not sure why this error persists.

**Comment by seanh** [comment]
> ./bin/install-python: 31: ./bin/install-python: pyenv: not found

Hi, it looks like `pyenv` isn't installed properly. For example does `pyenv --help` work in your terminal? What about `which pyenv`?

**Comment by m0107** [comment]
Hi, the issue was solved as I installed pyenv as normal user and was using it as root user.

**Comment by robertknight** [comment]
Glad the issue is resolved. Thanks for updating us m0107!
