### ISSUE TITLE
Change how API is represented in documentation

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/h#5696]
This is from feedback from Ghotit, found in ZD here: https://hypothesis.zendesk.com/agent/tickets/5816

API Reference at 
https://h.readthedocs.io/en/latest/api-reference/

In examples for several places Target in Annotation Json at the example right side is shown as a field, whereas the server sends it as an array containing one array element.

**Comment by shawninder** [comment]
I can confirm there is a documentation issue here.

Indeed, endpoints like [`GET /search`](https://h.readthedocs.io/en/latest/api-reference/#tag/annotations/paths/~1search/get), [`POST /annotations`](https://h.readthedocs.io/en/latest/api-reference/#tag/annotations/paths/~1annotations/post) and [`GET /annotations/{id}`](https://h.readthedocs.io/en/latest/api-reference/#tag/annotations/paths/~1annotations~1{id}/get) return annotation objects that have a `target` property of type `array` despite it being documented as `object` both in the Response Schema as well as the Response examples in the documentation for each endpoint.

I have made a PR to attempt to fix this [here](https://github.com/hypothesis/h/pull/7892).

----

@mkdir-washington-edu Can I suggest renaming this issue to be more specific?
Here's a suggestion: "`target` is array but documented as `object` in annotation schema"
