### ISSUE TITLE
Find and remove Python 2-compatibility str() calls

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#5719]
Find and remove `str()` calls that exist for py2 compat, e.g. https://github.com/hypothesis/h/pull/4962/commits/f84bc84f3f281ad6e0471e321606956297e7dae2

**Comment by robertknight** [comment]
All the code that was explicitly called out as being for Python 2 compatibility was removed in https://github.com/hypothesis/h/pull/5729 and https://github.com/hypothesis/h/pull/5733, with the exception of the `text_types` and `string_type` helpers in `h._compat` which are handled in https://github.com/hypothesis/h/pull/5723.
