### ISSUE TITLE
Unable to fetch private annotations using API

### ISSUE THREAD

**Issue by anushaharish538** [hypothesis/h#5840]
I'm using H in my web application. I implemented OAuth and i'm able to login automatically. But i'm unable to retrive annotations of a group and private annotations using API.

**Comment by robertknight** [comment]
Hello.

The API supports retrieving annotations from groups or private annotations. The Hypothesis client relies on this. Can you provide details of how you are interacting with the API, including which credentials you are sending and how you are sending them?

**Comment by anushaharish538** [comment]
Hi @robertknight  Thank you for your resopnse.
I generated token using the following code:
   $CLIENT_SECRET = "ec9817e8-f7e7-11e9-b857-87a33ee076aa";
    $CLIENT_ID = "W0gTvUJii5MrqgsJChUNRIVZ0kttC6HEG4dAXi9US8U";
    $CLIENT_AUTHORITY = "localhost";
    $now = time();

    $payload = array(
        "aud" => "an.htest.com",
        "iss" => $CLIENT_ID,
        "sub" => "acct:$username@$CLIENT_AUTHORITY",
        "nbf" => $now,
        "exp" => $now + (60 * 10),
    );


$gran_token= JWT::encode($payload, $CLIENT_SECRET);
I'm passing this to H client:
<script>
    window.hypothesisConfig = function() {
        return {
            // theme: 'clean',
            openSidebar: false,

            services: [{
                apiUrl: "https://an.htest.com/api/",
                authority: "localhost",
                grantToken: grantToken,

      
        }
    }
</script>

Now the user is getting loggedin automatically.
To Retive annnotations based on group i'm using the following curl API call:
 $group='ZkyYAAg5'; //groupid
    $ch = curl_init();
    $url="https://an.htest.com/api/search?group=".$group;

    curl_setopt($ch, CURLOPT_URL,$url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    $headers = [

        "Authorization: Bearer $$gran_token", //jwt grant token
        "Content-Type: application/json",
    ];

    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $server_output = curl_exec ($ch);
i'm getting total rows:0 but the annotations are avilable

**Comment by robertknight** [comment]
> I generated token using the following code:

I assume you're not using those secrets in production! If so, please change them.

>     "Authorization: Bearer $$gran_token", //jwt grant token

You can't use a JWT grant token directly for API requests. You need to exchange it for an access token using a `POST /api/token` request [as described in step (2) here](https://h.readthedocs.io/en/latest/api/using-oauth/#implementing-oauth-flow). The general flow for using the API is:

1. Authenticate the user. Depending on the kind of OAuth client you are using this will result in either a temporary JWT grant token or a temporary "authorization code"
2. Exchange the temporary token using an access token using the `POST /api/token` endpoint
3. Make requests to the API and include the token in the `Authorization` header via `Authorization: Bearer $ACCESS_TOKEN`

**Comment by robertknight** [comment]
For a concrete example, the Hypothesis client handles authentication in the [oauth-auth service](https://github.com/hypothesis/client/blob/35a73171dfa8c8220cc7c48503700c157726ff71/src/sidebar/services/oauth-auth.js#L170), where the `tokenGetter` function is called by other code whenever the Hypothesis client is about to make an API call and needs a valid access token for the logged-in user.

**Comment by anushaharish538** [comment]
The user is already logged in client means the temporary token is already exchanged. So Is there any way to get token from client?.

**Comment by robertknight** [comment]
No. You shouldn't try to re-use the client's access token. Generate another JWT and exchange that if you want to make API calls from a different context (eg. from your server to h).

**Comment by anushaharish538** [comment]
Ok. @robertknight Thank you.
For the generation of JWT token what grant type of  OAuth client, we need to use?. I used jwt_bearer and client_credentials in H client login.

**Comment by robertknight** [comment]
It depends on the scenario:

If you are trying to integrate Hypothesis with an existing account system and want to automatically log the user into the client, and also perhaps make some API calls on their behalf, then you would use the `jwt_bearer` client in both cases to generate a grant token.

The other type of OAuth client (`authorization_code`) is for when you want to allow a third-party client to interact with your h instance without the user entering their username/password directly into the third-party client. This is similar to when you visit a non-Facebook website and use the "Login with Facebook" button for example.

**Comment by anushaharish538** [comment]
Ok. Thank you. Our scenario is the same as https://github.com/hypothesis/publisher-account-test-site. We are using our web application login. So I need to use authorization_code  grant type but authorization_code grant type does not generate secret code it generates only client id. Secret code is needed for JWT token generation.

**Comment by anushaharish538** [comment]
Hi @robertknight 
https://h.readthedocs.io/en/latest/api/using-oauth/#implementing-oauth-flow
As mentioned here when we call GET /oauth/authorize?client_id=510cd02e-767b-11e7-b34b-ebcff2e51409&redirect_uri=https%3A%2F%2Fmyapp.com%2Fauthorize&response_type=code&state=aa3d3062b4dbe0a1 HTTP/1.1 it should return authorization code but it is returning the redirect url.
The response is :
302 Found
The resource was found at https://an.htest.com/login?next=https%3A%2F%2Fan.htest.com%2Foauth%2Fauthorize%3Fclient_id%3D83e6570c-0c2b-11ea-90f1-ffb3a7a2d3da%26redirect_uri%3Dhttps%3A%2F%2Fan.htest.com%2Fapp.html%26response_type%3Dcode%26state%3D9de9a2dbb8e9fafe&for_oauth=True; you should be redirected automatically. "

**Comment by robertknight** [comment]
>  it should return authorization code but it is returning the redirect url.

The `/oauth/authorize` endpoint is not something you request from a backend server. Rather it is something that you redirect the user's browser to if you have a third-party client that wants to access data of a user of your h instance. The flow in that case is:

1. User loads the third-party client and clicks a "Sign in" button (or similar)
2. The third-party client redirects to the authorize page on the h server, and the h server displays a prompt saying "Do you want to allow <third party app> to access your data in Hypothesis?"
3. If the user approves, the h server redirects _back_ to the third-party client passing an auth code 
4. The third-party app exchanges the auth code for an access token using the `POST /api/token` endpoint

If you are writing a backend app that can generate JWT grant tokens and you want to perform API calls on behalf of a user, you can go to step 4 directly, passing the JWT grant token instead of the auth code.

**Comment by anushaharish538** [comment]
@robertknight Thank you. But for generations of JWT grant token require CLIENT_SECRET  which we will not get when we use "authorization_code" grant type. How do I get   CLIENT_SECRET?

**Comment by robertknight** [comment]
Don't use the `authorization_code` grant type if you want to generate a JWT grant token. Use the `jwt_bearer` type instead.

**Comment by robertknight** [comment]
`authorization_code` OAuth clients and the redirect flow I described above can be used either with a browser-based app (known as a "public client"), which can't keep secrets, or a backend server which can keep a secret. The h server currently assumes you are creating a public client when you use the `authorization_code` grant type, so it doesn't generate a secret. If you were creating a non-public client you could generate your own secret.

In your context though, if you want to generate a JWT grant token, you need to use the `jwt_bearer` type.

**Comment by anushaharish538** [comment]
@robertknight Thank you
Do I need to change anything in the request if I use jwt_bearer grant type except grant_type=jwt_bearer.

POST /api/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

client_id=631206c8-7792-11e7-90b3-872e79925778&code=jwt_token&grant_type=jwt_bearer

I got jwt_token too lengthy like 
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJhbi52ZXJpZmllZHN1cHBseS5jb20iLCJpc3MiOiJrMnROdW1GajFXTXU2VG1ReG........................................................................GxvY2FsaG9zdCIsIm5iZiI6MTU3NDMzOTM1MSwiZXhwIjoxNTc0MzM5OTUxfQ.vZSPi4vU7Ap6oBej4dG0ZkSil8nJSPi-0oqTTJFt8FQ

I used this and called /api/token got
  {"status": "failure", "reason": null} as response.

Is there anything i need to change in request?

Thank you.

**Comment by anushaharish538** [comment]
Adding a secret key also giving the same response.

**Comment by anushaharish538** [comment]
There is no document also. :(

**Comment by anushaharish538** [comment]
@robertknight can you please respond.
Thank you .

**Comment by anushaharish538** [comment]
I fixed it.

**Comment by Goddywu** [comment]
@anushaharish538 

What...how to resolve it? I got the same question ...

here is how I got jwt 👇
![image](https://user-images.githubusercontent.com/29056050/80376064-dca8a580-88cb-11ea-8350-203575f815ac.png)

here is how I exchange my token 👇

![image](https://user-images.githubusercontent.com/29056050/80376178-05309f80-88cc-11ea-880f-371a58de0605.png)

so confused...

**Comment by Goddywu** [comment]
> @anushaharish538
> 
> What...how to resolve it? I got the same question ...
> 
> here is how I got jwt 👇
> ![image](https://user-images.githubusercontent.com/29056050/80376064-dca8a580-88cb-11ea-8350-203575f815ac.png)
> 
> here is how I exchange my token 👇
> 
> ![image](https://user-images.githubusercontent.com/29056050/80376178-05309f80-88cc-11ea-880f-371a58de0605.png)
> 
> so confused...

@robertknight  help...

**Comment by Goddywu** [comment]
> here is how I got jwt 👇



> @anushaharish538
> 
> What...how to resolve it? I got the same question ...
> 
> here is how I got jwt 👇
> ![image](https://user-images.githubusercontent.com/29056050/80376064-dca8a580-88cb-11ea-8350-203575f815ac.png)
> 
> here is how I exchange my token 👇
> 
> ![image](https://user-images.githubusercontent.com/29056050/80376178-05309f80-88cc-11ea-880f-371a58de0605.png)
> 
> so confused...


solved，I have found test code below 👇

![image](https://user-images.githubusercontent.com/29056050/80556747-31047000-8a07-11ea-8520-8370c0fdc760.png)

As a result, get my token finally!

![image](https://user-images.githubusercontent.com/29056050/80556801-5f824b00-8a07-11ea-9da7-782df5db5af5.png)


```
urn:ietf:params:oauth:grant-type:jwt-bearer
```
