### ISSUE TITLE
Cannot select text with iPad or iPhone (Both Chrome and Safari)

### ISSUE THREAD

**Issue by RawKStar77** [hypothesis/h#587]
Apple grabs the text selection event to produce its own context menu. Is there a way around this? People are going to want to annotate using their iPads. 

Other than text selection, everything else seems to work. We can login, read annotations, and even reply. 

This is what happens when text is selected:
![photo](https://f.cloud.github.com/assets/521978/928440/dfa0fba2-ffb6-11e2-97bf-384dda0f830b.PNG)

Could someone with an Android tablet explore whether or not the application works?

**Comment by RawKStar77** [comment]
Closed by https://github.com/hypothesis/h/pull/2137

**Comment by robertknight** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;zvmbTi4a&#x2F;328-spike-suggest-improvements-to-mobile-touch-support"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> [SPIKE] Suggest improvements to mobile&#x2F;touch support</a>

**Comment by robertknight** [comment]
A better fix is coming in https://github.com/hypothesis/h/pull/3347

**Comment by JakeHartnell** [comment]
> A better fix is coming in #3347

:tada:
