### ISSUE TITLE
TAGS: list of tags & two-word tags

### ISSUE THREAD

**Issue by Gahamelas** [hypothesis/h#6113]
1. Is there a way to see all my list of tags?
2. I have two-word tags that are not possible to be searched as the tag:nameoftag only allows one word. Any way to override this behaviour? Thanks.

**Comment by Gahamelas** [comment]
I have found how to search for all my tags in the jonudell.info tool. However, for second question, I don't know.

**Comment by jessedepagter** [comment]
Hi, concerning your second question: I had the same problem today and I think I found a solution. As far as I tried you can basically use most symbols that you usually would not use in tags and that are also not used by the hypothesis search engine as search operators, for instance: \ or - or + or $. So just to give an example, I have a tag that is called "human robot interaction". So let's say I want to search for that I would type: "tag:human\robot\interaction" or "tag:human$robot$interaction" or any of the other symbols (there are probably more, those are the ones I tried). 

Hope this helps

Jesse

**Comment by Gahamelas** [comment]
Thanks, this works great!
