### ISSUE TITLE
Privacy issue with "Only me" annotations.

### ISSUE THREAD

**Issue by nielsthl** [hypothesis/h#6185]
Working with the js plugin in the head section of a webpage:

<b>Update:</b> <p>The "Only me" annotations work fine in the setup below (Old version). The issue appears if Alice and Eve both are members of the group <em>A</em>. Alice, but not Eve, is a member (owner) of another group <em>B</em>.  Suppose they are both annotating the same website simultaneously.</p>
<p>When Alice makes an annotation in <em>B</em> and Eve browses annotations in <em>A</em> in the right menu, the annotation of Alice in <em>B</em> pops up in Eve's right menu. It disappears after browser reload.</p>

![Annotbug](https://user-images.githubusercontent.com/23010769/92450094-4a8aa500-f1bb-11ea-8154-04e860bcdda3.png)

<u>Caption</u>: Both parties are members of the groups <tt>IMO20</tt> and <tt>IMOVIP20</tt>. The right menu is showing Eve (=me) browsing the annotations in the group <tt>IMO20</tt>. The top annotation from Alice (=JensKristianRNielsen) has just been made in another group, not having Eve as a member. Strangely it appears with a blank group.
</p>

<b>Old version:</b>
<p>
Teaching a larger class, one of my teaching assistants found out that "Only me" notes posted under a group are visible in the right menu listing for people logged into the group simultaneously (using reload "red icon" of annotations or "Newest"). They only become invisible after browser reload.

I am only using the js plugin <tt><script async defer src="https://hypothes.is/embed.js"></script></tt> in the header of the webpage.

</b>

**Comment by mkdir-washington-edu** [comment]
https://hypothesis.zendesk.com/agent/tickets/13190

**Comment by klemay** [comment]
Hi @nielsthl, thanks for bringing this to our attention! I can see from your exchange with @mkdir-washington-edu on the support ticket that this does not happen with Only Me annotations. I'm closing this issue in favor of https://github.com/hypothesis/support/issues/137, so we have a more accurate documentation of the issue and so our developers can move it to the appropriate repo when fixing.
