### ISSUE TITLE
Implement a kill switch for the WebSocket feature

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#6190]
During recent problems it's been observed that:

 * ~50% of CPU usage on any given `h` instance was due to the web socket
 * This may have pushed the CPU usage to a point where other requests could not be served
 * The websockets may have been overwhelming the backend Rabbit MQ server

If we are having problems with the websocket, it would be very useful to be able to disable it in such a way as it will no longer consume any resources. This should:

 * Block and unblock quickly
 * Not affect other services (annotation, search etc)
 * Ideally be distinguishable from other failures

## Implementation suggestions

 * An environment variable in AWS config which disables the app
 * Removing all the content of the app / replacing routes with routes that return "429 - Rate limiting"

**Comment by jon-betts** [comment]
Details of using the kill switch are here: https://stackoverflow.com/c/hypothesis/questions/361/362
