### ISSUE TITLE
Implement a kill switch for the badge feature

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#6191]
The badge is the source of a lot of traffic and is a likely source of large scale demand. We can see from New Relic that ~70% of our time is spend on badge calls.

In the event that we are experiencing degraded service it would be useful to be able to temporarily disable the badge end-points to free resources for more critical functions.

Ideally we should be able to:

 * Block and unblock quickly
 * Not affect other services (annotation, search etc)
 * Ideally be distinguishable from other failures

## Implementation ideas

 * Blocking rules in Cloudflare
   * Pros: Very fast to implement, prevents traffic before it even hits our services at all
   * Cons: Not consistent with how we block the websocket
 * An environment variable in AWS config which disables the app
   * Pros: Consistent with how we block the websocket, and could be applied simultaneously
   * Cons: Slower, and means our app still has to serve 400 responses

**Comment by ajpeddakotla** [comment]
found this doc when I was doing some digging - the historical context _may be_ helpful?  https://docs.google.com/document/d/1TqNduRkkjfIVK98QKrWGpJW3eWmPx2ns4XSrHJfBSdE/edit

**Comment by jon-betts** [comment]
There are firewall rules which appear to do exactly what we want. Better yet they can be configured and left "off" so all you have to do is toggle them.

I've created these and written up how to use them here: https://stackoverflow.com/c/hypothesis/questions/364/365#365

I've tested this in QA, but I've not done it in live for obvious reasons. It's very simple though, so it's the sort of thing I'd be happier to fix when we need it than disrupt customers now.

**Comment by ajpeddakotla** [comment]
Closing as work has been completed.
