### ISSUE TITLE
Remove message queue from annotation create critical path

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#6195]
Avoid using the Celery & RabbitMQ stack to add annotations to Elasticsearch. Instead just add them to Elasticsearch directly during Pyramid request processing.

## Feature flag

We should feature flag this so we can test it in QA and prod, and can quickly turn if off again if we notice problems after releasing it.

## Reasons

* It means that RabbitMQ outages are less critical.

  The effects of a RabbitMQ outage with out current system are very bad: annotations get written to Postgres and look to client users like they've been saved successfully (the client receives a successful response from the h API) but they disappear from the client after a reload because they haven't been added to Elasticsearch. We could try to fix that by aborting the Postgres transaction and erroring the API request if writing to RabbitMQ fails. Or we could remove RabbitMQ from the whole process.

  Of course an _Elasticsearch_ outage would still be just as bad. And a Postgres outage even worse. But that's the case currently. Removing RabbitMQ from annotation writing makes a RabbitMQ outage much less bad.

* Removing RabbitMQ makes it much easier to understand how annotations get created. Since Celery and Rabbit are no longer involved in this process. Much easier to follow.

* It _might_ result in fewer failures to add annotations to Elasticsearch. Since the stack involved is simpler, just writing to Es directly in the request rather than writing to a task to a CloudAMQP-hosted queue that then gets consumed by a Celery worker that writes to Es.

  On the other hand it might actually result in more failures. If writing to the CloudAMQP queue is more reliable than writing to Es, and if once written to CloudAMQP a task will be repeatedly retried until it's successfully written to Es, then the current task queue-based system might actually have _fewer_ dropped writes than simply writing to Es directly. This is all pure speculation though, and I think we'd still want to make this change for the other reasons above. We're going to want to [add a regular Elasticsearch syncing task](https://github.com/hypothesis/h/issues/6235) no matter what we do, which will reduce the consequences of Es-writing failures.

## Speed considerations

* Writing to Elasticsearch is very fast so this shouldn't make annotation create API response times too slow:
  * In New Relic Elasticsearch index request response time average is under 20ms and it never peaks above 40ms
  * The current `add_annotation` worker task takes about 30-45ms, and that does a lot of Python and Postgres stuff, not just the Elasticsearch call
  * The annotation create API's response time is currently about 80-140ms, so we have some headroom to add more work to it.
  * We'll also be _removing_ writing to RabbitMQ from this response time. I don't know how long writing to RabbitMQ takes, New Relic doesn't seem to know about RabbitMQ. But we're swapping one thing for another, not just adding a thing
  * We might want to consider what happens when writing to Elasticsearch fails, though. A periodic task will pick up the dropped annotation and index it, so we're not worried about that. But could Es writing fails cause create API requests to be too slow to respond? We might want to use a fairly tight timeout on the Es write requests.

## How does writing annotations work currently with Celery and Rabbit?

[How annotations are added to Elasticsearch currently](https://github.com/hypothesis/h/issues/6194#issuecomment-692099039) (using Celery and RabbitMQ)

## Implementation notes

Given that we're going to be [implementing a sweeper task](https://github.com/hypothesis/h/issues/6235) anyway, I don't think we need to try to strictly ensure that transactions don't get committed if annotations aren't successfully added to Elasticsearch. For example I don't think we should try and abort or roll back the Postgres transaction if adding to Elasticsearch fails.

I _do_ think that we should try to ensure that we _don't_ write to Elasticsearch unless writing to Postgres succeeded, just because that's easy to do: don't try to write to Elasticsearch until after the Postgres transaction has been successfully committed.

Possible approaches:

* Use the `transaction` package's after commit hook: https://transaction.readthedocs.io/en/latest/hooks.html#the-addaftercommithook-method Note that the docs say this is still called if the commit failed, so we may need to check the result of the commit before writing to Elasticsearch

* Use something from [Pyramid's request processing lifecycle](https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/router.html) that executes after [pyramid_tm](https://docs.pylonsproject.org/projects/pyramid_tm/en/latest/)'s tween has committed the transaction. Again, you may need to check whether the transaction was committed successfully. For example h's [`request.notify_after_commit()`](https://github.com/hypothesis/h/blob/3203f3d1f2a43a57c0edfb53c16aef8d91d4cc9e/h/eventqueue.py#L19-L73), which is currently used to add the Elasticsearch writing task to the task queue, is [implemented as a Pyramid response callback](https://github.com/hypothesis/h/blob/3203f3d1f2a43a57c0edfb53c16aef8d91d4cc9e/h/eventqueue.py#L37) so that it executes after tween egress. See the Pyramid docs: https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/hooks.html#using-response-callbacks A `NewResponse` listener or finished callback might also be an option 

## See also

Some Slack threads about this

* https://hypothes-is.slack.com/archives/C4K6M7P5E/p1600090878404000
* https://hypothes-is.slack.com/archives/C4K6M7P5E/p1600097293415400

**Comment by seanh** [comment]
Some Slack threads about this

* https://hypothes-is.slack.com/archives/C4K6M7P5E/p1600090878404000
* https://hypothes-is.slack.com/archives/C4K6M7P5E/p1600097293415400

Given that we're going to be [implementing a sweeper task](https://github.com/hypothesis/h/issues/6235) anyway, I don't think we need to try to strictly ensure that transactions don't get committed if annotations aren't successfully added to Elasticsearch. For example I don't think we should try and abort or roll back the Postgres transaction if adding to Elasticsearch fails.

I _do_ think that we should try to ensure that we _don't_ write to Elasticsearch unless writing to Postgres succeeded, just because that's easy to do: don't try to write to Elasticsearch until after the Postgres transaction has been successfully committed.

Possible approaches:

* Use the `transaction` package's after commit hook: https://transaction.readthedocs.io/en/latest/hooks.html#the-addaftercommithook-method Note that the docs say this is still called if the commit failed, so we may need to check the result of the commit before writing to Elasticsearch

* Use something from [Pyramid's request processing lifecycle](https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/router.html) that executes after [pyramid_tm](https://docs.pylonsproject.org/projects/pyramid_tm/en/latest/)'s tween has committed the transaction. Again, you may need to check whether the transaction was committed successfully. For example h's [`request.notify_after_commit()`](https://github.com/hypothesis/h/blob/3203f3d1f2a43a57c0edfb53c16aef8d91d4cc9e/h/eventqueue.py#L19-L73), which is currently used to add the Elasticsearch writing task to the task queue, is [implemented as a Pyramid response callback](https://github.com/hypothesis/h/blob/3203f3d1f2a43a57c0edfb53c16aef8d91d4cc9e/h/eventqueue.py#L37) so that it executes after tween egress.

**Comment by seanh** [comment]
Todo:

- [ ] Fix sending of reply notification emails. We think these can cause the create annotation API to fail currently if Rabbit is down
- [ ] Remove feature flag

**Comment by jon-betts** [comment]
Feature flag has now been removed
