### ISSUE TITLE
Implement V2 of Highlighting Mode

### ISSUE THREAD

**Issue by csillag** [hypothesis/h#622]
Specs is [here](https://docs.google.com/document/d/1QSKY_Lc5et4F0pwu0d4AttxIME_E4rjaCHzuwQIgiyc/edit), with some clarifications [here](https://docs.google.com/document/d/1kRVMVI1Pt2YdlDMfT3WESxa3rL7YqZj0xsHHG23GhHU/edit).

V1 was implemented by #530.

**Comment by RawKStar77** [comment]
No discussion in years and much has recently changed in the way highlight mode works. We should open new issues for whatever we decide constitutes "V2" highlights. Mostly options to change color, delete, etc.

Closing.

**Comment by tilgovi** [comment]
\o/ thanks, @RawKStar77
