### ISSUE TITLE
Add a "sweeper" task for adding annotations to  Elasticsearch

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#6235]
Add a regularly-scheduled Celery task that runs once every N minutes (N to be decided), finds annotations in Postgres that weren't successfully added to Elasticsearch, and adds them.

There are three separate cases to handle:

- [x] A new annotation was added to Postgres but not added to Elasticsearch
- [x] An existing annotation was updated in Postgres but not updated in Elasticsearch
- [x] An existing annotation was deleted from Postgres but not deleted from Elasticsearch

(These may actually be handled by separate tasks. For example syncing deletes can probably run much less frequently)

- [ ] We should add a Dead Man's Snitch alarm to ensure that the task is running

**Comment by seanh** [comment]
Some Slack threads about running periodic tasks on h:

* https://hypothes-is.slack.com/archives/C4K6M7P5E/p1600158831427900
* https://hypothes-is.slack.com/archives/C4K6M7P5E/p1600181087459700

We should be able to add a periodic Celery task to [h-periodic](https://github.com/hypothesis/h-periodic) pretty easily.

Some Slack threads about the sweeper task design:

* https://hypothes-is.slack.com/archives/C4K6M7P5E/p1600084957385900
* https://hypothes-is.slack.com/archives/C4K6M7P5E/p1600177542456100?thread_ts=1600176747.453700&cid=C4K6M7P5E

**Comment by robertknight** [comment]
@seanh - My understanding from the presentation you gave recently is that this task is done. Is there anything more to do here?

**Comment by seanh** [comment]
It's not done yet -- we still need to create alarms in New Relic based on the metrics we have. I'm letting the metrics gather for another week first.

**Comment by seanh** [comment]
There's still only one thing I want to do to finish this off: set alarms. But I think we need to wait until we've disabled periodic jobs for h-qa (this PR should do it: https://github.com/hypothesis/h-periodic/pull/54) and then let the dashboard collect data for another week to know how to tune the alarms

**Comment by seanh** [comment]
I've created a separate issue for the alarms: https://github.com/hypothesis/h/issues/6454 Closing this one
