### ISSUE TITLE
Healthcheck endpoint (/_status) does not account for WebSocket or worker processes

### ISSUE THREAD

**Issue by robertknight** [hypothesis/h#6274]
Last week we had an issue where a change was deployed to QA which caused the "worker" process to crash on startup. See discussion at https://hypothes-is.slack.com/archives/C074BUPEG/p1600791664024100 and https://github.com/hypothesis/h/pull/6255 for the fix. Since the "web" process was running normally, healthchecks completed successfully and Elastic Beanstalk did not detect that the instance was not functioning properly.

I think it would be a good idea if h's healthcheck endpoint could somehow verify that the websocket and worker processes were running and had completed initialization.

**Comment by indigobravo** [comment]
If we can do this and change the value of the status endpoint response from: {"status": "okay"}  to something like {"status": "worker_failure"} or some other error code we can look up. Then NewRelic can be setup to specifically look for that and alert us to the failure.

**Comment by robertknight** [comment]
Related Slack thread: https://hypothes-is.slack.com/archives/CR3E3S7K8/p1602728100179900

**Comment by jon-betts** [comment]
Fixed in:

 * https://github.com/hypothesis/h/pull/7018

For:

 * https://github.com/hypothesis/playbook/issues/703
