### ISSUE TITLE
Re-use RabbitMQ connections (Invalid: we already do)

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#6281]
I think h may be making a new RabbitMQ connection for every request. Verify this and if it is, fix it to reuse a pool of connections instead.

See https://stackoverflow.com/questions/62513766/connection-pool-to-external-services-redis-in-pyramid

**Comment by jon-betts** [comment]
I'm fairly certain this isn't actually true. I we seeing connections made every time, but then again I was killing Rabbit during this. There's no way it could maintain and re-use a connection in this scenario.

We should still convince ourselves anyway... A simple way to rule this in (but not out) would be to print the id of the object. If we get the same one we're sharing. If we don't, we need to investigate more.

**Comment by jon-betts** [comment]
Yep, simple ID check showed it. We seem to re-use them between requests already!
