### ISSUE TITLE
h + client: Can't log in

### ISSUE THREAD

**Issue by tgiardina** [hypothesis/h#6444]
#### In terminal 1
```
git pull git@github.com:hypothesis/h.git
cd h
make services
tox -qe dev -- sh bin/hypothesis --dev user add
# You will be prompted to set a username, email, and password here
tox -qe dev -- sh bin/hypothesis --dev user admin <username>
make dev
```
#### In a browser
navigate to `localhost:5000` and perform the in-browser steps described [here](https://h.readthedocs.io/en/latest/developing/integrating-client/).

#### In terminal 1
Kill the currently running `make dev` and then restart it with the appropriate env variables:
```
export CLIENT_OAUTH_ID=<CLIENT_ID> # E.g., a7794356-4ed7-11eb-9d25-f7d81cbd88c8
export CLIENT_URL=http://localhost:3001/hypothesis
make dev
```

#### In terminal 2:
```
git pull git@github.com:hypothesis/client.git
cd client
make dev
```
#### In a browser
Navigate to `localhost:3000`, click 'login', and enter your credentials.

### Expected behaviour
I should be able to log in.

### Actual behaviour
Nothing happens.

### Browser/system information
- Ubuntu 20.04
- Firefox 84.0 for Ubuntu canonical - 1.0

### Additional details
I can hack together a temporary fix by editing two files: `/h/h/util/uri.py` and `h/static/scripts/post-auth.js`.

In `uri.py`, change the line 
```url = template.replace("{current_host}", parsed.hostname)```
 to 
 ```url = template.replace("{current_host}", "localhost")```

 In `post-auth.js` change the line
 ```
 window.opener.postMessage(msg, settings.origin);
 ```
 to
 ```window.opener.postMessage(msg, "*");```

**Comment by leedenison** [comment]
Please reopen if this continues to be an issue.
