### ISSUE TITLE
Upgrade to Python 3.8

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/h#6600]
For: https://github.com/hypothesis/product-backlog/issues/1199

Our dependencies:

 * [x] `h-api` - https://github.com/hypothesis/h-api/issues/6

Some specific deps for `h`:

* [x] `ws4py` - 3.5 - Needs fixes to work post 3.6: https://github.com/hypothesis/h-ws4py/pull/2 (This works locally... so ok?)
* [x] `pyramid_layout` - 3.3 Tests locally to 3.9: https://github.com/Pylons/pyramid_layout/pull/36
* [x] `itsdangerous` - 3.7 - Py 3.9 listed in master. Tests locally to 3.9 on released version 1.1.0
* [x] `mistune` - 3.7 - Tests locally to 3.9. 3.8 listed in master
* [x] `psycogreen` - 3? I'm not really sure with this one. It doesn't seem to have tests in the conventional style. Apparently it supports all Python https://github.com/psycopg/psycogreen/issues/1 - Not super convinved. Very small codebase though (This works locally... so ok?)
* [x] `pyramid-mailer` - 3.4 - Tested to 3.9 locally and PR submitted: https://github.com/Pylons/pyramid_mailer/pull/96
* [x] `python-slugify` - 3.7 - PR in to add tox and 3.9 support: https://github.com/un33k/python-slugify/pull/98 (Accepted woo!)

Extra credit for the docs:

* [x] `sphinx-rtd-theme` - 3.6 - This has undeclared 3.9 support in the tests: https://github.com/readthedocs/sphinx_rtd_theme/blob/0.5.2/tox.ini

The dependencies will likely need to be re-analysed as other projects should hopefully fix some of this before we are get here.

![app_h](https://user-images.githubusercontent.com/7131143/116445703-13eac300-a84e-11eb-8332-7562976a108f.png)

**Comment by jon-betts** [comment]
From what I can see the websocket works absolutely fine, which is a little good news / a little terrifying, as I can see code in `ws4py` which definitely isn't Python 3.8 compatible.

My guess is we just happen to swerve around it, which is "good" news I suppose, as we could not bother forking it etc. But it's also a little disturbing.

**Comment by jon-betts** [comment]
Yep, we don't use the affected part of the code, which is `ws4py.async_websocket`. We use `ws4py.websocket`. So this is _sort of_ ok to carry on using without forking etc?

**Comment by jon-betts** [comment]
For now I think we're going to note that both `ws4py` and `psycogreen` are pretty dodgy looking as dependencies, but seem to work for the moment. 

This means the next time we come to upgrade Python:

 * We should re-evaluate those from scratch again
 * We might want to think about replacing this / having already done this

**Comment by jon-betts** [comment]
Done!

**Comment by dwhly** [comment]
Noice!
