### ISSUE TITLE
Document Media Types

### ISSUE THREAD

**Issue by CxRes** [hypothesis/h#6825]
Please document media types when making `GET` request with Hypothesis API, say using `search/`

In particular do you support anything other than:
`application/json`
`application/vnd.hypothesis.v1+json`
`application/vnd.hypothesis.v2+json`

i.e. Can hypothesis respond in any other format than json?

**Comment by robertknight** [comment]
> i.e. Can hypothesis respond in any other format than json?

The API only supports JSON format output. There is also something similar to the `https://hypothes.is/api/search` endpoint that returns RSS at https://hypothes.is/stream.rss and one that returns Atom at https://hypothes.is/stream.atom.

**Comment by CxRes** [comment]
Thanks! I read something about JSON-LD? Is the Hypothesis JSON format otherwise documented somewhere?

**Comment by robertknight** [comment]
There is documentation on the JSON response format here: https://h.readthedocs.io/en/latest/api-reference/#tag/annotations/paths/~1annotations~1{id}/get. The Hypothesis client has more details on some of the fields in its [type definitions for the Hypothesis API](https://github.com/hypothesis/client/blob/master/src/types/api.js).

**Comment by CxRes** [comment]
Thanks!!! Please consider documenting these in the Readme or somewhere more central.
