### ISSUE TITLE
Run the functests in a different order on CI

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#6883]
This could be important now that we no longer reset the DB between tests.

Can we use a pytest option? Or plugin?

Run them in reverse order? Or in a random order (but the order must *not* change if the same commit is re-run)?

**Comment by jon-betts** [comment]
From https://pypi.org/project/pytest-reverse/

> I’m the creator and maintainer of pytest-randomly, a plugin for randomly ordering tests. @thbde opened an issue there pointing to the paper Empirically revisiting the test independence assumption, which covers test reordering techniques. It turns out that reversal is nearly as effective as randomization.
