### ISSUE TITLE
All /api links are in HTTP scheme, not following reverse-proxified HTTPS.

### ISSUE THREAD

**Issue by fishfree** [hypothesis/h#6969]
I set a reverse proxy in Nginx for http://localhost:5000 of Hypothesis H, so now the public URL is https://*** (and automatically redirect all HTTP to HTTPS). But the response from https://***/api/links are all in the scheme of HTTP, which leads Mixed content error and not working.
![image](https://user-images.githubusercontent.com/1741341/129661926-b0d77cff-123e-44fe-9204-667c0e0eb720.png)

**Comment by robertknight** [comment]
For situations where h is running behind a reverse proxy, h respects the `X-Forwarded-Port` and `X-Forwarded-Proto` headers when generating URLs. Typically `X-Forwarded-Port` would be 443 and `X-Forwarded-Proto` would be `https`. This allows h to know that it is being connected to via HTTPS even if h itself is running over HTTP.

**Comment by fishfree** [comment]
@robertknight Thank you! It works now.
