### ISSUE TITLE
CLI authclient lacks some functionality of admin/oauthclient/new web view

### ISSUE THREAD

**Issue by bpow** [hypothesis/h#7009]
### Steps to reproduce
1. Generate an OAuth client record in the [web UI](http://localhost:5000/admin/oauthclients/new). You will have options for Name, Authority, Grant Type, Trusted and Redirect URL
2. Now try to make the same record with `bin/hypothesis authclient add`...

### Expected behaviour
I would like to have all of the same options as are available in the web UI.

### Actual behaviour
`h/cli/commands/authclient.py` function `add` only takes parameters for name, authority, and type ('public' or 'confidential'). There is no way from this command to set the grant_type, response_type, redirect_uri, or trusted fields.

### Browser/system information
This is browser/system independent, but for completeness: Firefox 91.0.2 on Ubuntu 21.04 with dev instance running in docker.

### Additional details
I know this probably doesn't come up for the main hyp.is developers, because they use `devdata` to populate auth ids into dev instances. But those of us outside of hyp.is do not have access to `devdata` (and the CLI devdata command is hard-coded to use that one git repo, so we could not even make our own equivalent json and use it even if the contents of the devdata repo were documented).

So allowing developer users to create authclient records without firing up their web browsers would be helpful for external integration testing and such, or even setting up production servers consistently.

**Comment by seanh** [comment]
This was done in https://github.com/hypothesis/h/pull/7965
