### ISSUE TITLE
indicate offline mode

### ISSUE THREAD

**Issue by csillag** [hypothesis/h#703]
Usually, our pages are live: the updates are delivered to the sidebar, the displayer pages and the stream pages.

However, on connection failures, this process is obviously disrupted.

In these cases, we should indicate that we are in offline state.

I think what (for example) gmail does in this regard makes perfect sense: show a small (bug highly visible) note, some countdown to next connection attempt, etc.

We should imitate that.

**Comment by nickstenning** [comment]
Closing as a feature that will come down the product prio and design pipeline.
