### ISSUE TITLE
Remove the Websocket from the main "web" docker image

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/h#7089]
The websocket was separated out to run in it's own docker image in: https://github.com/hypothesis/playbook/issues/703

This seems to have worked, and we probably don't need the websocket in the main image any more. We should:

* :x: Check that we aren't using this anywhere (for example the Canada deployments) - **This is in use in Canada!**
* [ ] https://github.com/hypothesis/h/pull/7108
* [ ] https://github.com/hypothesis/h/pull/7109

### How much resource to the idle process take up?

These are the figures from `top` on a random machine:

```
 PID  USER     PR   NI VIRT    RES     SHR  S  %CPU %MEM     TIME+ COMMAND         
4818 102       20   0  103512  95416   7816 S   0.3  1.2   6:37.54 pserve 
4820 102       20   0  102888  94776   7828 S   0.0  1.2   6:35.03 pserve
```

So they look like they might be consuming 2.4% (~200Mb) of RAM between them and a trickle of CPU now and again. So not much. But also some.

**Comment by leedenison** [comment]
Obsolete.
