### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#722]
Provide initial support for keyboard shortcuts.  

As proposed by @aculich:

Keyboard shortcuts!!!! This is the single most important 
  improvement for me! I would like to be able to select paragraphs 
  using simple key combinations as listed here: 

  "+ j"  select next paragraph (deselect current if selected) 
  "+ k"  select previous paragraph (deselect current if selected) 
  "+ l"  in selected paragraph, deselect whole paragraph and instead 
       select the current sentence; pressing 'l' again will then 
       cycle through each sentence in turn. After reaching the last 
       sentence, return to full-paragraph selection and start cycle 
       over again. 
  "+ ;"  annotate the selected text 
  "+ h" make selection "sticky" which means, for example, if I hit 'h' 
       and then hit 'jjj' it will select three paragraphs (or 
       sentences if in that mode), instead of the default for 'j' which 
       is to deselect the currently selected paragraph and then select 
       the next paragraph.

**Comment by JakeHartnell** [comment]
No discussion in almost 2 years.

I think keyboard short cuts will likely come up again in different contexts, but having a big blanket issue for them doesn't strike me as super helpful. So in the name of reducing clutter, closing unless someone objects...

**Comment by aculich** [comment]
Indeed... makes sense to close this... and will only re-open it again later if I've got a pull-request to contribute. :)

**Comment by JakeHartnell** [comment]
Thanks @aculich! : )
