### ISSUE TITLE
Use conneg for REST API Versioning

### ISSUE THREAD

**Issue by tilgovi** [hypothesis/h#733]
We should use content negotiation and vendor mime types to version our APIs so that we can easily make backward-compatible advances on the server.

This supersedes #727, which was closed with a temporary fix.

**Comment by BigBlueHat** [comment]
:+1: :wink:

**Comment by nickstenning** [comment]
I'm going to close this. We may at some point (and maybe even some point soon) decide we need to start versioning our API. But when we do I reckon we should have a sit down to work out our options.
