### ISSUE TITLE
search_after isn't applied with user query parameter for search annotations api

### ISSUE THREAD

**Issue by sartoshi-foot-dao** [hypothesis/h#7337]
### Steps to reproduce
1. Request endpoint with relevant auth headers: `https://hypothes.is/api/search?order=desc&sort=updated&search_after=1648035950905&user=${userId}`. Response simply contains 20 latest annotations, without search_after filter. Same outcome if using ISO string.
2. Request endpoint without `user` parameter: `https://hypothes.is/api/search?order=desc&sort=updated&search_after=1648035950905`. Response correctly shows the 20 (global) annotations after `search_after` date.

### Expected behaviour
To receive only the 20 annotations updated after `search_after` for a given user.

### Actual behaviour
Received 20 latest-updated annotations for given user, as if `search-after` failed to apply.

### Browser/system information
Firefox Dev Ed (64-bit) 99.0b6
macOS Big Sur 11.6.5

**Comment by robertknight** [comment]
I got the expected result when I did a quick unauthenticated test searching my public annotations:

```shellsession
$ curl -s 'https://hypothes.is/api/search?order=desc&sort=updated&search_after=2021-01-01T00:00:00&user=acct:robertknight@hypothes.is&limit=5'  | jq '.rows[].updated'
"2020-12-19T21:55:55.658155+00:00"
"2020-12-15T09:27:28.587834+00:00"
"2020-08-18T15:18:12.279709+00:00"
"2020-06-12T14:26:42.358490+00:00"
"2020-05-09T20:39:33.356041+00:00"
$ curl -s 'https://hypothes.is/api/search?order=desc&sort=updated&search_after=2020-01-01T00:00:00&user=acct:robertknight@hypothes.is&limit=5'  | jq '.rows[].updated'
"2019-11-06T17:03:12.549342+00:00"
"2019-11-06T17:02:42.287168+00:00"
"2019-11-06T17:00:51.171395+00:00"
"2019-11-01T12:13:15.027970+00:00"
"2019-10-31T23:47:26.989581+00:00"
```


If using ISO dates which contain a timezone specifier (`+`), make sure you URL-encode the value properly (`encodeURIComponent` in JS).

**Comment by sartoshi-foot-dao** [comment]
Hi Robert, I really appreciate your quick response. I'll test a bit more and report back.

**Comment by sartoshi-foot-dao** [comment]
Hi Robert, thanks for your examples; I see where I went wrong.

If anyone else is running into trouble trying to obtain their latest annotations, see if my solution below helps:

search params
`order:desc`
`sort: updated`
`limit:5`
`search_after:2022-03-22T00:00:00` (unix/epoch time works fine too)

While we might intuitively expect to see 'annotations after 22/03/22' for the query `search_after:2022-03-22T00:00:00`&`order:desc` (the default order), what's actually returned are annotations after `2022-03-22T00:00:00`'s index *in the return object*, not chronologically. Use `order:asc` (which will order your latest annotations last i.e. after everything) with `search_after` for 'annotations after X'.

# Example
`order:desc`
[0]: "2022-03-24T21:55:55.658155+00:00"
[1]: "2022-03-23T21:55:55.658155+00:00"
[2]: "2022-03-22T21:55:55.658155+00:00"
[3]: "2022-03-21T21:55:55.658155+00:00"
[4]: "2022-03-20T21:55:55.658155+00:00"

`search_after:2022-03-22T21:55:55.658155+00:00` will return items 3, 4 etc.

`order:asc` would flip the order.
 
# Reference
Quoting from the search section of the [docs](https://h.readthedocs.io/en/latest/api-reference/#tag/annotations/paths/~1search/get): 
`The returned subset of search results will begin with the first annotation whose sort field's value comes after the value of search_after sequentially.`
