### ISSUE TITLE
Hypothes.is Flavored Markdown

### ISSUE THREAD

**Issue by csillag** [hypothesis/h#763]
As we all know, GitHub is using a special version of MarkDown, called [GitHub Flavored Markdown] (http://github.github.com/github-flavored-markdown/). The main feature is that they auto-generate links for various items. (Like issues, PRs, users, commits, GitHub projects, etc.)

I think we should implement our own *Hypothes.is Flavored Markdown*, which should be used when rendering annotation bodies and other texts.

Proposed specification:

* @username should be rendered as link to user profile (see #128)
* #tag should be rendered as links to tag stream
* $id should be rendered as a link to an annotation (question: what should be the displayed text of the link?)
* $$id should be rendered as an embedded annotation (see #141)

Furthermore, we should recognize cases when the user has placed the actual links (to user profiles, tag streams or annotations) in the source text, and change the rendered text to the short form.

Also-- when a username is mentioned, it should be notified.  This is what #580 referred to.

**Comment by nickstenning** [comment]
This is an expansive issue and I think we're better off discussing specific enhancements we want to make to our markup format. Closing.
