### ISSUE TITLE
Support the latest version of Elasticsearch in h

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#7640]
h is currently using Elasticsearch 6.2.

6.2 is already end-of-life'd by elastic.co but is still supported by Amazon OpenSearch (which is what we actually use in production) who haven't announced an end-of-life. When they do announce an EOL we expect them to give plenty of warning.

6.2 is a time-consuming pain to boot up on Apple Silicon developer machines.

This ticket is to make sure that h works with the latest version of Elasticsearch that is supported by Amazon OpenSearch, fix any issues necessary to get it working, and provide a PR to upgrade the development environment (though we may not choose to merge that PR yet). Actually upgrading our production Elasticsearch will then be handled separately.

This work will hopefully provide an easy way for Apple Silicon developers to get h working with a newer Elasticsearch in development.

See also: https://github.com/hypothesis/bouncer/issues/563

**Comment by nairiboo** [comment]
https://github.com/hypothesis/product-backlog/issues/1463
