### ISSUE TITLE
Privately Hosted Hypothesis Server

### ISSUE THREAD

**Issue by cadojo** [hypothesis/h#7653]
First off, I think the Slack [invite](https://hypothesis-open.slack.com/join/shared_invite/enQtMzAxMTEwODAwMTgxLTk5NzM0YmZlNTk0YjgwZmU4NDVhZDYwNTY2MWZhNzk1ODY2ZjdhNmE0YTI5MmZkMzcwMmRhNzI4YmViYjE1MjA#/shared-invite/error) link has expired!

Does Hypothesis support completely private documents, comments, etc? If I have a privately hosted website that isn't on the broader internet for a company, can I host a private Hypothesis server without any API calls to a public computer?

I've searched the documentation but couldn't figure this out! Sorry if I've missed something.

**Comment by robertknight** [comment]
> Does Hypothesis support completely private documents, comments, etc? If I have a privately hosted website that isn't on the broader internet for a company, can I host a private Hypothesis server without any API calls to a public computer?

Yes. If you host Hypothesis yourself, it does not rely on external services. There are some optional features (eg. New Relic integration) that we use in production which talk to public services, but these will be off if you don't configure them.

**Comment by robertknight** [comment]
For Slack, try this link: https://join.slack.com/t/hypothesis-open/shared_invite/zt-1k5je7i7p-a1~SiSRwUXmKkFq0U2ALOQ

**Comment by leedenison** [comment]
I'm closing this issue assuming the response from @robertknight helped.  Please reopen if needed.
