### ISSUE TITLE
Activity Page search shows same results on page 50 and higher

### ISSUE THREAD

**Issue by mattdricker** [hypothesis/h#7723]
## Bug report form
Reported by user: https://app.hubspot.com/contacts/6291320/ticket/925726335
### Steps to reproduce

1. Perform a search that generates more that 50 pages of results, such as an unfiltered search in the public group: https://hypothes.is/search
2. Jump to page 50: https://hypothes.is/search?page=50
3. Visit page 51, 52, 53, etc., and compare the results of each page

<img width="995" alt="Screen Shot 2022-06-10 at 1 59 48 PM" src="https://user-images.githubusercontent.com/71603629/173124888-60f19c8f-f391-48d2-b206-e6d2ab64790e.png">
<img width="995" alt="Screen Shot 2022-06-10 at 2 00 00 PM" src="https://user-images.githubusercontent.com/71603629/173124892-d31e1a7e-cb3c-4dc1-a22c-27949cc56b01.png">
<img width="995" alt="Screen Shot 2022-06-10 at 2 00 31 PM" src="https://user-images.githubusercontent.com/71603629/173124891-9ea43b4a-4f1f-4353-b27c-a1c8ad727e4d.png">

### Expected behavior
Each page past 50 should show additional unique results.

### Actual behaviour
Every page from 50+ on displays the same list of results.

**Comment by jon-betts** [comment]
I think the conclusion was that activity pages isn't being actively developed any more. It will be replaced with Project Notebook. It's extremely unlikely whatever is causing this to happen would be replicated there, and if by some chance it was, it would be a different bug anyway.
