### ISSUE TITLE
Page with rel="canonical" href(unknown) incorrectly equates document

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/h#7725]
**Describe the bug**
A user found a page that uses rel="canonical" but doesn't specify a URL. It seems like Hypothesis performs document equivalence but with a poor choice of page.

https://hypothesis.zendesk.com/agent/tickets/14720

The page is: https://ieeexplore.ieee.org/document/9152704
The HTML is:
![image](https://user-images.githubusercontent.com/22603275/96619108-c22c1380-12d3-11eb-84e0-3750bf61e631.png)
Hypothesis points to:
https://ieeexplore.ieee.org/document/

**To Reproduce**
1. Go to https://ieeexplore.ieee.org/document/9152704
2. Create an annotation
3. See that the share link for the annotation contains .../ieeexplore.ieee.org/document/

**Expected behavior**
The annotation share link is for /9152704

---

## Ideas

Determine what to do if rel="canonical" is used without pointing to a URL. When a site doesn't specify a URL in rel="canonical" we probably shouldn't perform document equivalence.

**Comment by darylhedley** [comment]
Closed due to not able to reproduce
