### ISSUE TITLE
how to stop service with shell

### ISSUE THREAD

**Issue by nanfeng-taku** [hypothesis/h#7751]
I want to use the shell command to restart the service regularly, but I don't know how to stop it

**Comment by robertknight** [comment]
> I want to use the shell command to restart the service regularly, but I don't know how to stop it

In development, you can just stop the `make dev` command by pressing Ctrl+C. In production, the service runs as a Docker container, so you can use the standard Docker commands to stop the container (`docker stop <container ID>`). If using a cloud service that handles launching the container, that might have its own APIs to stop/restart containers.

What are you trying to achieve by restarting the service though?

**Comment by nanfeng-taku** [comment]
> > I want to use the shell command to restart the service regularly, but I don't know how to stop it
> 
> In development, you can just stop the `make dev` command by pressing Ctrl+C. In production, the service runs as a Docker container, so you can use the standard Docker commands to stop the container (`docker stop <container ID>`). If using a cloud service that handles launching the container, that might have its own APIs to stop/restart containers.
> 
> What are you trying to achieve by restarting the service though?

Thank you for your answer. It helped me a lot. Then I can close the Docker to achieve my goal.

I don't know why. My h can't always be woken up on the page, so I plan to restart the service regularly.

I don't understand this at all, so this problem is caused. Thanks again
