### ISSUE TITLE
'Cancel' doesn't cancel on https://hypothes.is/account/settings

### ISSUE THREAD

**Issue by earcanal** [hypothesis/h#7832]
https://hypothes.is/account/settings

Expected: Cancel link leaves page
Actual: Cancel link doesn't leave page. No in page way to do this.

**Comment by robertknight** [comment]
What happens when you click "Cancel" and what browser/version are you using? The expected behavior is that the Cancel/Save links go away and the other elements of the page become fully opaque again.

**Comment by earcanal** [comment]
Clicking "Cancel" returns to the same page in the same state.
Browser: Chrome/Firefox (suspect any version).

Resolved by disabling password manager extension.

**Comment by robertknight** [comment]
> Resolved by disabling password manager extension.

Which extension were you using? It would be useful to know in case someone else runs into this.
