### ISSUE TITLE
Reduce h's dependence on Elasticsearch

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#7975]
We think h could use Postgres for a lot of what it currently uses Elasticsearch for, making Elasticsearch a less crucial dependency, meaning that Hypothesis developers need less Elasticsearch knowledge, and making h simpler overall.

See also: https://github.com/hypothesis/bouncer/issues/645

**Comment by mpr1255** [comment]
The tantivy plugin (basically https://github.com/paradedb) could be interesting in that regard. Brings very powerful full text search to postgres.
