### ISSUE TITLE
Special behavior for selected annotations

### ISSUE THREAD

**Issue by csillag** [hypothesis/h#800]
A focused annotation is something we are currently looking at.

More exact definition: a focused annotation is an annotation (or highlight) that is
 * currently displayed in the sidebar, and
 * has it's annotation card opened (not collapsed)

  * * *

V1 features:

We can focus on annotations using one of the following ways:
 * From the document:
   - [x] Clicking on the highlight. (Currently, this does not yet open the annotation card, but I think it should.)
  - [x] Clicking on a tab on a heatmap, which has only one annotation. (Same as above.)
  - [x] Newly created annotations should be immediately focused
 * From the sidebar
   - [x] Opening the annotation card, by clicking on it

We can un-focus annotations by
 - [x] Collapsing the annotation card
 - [x] Removing the from the sidebar by switching the view
 - [x] Scrolling away, if in dynamic mode

Behavior:
 - [x] When we are focusing on an annotation, then we scroll the document to it. (Already implemented for #787)
 - [x] While the annotation is focused, it's highlight in the document is always visible. (Even when not in always-on mode.)

  * * *

V2 features:

 * An annotation can also be focused by arriving to the document by following a source link, which specifically references an annotation. (See #769)

**Update: The list of conditions have been updated**

**Comment by csillag** [comment]
It looks like we have lost this ability along the way. (The "focused state" didn't survive one of the refactorings of the viewer code.)

I want to reimplement at least a part of it, because I need it for direct linking (#769).
So, reopening.

**Comment by tilgovi** [comment]
Sorry... what is meant by focused?

**Comment by csillag** [comment]
Basically, it's "something we are currently looking at".

See the OP for details on what triggers (or used to trigger) the focused state, and what behavior it has (used to have).

The most crucial detail for my current use-case is this:

> While the annotation is focused, it's highlight in the document is always visible. (Even when not in always-on mode.)

**Comment by tilgovi** [comment]
I'm not going to tell you what you should or shouldn't do, but I would _suggest_ ignoring this issue for your initial implementation. If you can even just pass the right information between the components that would be pretty great.

**Comment by csillag** [comment]
Yes, in the first round, I simply plan to fall back to scrolling to the annotation.

But having the highlight visible in the document would be really neat, IMO.

**Comment by csillag** [comment]
Since our nomenclature has been clarified and changed since this issue was created, I changed the title from "focused annotations" to "selected annotations".

**Comment by judell** [comment]
If I understand this, we do what's asked now. Close?
