### ISSUE TITLE
Change username (web app)

### ISSUE THREAD

**Issue by jeremydean** [hypothesis/h#8064]
Over the past year, these support tickets were the highest volume:

Delete account = 17%	
Change username =3%

We should consider allowing users to do these things themselves.

**Comment by jeremydean** [comment]
merged with [#1476](https://github.com/orgs/hypothesis/projects/51/views/34?pane=issue&itemId=29777273)

**Comment by robertknight** [comment]
Duplicate of https://github.com/hypothesis/h/issues/8330.
