### ISSUE TITLE
Lenses

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#813]
Borrowing the term lens from the lens.elifesciences.org project.

We might want to:
- Make citations in scientific papers clickable, so that they take you to the doi stub-- or to the article itself ideally.
- Make section numbers in law clickable, like for instance in the DC code
- Provide glossaries for domains (like the law).
- Leverage dbpedia
- Enable other kinds of enhancements via entity extraction.

**Comment by gergely-ujvari** [comment]
@dwhly: If possible can we move what is relevant from this issue to our vision repo?
(Sorry, it is not urgent, I'm just gardening)

**Comment by dwhly** [comment]
I think doing an integration with lens makes a lot of sense.  As for other kinds of entity extraction, it's probably better reformulated differently later.  Closing for now.
