### ISSUE TITLE
Erratic WebSocket messages delivery

### ISSUE THREAD

**Issue by kael** [hypothesis/h#8183]
Since perhaps one week WebSocket messages delivery has been erratic.

Although the WebSocket connection is established (no `close` or `error` events are emitted), messages are not received and pings not replied for approximately 4/5 of WebSocket connections.

**Comment by robertknight** [comment]
We have traced the problem to an issue when connecting through Cloudflare. Connecting directly to the service running in AWS (ignoring the expected SSL errors) works reliably. We're continuing to trace the problem.

**Comment by kael** [comment]
It seems back to normal today.

Yesterday the connection was closed but gracefully (compared to days before when the connection was stalled with `WebSocket.readyState = 2` without any thrown error).

And today the connection works immediately and messages delivery as well.

At first glance WebSocket connectivity and messages delivery look good.

**Comment by robertknight** [comment]
I can confirm. I created https://github.com/hypothesis/websocket-tester when investigating this and a run failed 70/100 attempts yesterday, but just now succeeded 100/100 attempts.

Thanks for the report @kael.

**Comment by kael** [comment]
> Thanks for the report @kael.

Thank you. :+1:

**Comment by kael** [comment]
It seems to happen again since 2 days.

**Comment by robertknight** [comment]
Thanks for the report. I can confirm there is an issue with the Cloudflare proxy again. Testing using https://github.com/hypothesis/websocket-tester:

Against the Cloudflare-proxied endpoint:

```sh
pipenv run python -m websocket_tester
```

This fails frequently. Testing against the AWS endpoint directly:

```
pipenv run python -m websocket_tester --no-ssl-verify --endpoint wss://h-websocket-prod.eba-2dpeeum3.us-west-1.elasticbeanstalk.com/ws
```

Succeeds each time.

**Comment by robertknight** [comment]
Another Cloudflare user reported the original problem at https://community.cloudflare.com/t/websocket-is-unstable/552214/6. I have posted on there to try and reach someone on Cloudflare's end.

**Comment by kael** [comment]
> I have posted on there to try and reach someone on Cloudflare's end.

Cloudflare devs are quite available on Github, though - for example https://github.com/cloudflare/workers-sdk - if you can find the right repo. :)

**Comment by kael** [comment]
(For the story, I use a Greasemonkey script that subscribes to the WebSocket stream and notifies me when [someone I'm following](https://hypothes.is/users/kael?q=tag%3Aaction%3Afollow) posts an annotation).

**Comment by robertknight** [comment]
WebSocket connections were still unreliable when proxied through Cloudflare, so we have reconfigured DNS for the WebSocket server (wss://h-websocket.hypothes.is/ws) to go direct to AWS instead.

**Comment by kael** [comment]
> we have reconfigured DNS for the WebSocket server (wss://h-websocket.hypothes.is/ws)

Alright.

It's working fine at first glance. Thank you.

Is `wss://hypothes.is/ws` still the reference URI ?

**Comment by robertknight** [comment]
The canonical URI for the WebSocket is the one that appears in the JSON response from https://hypothes.is/api/links.

**Comment by kael** [comment]
> I have posted on there to try and reach someone on Cloudflare's end.

There's a [WebSocket incident report](https://www.cloudflarestatus.com/incidents/9548jjpnvhsh) from today:

> ### Issues with WebSockets Performance
> #### Incident Report for [Cloudflare](https://www.cloudflarestatus.com/)
> ##### Update
> We are continuing to investigate this issue.
> Posted Oct 20, 2023 - 15:01 UTC
> 
> ##### Investigating
> Cloudflare is investigating potential issues with WebSockets performance. Affected WebSockets connections may fail at the start or terminate at a rate that is higher than expected.
> 
> We are working to analyse and mitigate this problem. More updates to follow shortly.
> Posted Oct 20, 2023 - 12:22 UTC
