### ISSUE TITLE
heatmap should handle pages where the scrolling happens on a child element (rather than the document as a whole)

### ISSUE THREAD

**Issue by RawKStar77** [hypothesis/h#821]
This page causes problems for the heatmap: http://www.deathandtaxesmag.com/207311/the-5-creepiest-things-about-how-the-koch-brothers-engineered-the-shutdown/

The tabs freeze and do not move when you scroll the page. Clicking on the up or down arrow tabs doesn't do anything either.

**Comment by tilgovi** [comment]
Old issue, never decided what the behavior should be. @csillag, if you see a reason to keep this open, re-open it and determine what the expected behavior is, otherwise we'll resurrect this if it comes up again.
