### ISSUE TITLE
Identify active H users that are possiblty edu prospects

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#8281]
(Joe)
We have met with several faculty who are using the Chrome extension and didn't know the differences between Chrome and LMS.

I am thinking that there might be a lot of these and we could make a pop for Spring with a great offer.

I've asked for lists of in the wild users in the past and was blocked (mostly by Jon B).  How can we get a list of active in the wild users from the last 12 months?  I'd like to filter .edu email addresses and see if we can find new customers.

Cara- do we have any information about benefits for Chrome extension v LMS that we can use, or I can start drafting

Thanks!

**Comment by marcospri** [comment]
https://hypothes-is.slack.com/archives/C4K6M7P5E/p1698338556273959
