### ISSUE TITLE
Replace Google Analytics integration with Google Tag Manager

### ISSUE THREAD

**Issue by indigobravo** [hypothesis/h#8628]
### Requirement

- Replace Google Analytics integration with Google Tag Manager

### Why

- Marketing would like to:
    - Track users navigating from web.hypothes.is to hypothes.is
    - Track users signing up to hypothes.is

### References

- [Slack conversation](https://hypothes-is.slack.com/archives/C2C2U40LW/p1710493717776609)

**Comment by robertknight** [comment]
Today we include the old `analytics.js` script on all pages on h as part of the [base.html](https://github.com/hypothesis/h/blob/053b2c7200e66f6e76604551cf33fcb705cb7770/h/templates/layouts/base.html.jinja2#L51) template. This needs to be migrated to the modern Google Analytics script. See [instructions](https://developers.google.com/analytics/devguides/migration/ua/analyticsjs-to-gtagjs). Also the tracking ID needs to be updated.

A complication we will run into with using the standard setup instructions for Google Analytics 4 is that we use a strict Content-Security-Policy which disallows running inline JS. See https://github.com/hypothesis/h/blob/053b2c7200e66f6e76604551cf33fcb705cb7770/h/app.py#L134.

The easiest workaround for this, which doesn't introduce extra security risk, would be to put the inline script in a separate file, which reads the tag ID from the existing `<meta>` tag. Another option is to generate a random nonce as part of the request and include that in both the `Content-Security-Policy` header and the inline `<script>` tag on the page. See [MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/Sources#sources).

**Comment by dwhly** [comment]
Do we want to actually "replace GA with GTM"?  I think what we may want to do is replace an old GA account number with a GA-4 account number, and also implement GTM with the specific GA-4 accounts.  No?

**Comment by robertknight** [comment]
This is now done. If you go to a URL like https://hypothes.is/search you'll see this in the HTML:

<img width="605" alt="Google Tag Manager" src="https://github.com/hypothesis/h/assets/2458/21f0493d-86f2-46b5-b850-4980e230e90d">
