### ISSUE TITLE
Fix custom metrics reporting with New Relic's python agent 9.9.0

### ISSUE THREAD

**Issue by marcospri** [hypothesis/h#8669]
Last version caused an incident as no metrics were being reported, more context on:

https://hypothes-is.slack.com/archives/C074BUPEG/p1714036107803969
https://hypothes-is.slack.com/archives/C1MA4E9B9/p1714046651276359

**Comment by seanh** [comment]
Done, see https://hypothes-is.slack.com/archives/C4K6M7P5E/p1719312833685579
