### ISSUE TITLE
Protection agains double deployment

### ISSUE THREAD

**Issue by csillag** [hypothesis/h#871]
Upon deploy H twice on the same page, there should be a warning message.
Currently there is none. Here is what happens:

### Bookmarklet + Bookmarklet

Uncaught TypeError: Cannot read property 'Host' of undefined
(anonymous function)
yepnope.complete embed.js:33
s embed.js:4
(anonymous function) embed.js:4
a embed.js:4
l embed.js:4
i embed.js:4
n embed.js:4
o embed.js:4
f embed.js:4
(anonymous function)

###  Extension + Bookmarklet

Same as above:

Uncaught TypeError: Cannot read property 'Host' of undefined
(anonymous function)
yepnope.complete embed.js:33
s embed.js:4
(anonymous function) embed.js:4
a embed.js:4
l embed.js:4
i embed.js:4
n embed.js:4
o embed.js:4
f embed.js:4
(anonymous function)

###  Bookmarklet + Extension

Fails silently (?)

**Comment by gergely-ujvari** [comment]
We have this issue again.
Seen on recent master branch, using bookmarklet.
Reopening.

**Comment by gergely-ujvari** [comment]
Sorry, different error message, opening a separate issue.
