### ISSUE TITLE
Is it possible to import Word documents and annotate them through a rich text editor?

### ISSUE THREAD

**Issue by chenj-WUST** [hypothesis/h#8835]
Is it possible to import Word documents and annotate them through a rich text editor, or is it feasible to load Word documents on a webpage for editing and annotation?

**Comment by robertknight** [comment]
Hypothesis doesn't have native support for annotating Word documents, but you can [export as a PDF](https://support.microsoft.com/en-gb/office/export-word-document-as-pdf-4e89b30d-9d7d-4866-af77-3af5536b974c) and then annotate that locally. See [this article](https://web.hypothes.is/help/annotating-locally-saved-pdfs/) for details of how to annotate a local PDF using the Chrome extension.

Another option is to export the Word document to HTML and host that somewhere. This requires more technical knowledge however to set up the hosting.

**Comment by chenj-WUST** [comment]
> Hypothesis doesn't have native support for annotating Word documents, but you can [export as a PDF](https://support.microsoft.com/en-gb/office/export-word-document-as-pdf-4e89b30d-9d7d-4866-af77-3af5536b974c) and then annotate that locally. See [this article](https://web.hypothes.is/help/annotating-locally-saved-pdfs/) for details of how to annotate a local PDF using the Chrome extension.
> 
> Another option is to export the Word document to HTML and host that somewhere. This requires more technical knowledge however to set up the hosting.

Thank you for your reply!
